= BIK BITV-Test (App)
DIAS GmbH <info@dias.de>
2020-03-03
:lang: de

Willkommen im Projektverzeichnis des https://www.bitvtest.de)[BIK BITV-Test] zur Entwicklung des **BIK BITV-Test (App)** für die Prüfung der Barrierefreiheit von mobilen Apps.
Dieses Projekt widmet sich der Pflege und Weiterentwicklung der Prüfschritte des BIK BITV-Test (App).
Unterstützt werden die Betriebssysteme Android, iOS und iPadOS.

Die zugrunde liegenden Kriterien richten sich nach der aktuell veröffentlichen https://www.etsi.org/deliver/etsi_en/301500_301599/301549/03.02.01_60/en_301549v030201p.pdf[EU Norm 301 549 V3.2.1 (PDF)].

* link:Prüfschritte/de/[Zu den Prüfschritten]

## Mitwirkung

Sie sind herzlich eingeladen, sich in die Pflege und Weiterentwicklung der Prüfschritte einzubringen.
Bitte machen Sie sich mit unseren Hinweisen zur Mitwirkung vertraut, um einen schnellen Einstieg zu finden.

* link:https://github.com/BIK-BITV/BIK-Web-Test/blob/main/CONTRIBUTING.md[Hinweise zur Mitwirkung]

== Nutzungsbedingungen

Die BIK Prüfschritte bilden die Grundlage des BIK Prüfverfahrens. Ein BITV-Test (App) nach dem BIK Prüfverfahren kann nur von https://ergebnis.bitvtest.de/bik-bitv-test-pruefverbund#c483)[BIK Prüfstellen] durch qualifizierte BIK Prüfende durchgeführt werden. Zentral wichtig  hierfür sind die im Prüfverfahren festgelegten Abläufe, die durch  ausgebildete und erfahrene BIK Qualitätssichernde begleitet werden. Eine Nutzung der BIK Prüfschritte außerhalb der in den BIK Prüfverfahren festgelegen Abläufe ohne BIK Qualitätssicherung ist kein BIK BITV-Test.

Außerhalb des BIK Prüfverfahrens können die Prüfschritte im Rahmen der https://ergebnis.bitvtest.de/tests-und-beratung/selbst-testen/bitv-selbstbewertung)[BITV-Selbstbewertung] für interne Prüfungen genutzt werden. Die BITV-Selbstbewertung darf nicht für kommerzielle Testaufträge eingesetzt werden.

=== Markenschutz

BIK ist eine seit 2004 beim Deutschen Patent- und Markenamt  eingetragene und geschützte Marke. Markenschutz besteht auch für die  unter der Marke entwickelten und registrierten Dienstleistungen, etwa  den BIK BITV-Test. Wir betrachten es als markenrechtlichen Verstoß,  Dienstleistungen anzubieten, die identische oder ähnliche Bezeichnungen  nutzen bzw. für Verbraucher*innen mit unseren BIK Dienstleistungen  verwechslungsfähig sind.
