= README
DIAS GmbH <info@dias.de>
2020-03-03
:lang: de

In diesem Projekt werden Prüfschritte für die Barrierefreiheit von mobilen Apps entwickelt.
Unterstützt werden die Betriebssysteme Android, iOS und iPadOS.

Die zugrunde liegenden Kriterien richten sich nach der aktuell veröffentlichen https://www.etsi.org/deliver/etsi_en/301500_301599/301549/03.02.01_60/en_301549v030201p.pdf[EU Norm 301 549 V3.2.1 (PDF)].

* link:Prüfschritte/de/[Zu den Prüfschritten]

== Prüfschritte zu HTML umwandeln

Die Prüfschritte sind in einzelnen AsciiDoc-Dateien aufgeteilt.
Um die Prüfschritte umzuwandeln wird der Ruby-Interpreter und das GEM-Paket
`Asciidoctor` benötigt.
Im Ordner `"support"` stellen wir eine <<support/convert2html.adoc#,Anleitung>> für die Installation und Verwendung bereit.

Die Prüfschritte sind in der Auszeichnungssprache AsciiDoc verfasst, um die
Mitarbeit zu unterstützen, stellen wir ein Tutorial für den Schnelleinstieg
bereit.
Orientieren Sie sich bei der Gestaltung des Quelltextes (Einrückungen etc.)
an der Art und Weise, die Sie vorfinden.

* <<support/AsciiDoc/AsciiDoc Tutorial.adoc#, Zum AsciiDoc Tutorial>>
