= README
DIAS GmbH <info@dias.de>
2020-03-03
:lang: de

In diesem Projekt werden Prüfschritte für die Barrierefreiheit von mobilen Apps entwickelt.
Unterstützt werden die Betriebssysteme Android, iOS und iPadOS.

Die zugrunde liegenden Kriterien richten sich nach der aktuell veröffentlichen https://www.etsi.org/deliver/etsi_en/301500_301599/301549/03.02.01_60/en_301549v030201p.pdf[EU Norm 301 549 V3.2.1 (PDF)].

* link:Prüfschritte/de/[Zu den Prüfschritten]

== Prüfschritte zu HTML umwandeln

Die Prüfschritte sind in einzelnen AsciiDoc-Dateien aufgeteilt.
Um die Prüfschritte umzuwandeln wird der Ruby-Interpreter und das GEM-Paket
`Asciidoctor` benötigt.
Im Ordner `"support"` stellen wir eine <<support/convert2html.adoc#,Anleitung>> für die Installation und Verwendung bereit.

Die Prüfschritte sind in der Auszeichnungssprache AsciiDoc verfasst, um die
Mitarbeit zu unterstützen, stellen wir ein Tutorial für den Schnelleinstieg
bereit.
Orientieren Sie sich bei der Gestaltung des Quelltextes (Einrückungen etc.)
an der Art und Weise, die Sie vorfinden.

* <<support/AsciiDoc/AsciiDoc Tutorial.adoc#, Zum AsciiDoc Tutorial>>

== Nutzungsbedingungen

Die BIK Prüfschritte bilden die Grundlage des BIK Prüfverfahrens. Ein BITV-Test (App) nach dem BIK Prüfverfahren kann nur von [BIK Prüfstellen](https://ergebnis.bitvtest.de/bik-bitv-test-pruefverbund#c483) durch qualifizierte BIK Prüfende durchgeführt werden. Zentral wichtig  hierfür sind die im Prüfverfahren festgelegten Abläufe, die durch  ausgebildete und erfahrene BIK Qualitätssichernde begleitet werden. Eine Nutzung der BIK Prüfschritte außerhalb der in den BIK Prüfverfahren festgelegen Abläufe ohne BIK Qualitätssicherung ist kein BIK BITV-Test.

Außerhalb des BIK Prüfverfahrens können die Prüfschritte im Rahmen der [BITV-Selbstbewertung](https://ergebnis.bitvtest.de/tests-und-beratung/selbst-testen/bitv-selbstbewertung) für interne Prüfungen genutzt werden. Die BITV-Selbstbewertung darf nicht für kommerzielle Testaufträge eingesetzt werden.

=== Markenschutz

BIK ist eine seit 2004 beim Deutschen Patent- und Markenamt  eingetragene und geschützte Marke. Markenschutz besteht auch für die  unter der Marke entwickelten und registrierten Dienstleistungen, etwa  den BIK BITV-Test. Wir betrachten es als markenrechtlichen Verstoß,  Dienstleistungen anzubieten, die identische oder ähnliche Bezeichnungen  nutzen bzw. für Verbraucher*innen mit unseren BIK Dienstleistungen  verwechslungsfähig sind.
