= Prüfschritt 1.2.4a Videos (live) mit Untertiteln
include::include/author.adoc[]
include::include/config.adoc[]

== Was wird geprüft?

Wenn die Tonspur einer Live-Übertragung Informationen enthält, müssen Untertitel als Alternative bereitgestellt werden.

== Warum wird das geprüft?

Filme sind in der Regel ohne den Ton nicht zu verstehen. Dies gilt auch für Live-Übertragungen. Daher muss für Menschen mit Hörbehinderung der Inhalt der Tonspur durch Untertitel bereitgestellt werden.

Untertitel können auch für andere Nutzer hilfreich sein, zum Beispiel für Personen, die mit der Sprache des Films nicht vertraut sind.

== Wie wird geprüft?

=== Anwendbarkeit des Prüfschritts

Der Prüfschritt ist anwendbar, wenn Live-Übertragungen mit synchroner Bild- und Tonspur vorhanden sind.

Live-Videos ohne Tonspur brauchen keine Untertitel, der Prüfschritt ist für sie nicht anwendbar. Alternativen für Videos ohne Tonspur werden in Prüfschritt 1 "Audiodateien und stumme Videodateien mit Textalternativen" geprüft.

=== Prüfung auf Untertitel

Das Video wird in der App oder in einem externen, vom Format abhängigen Video-Player abgespielt.

Es wird geprüft, ob parallel zum Video Untertitel automatisch angezeigt werden oder zugeschaltet werden können.

Wenn Untertitel vorhanden sind, wird eine kurze Sequenz des Videos mit Untertiteln angesehen, um stichprobenartig festzustellen, ob die Untertitel dem hörbaren Inhalt entsprechen. Dies betrifft auch akustische Ereignisse, die für das Verständnis des Inhalts wichtig sind.

=== 3. Bewertung

Erfüllt:

Live-Übertragungen mit synchroner Bild- und Tonspur haben erweiterte Untertitel, die alle Informationen der Tonspur enthalten. Dazu gehört gegebenenfalls die Anzeige, wer spricht, und bedeutungstragende Tonereignisse (etwa informationstragende Geräusche, Lachen, oder Applaus).

Nicht erfüllt:

Live-Übertragungen sind ohne Untertitel.

== Einordnung des Prüfschritts

=== Formulierung BITV 2.0

Bedingung 1.2.4 Live-Untertitel:

Bei Live-Übertragungen synchronisierter Medien sind alle Audio-Inhalte als erweiterte Untertitel (Captions) bereitzustellen.

=== Abgrenzung zu anderen Prüfkriterien

Aufgezeichnete Videos

Die Untertitelung von aufgezeichneten Videos wird in Prüfschritt 1 geprüft.

Stumme Videodateien

Bei diesem Prüfschritt geht es um die synchrone Vermittlung von visuellen und akustischen Informationen. Der Prüfschritt ist relevant, wenn für das Verständnis eines Elements die parallele Wahrnehmung von Bild und Ton erforderlich ist. Ein einfacher Alternativtext oder eine zusammenfassende Beschreibung ist dann nicht (mehr) ausreichend. Stumme Video-Dateien werden im Prüfschritt Prüfschritt 1 "Alternativen für Audiodateien und stumme Videos" geprüft.

Alternativtexte für Objekte

Alternativtexte für Multimedia-Objekte, etwa Video- oder Audio-Dateien oder Applets, werden in Prüfschritt 1 "Alternativtexte für Grafiken und Objekte" geprüft.

=== Einordnung des Prüfschritts nach WCAG 2.1

Guideline

Guideline 1.2 Time-based Media: Provide alternatives for time-based media

Success criteria

1.2.4 Captions (Live) (Level AA)

Techniques

General Techniques

G9: Creating captions for live synchronized media

G87: Providing closed captions

G93: Providing open (always visible) captions

SMIL Techniques

SM11: Providing captions through synchronized text streams in SMIL 1.0

SM12: Providing captions through synchronized text streams in SMIL 2.0
