= Prüfschritt 1.2.5a Audiodeskription für Videos
include::include/author.adoc[]
include::include/config.adoc[]

== Was wird geprüft?

Für informationstragende visuelle Videoinhalte muss eine Audiodeskription bereitgestellt werden.

== Warum wird das geprüft?

Die Handlung von Videos kann oft auch ohne Bild recht gut verfolgt werden. Den Sprecher einer Nachrichtensendung muss man zum Beispiel nicht sehen, um zu verstehen, worum es geht. Dagegen enthalten Spielfilme und Reportagen oft Passagen, in denen wenig gesprochen wird und Inhalte über das Bild vermittelt wird. Damit ein blinder Zuschauer den Film verfolgen kann, müssen ihm solche Passagen beschrieben werden. Hierfür wird das Verfahren der Audiodeskription eingesetzt.

== Wie wird geprüft?

=== Anwendbarkeit des Prüfschritts

Der Prüfschritt ist anwendbar, wenn Videos mit synchroner Bild- und Tonspur vorhanden sind und Informationen über das Bildgeschehen für das Verständnis erforderlich sind.

Videos brauchen keine Audiodeskription, wenn der Fortgang des Bildgeschehens nicht in Worte gefasst werden kann. Der Prüfschritt ist dann nicht anwendbar.

Verzichtbar ist die Audiodeskription, wenn die synchrone Wahrnehmung von Bild und Ton für das Verständnis des Videos nicht erforderlich ist oder wenn das Video keine Tonspur hat (siehe Prüfschritt 1 "Audiodateien und stumme Videodateien mit Textalternativen").

Verzichtbar ist die Audiodeskription auch für Videos, die lediglich als Medienalternative zu einem textbasierten Inhalt dienen, das heißt ergänzend zu einem Text angeboten werden, um den Textinhalt zusätzlich in anderer Form zu vermitteln. Dies gilt nur für Videos, die keine über den Textinhalt hinausgehende Informationen bieten und die klar als Medienalternative zum Text erkennbar sind.

Gebärdensprachvideos brauchen keine Audiodeskription.

=== Audiodeskription prüfen

Es wird eine Sicht- und Hörprüfung vorgenommen.

Art der Einbindung feststellen. Die Audiodeskription kann auf verschiedenem Wege angeboten werden:

Die Audiodeskription ist bereits in der normalen Tonspur enthalten.

Eine weitere Version des Videos mit Audiodeskription wird angeboten. Diese Version wird geprüft. Ein funktionierender Link zu dieser Version muss im unmittelbaren Kontext des Videos angeboten werden, ebenso wie ein Zurück-Link. Das Video hat eine zuschaltbare Tonspur mit der Audiodeskription. Diese Spur wird zusätzlich geschaltet.

Das Video wird in der App oder in einem externen, vom Format abhängigen Video-Player abgespielt.

Wenn eine Audiodeskription vorhanden ist, wird eine kurze Sequenz der Deskription angehört, um stichprobenartig festzustellen, ob sie nutzbar ist.

=== Bewertung

Nicht voll erfüllt:

Die Bildbeschreibungen der Audiodeskription sind nicht aussagekräftig oder nicht vollständig.

Nicht erfüllt:

Das informationstragende, visuelle Video hat keine Audiodeskription.

== Einordnung des Prüfschritts

=== Formulierung BITV 2.0

Bedingung 1.2.5 Audio-Deskription:

Für alle vorab aufgezeichneten Video-Inhalte synchronisierter Medien ist eine Audio-Deskription bereitzustellen. Dies gilt nicht für Medien-Alternativen für Text, die klar als solche gekennzeichnet sind.

=== Abgrenzung zu anderen Prüfschritten

In diesem Prüfschritt wird nur geprüft, ob das Video eine Audiodeskription hat. Eine Volltextalternative wird im Prüfschritt 1.3.1a bewertet.

=== Einordnung des Prüfschritts nach WCAG 2.1

Guideline

Guideline 1.2 Time-based Media: Provide alternatives for time-based media

Success criteria

1.2.5 Audio Description (Prerecorded) (Level AA)

Techniques

General Techniques

G78: Providing a second, user-selectable, audio track that includes audio descriptions

G173: Providing a version of a movie with audio descriptions

G203: Using a static text alternative to describe a talking head video

SMIL Techniques

SM1: Adding extended audio description in SMIL 1.0

SM2: Adding extended audio description in SMIL 2.0

SM6: Providing audio description in SMIL 1.0

SM7: Providing audio description in SMIL 2.0

== Quellen

BIK für Alle: Leitfaden barrierefreie Online-Videos

Für Webentwickler: Einbindung in die Internetseite

Hinweise zur Wahl von Mediaelementen.

Audiodeskription

Blogartikel von 'Sprungmarker' zur Barrierefreiheit von Media-Playern (Stand 09/2014):

Barrierefreiheit & Media Player: eine Kurzübersicht - Teil 1

Blogartikel von Terrill Thompson zu Audio Description (Stand 03/2017):

My Audio Description Talk @ CSUN
