= Prüfschritt 1.3.1g Kein Strukturmarkup für Layouttabellen
include::include/author.adoc[]
include::include/config.adoc[]

Was wird geprüft?

Tabellenstruktur-Auszeichnungen sollen nicht für Layouttabellen verwendet werden.

== Wie wird geprüft?

=== 1. Anwendbarkeit des Prüfschritts

Der Prüfschritt ist anwendbar, wenn die Software Tabellen für das Layout verwendet.

=== 2. Prüfung

Bei Software kann in der Regel nur ein Blackbox-Test mittels Screenreader durchgeführt werden. Da wo eine inkorrekt eingesetzte Tabelle vermutet wird, kann mit dem SR navigiert werden. Der Screenreader sagt dann an, ob es sich um eine „richtige“ semantische Tabelle handelt (ein Zusatz wie „Tabelle“ wird ausgegeben).

[arabic]
. Screenreader starten (siehe Handreichung)
. Zu testende App starten
. Den Bereich navigieren bzw. antippen, der für eine semantische Tabelle gehalten wird. Prüfen ob der Screenreader den Zusatz „Tabelle“ ausgibt.

=== 4. Bewertung

Nicht erfüllt:

Es werden Layouttabellen eingesetzt, der Screenreader gibt unnötige weitere Tabellendetails aus.

== Einordnung des Prüfschritts

=== Formulierung BITV 2.0

1.3.2 Aussagekräftige Reihenfolge

Wenn die Reihenfolge, in der der Inhalt präsentiert wird, Auswirkungen auf dessen Bedeutung hat, ist die richtige Lese-Reihenfolge durch Programme erkennbar.

=== Einordnung des Prüfschritts nach WCAG 2.1

Guideline

Guideline 1.3 Adaptable: Create content that can be presented in different ways (for example simpler layout) without losing information or structure

Success criterion

1.3.1 Info and Relationships (Level A)

Techniques

General Techniques

G115: Using semantic elements to mark up structure

G140: Separating information and structure from presentation to enable different presentations

HTML Techniques

H39 Using caption elements to associate data table captions with data tables

H73 Using the summary attribute of the table element

Failure

F46 Failure of Success Criterion 1.3.1 due to using th elements, caption elements, or non-empty summary attributes in layout tables

== Quellen

F46: Failure of Success Criterion 1.3.1 due to using th elements, caption elements, or non-empty summary attributes in layout tables

Although WCAG 2.1 does not prohibit the use of layout tables, CSS-based layouts are recommended in order to retain the defined semantic meaning of the HTML table elements and to conform to the coding practice of separating presentation from content. When a table is used for layout purposes the th element should not be used. Since the table is not presenting data there is no need to mark any cells as column or row headers. Likewise, there is no need for an additional description of a table which is only used to layout content. Do not include a summary attribute and do not use the summary attribute to describe the table as, for instance, "layout table". When spoken, this information does not provide value and will only distract users navigating the content via a screen reader. Empty summary attributes are acceptable on layout tables, but not recommended.

Quelle: https://www.w3.org/WAI/WCAG21/Techniques/failures/F46.html
