= Prüfschritt 2.4.6a Aussagekräftige Überschriften und Beschriftungen
include::include/author.adoc[]
include::include/config.adoc[]

== Was wird geprüft?

Überschriften beschreiben den folgenden Inhaltsteil, Beschriftungen sind sinngebend.

== Warum wird das geprüft?

Visuell werden Webseiten-und Software-Inhalte durch Überschriften strukturiert. Dank dieser Strukturierung weiß der Benutzer, was zusammengehört, kann die Inhalte leicht überblicken und gezielt auf Inhalte zugreifen, die ihn interessieren.

Wenn Formularfelder sinngebend beschriftet sind, können Sie von Nutzer als solche erkannt und bedient werden.

== Wie wird geprüft?

=== Anwendbarkeit des Prüfschritts

Der Prüfschritt ist anwendbar, wenn es in der App-Ansicht Inhalte gibt, die durch Überschriften strukturiert werden können und wenn die Ansicht Formularelemente enthält.

=== Prüfung

[arabic]
. App mit zu prüfender Ansicht löffnen.
. Prüfen, ob die Überschriften im Zusammenhang mit den durch sie strukturierten Inhalten aussagekräftig sind.
. Prüfen, ob Beschriftungen von Formularelementen aussagekräftig sind.
. Wenn Gruppen von Bedienelementen durch Legenden beschriftet werden: Sind Legende und Label bzw. Beschriftung des Bedienelements, zusammen vorgelesen, bei allen Formularelementen in der Gruppierung sinnvoll?

=== Hinweise

Besonders in Fachanwendungen gibt es Labels und Überschriften, die in dem betreffenden Nutzerkreis bestimmten, etablierten Vokabularen entsprechen (einschließlich viel genutzter Abkürzungen). Die Verwendung in Interfaces bringt Vorteile mit (Wiedererkennbarkeit, Präzision, Kürze), kann aber auch dazu führen, dass sie nicht unbedingt für jeden aussagekräftig oder anschaulich sind, was aber nicht zu einer negativen Bewertung führen soll.

== Einordnung des Prüfschritts

=== Formulierung BITV 2.0

2.4.6 Beschreibungen

Überschriften und Label (Beschriftungen) kennzeichnen das Thema oder den Zweck.

=== Abgrenzung von anderen Prüfkriterien

In diesem Prüfschritt geht es um die Aussagekraft von Überschriften und Beschriftungen. Die programmatische Ermittelbarkeit durch Assistive Technologien ist den Prüfkriterien 1.3.1a "HTML-Strukturelemente für Überschriften" und 1.3.1h "Beschriftung programmatisch ermittelbar" zugeordnet.

=== Einordnung des Prüfschritts nach WCAG 2.1

Guideline

Guideline 2.4 Navigable: Provide ways to help users navigate, find content, and determine where they are. .

Success criterion

2.4.6 Headings and Labels (Level A)

Techniques

General Techniques

G130: Providing descriptive headings

G131: Providing descriptive labels
