= Prüfschritt 3.3.4a Fehlervermeidung wird unterstützt
include::include/author.adoc[]
include::include/config.adoc[]

== Was wird geprüft?

Bei wichtigen Dateneingaben (etwa bei finanziellen Transaktionen) gibt es die Möglichkeit, die Dateneingabe rückgängig zu machen oder sie vor dem Abschicken zu überprüfen und zu korrigieren. Erfolgreiche Eingaben werden bestätigt.

== Warum wird das geprüft?

Bei jeder Dateneingabe können Fehler passieren. Gerade wenn sich der Prozess nicht rückgängig machen lässt, ist es wichtig, Benutzer dazu anzuhalten, die eingegebenen Daten vor dem Abschicken noch einmal zu überprüfen.

Dies ist für alle Benutzer wichtig. Für Benutzer mit Behinderungen ist jedoch in vielen Fällen das Risiko von Fehleingaben größer. Benutzer mit Legastenie vertauschen häufiger Zahlen, Benutzer mit motorischen Einschränkungen drücken häufiger versehentlich falsche Tastaturtasten. Deshalb ist das Rückgängig-Machen oder Anzeigen, Überprüfen und gegebenenfalls Korrigieren eingegebener Daten für diese Benutzer besonders wichtig.

== Wie wird geprüft?

=== Anwendbarkeit des Prüfschritts

Der Prüfschritt ist anwendbar, wenn die App-Ansicht Formulare für Transaktionen enthält, durch die Nutzer rechtlich bindende Verpflichtungen eingehen. Dazu gehören Online-Bestellvorgänge und andere finanzielle Transaktionen.

=== Prüfung

Formular mit Beispieldaten ausfüllen und Prozess fortsetzen. Eine der folgenden drei Optionen soll erfüllt sein:

* Datenanzeige mit Korrekturmöglichkeit. Die eingegebenen Daten werden dem Benutzer vor dem Abschicken noch einmal angezeigt, es gibt an dieser Stelle die Möglichkeit, die Daten zu korrigieren.
* Bestätigung. Das Abschicken erfolgt erst nach Bestätigung eines Dialogs, der die Konsequenzen der Transaktion beschreibt.
* Unmittelbare Rückabwicklung. Die Transaktion (etwa das Löschen von angelegten Datensätzen) kann unmittelbar rückgängig gemacht werden.

=== Hinweise

Eine Checkbox oberhalb des "Abschicken"-Buttons zur Bestätigung der Richtigkeit von Benutzereingaben ist ein wesentlich schwächeres Instrument als die Anzeige der kompletten Eingabe auf einer neuen Ansicht vor dem endgültigen Abschicken des Formulars. Solche Checkboxen werden häufig für formalrechtlich relevante Funktionen genutzt, wie etwa die Bestätigung der Geschäftsbedingungen eines Anbieters. Sie werden deshalb von vielen Benutzern nicht richtig wahrgenommen und routinemäßig gesetzt. Für die Bestätigung wichtiger Eingaben sind sie deshalb weniger geeignet.

Erfolgreiche Eingaben sollten nach dem Abschicken bestätigt werden.

=== Bewertung

Nicht voll erfüllt:

* Daten werden vor dem Abschicken zum Überprüfen angezeigt, es gibt aber keinen expliziten Button zurück zum Formular, um Daten zu korrigieren oder zu ergänzen.
* Es gibt weder eine Datenanzeige mit Korrekturmöglichkeit noch die Möglichkeit der unmittelbaren Rückabwicklung. Zum Bestätigen der Eingabe gibt es keinen Dialog, sondern lediglich eine Checkbox über dem "Abschicken"-Button.
* Nach dem erfolgreichen Abschicken gibt es keine Bestätigung.

Nicht erfüllt:

* Wichtige Daten werden ohne vorherige Datenanzeige, Dialog zur Bestätigung, oder Möglichkeit der sofortigen Rückabwicklung abgeschickt.
* Bei Neuanzeige des Formulars sind bereits gemachte Eingaben gelöscht, die Felder sind wieder leer und müssen erneut ausgefüllt werden.

== Einordnung des Prüfschritts

=== Formulierung BITV 2.0

3.3.4 Fehlervermeidung

Bei Webseiten, die rechtliche Verpflichtungen begründen oder zu finanziellen Transaktionen der Nutzerinnen und Nutzer führen oder von Nutzerinnen und Nutzern kontrollierbare Daten in Datenspeichersystemen ändern bzw. löschen oder Testantworten der Nutzerinnen und Nutzer absenden, haben Nutzerinnen und Nutzer mindestens eine der folgenden Möglichkeiten:

Die Ausführung kann rückgängig gemacht werden.

Die eingegebenen Daten werden auf Eingabefehler überprüft und es besteht die Möglichkeit, diese gegebenenfalls zu korrigieren.

Die Informationen können durchgesehen, korrigiert und bestätigt werden, bevor sie endgültig abgeschickt werden.

=== Einordnung des Prüfschritts nach WCAG 2.1

Guideline

Guideline 3.3 Input Assistance: Help users avoid and correct mistakes.

Success criterion

3.3.4 Error prevention (Legal, Financial, Data) (Level AA)

Techniques

General techniques

G98: Providing the ability for the user to review and correct answers before submitting

G99: Providing the ability to recover deleted information

G155: Providing a checkbox in addition to a submit button

G164: Providing a stated time within which an online request (or transaction) may be amended or canceled by the user after making the request

G168: Requesting confirmation to continue with selected action

G199: Providing success feedback when data is submitted successfully
