= 1.1.1c Leere alt-Attribute für Layout-Grafiken
include::include/author.adoc[]
include::include/config.adoc[]

== Was wird geprüft?

Eine Grafik, die keine informative Funktion hat, benötigt keinen Alternativtext. Grafiken ohne informative Funktion sind zum Beispiel Abstandshalter, Farbflächen, Muster, oder rein dekorative Fotos. Solche Grafiken sollen für Screenreader ausgeblendet werden.

Thema des Prüfschritts sind auch Icons, die mittels Icon Font eingebunden sind.

== Warum wird das geprüft?

Der Screenreader kann Layoutgrafiken nicht von Informationstragenden Grafiken unterscheiden und gibt daher beide Grafikarten an den Nutzer aus. Wenn in einer Ansicht mehrere Layoutgrafiken auftauchen, kann dies schnell zu vielen unbrauchbaren Ausgaben durch den Screenreader führen. Diese unnützen Ausgaben unterbrechen den Informationsfluss und sind für den Screenreader-Nutzer sehr störend. Entwickler können Layoutgrafiken mit plattformspezifischen Mitteln vor dem Screenreader verbergen, um diese Störung zu vermeiden.

Icon Fonts sind Schriftarten, die Symbole statt Buchstaben beinhalten. Manche moderne Plattformen übergeben an den Screenreader ein Unicode-Äquivalent, was bei dekorativen Icons störend ist.

== Wie wird geprüft?

=== 1. Anwendbarkeit des Prüfschritts

Der Prüfschritt ist anwendbar, wenn eingebundene Grafiken oder Font Icons für Layout-Zwecke verwendet werden.

=== Prüfung

[arabic]
. App mit zu prüfender Ansicht starten
. Prüfen ob Layoutgrafiken bzw. Icon-Fonts eingesetzt werden
. Screenreader starten (siehe Handreichung) und prüfen ob beim Antippen der Layoutgrafiken bzw. der Icon-Fonts eine Ausgabe durch den Screenreader stattfindet.

____
Der Screenreader sollte bei Layout-Grafiken nichts ausgeben.
____

=== 3. Hinweise

Bei aus mehreren Teilbildern zusammengesetzten Bilder mit Informationsgehalt sollte eines der Teilbilder einen Alternativtext haben, der über den Inhalt des zusammengesetzten Bildes informiert. Die anderen Teilbilder sollten dann vor dem Screenreader ausgeblendet werden.

=== Bewertung

Nicht voll erfüllt:

* Layout-Grafiken werden in Software vom Screenreader in irgendeiner Weise ausgegeben, die Ausgabe ist dabei jedoch kurz.

== Einordnung des Prüfschritts

=== Formulierung BITV 2.0

Siehe Prüfschritt 1 "Alternativtexte für Bedienelemente"

=== Einordnung des Prüfschritts nach WCAG 2.1

Guideline

Guideline 1.1 Text Alternatives: Provide text alternatives for any non-text content so that it can be changed into other forms people need, such as large print, braille, speech, symbols or simpler language

Success Criterion

1.1.1 Non-text Content (Level A)

Techniques

HTML Techniques

H67: Using null alt text and no title attribute on img elements for images that AT should ignore

CSS Techniques

C9: Using CSS to include decorative images

Failures

F38: Failure of Success Criterion 1.1.1 due to omitting the alt-attribute for non-text content used for decorative purposes only in HTML

F39: Failure of Success Criterion 1.1.1 due to providing a text alternative that is not null. (e.g. alt='spacer' or alt='image') for images that should be ignored by assistive technology

== Quellen

Die WCAG 2.0-Technik H67 sieht zusätzlich vor, dass bei Layout-Grafiken auch kein title-Attribut vorhanden sein soll oder dass das title-Attribut leer ist:

For each image that should be ignored:

Check that title attribute is either absent or empty.

Check that alt attribute is present and empty or contains only whitespace (but not )

Quelle: H67: Using null alt text and no title attribute on img elements for images that AT should ignore

== Fragen zu diesem Prüfschritt

Warum soll man bei Layout-Grafiken nicht die jeweilige Aufgabe des Bildes, also zum Beispiel "Abstandhalter" in den Alternativtext schreiben?

Wofür sollte das gut sein? Den Abstand herstellen, also die Aufgabe des Bildes übernehmen kann der Alternativtext nicht. Die Information, dass da irgendwo Abstände zwischen Elementen der Seite sind, ist nutzlos. Wie die Elemente auf der Seite angeordnet sind, lässt sich der Tatsache, dass an irgend welchen Stellen Abstandhalter sind, auch nicht entnehmen.

Solche Alternativtexte haben also keinen Nutzen. Auf der anderen Seite kann es sehr störend sein, wenn der Screenreader dauernd "Abstandhalter Abstandhalter Abstandhalter ..." vorliest.
