= Prüfschritt 1.2.3a Audiodeskription oder Volltext-Alternative für Videos
include::include/author.adoc[]
include::include/config.adoc[]

== Was wird geprüft?

Für informationstragende visuelle Videoinhalte muss eine Audiodeskription oder Volltext-Alternative bereitgestellt werden.

== Warum wird das geprüft?

Die Handlung von Videos kann oft auch ohne Bild recht gut verfolgt werden. Den Sprecher einer Nachrichtensendung muss man zum Beispiel nicht sehen, um zu verstehen, worum es geht. Dagegen enthalten Spielfilme und Reportagen oft Passagen, in denen wenig gesprochen wird und Inhalte über das Bild vermittelt werden. Damit ein blinder Zuschauer den Film verfolgen kann, müssen ihm solche Passagen beschrieben werden. Hierfür wird das Verfahren der Audiodeskription eingesetzt.

== Wie wird geprüft?

=== 1. Anwendbarkeit des Prüfschritts

Der Prüfschritt ist anwendbar, wenn Videos mit synchroner Bild- und Tonspur vorhanden sind und Informationen über das Bildgeschehen für das Verständnis erforderlich sind.

Videos brauchen keine Audiodeskription, wenn der Fortgang des Bildgeschehens nicht in Worte gefasst werden kann. Der Prüfschritt ist dann nicht anwendbar.

Verzichtbar ist die Audiodeskription, wenn die synchrone Wahrnehmung von Bild und Ton für das Verständnis des Videos nicht erforderlich ist oder wenn das Video keine Tonspur hat (siehe Prüfschritt 1 "Audiodateien und stumme Videodateien mit Textalternativen").

Verzichtbar ist die Audiodeskription auch für Videos, die lediglich als Medienalternative zu einem textbasierten Inhalt dienen, das heißt ergänzend zu einem Text angeboten werden, um den Textinhalt zusätzlich in anderer Form zu vermitteln. Dies gilt nur für Videos, die keine über den Textinhalt hinausgehende Informationen bieten und die klar als Medienalternative zum Text erkennbar sind.

Gebärdensprachvideos brauchen keine Audiodeskription.

=== Prüfung

Audiodeskription prüfen

Es wird eine Sicht- und Hörprüfung vorgenommen.

Art der Einbindung feststellen. Die Audiodeskription kann auf verschiedenem Wege angeboten werden:

Die Audiodeskription ist bereits in der normalen Tonspur enthalten.

Eine weitere Version des Videos mit Audiodeskription wird angeboten. Diese Version wird geprüft. Ein funktionierender Link zu dieser Version muss im unmittelbaren Kontext des Videos angeboten werden, ebenso wie ein Zurück-Link.

Das Video hat eine zuschaltbare Tonspur mit der Audiodeskription. Diese Spur wird zusätzlich geschaltet.

Das Video wird In der App oder in einem externen, vom Format abhängigen Video-Player abgespielt.

Wenn eine Audiodeskription vorhanden ist, wird eine kurze Sequenz der Deskription angehört, um stichprobenartig festzustellen, ob sie nutzbar ist.

Volltextalternative prüfen

Es wird eine Sicht- und Hörprüfung vorgenommen.

Das Video wird in der App oder in einem externen, vom Format abhängigen Video-Player abgespielt.

Volltextalternative prüfen. Sie sollte folgende Informationen enthalten:

Eine fortlaufende Beschreibung des Geschehens

Alle visuellen Information, eingeschlossen Beschreibungen des visuellen Kontexts, Aktionen und der Ausdruck der Schauspieler.

Geräusche (Gelächter, off-Screen-Stimmen etc.)

Transkriptionen aller Dialoge

Die Abfolge der Beschreibung und Dialoge sollte der Abfolge im Video entsprechen.

Falls interaktive Elemente vorkommen (z.B. „Aktivieren Sie jetzt, um die Frage zu beantworten“), sollte die Volltextalternative Links oder ähnliches vorsehen, um dieselbe Funktionalität zu gewährleisten.

=== 3. Bewertung

Nicht voll erfüllt:

Es wird keine Audiodeskription angeboten, informationstragende Bilddinhalte sind nicht vollständig in der angebotenen Volltextalternative enthalten.

Nicht erfüllt

Das informationstragende, visuelle Video hat weder eine Audiodeskription noch eine Volltextalternative.

Abwertung des Gesamtergebnisses

Die Abwertung ist erforderlich, wenn Bildinhalte eines Videos ohne Audiodeskription für die Nutzung der App von zentraler Bedeutung sind: Die App kann wegen Unzugänglichkeit des Videos von blinden oder sehbehinderten Menschen nicht genutzt werden.

== Einordnung des Prüfschritts

=== Formulierung BITV 2.0

Bedingung 1.2.3 Audio-Deskription oder Volltext-Alternative:

Für aufgezeichnete synchronisierte Medien ist eine Volltext-Alternative einschließlich aller Interaktionen oder eine Audiodeskription bereitzustellen. Dies gilt nicht für Medienalternativen für Text, die klar als solche gekennzeichnet sind.

=== Einordnung des Prüfschritts nach WCAG 2.1

Guideline

Guideline 1.2 Time-based Media: Provide alternatives for time-based media

Success criteria

1.2.3 Audio Description or Media Alternative (Prerecorded) (Level A)

Techniques

General Techniques

G58: Placing a link to the alternative for time-based media immediately next to the non-text content

G69: Providing an alternative for time based media

G78: Providing a second, user-selectable, audio track that includes audio descriptions

G173: Providing a version of a movie with audio descriptions

G203: Using a static text alternative to describe a talking head video

SMIL Techniques

SM1: Adding extended audio description in SMIL 1.0

SM2: Adding extended audio description in SMIL 2.0

SM6: Providing audio description in SMIL 1.0

SM7: Providing audio description in SMIL 2.0

== Quellen

BIK für Alle: Leitfaden barrierefreie Online-Videos

Für Webentwickler: Einbindung in die Internetseite

Hinweise zur Wahl von Mediaelementen.

Audiodeskription

Blogartikel von 'Sprungmarker' zur Barrierefreiheit von Media-Playern (Stand 09/2014):

Barrierefreiheit & Media Player: eine Kurzübersicht - Teil 1

Blogartikel von Terrill Thompson zu Audio Description (Stand 03/2017):

My Audio Description Talk @ CSUN
