= Prüfschritt 1.3.1f Zuordnung von Tabellenzellen
include::include/author.adoc[]
include::include/attributes.adoc[]

== Was wird geprüft?

In komplexen Datentabellen soll der Bezug von Überschriften und Inhalten
definiert sein, ausdrückliche Zuordnungen von Überschriften und Inhalten in
einfachen Datentabellen sollen korrekt sein.

== Warum wird das geprüft?

Bei komplexen Tabellen können Screenreader aus dem Tabellengerüst allein
nicht schließen, welche Bezüge es zwischen Daten- und Überschriftenzellen
gibt.
Deshalb müssen diese Verknüpfungen mithilfe der in der Software zur
Verfügung stehenden Attribute vom Software-Hersteller ausdrücklich definiert
werden.

Es kann vorkommen, dass auch einfache Datentabellen speziell für
Hilfstechnologien ausgezeichnet wurden.
Screenreader richten sich dann nicht nach allgemeinen Regeln, sondern nach der
vorliegenden Auszeichnung.
Deshalb muss die Auszeichnung auch dann richtig sein, wenn sie eigentlich
nicht nötig wäre.
Denn bei falscher direkter Zuordnung von Datenzellen werden die Überschriften
nicht oder fehlerhaft ausgegeben.

*Hinweis:* Für Benutzer von Screenreadern sind komplexe Tabellen schwerer zu
erfassen als einfache, selbst bei perfekter Auszeichnung.
Zu empfehlen ist also die Vermeidung von Tabellen mit mehreren logischen
Ebenen (siehe Frage zu Tabellen mit mehreren logischen Ebenen).
In vielen Fällen können komplexe Tabellen geteilt und durch mehrere einfache
Tabellen ersetzt werden.
Die beste Bewertung für diesen Prüfschritt ist deshalb immer "nicht anwendbar".

== Wie wird geprüft?

=== Anwendbarkeit des Prüfschritts

Der Prüfschritt ist anwendbar,

* wenn eine Datentabelle komplex ist, also mehrstufige Zeilen- oder
  Spaltenüberschriften vorhanden sind
* wenn in einer einfachen Datentabelle Zellen ausdrücklich bestimmten
  Überschriften zugeordnet sind (auch wenn diese Zuordnung eigentlich nicht
  erforderlich wäre).

Einfache Datentabellen haben im Unterschied zu komplexen Datentabellen nur
jeweils eine Zeile oder Spalte für Überschriften.
Bei solchen Tabellen ist es eigentlich nicht erforderlich, die Zellen "ihren"
Überschriften zuzuordnen.

=== Prüfung

Bei Software ist es in der Regel nicht ohne den Quelltext möglich, die
korrekte syntaktische Auszeichnung festzustellen.
Hier muss dann ein Blackbox-Test mit einem Screenreader durchgeführt werden.
Dieser sagt dann an, ob es sich um eine „richtige“ Tabelle handelt und
kann beim navigieren über Zeilen und Spalten ggf. auch dessen Überschriften
ausgeben.

. Screenreader starten (siehe Handreichung)
. Zu testende App starten
. Mit dem Screenreader über die Tabelle navigieren bzw. diese direkt antippen
  und prüfen ob der Screenreader den Zusatz „Tabelle“ ausgibt.
. Mit Wischbewegungen weiter über die Tabelle navigieren und prüfen ob beim
  Zeilen und/oder Spaltenwechsel auch dessen Überschriften ausgegeben werden.
  Weitere Überschriftebenen bei komplexen Tabellen müssen berücksichtigt
  werden.

=== Hinweis

Grundlage der Prüfung ist die vorangegangene Überprüfung des Aufbaus der
Datentabelle und der Auszeichnung von Überschriften in Prüfschritt
<<1.3.1e Datentabellen richtig aufgebaut.adoc#,1.3.1e Datentabellen richtig
aufgebaut>>.
Dieser Prüfschritt 1.3.1f beschränkt sich auf die Vollständigkeit und die
formale Korrektheit der Zuordnung von Inhalten zu Überschriften.

== Einordnung des Prüfschritts

=== Formulierung BITV 2.0

==== 1.3.1 Informationen und Beziehungen

Alle Informationen, Strukturen und Beziehungen, die durch Layout und
Präsentation vermittelt werden, sind durch Programme erkennbar oder im Text
verfügbar.

=== Einordnung des Prüfschritts nach WCAG 2.1

==== Guideline

* https://www.w3.org/WAI/WCAG21/quickref/?showtechniques=131#adaptable[Guideline
  1.3 Adaptable: Create content that can be presented in different ways (for
  example simpler layout) without losing information or structure]

==== Success criterion

* https://www.w3.org/WAI/WCAG21/quickref/?showtechniques=131#info-and-relationships[
  1.3.1 Info and Relationships (Level A)]

==== Techniques

.General Techniques
* https://www.w3.org/WAI/WCAG21/Techniques/general/G115.html[G115: Using
  semantic elements to mark up structure]
* https://www.w3.org/WAI/WCAG21/Techniques/general/G140.html[G140: Separating
  information and structure from presentation to enable different presentations]

==== Failures

* https://www.w3.org/WAI/WCAG21/Techniques/failures/F90.html[F90: Failure of
  Success Criterion 1.3.1 for incorrectly associating table headers and
  content via the headers and id attributes]
* https://www.w3.org/WAI/WCAG21/Techniques/failures/F92.html[F92: Failure of
  Success Criterion 1.3.1 due to the use of role presentation on content which
  conveys semantic information]

== Quellen

=== Was sind Tabellen mit mehreren logischen Ebenen?

[.BLOCK_LANG_EN]
--
(...) the average table of data with a row of headers across the top, and a
column of headers down one side or the other (or sometimes the same headers
reproduced at either side, to make life easier) has only one logical level of
headers.

Tables with two or more levels are those where the row of headers "closest to
the content" itself has headers.
A trivial example would be months, which have season headers (...)
--

Quelle: http://lists.w3.org/Archives/Public/wai-wcag-editor/2000OctDec/0155.html

== Weiterführende Links:

* pro-barrierefreiheit:
  http://www.pro-barrierefreiheit.de/entwickler/tabellen/strukturierung/[
  Strukturierung von Tabelleninhalten]
* Roger Hudson, Web Usability: http://www.usability.com.au/resources/tables.cfm[
  Accessible Data Tables]
