= Prüfschritt 1.3.1h Beschriftung von Formularelementen programmatisch ermittelbar
include::include/author.adoc[]
include::include/config.adoc[]

== Was wird geprüft?

Beschriftungen sollen über die entsprechende Auszeichnung im Programm-Code
mit den Eingabefeldern verknüpft sein, zu denen sie gehören.

Visuell voneinander abgesetzte oder logisch miteinander verbundene Gruppen von
Formularelementen sind z. B. mithilfe von Überschriften sinnvoll strukturiert.

Ist bei Gruppen von Formularelementen eine Gruppenbeschriftung für das
Verständnis der Beschriftung der einzelnen Formularelemente nötig, sollte
die Verfügbarkeit sichergestellt werden.

== Warum wird das geprüft?

Die Verknüpfung von Beschriftungen mit den zugeordneten Eingabefeldern stellt
sicher, dass der Aufbau einer Software-Ansicht unabhängig von der
Präsentation festgelegt und zugänglich ist:

* Der Screenreader liest die Beschriftungen vor, wenn der Benutzer durch die
  Formularelemente wandert.
* Das jeweils aktive Label kann deutlich hervorgehoben werden ggf. kann eine
  Hilfstechnologie beim Antippen / Anklicken des Labels den Fokus auf das zugehörige Formularelement setzen.

Auch wenn die Beschriftungen der Formularelemente korrekt ausgezeichnet sind so
kann es sein, dass diese nicht ausreichen und z. B. eine gemeinsame
Überschrift für das Verständnis notwendig ist.

== Wie wird geprüft?

=== Anwendbarkeit des Prüfschritts

Der Prüfschritt ist anwendbar, wenn die Software-Ansicht Formularelemente
enthält.

=== Prüfung

Ob die Semantik im Quelltext der Anwendung korrekt gesetzt ist, kann in der
Regel nicht ohne weiteres festgestellt werden.
Hier muss dann ein Blackbox-Test z. B. mittels Screenreader durchgeführt
werden.
Zu beachten ist, das hier auch gruppierte Bedienelemente ggf. eine
Gruppenbeschriftung benötigen und diese muss auch vom Screenreader ausgegeben
werden können.

. Screenreader starten (siehe Handreichung)
. Zu testende App starten
. Über Formularelemente navigieren bzw. diese direkt antippen und prüfen, ob
  dessen Beschriftungen [.underline]#und# Gruppenbeschriftungen korrekt
  ausgegeben werden.

=== Hinweise

Bei kombinierten Eingabeelementen hat nicht immer jedes Element eine
zugeordnete Beschriftung.
In diesem Fall sollen Elemente mit einer passenden (nicht sichtbaren)
Bezeichnung für Screenreader versehen werden.
Beispiel:
In einem Formular werden für die Eingabe eines Datums drei Auswahllisten
angeboten (Tag, Monat und Jahr).
Die drei Auswahllisten haben eine gemeinsame Beschriftung: Datum.
Die Auswahllisten für Tag, Monat und Jahr sind mit einer erklärenden
Bezeichnung für Screenreader versehen.
Diese Bezeichnungen sind dann nur von der Hilfstechnologie auswertbar, die
entsprechenden Bezeichnungen sind nicht sichtbar.

Wenn ein einfaches Suchformular nur aus einem Eingabefeld und einem Button
besteht, ist oftmals keine sichtbare Beschriftung notwendig.
Hier ist es ausreichend, wenn Eingabefeld und Button direkt nebeneinander
positioniert sind, das Eingabefeld eine sinnvolle Textvorbelegung hat oder die
Beschriftung des Buttons die Funktion eindeutig kennzeichnet (etwa "Suchen").
Das unbeschriftete Eingabefeld mit Textvorbelegung muss in solchen Fällen
eine aussagekräftige (nicht sichtbare) Bezeichnung für den Screenreader
haben, da für Screenreader-Nutzer der nachfolgende Button nicht
gleichermaßen als Beschriftung taugt.

=== Bewertung

*Nicht erfüllt:*

* Beschriftungen sind nicht korrekt mit den dazugehörigen Eingabefeldern
  verknüpft.

== Einordnung des Prüfschritts

=== Formulierung BITV 2.0

==== 1.3.1 Informationen und Beziehungen

Alle Informationen, Strukturen und Beziehungen, die durch Layout und
Präsentation vermittelt werden, sind durch Programme erkennbar oder im Text
verfügbar.

=== Abgrenzung von anderen Prüfkriterien

Ob bei Nutzung von gruppierenden Überschriften der Text zusammen mit
verknüpften Beschriftungen der Formularfelder (label) Sinn ergibt, wird in
Prüfschritt
<<2.4.6a Aussagekräftige Überschriften und Beschriftungen.adoc#,2.4.6a
Aussagekräftige Überschriften und Beschriftungen>>
geprüft.

=== Einordnung des Prüfschritts nach WCAG 2.1

==== Guidelines

* https://www.w3.org/TR/WCAG21/#adaptable[Guideline 1.3 Adaptable: Create
  content that can be presented in different ways (for example simpler layout)
  without losing information or structure.]

==== Success criteria

* https://www.w3.org/TR/WCAG21/#info-and-relationships[1.3.1 Info and
  Relationships (Level A)]

==== Techniques

.General Techniques
* https://www.w3.org/WAI/WCAG21/Techniques/general/G162.html[G162: Positioning
  labels to maximize predictability of relationships]
