= Prüfschritt 1.3.4a Keine Beschränkung der Bildschirmausrichtung
include::include/author.adoc[]
include::include/config.adoc[]

== Was wird geprüft?

Software-Inhalte sollen sich an die nutzergewählte Ausrichtung von Ausgabegeräten anpassen. Sie sollten sowohl im Hochformat als auch im Querformat dargestellt werden und nutzbar sein, es sei denn, eine bestimmte Ausrichtung des Inhalts ist unerlässlich.

Beispiele für Inhalte, bei denen die Ausrichtung unerlässlich sein können, sind ein Bankcheck, eine online-Klavier-Tastatur, Präsentationsfolien für einen Projektor oder Bildschirm, oder Inhalte eine Virtual-Reality (VR) Anwendung bei der es keine binäre Ausrichtung gibt (also nicht: entweder Hoch- oder Querformat).

Es wird nicht verlangt, dass in beiden Ausrichtungen Inhalte und Funktionen in der gleichen Form angeboten werden. So können in einer anderen Orientierung Inhalte ggf. erst nach Aktivierung von Ausklappbereichen oder mittels Links oder Buttons auf andere Seiten angeboten werden.

== Warum wird das geprüft?

Für Menschen mit Behinderung ist es oft besonders wichtig, ein Ausgabegerät (z.B. ein Smartphone) in einer bestimmten Ausrichtung nutzen zu können. Wenn beispielsweise Text stark vergrößert wird, bietet die Verwendung des Querformats oft ein besseres Leseerlebnis, da mehr Wörter in eine Zeile passen.

Außerdem haben einige Benutzer ihre Geräte in einer festen Ausrichtung montiert (z.B. am Arm eines Elektrorollstuhls). Daher sollten Anwendungen die Darstellung von Inhalten nicht auf eine Ausrichtung einschränken.

== Wie wird geprüft?

=== 1. Anwendbarkeit des Prüfschritts

Der Prüfschritt ist immer anwendbar.

=== 2. Prüfung

[arabic]
. Ein aktuelles Android-Smartphone oder iPhone mit ca. 4-6 Zoll Bildschirmdiagonale zur Prüfung verwenden.
. Sicherstellen, dass auf dem mobilen Prüfgerät die Ausrichtung nicht hardware- oder betriebssystemseitig festgestellt bzw. arretiert ist.
. In der App wird die entsprechende Ansicht in den beiden Ausrichtungen geöffnet.
. Prüfen, ob Inhalte dargestellt werden und nutzbar sind.
. Der zu prüfende Inhalt wird in der anderen Ausrichtung neu geladen.
. Prüfen, ob Inhalte dargestellt werden und nutzbar sind. Treten Beschränkungen beim Wechsel der Ausrichtung auf, etwa Meldungen, welche zur Nutzung der jeweils anderen Ausrichtung auffordern?
. Wenn nur eine Ausrichtung unterstützt wird und in der anderen Ausrichtung entweder der Inhalt nicht erscheint, um 90 Grad gedreht erscheint, oder aber eine Meldung ausgegeben wird, dass die andere Ausrichtung zu nutzen ist: Prüfen, ob die unterstützte Ausrichtung unerlässlich ist, die Inhalte in der nicht unterstützten Ausrichtung also nicht oder nur schlecht dargestellt werden könnten.

=== 3. Hinweise

Es wird nicht verlangt, dass eine Änderung der Ausrichtung die Inhalte dynamisch anpasst (obwohl dies wünschenswert und bei responsiven Angeboten meist auch der Fall ist). Der Inhalt muss also in beiden Ausrichtungen jeweils neu gestartet werden.

=== 4. Bewertung

Prüfschritt erfüllt:

Beide Ausrichtungen werden unterstützt.

Wenn nur eine Ausrichtung angeboten wird, ist sie für den Inhalt unerlässlich.

== Quellen

Understanding Success Criterion 1.3.4: Orientation (zur Zeit nur auf Englisch verfügbar)
