= Prüfschritt 1.3.2a Sinnvolle Reihenfolge
include::include/author.adoc[]
include::include/config.adoc[]

== Was wird geprüft?

in Software-Ansichten sollen korrekte Reihenfolgen vorherrschen z. B. folgt ein Informationstext nach dessen Überschrift. Hier muss meist mangels Quelltextzugriff ein Blackbox-Test z. B. mittels Screenreader durchgeführt werden.

Warum wird das geprüft?

Screenreader lesen die Elemente, die auf dem Bildschirm in der Fläche angeordnet sind, nacheinander vor - und zwar in der Reihenfolge, in der sie im Quellcode stehen. Die Reihenfolge der Elemente muss also gut verständlich und nutzbar sein.

== Wie wird geprüft?

=== 1. Anwendbarkeit des Prüfschritts

Der Prüfschritt ist anwendbar, wenn Bei Software ist dieser Prüfschritt immer anwendbar.

=== 2. Prüfung

Bei Software soll die Element-Reihenfolge im Wesentlichen die visuelle Reihenfolge der Elemente abbilden. Häufig kann dies mittels (Bluetooth-) Tastatur und aktiviertem Screenreader getestet werden. Da dieser Prüfschritt alle Elemente auf einer Ansicht prüft, betrifft dies auch Nicht-Steuerelemente. Mit dem Screenreader wandert man dazu auf das erste Element der Ansicht und navigiert ab dort nach rechts die Elemente durch. Hierbei wird beurteilt ob die Reihenfolge der Elemente sinnvoll und im Wesentlichen der visuellen Reihenfolge entspricht.

Für die Bedienung der verschiedenen Screenreader beachten Sie bitte die entsprechenden Handreichungen.

=== 4. Bewertung

Nicht voll erfüllt:

Die Reihenfolge der Elemente ist nicht sinnvoll oder entspricht nicht der Wesentlichen visuellen Folge.

== Einordnung des Prüfschritts

=== Formulierung BITV 2.0

1.3.2 Aussagekräftige Reihenfolge

Wenn die Reihenfolge, in der der Inhalt präsentiert wird, Auswirkungen auf dessen Bedeutung hat, ist die richtige Lese-Reihenfolge durch Programme erkennbar.

=== Abgrenzung von anderen Prüfkriterien

Custom controls, werden bereits in einer Reihe von bestehenden Prüfkriterien implizit geprüft, etwa 1 "Aktuelle Position des Fokus deutlich", und 1 "Name und Rolle von Bedienelementen verfügbar".

Die korrekte Reihenfolge im Quelltext bei dynamisch generierten oder eingeblendeten Elementen ist Gegenstand von Prüfschritt 1 "Schlüssige Reihenfolge bei Tastaturbedienung".

=== Einordnung des Prüfschritts nach WCAG 2.1

Guideline

Guideline 1.3 Adaptable: Create content that can be presented in different ways (for example simpler layout) without losing information or structure.

Success criteria

1.3.2 Meaningful Sequence (Level A)

Techniques

General Techniques

G57 Ordering the content in a meaningful sequence

CSS Techniques

C6 Positioning content based on structural markup

C8 Using CSS letter-spacing to control spacing within a word

C27: Making the DOM order match the visual order

Scripting Techniques

SCR21: Using functions of the Document Object Model (DOM) to add content to a page

SCR28: Using an expandable and collapsible menu to bypass block of content

Failures

F1: Failure of Success Criterion 1.3.2 due to changing the meaning of content by positioning information with CSS

F32: Failure of Success Criterion 1.3.2 due to using white space characters to control spacing within a word

F34: Failure of Success Criterion 1.3.1 and 1.3.2 due to using white space characters to format tables in plain text content

F49 Failure of Success Criterion 1.3.2 due to using an HTML layout table that does not make sense when linearized
