= Prüfschritt 1.4.2a Ton abschaltbar
include::include/author.adoc[]
include::include/attributes.adoc[]

== Was wird geprüft?

Automatisch abgespielte Töne, die nicht nach drei Sekunden enden, sollen
abschaltbar sein.

== Warum wird das geprüft?

Automatisch abgespielte Töne stören Nutzer, die sich in einer Software
mittels Sprachausgabe orientieren.

Falls ein Tonelement nach dem starten einer Software automatisch startet, ist
es deshalb wichtig, dass es sich über einen am Beginn der Ansicht
befindlichen barrierefreien Mechanismus abschalten, anhalten oder herunter
regeln lässt.

== Wie wird geprüft?

=== Anwendbarkeit des Prüfschritts

Der Prüfschritt ist anwendbar, wenn nach dem starten einer Software bzw. beim
Wechsel auf die zu prüfende Ansicht Tonelemente automatisch länger als drei
Sekunden abgespielt werden.

=== Prüfung

Wenn nach starten der Software bzw. beim Wechsel auf die zu prüfende Ansicht
ein Tonelement automatisch abgespielt wird:

* Prüfen, ob der Ton länger als 3 Sekunden dauert.
+
Wenn das der Fall ist:
Prüfen, ob sich am Beginn der Ansicht ein Mechanismus (Button, Link, oder
Lautstärke-Regler) befindet, mit dem sich der Ton abschalten oder unabhängig
von der Systemlautstärke herunter regeln lässt.
Der Fokus soll bei Aufruf der Ansicht auf dem Bedienelement zum Pausieren der
Wiedergabe gesetzt sein.

* Den Mechanismus bedienen und den Ton abschalten.

Wenn sich die Lautstärke regeln lässt:

* die Systemlautstärke darf durch den Regler in der App nicht verändert
werden.
+
Hier kann z. B. vor und nach einem Test ein Vergleichs-Sound abgespielt
werden, um zu beurteilen, ob eine Veränderung der Systemlautstärke
stattgefunden hat.

=== Hinweise

Töne, die nicht nach kurzer Zeit enden, können auch die Verständlichkeit
der Sprachausgabe des Abschaltmechanismus stören.
Deshalb wird auch berücksichtigt, wie störend sich der Ton auswirkt.
Sprache oder laute Geräusche etwa stören mehr als eine gleichmäßige
Hintergrundmusik.

Der Mechanismus zum Herunterregeln des Tones darf nicht die
Systemtonlautstärke ändern, da dies auch die Tonausgabe von Hilfsmitteln mit
Sprachausgabe beeinträchtigen würde.

Der Mechanismus zum Abschalten oder Herunterregeln des Tons muss sich in jeder
Ansicht befinden, in denen Ton abgespielt wird und soll selbst alle
Anforderungen an Barrierefreiheit erfüllen, also etwa ausreichende Kontraste
haben und tastaturbedienbar sein.

Wenn sich der Ton herunterregeln lässt, soll er auf der niedrigsten Stellung
des Reglers nicht mehr hörbar sein.

Es reicht zur Erfüllung dieses Prüfschritts nicht aus, wenn sich der Ton
über Tastaturbefehle (etwa die Escape-Taste) abschalten lässt.
Diese Funktion kann sinnvoll sein, wird aber von vielen Nutzern nicht vermutet.
Insbesondere auf Touch-Geräten soll der Fokus standardmäßig auf dem Play /
Pause / Mute Bedienelement sein, damit dieses sofort bedient werden kann und
nicht erst gesucht werden muss.

=== Bewertung

*Erfüllt:*

* Automatisch abgespielte Töne dauern nicht länger als drei Sekunden oder
  sind über einen barrierefreien Mechanismus in jeder Ansicht, in der Ton
  abgespielt wird, leicht abschaltbar.

*Nicht voll erfüllt:*

* Automatisch abgespielter Ton enthält von Beginn an längere Sprachpassagen
  oder andere laute und störende Ton-Ereignisse.
  Die Sprachausgabe des Abschaltmechanismus kann deshalb nur schlecht
  wahrgenommen werden.
* Der Mechanismus zum Abschalten des Tons befindet sich nicht auf der Ansicht,
  in der Ton abgespielt wird.
* Es gibt lediglich eine Erklärung, wie der Ton mittels Tastatur abschaltbar
  ist.

== Einordnung des Prüfschritts

=== Formulierung BITV 2.0

==== 1.4.2 Audio-Kontrolle

Bei Tonelementen, die auf einer Webseite automatisch länger als drei Sekunden
abgespielt werden, gibt es:

* entweder einen Mechanismus zum Unterbrechen oder Beenden des Tons
* einen Mechanismus zur Regelung der Lautstärke unabhängig von der
  Systemlautstärke

=== Einordnung des Prüfschritts nach WCAG 2.1

==== Guideline

* https://www.w3.org/TR/WCAG21/#audio-control[Guideline 1.4 Distinguishable: Make
  it easier for users to see and hear content including separating foreground
  from background.]

==== Success criterion

* https://www.w3.org/TR/WCAG21/#audio-control[1.4.2 Audio Control (Level A)]

==== Techniques

.General Techniques
* https://www.w3.org/WAI/WCAG21/Techniques/general/G60.html[G60: Playing a
  sound that turns off automatically within three seconds]
* https://www.w3.org/WAI/WCAG21/Techniques/general/G170.html[G170: Providing a
  control near the beginning of the Web page that turns off sounds that play
  automatically]
* https://www.w3.org/WAI/WCAG21/Techniques/general/G171.html[G171: Playing
  sounds only on user request]

==== Failures

* https://www.w3.org/WAI/WCAG21/Techniques/failures/F23.html[F23: Failure of 
  1.4.2 due to playing a sound longer than 3 seconds where there is no
  mechanism to turn it off]
* https://www.w3.org/WAI/WCAG21/Techniques/failures/F93.html[F93: Failure of
  Success Criterion 1.4.2 for absence of a way to pause or stop an HTML5 media
  element that autoplays]

== Quellen

=== Bedeutung der Tonabschaltung nach WCAG 2.1

[.BLOCK_LANG_EN]
--
Individuals who use screen reading software can find it hard to hear the
speech output if there is other audio playing at the same time.
This difficulty is exacerbated when the screen reader's speech output is
software based (as most are today) and is controlled via the same volume
control as the sound.
Therefore, it is important that the user be able to turn off the background
sound.

* Note: Having control of the volume includes being able to reduce its volume to
zero.
* Note: Playing audio automatically when landing on a page may affect a screen
  reader user's ability to find the mechanism to stop it because they navigate
  by listening and automatically started sounds might interfere with that
  navigation.
  Therefore, we discourage the practice of automatically starting sounds
  (especially if they last more than 3 seconds), and encourage that the sound
  be started by an action initiated by the user after they reach the page,
  rather than requiring that the sound be stopped by an action of the user
  after they land on the page.
--

Quelle: https://www.w3.org/WAI/WCAG21/Understanding/audio-control.html[Audio
Control: Understanding SC 1.4.2]
