= Prüfschritt 1.4.4a Text auf 200% vergrößerbar
include::include/author.adoc[]
include::include/config.adoc[]

== Was wird geprüft?

Text soll um bis zu 200 Prozent geändert werden können, ohne dass dabei
Inhalt oder Funktionalität verloren geht.
Eine der folgenden Voraussetzung soll erfüllt sein:

* * Mit der Zoom-Funktion des Betriebssystems kann das gesamte Layout
  proportional zur Schriftgröße vergrößert werden.
* Mit der Nur-Text-Vergrößerung des Betriebssystems kann der Text
  vergrößert werden.
* Über ein Bedienelement der Software-Ansicht kann die Schriftgröße
  vergrößert werden.

Da die gängigen mobilen Plattformen wie iOS / iPadOS und Android
Bedienungshilfen mit Vergrößerungsfunktionalitäten anbieten, ist dieser
Prüfschritt erfüllt, wenn die Software ordungsgemäß mit diesen
Systemfunktionen nutzbar ist.

== Warum wird das geprüft?

Benutzer sollen die Schriftgröße nach ihren Bedürfnissen einstellen können.
Die gängigen Betriebssysteme bieten zwei verschiedene
Vergrößerungsmöglichkeiten: die klassische Nur-Text-Vergrößerung und die
Zoom-Vergrößerung des gesamten Bildschirminhalts.

== Wie wird geprüft?

=== Anwendbarkeit des Prüfschritts

Der Prüfschritt ist anwendbar, wenn die Software-Ansicht Text enthält.

=== Prüfung

. Zoom-Funktionalität in den Bedienungshilfen von iOS / iPadOS bzw. Android
  aktivieren (siehe
  Handreichung)
. App mit zu prüfender Ansicht starten
. Ansicht mittels der Zoomfunktion des Betriebssystems um 200% vergrößern
  und dabei prüfen, ob dies Probleme bei der zu prüfenden Ansicht hervorruft.

==== Prüfung der Schriftvergrößerung durch Bedienelemente in der Software

Wenn die Software eigene Bedienelemente bereithält, um die Schriftgröße zu
vergrößern:

Muss nur geprüft werden, wenn die Systemfunktion zum vergrößern nicht
vorhanden ist oder diese mit der App zu Problemen führt.

. Prüfen, ob die Bedienelemente für Schriftvergrößerung deutlich sichtbar
  im oberen Bereich der Ansicht angeboten werden.
. Prüfen, ob die Schrift mit Hilfe der auf der Ansicht angebotenen
  Bedienelemente schrittweise vergrößert werden kann (wie stark die
  Vergrößerung ist spielt dabei keine Rolle).
. Prüfen, ob sich über die angebotenen Bedienelemente die
  Ausgangsschriftgröße wiederherstellen lässt.

=== Hinweise

Werden Apps getestet, kommen die Funktionen Zoomen und/oder
Nur-Text-Vergrößerung des Betriebssystems zum Einsatz
Bietet das Betriebssystem eine normale Zoomfunktion (Vergrößerung des
gesamten Bildausschnitts) an, wird diese meist eine 200%ige Vergrößerung
ermöglichen.
Funktioniert die Zoomfunktion mit der zu testenden Software, ist dieser
Prüfschritt bestanden.
Falls das Betriebssystem auch eine Nur-Text-Vergrößerung anbietet, sollte
diese dennoch mit der Software getestet werden.
Probleme mit der Nur-Text-Vergrößerung sollten dabei zumindest
angemerkt werden, da diese für einige Nutzer Vorteilhafter als die
Vergrößerung des gesamten Bildausschnitts ist (z. B. bessere Orientierung).

Die Prüfung der Schriftvergrößerung durch eigene Bedienelemente in der zu
testenden Software-Ansicht erfolgt nur unter folgenden Bedingungen:

* Das Bedienelement erfüllt alle Anforderungen an Barrierefreiheit (es ist
  zum Beispiel tastaturbedienbar, erfüllt die Kontrastanforderungne etc.)

=== Bewertung

*Erfüllt:*

* Der Bildschirminhalt (inkl. Text) lässt sich mittels der Systemfunktionen
  auf 200 % vergrößern, ohne dass es zu Überlappungen oder abgeschnittenen
  Inhalten kommt und ohne dass Funktionalitäten beeinträchtigt werden.

== Einordnung des Prüfschritts

=== Formulierung BITV 2.0

==== 1.4.4 Veränderbare Textgröße

Der Text lässt sich ohne assistive Technologie bis auf 200 % vergrößern,
ohne dass es zu einem Verlust von Inhalt oder Funktionalität kommt.

=== Abgrenzung zu anderen Prüfkriterien

Mangelnde Vergrößerbarkeit von Schriftgrafiken:
siehe Prüfschritt
<<1.4.5a Verzicht auf Schriftgrafiken.adoc#,1.4.5a Verzicht auf
Schriftgrafiken>>.

=== Einordnung des Prüfschritts nach WCAG 2.1

==== Guideline

* https://www.w3.org/TR/WCAG21/#distinguishable[Guideline 1.4 Distinguishable:
  Make it easier for users to see and hear content including separating
  foreground from background]

==== Success criterion

* https://www.w3.org/TR/WCAG21/#resize-text[1.4.4 Resize text (Level AA)]

==== Techniques

.General Techniques
* https://www.w3.org/WAI/WCAG21/Techniques/general/G146.html[G146: Using
  liquid layout]
* https://www.w3.org/WAI/WCAG21/Techniques/general/G178.html[G178: Providing
  controls on the Web page that allow users to incrementally change the size
  of all text on the page up to 200 percent]
* https://www.w3.org/WAI/WCAG21/Techniques/general/G179.html[G179: Ensuring
  that there is no loss of content or functionality when the text resizes and
  text containers do not change their width]

==== Failures

* https://www.w3.org/WAI/WCAG21/Techniques/failures/F69.html[F69: Failure of
  Success Criterion 1.4.4 when resizing visually rendered text up to 200
  percent causes the text, image or controls to be clipped, truncated or obscured]
* https://www.w3.org/WAI/WCAG21/Techniques/failures/F80.html[F80: Failure of
  Success Criterion 1.4.4 when text-based form controls do not resize when visually rendered text is resized up to 200%]

== Quellen

=== WCAG 2.1 über die Skalierung von Text

[.BLOCK_LANG_EN]
The scaling of content is primarily a user agent responsibility.
User agents that satisfy UAAG 1.0 Checkpoint 4.1 allow users to configure text
scale.
The author's responsibility is to create Web content that does not prevent the user
agent from scaling the content effectively.
Authors may satisfy this Success Criterion by verifying that content does not
interfere with user agent support for resizing text, including text-based
controls, or by providing direct support for resizing text or changing the
layout.
An example of direct support might be via server-side script that can be used
to assign different style sheets.

Quelle: https://www.w3.org/WAI/WCAG21/Understanding/resize-text.html[Resize text: Understanding SC 1.4.4]

=== Die WCAG 2.1 zur Nutzung absoluter und relativer Maßeinheiten für Text

[.BLOCK_LANG_EN]
--
(...) specify text font size in em units so that user agents can scale content
effectively.
Since the em is a property of the font, it scales as the font changes size. If
a font-size is specified for the body element, all other elements inherit that
value, unless overridden by a more specific selector.

When font size is given in absolute units of measurement, such as points or
pixels, the Text Size menu commands in Internet Explorer 7 and earlier do not
resize the text.

Internet Explorer 7 only changes the text size when the CSS is defined in a
style element (...). When using inline style with the style attribute, the
text size change is not supported.
--

Quelle: WCAG 2.1 Technik https://www.w3.org/WAI/WCAG21/Techniques/css/C14.html[
C14: Using em units for font sizes]
