= Prüfschritt 11.1.3.1b Datentabellen richtig aufgebaut
include::include/author.adoc[]
include::include/attributes.adoc[]

== Was wird geprüft?

Datentabellen sind strukturell richtig aufgebaut, Zeilen- und Spaltenüberschriften sind plattformspezifisch im Programm-Code ausgezeichnet. Tabellen sind wegen des reduzierten Viewports in nativen Apps eher selten, tauchen aber häufiger in Webviews auf. Zum Teil erscheinen Sie in unterschiedlicher Form abhängig von der Viewportbreite des Ausgabegeräts bzw, der Ausrichtung des Geräts. Gehört die die Püfung auf Tablets zum Umfang des Tests, sind hier also unter Umständen abweichende Ansichten zu berücksichtigen.

== Warum wird das geprüft?

Sehbehinderte und blinde Nutzende erschließen sich Datentabellen analytisch und entwickeln anhand der Spalten- und ggf. Zeilen-Überschriften eine Vorstellung vom Aufbau der Tabelle. Wenn es solche semantischen Überschriften gibt (oft sind diese auch visuell hervorgehoben) und Zelleninhalte nur mit diesen zusammen aussagekräftig sind, sollen sie beim Navigieren der Tabellenzellen verfügbar sein. Bei jedem Wechsel zur nächsten Zelle wird dann die jeweils neue Spalten- oder Zeilenüberschrift ausgegeben. 

== Wie wird geprüft?

=== 1. Anwendbarkeit des Prüfschritts

Der Prüfschritt ist immer anwendbar, wenn Tabellen in der App-Ansicht vorhanden sind.

=== 2. Prüfung
Die Screenreader-Navigation und Ausgabe von Datentabellen in Apps, besonders in Webviews, is oft uneinheitlich. Es kommt vor, dass Tabellen unter manchen Bedingungen fokussierbar und navigierbar sind und unter anderen nicht, selbst auf dem gleichen Gerät. Semantisch richtig aufgebaute Datentabellen können ggf. in responsiven Ansichten nicht zugänglich sein, zum Beispiel nicht im Lesemodus erreichbar sein, obwohl sie semantisch korrekt umgesetzt sind. Dies kann an der App selbst liegen oder auch auf einen Bug des Betriebssystems, des in Webviews transparent genutzten Browsers, oder des Screenreaders hindeuten. Das ist ohne Quelltextzugang nicht immer klar zu entscheiden. Ggf. während der Prüfung die App neu laden, Ansichten neu aufrufen, Screenreader deaktiveren und wieder reaktivieren, Geräte neu starten. Das Ziel ist, die programmatische Umsetzung der App zu bewerten und *nicht* Lücken oder Bugs in der Hilfsmittelunterstützung. Bei Webviews hift es, wenn die Quelle identifizierbar ist, im Desktop-Browser aufgerufen werden kann und dort mit Bordmtteln untersucht werden kann.

Zur Tabellennavigation mit dem Screenreader, siehe Hinweise für iOS und Android in Abschnitt 3.

==== 2.1 Werden Tabellen für tabellarische Daten verwendet?

. Prüfen, ob die App-Ansicht Datentabellen enthält (d.h. Daten stehen in einer logischen Beziehung zueinander und sind rasterartig organisiert).
. iOS: Alternativ mit aktiviertem Screenreader und Rotor-Einstellung "Tabelle" über vertikale Wischgesten erkunden, ob Datentabellen gefunden werden. 
. Visuelle Prüfung: Erste Zelle (oben links) antippen, prüfen, ob nach Ausgabe des Zellen-Inhalts sowie Zeilen- und Spaltennummern "Anfang der Tabelle" (iOS) oder "In Tabelle" (Android) ausgegeben wird. 
. Über horizontale Wischgesten die Zellen der Tabelle linear durchlaufen. Falls Spalten-Überschriften vorhanden sind, prüfen, ob diese bei Fokussierung der Datenzelle ausgegeben werden. (Eine vertikale Wischgesten-Navigation ist meist nicht in gleicher Weise möglich, weil diese Geste vom Screenreader "verbraucht" oder auf die horizontale Naviogation gemappt wird.)

==== 2.2 Prüfung der Auszeichnung von Tabellen

. App mit zu prüfender Ansicht öffnen.
. Prüfen, ob die App-Ansicht eine Datentabelle enthält.
. Screenreader starten und mit Hilfe der Wischgeste durch die Tabelle navigieren.
. Prüfen, ob alle Spalten- und Zeilenüberschriften zusammen mit der Datenzelle ausgegeben werden. 
. Alternativ die Zeilen- bzw. Spaltenüberschrift angetippen und prüfen, was der Screenreader ausgibt: Wenn der Screenreader "Zeilenüberschrift", "Spaltenüberschrift" oder ähnlich als Zusatz spricht, sind die entsprechenden Überschriften korrekt ausgezeichnet.

=== 3. Hinweise
Tabellen-Überschriften werden nicht generell verlangt. Sie sind überflüssig, wenn in den Zellen neben den Einzelwerten auch deren Bedeutung angegeben ist oder wenn die Bedeutung der Einzelwerte sich von selbst versteht. Ein typisches Beispiel dafür sind Preislisten: in der linken Spalte stehen die meist selbsterklärenden Produktbezeichnungen, in der rechten Spalte Betrag und Währungszeichen.

==== 3.1 Allgemeine Hinweise zur Navigation von Tabellen
* Eine vertikale Screenreader-Navigation der Tabelle über Wischgesten ist in der Regel nicht möglich. 
* Ggf. wird die Pfeiltastennavigation zwischen Zellen unterstützt. 

==== 3.2 Erschließen von Tabellen in iOS
* Vor der Prüfung sicherstellen, dass "Tabellen" im Rotor als Navgationsmöglichkeit aktiviert ist.
* Mit Rotoreinstellung "Tabellen" sind Tabellen über vertikale Wischgeste erreichbar (fokussiert wird die Zelle links oben)
* iOS nit Tastatur: Über CTR + Option + Pfeiltasten können Tabellenzellen durchlaufen werden. Dabei werden semantisch umgesetzte Spaltenüberschriften ausgegeben.
* iOS nit Tastatur: Über Kurzbefehle (bei iOS mit Tastatur, CTR + Option + C) können Spaltenheader ausgegeben werden.

==== 3.3 Erschließen von Tabellen in Android

==== 3.3 Tabellen mit eingesparten Überschriften



=== 4. Bewertung

==== Nicht voll erfüllt:

* Für Datentabellen wird keine Tabellensemantik verwendet.

== Einordnung des Prüfschritts

=== Einordnung des Prüfschritts nach WCAG 2.1

==== Guideline

* https://www.w3.org/TR/WCAG21/#adaptable[Guideline 1.3 Adaptable: Create
  content that can be presented in different ways (for example simpler layout)
  without losing information or structure]

==== Success criterion

* https://www.w3.org/TR/WCAG21/#info-and-relationships[1.3.1 Info and
  Relationships (Level A)]

==== Techniques

.General Techniques
* https://www.w3.org/WAI/WCAG21/Techniques/general/G115.html[G115: Using
  semantic elements to mark up structure]
* https://www.w3.org/WAI/WCAG21/Techniques/general/G140.html[G140: Separating
  information and structure from presentation to enable different presentations]

== Quellen


==== Informationen für Entwickler (iOS / iPadOS)

Personen, die Apps entwickeln, können das Protokoll `link:https://developer.apple.com/documentation/uikit/uiaccessibilitycontainerdatatable[
UIAccessibilityContainerDataTable]` zur Auszeichnung von barrierefreien Datentabellen nutzen.

=== W3C - Web Accessibility Tutorials

* https://www.w3.org/WAI/tutorials/tables/[Tables Tutorial]

=== Entwicklerressourcen

* Apple Developer:
  https://developer.apple.com/documentation/uikit/uiaccessibilitycontainerdatatable[
  UIAccessibilityContainerDataTable]
