= Prüfschritt 11.1.3.1e Beschriftung von Formularelementen programmatisch ermittelbar
include::include/author.adoc[]
include::include/attributes.adoc[]

*Hinweis: Dies ist ein Entwurf. Inhalte können sich jederzeit ändern.*

== Was wird geprüft?

Beschriftungen von Eingabefeldern sollen programmatisch (d.h. über die entsprechende Auszeichnung im Code) verfügbar sein.

== Warum wird das geprüft?
Wenn Appps Eingabefelder verwenden, müssen diese nicht nut viosuell beschriftet sein. Für Screenreader-Nutzende ist es wichtig, dass das Label programmatisch verfügbar ist Eingabefeld ind label sollten dafür im besten Fall nur einmal fokussiert werden. Das funktioniert, denn das Feld eine programmatische Beschriftung enthält die dem visuellen Label entspricht. Der Screenreader liest die jeweileige Feld-Beschriftung vor, wenn der Benutzer durch die Formularelemente navigiert.

Wenn Gruppen von Formularelementen eine Überschrift haben, sollte diese in der linearen navigation übe rhorizontale Wischgesten vo den Formularelementen fokussiert werden und muss programmatisch zugänglich sein (siehe auch 3. Hinweise).

== Wie wird geprüft?

=== 1. Anwendbarkeit des Prüfschritts

Der Prüfschritt ist anwendbar, wenn die App-Ansicht Formularelemente enthält.

=== 2. Prüfung

. App mit der zu prüfenden Ansicht öffnen.
. Screenreader starten und mit Hilfe der Wischgeste durch die Ansicht navigieren.
. Prüfen, ob die Feld-Beschriftungen und (wenn vorhanden) Gruppenbeschriftungen korrekt ausgegeben werden.

=== 3. Hinweise

==== Kombinierte Eingabeelemente

Bei kombinierten Eingabeelementen hat nicht immer jedes Element eine zugeordnete Beschriftung. In diesem Fall sollen Elemente mit einer passenden (nicht sichtbaren)
Bezeichnung für Screenreader versehen werden. Beispiel: In einem Formular werden für die Eingabe eines Datums drei Auswahllisten angeboten (Tag, Monat und Jahr).
Die drei Auswahllisten haben eine gemeinsame Beschriftung: Datum. Die Auswahllisten für Tag, Monat und Jahr sind mit einer erklärenden Bezeichnung für Screenreader versehen.
Diese Bezeichnungen sind dann nur von der Hilfstechnologie auswertbar, die entsprechenden Bezeichnungen sind in manchen Fällen nicht sichtbar.

Wenn ein einfaches Suchformular nur aus einem Eingabefeld und einem Button besteht, ist oftmals keine sichtbare Beschriftung notwendig. Hier ist es ausreichend, wenn Eingabefeld und Button direkt nebeneinander positioniert sind, das Eingabefeld eine sinnvolle Textvorbelegung hat oder die Beschriftung des Buttons die Funktion eindeutig kennzeichnet (etwa "Suchen"). Das unbeschriftete Eingabefeld mit Textvorbelegung muss in solchen Fällen eine aussagekräftige (nicht sichtbare) Bezeichnung für den Screenreader
haben, da für Screenreader-Nutzende der nachfolgende Button nicht gleichermaßen als Beschriftung taugt.

==== Gruppenbeschriftungen
In manchen Fällen gibt es für Gruppen von Bedienelementen (z.B. eine Gruppe von Radio-Inputs oder Checkboxen, bei iOS als Schalter umgesetzt) eine Gruppenüberschrift, die zum Verständnis der Einzel-Beschriftungen wichtig sein kann. Solche Gruppenüberschriften lassen sich in nativen Umgebungen nicht auf die gleiche Weise umsetzen, wie dies in HTML über das `fieldset/legend` Konstrukt möglich ist. Die Gruppenbeschriftung in Apps muss in der Lesereihenfolge direkt vor der Gruppe stehen und im normalen Navigationsmodus über horizontale Wischgesten programmatisch ausgegeben werden (vergl. Prüfschritte 11.1.3.1c Text programmatisch verfügbar 11.1.3.2 Sinnvolle Reihenfolge). Ist sie visuell eine Überschrift, sollte sie auch als Überschrift ausgezeichnet sein (vergl. Prüfschritt 11.1.3.1a Überschriften). Es ist nicht erforderlich, dass im Navigationmodus über Elemente (etwa "Steuerelemente" unter Android) bei Fokussierung der Steuerelemente in der Gruppe die Gruppenbeschriftung mit ausgegeben wird, da sich dies nicht in gleicher Weise dynamisch umsetzen lässt wie in HTML. Die Alternative, der Einschluss der Gruppenbeschriftung in jede Einzelbeschriftung, wäre zwar möglich, aber auch sehr redundant und dadurch störend, auch weil das unterscheidende Element erst der ggf. längeren, immer gleichen Gruppenbeschriftug ausgegeben würde.

==== Programmatische Verknüpfung von Label und Formularelment

In der Praxis kommt es immer wieder vor, dass Label und dessen Bedienelement getrennt voneinander vorgelesen werden. Dies ist meist dann der Fall, wenn Bedienelement und Label keine programmatische Verbindung haben bzw. nicht gruppiert wurden. Um die Verbindung programmatisch herzustellen, bieten die Plattformen unterschiedliche Mögglichkeiten an.
Bei iOS / iPadOS können diese Elemente
https://developer.apple.com/documentation/uikit/accessibility/delivering_an_exceptional_accessibility_experience#3542986[
gruppiert werden], sodass sie für den Screenreader als eine Einheit agieren.
Bei Android gibt es dazu https://developer.android.com/guide/topics/ui/accessibility/principles[
vergleichbare Ansätze].

=== 4. Bewertung

==== Nicht erfüllt:

* Beschriftungen sind nicht korrekt mit den dazugehörigen Eingabefeldern verknüpft.

== Einordnung des Prüfschritts

=== Abgrenzung von anderen Prüfkriterien

Ob bei Nutzung von gruppierenden Überschriften der Text zusammen mit
verknüpften Beschriftungen der Formularfelder (label) Sinn ergibt, wird in
Prüfschritt
ifdef::env_embedded[11.2.4.6 "Aussagekräftige Überschriften und Beschriftungen"]
ifndef::env_embedded[]
  <<11.2.4.6 Aussagekräftige Überschriften und Beschriftungen.adoc#,11.2.4.6
  Aussagekräftige Überschriften und Beschriftungen>>
endif::env_embedded[]
geprüft.

=== Einordnung des Prüfschritts nach WCAG 2.1

==== Guidelines

* https://www.w3.org/TR/WCAG21/#adaptable[Guideline 1.3 Adaptable: Create
  content that can be presented in different ways (for example simpler layout)
  without losing information or structure.]

==== Success criteria

* https://www.w3.org/TR/WCAG21/#info-and-relationships[1.3.1 Info and
  Relationships (Level A)]

==== Techniques

.General Techniques
* https://www.w3.org/WAI/WCAG21/Techniques/general/G162.html[G162: Positioning
  labels to maximize predictability of relationships]

== Quellen
* https://www.bbc.co.uk/accessibility/forproducts/guides/mobile/labelling-form-controls/[Allgemeine Informationen der BBC, 
Accessibility for Products: Labeling form controls]

=== iOS
* https://developer.apple.com/documentation/uikit/accessibility/delivering_an_exceptional_accessibility_experience#3542986[
  Apple Developer Documentation: Group Labels]
* https://developer.apple.com/documentation/uikit/uiaccessibilityelement/1619577-accessibilitylabel[iOS accessibilityLabel] 

=== Android
* https://developer.android.com/guide/topics/ui/accessibility/custom-views[
Android Developers: Make custom views more accessible]
* https://developer.android.com/guide/topics/ui/accessibility/principles[Android Developers: Principles for improving app accessibility]

