= Prüfschritt 11.1.3.5 Eingabefelder zu Nutzerdaten vermitteln den Zweck
include::include/author.adoc[]
include::include/attributes.adoc[]

== Was wird geprüft?

Eingabefelder, die sich auf den Nutzer selbst beziehen, sollten eine semantisch eindeutige, sprachunabhängige Bestimmung ihres Zweckes ermöglichen.

In iOS/iPadOS und Android können manche Eingabefelder dem Zweck entsprechend ausgezeichnet werden, z. B. für die Eingabe einer E-Mail-Adresse. Hier kann dann das Betriebssystem u. a. eine optimierte Tastatur einblenden. Grundsätzlich ist aber auch die semantische Auszeichnung anderer Eingabezwecke denkbar. Bei Webangeboten werden hierfür zurzeit passende Werte des `autocomplete`-Attributs genutzt. Eine entsprechende Semantik wird unseres Wissens bei nativen Apps nicht unterstützt. Die Prüfung beschränkt sich deshalb auf Felder mit Eingabezwecken, die zu bestimmten angepassten Tastaturen wechseln können, etwa für die Eingabe von E-Mail Adressen oder von Zahlen.

Auf GitHub können Sie zu diesem Prüfschritt ein
https://github.com/BIK-BITV/BIK-App-Test/issues[Issue eröffnen], falls Sie
Hinweise zu diesem Prüfschritt haben.

== Warum wird das geprüft?

Duch die semantische Festlegung des Eingabezwecks von Eingabefeldern wäre es prinzipiell Bedienungshilfen des Betriebssystems möglich, bei Feldern, welche sich auf Daten des Nutzers beziehen, die Beschriftung anzupassen oder zusätzliche Informationen anzuzeigen, und zwar unabhängig vom der jeweils gewählten Beschriftung des Feldes und unabhängig von der natürlichen Sprache des Angebots.

Zusätzliche Informationen können etwa Bilder bzw. Icons sein, die über zukünftig ggf. verfügbare Bedienungshilfen des Betriebssystems bereitgestellt werden könnten und beim jeweiligen Eingabefeld anstelle der Textbeschriftung angezeigt würden. Für Menschen, die Schwierigkeiten mit dem Lesen haben oder bevorzugt über Bilder kommunizieren, könnte dies eine Identifizierung von nutzerbezogenen Feldern in Formularen erleichtern. Hier liegen bislang kaum empirische Erfahrungen vor.

== Wie wird geprüft?

=== Anwendbarkeit des Prüfschritts

Der Prüfschritt ist prinzipiell dann anwendbar, wenn Formular-Eingabefelder sich auf Nutzerdaten beziehen (etwa Login / Anmeldung, Kontaktformulare,
oder Ansichten zum Anlegen eines Nutzerprofils). Des Weiteren muss das Betriebssystem die Auszeichnung des Eingabezwecks unterstützen.
Außerdem müsste in den Bedienungshilfen oder den Einstellungen zur Barrierefreiheit von Android bzw. iOS Optionen auftauchen, mit denen die Anzeige des Eingabezwecks aktiviert bzw.verscheidene Optionen dafür ein- und ausgeschaltet werden könnten.
Dies ist zur Zeit (Mai 2022) nicht der Fall. Damit ist dieser Prüfschritt zurzeit nur anwendbar, um die Anzeige angepasster Tastaturen für bestimmte Eingabefelder (E-Mail, numerische Eingabefelder) zu überprüfen. Dies ist jedoch eher ein Nebeneffekt der eigentlichen Anforderung, die sich auf die Eingabefelder selbst und nicht auf dynamisch angepasste Tastaturen bezieht.

=== Prüfung

. Eingabefelder für E-Mail-Adressen fokussieren. Wird die dafür optimierte Tastatur eingeblendet? Auf der dann erscheinenden Tastatur ist dann z. B. gleich das „``@``“-Zeichen und der Punkt verfügbar, ohne erst auf die Symboltastatur wechseln zu müssen.
. Falls numerische Eingabefelder vorhanden sind: Diese fokussieren. Wird eine für numerische Eingaben optimierte Tastatur eingeblendet? 


=== Hinweis

Die Anforderung gilt nur für Felder, die sich auf den Nutzer selbst beziehen. Sie gilt nicht für Seiten bzw. Ansichten, auf denen die Eingabe von
persönlichen Daten mehrerer Personen möglich ist und die Felder für den Nutzer selbst nicht besonders gekennzeichnet sind. Ein Beispiel dafür sind Ticketbuchungsseiten / -Apps von Fluglinien. Hier sind die Eingabefelder für den Nutzer nicht von den Feldern für Mitreisende unterscheidbar.

=== Bewertung

==== Prüfschritt erfüllt:

* Bei Eingabefeldern für E-Mail-Adressen erscheint bei Fokussierung eine angepasste Tastatur. Geschieht dies nicht, ist der Prüfschritt mit eher erfüllt zu bewerten - eine Eingabe ist ja dennoch möglich.
* Sobald Bedienungshilfen mobiler Betriebssysteme die (auch teilweise) Auszeichnung des Eingabezwecks unterstützen, wird bei Eingabefeldern, die unterstützt sind und die sich klar auf Nutzende selbst beziehen, die voreingestellte angepasste Darstellung des Eingabezwecks angezeigt.

== Einordnung des Prüfschritts

=== Einordnung des Prüfschritts nach WCAG 2.1

==== Guideline

* https://www.w3.org/TR/WCAG21/#adaptable[Guideline 1.3 Adaptable: Create
  content that can be presented in different ways (for example simpler layout)
  without losing information or structure.]

==== Success criterion

* https://www.w3.org/TR/WCAG21/#identify-input-purpose[1.3.5 Identify Input
  Purpose (Level AA)]

== Quellen

* https://www.w3.org/WAI/WCAG21/Understanding/identify-input-purpose.html[
Understanding Success Criterion 1.3.5: Identify Input Purpose (zur Zeit nur auf
Englisch verfügbar)]

* Android Developer Resources: https://developer.android.com/guide/topics/text/autofill-optimize[Optimize your app for autofill (zur Zeit nur auf
Englisch verfügbar)]

* [BLOCK_LANG_EN]#Apple Developer Resources#: https://developer.apple.com/documentation/security/password_autofill/[Password AutoFill (zur Zeit nur auf
Englisch verfügbar)] Die unterstützten Arten von Autofill-Daten sind sehr begrenzt und dienen zur Zeit hauptsächlich dazu, die Tastatur dynamisch anzupassen https://developer.apple.com/documentation/uikit/uitextinputtraits/1649656-textcontenttype[textContentType (zur Zeit nur auf
Englisch verfügbar)]
