= Prüfschritt 11.1.1.1b Textalternativen für Grafiken und Objekte
include::include/author.adoc[]
include::include/attributes.adoc[]

*Hinweis: Dies ist ein Entwurf. Inhalte können sich jederzeit ändern.*

== Was wird geprüft?

Informative Grafiken und Bilder müssen Textalternativen haben. Die Textalternativen ersetzen das Bild, sie sollen (soweit wie möglich) die gleiche Information vermitteln wie das Bild.

Bei eingebundenen Multimedia-Objekten, Video- beziehungsweise Audio-Dateien soll die Textalternative zumindest eine beschreibende Identifizierung des Inhalts ermöglichen.

== Warum wird das geprüft?

Für blinde Benutzer sind Grafiken und Bilder nicht zugänglich. Die Textalternative tritt dann an die Stelle der Grafik, sie soll die Grafik inhaltlich ersetzen können.

Wenn Objekte (etwa Video- oder Audio-Dateien) nicht angezeigt werden können, weil sie z. B. nicht geladen werden können, sollen kurze beschreibende Textalternativen dem Nutzer eine Identifikation der Inhalte ermöglichen.

== Wie wird das geprüft?

=== 1. Anwendbarkeit des Prüfschritts

Der Prüfschritt ist anwendbar, wenn informative Grafiken oder, Bilder, Video- oder Audio-Dateien oder Multimedia-Objekte vorhanden sind.

Als informative Grafiken gelten:

* grafische Schriften
* Abbildungen, die zeigen sollen, wie ein Objekt oder eine Person aussieht
* Illustrationen, die einen Gegenstand, ein Konzept oder einen Prozess vorstellen, verdeutlichen oder veranschaulichen sollen (etwa Diagramme)
* Symbole

Dekorative Grafiken und Bilder sind Grenzfälle. Sie stellen (im Unterschied zu Layoutgrafiken) etwas dar, der dargestellte Gegenstand hat auch meist einen Bezug zum Thema der App-Ansicht. Ihr Informationsgehalt und ihr Nutzen für das Verständnis ist aber nicht klar. Sie können daher als dekorativ gekennzeichnet werden, der Prüfschritt ist dann nicht anwendbar.

Wenn Logo-artige Elemente, in denen Grafik und Schrift verbunden sind, auftauchen, sind diese fast nie als bloße Schmuckgrafik anzusehen und brauchen deshalb eine Textalternative. Dies ermöglicht blinden und sehenden Nutzern, sich gemeinsam auf diese Elemente zu beziehen. Die Textalternative muss aber nicht expliziter sein als das, was für den sehenden Nutzer erkenntlich ist.

Darüber hinaus ist der Prüfschritt anwendbar, wenn informative Audio-Elemente vorhanden sind.

=== 2. Prüfung

Für eine Prüfung mit VoiceOver / iOS müssen die AI/OCR-Erkennungsfunktionen ausgeschaltet sein (siehe "3. Hinweise").

. App mit zu prüfender Ansicht starten.
. Prüfen, ob unverlinkte informationstragende Grafiken oder Multimedia-Inhalte vorhanden sind.
. Screenreader starten und Fokus auf jede informationstragende Grafik setzen.
. Prüfen, ob der Screenreader informationstragende Grafiken aussagekräftigen Alternativtext ausgibt.
. Bei komplexen Grafiken prüfen, ob der Alternativtext Inhalt knapp nennt und auf ausführliche Textalternativen im Kontext der Grafik verweist. Diese können etwa unterhalb der Grafik, in einem Ausklappbereich oder in einer verlinkten Ansicht vorgehalten werden.
. Prüfen, ob Schmuckgrafiken Alternativtexte tragen. Bei Grenzfällen (Grafiken haben einen beschreibbaren Inhalt mit Bezug zum Thema, sind aber zum Verständnis der Inhalte nicht wichtig) können sowohl Alternativtexte als das Fehlen von Alternativtext akzeptiert werden.

=== 3. Hinweise

==== Einstellungen für die Prüfung mit VoiceOver / iOS

Die AI/OCR-Erkennungsfunktionen von VoiceOver müssen ausgeschaltet sein:

* iOS 14+: Einstellungen > Bedienungshilfen > VoiceOver > VoiceOver-Erkennung. (Diese Funktion wird nur auf iPhone XS/XR-Modellen und höher unterstützt).
* iOS 13: Einstellungen > Bedienungshilfen > VoiceOver > Verbosität > Sprechen erkannt > Sprechen von erkanntem Text und Bildern


==== Angemessene Alternativtexte

Entscheidend ist: Die App soll benutzbar sein, wenn für Grafiken oder Bilder die entsprechenden Textalternativen vom Screenreader ausgegeben werden.

In der Regel bedeutet das:

* Bei Schriftgrafiken soll die Textalternative den Text der Schriftgrafik wiederholen.
* Bei Symbolen oder Zeichen (Logos) soll die Textalternative sagen, dass ein Symbol, Zeichen oder Logo abgebildet ist und die Bedeutung des Symbols oder Zeichens wiedergeben.
* Bei Gruppen von zusammengehörigen Bildern kann auch eines der Bilder die Bedeutung der Gruppe wiedergeben, die anderen sollten als dekorativ gekennzeichnet werden.
* Bei Fotos, Reproduktionen von Gemälden oder anderen Nicht-Text-Elementen, die eine spezifische Sinneserfahrung vermitteln, genügt in der Regel eine knappe Bezeichnung des abgebildeten Gegenstandes.
* Bei Diagrammen oder technischen Zeichnungen sind unter Umständen ausführlichere Erläuterungen erforderlich.
  Textalternativen sind dafür nicht geeignet, sie sollen in der Regel 80 Zeichen nicht überschreiten. In der Textalternative steht dann nur, was dargestellt ist und wo (etwa: "Details im anschließenden Text"). Die ausführliche Textalternative soll sich in Kontext des Bildes befinden. Der Kontext kann zum Beispiel ein unmittelbar folgender Inhalt (Text oder Tabelle), ein Ausklappbereich oder auch ein Link zu einer Ansicht sein, die die ausführliche Alternative enthält.
* Bei Objekten, die nicht angezeigt werden können, sollen die Textalternative oder Text im unmittelbaren Kontext des Objekts (etwa eine vorangehende Überschrift oder nachfolgende Legende) eine kurze Beschreibung oder Identifizierung bieten und, falls vorhanden, auf eine Medienalternative verweisen.

Generell gilt: Textalternativen sollen kurz sein. Ausführliche Beschreibungen von Abbildungen sollen nicht in die Textalternative, sondern im Kontext der Abbildung zur Verfügung gestellt werden.

==== Angemessenheit von Textalternativen im Kontext

Wenn die Textalternative kein angemessener Ersatz für die Grafik oder das Bild sein kann, muss geprüft werden, ob die über das Bild vermittelte Information im Kontext als Text zur Verfügung steht.

Das betrifft zum Beispiel

* Diagramme
* technische Zeichnungen
* Anfahrtspläne

Zum Kontext einer Grafik oder eines Bildes gehört: der dazugehörige (vorangehende, folgende) Text und eine im unmittelbaren Kontext des Bildes angebotene verlinkte und klar benannte Textalternative.

Eine kurze Textalternative mit Bezeichnung des Bildes ist auch bei Nutzung von Textalternativen im Kontext erforderlich. Die Textalternative sagt, dass an dieser Stelle etwas Bestimmtes abgebildet ist, sie macht klar, worauf sich die Erläuterung im Kontext bezieht.

==== Beurteilung der Angemessenheit ====

Um die Angemessenheit der Textalternative einschätzen zu können, muss die Textalternative auf die Grafik beziehungsweise das Objekt bezogen werden, zu dem sie gehört.
Erforderlich ist also die wechselnde Betrachtung von Grafik/Objekt und zugehörige Textalternative.

== Einordnung des Prüfschritts

=== Einordnung des Prüfschritts nach WCAG 2.1

==== Guideline

* http://www.w3.org/TR/WCAG21/#text-alternatives[Guideline 1.1 Text
  Alternatives: Provide text alternatives for any non-text
  content so that it can be changed into other forms people need, such as large
  print, braille, speech, symbols or simpler language]

==== Success Criterion

* http://www.w3.org/TR/WCAG21/#x1-1-1-non-text-content[1.1.1 Non-text Content
  (Level A)]

==== Techniques

===== General Techniques

* https://www.w3.org/WAI/WCAG21/Techniques/general/G73[G73: Providing a long
  description in another location with a link to it that is immediately adjacent
  to the non-text content]
* https://www.w3.org/WAI/WCAG21/Techniques/general/G74[G74: Providing a long
  description in text near the non-text content, with a reference to the
  location of the long description in the short description]
* https://www.w3.org/WAI/WCAG21/Techniques/general/G82[G82: Providing a text
  alternative that identifies the purpose of the non-text content]
* https://www.w3.org/WAI/WCAG21/Techniques/general/G92[G92: Providing long
  description for non-text content that serves the same purpose and presents
  the same information]
* https://www.w3.org/WAI/WCAG21/Techniques/general/G94[G94: Providing short
  text alternative for non-text content that serves the same purpose and
  presents the same information as the non-text content]
* https://www.w3.org/WAI/WCAG21/Techniques/general/G95[G95: Providing short
  text alternatives that provide a brief description of the non-text content]
* https://www.w3.org/WAI/WCAG21/Techniques/general/G100[G100: Providing the
  accepted name or a descriptive name of the non-text content]
* https://www.w3.org/WAI/WCAG21/Techniques/general/G196[G196: Using a text
  alternative on one item within a group of images that describes all items in
  the group]

==== Failures

* https://www.w3.org/WAI/WCAG21/Techniques/failures/F20[F20: Failure of
  Success Criterion 1.1.1 and 4.1.2 due to not updating text alternatives when
  changes to non-text content occur]
* https://www.w3.org/WAI/WCAG21/Techniques/failures/F30[F30: Failure of
  Success Criterion 1.1.1 and 1.2.1 due to using text alternatives that are
  not alternatives]
* https://www.w3.org/WAI/WCAG21/Techniques/failures/F65[F65: Failure of Success
Criterion 1.1.1 due to omitting the alt attribute on img elements, area
elements, and input elements of type 'image']
* https://www.w3.org/WAI/WCAG21/Techniques/failures/F67[F67: Failure of Success
  Criterion 1.1.1 and 1.2.1 due to providing long description for non-text content
  that does not serve the same purpose or does not present the same information]

=== Abgrenzung zu anderen Prüfkriterien

* Textalternative für verlinkte Grafiken (z.B. Bedienelemente oder 
  Teaser-Bilder)
  werden in Prüfschritt
ifdef::env_embedded[11.1.1.1a "Textalternativen für Bedienelemente"]
ifndef::env_embedded[]
  <<11.1.1.1a Alternativtexte für Bedienelemente.adoc#,11.1.1.1a Textalternativen
  für Bedienelemente>>
endif::env_embedded[]
  geprüft.

* Einfache Animationen oder Videos ohne synchronisierungsbedürftige Tonspur
  werden in Prüfschritt
ifdef::env_embedded[11.1.2.1a "Alternativen für Audiodateien und stumme Videos"]
ifndef::env_embedded[]
  <<11.1.2.1 Alternativen für Audiodateien und stumme Videos.adoc#,11.1.2.1
  Alternativen für Audiodateien und stumme Videos>>
endif::env_embedded[]
  geprüft.

* Layout-Grafiken oder dekorative Grafiken werden in
  Prüfschritt
ifdef::env_embedded[11.1.1.1c "Leere alt-Attribute für Layoutgrafiken"]
ifndef::env_embedded[]
  <<11.1.1.1c Leere alt-Attribute für Layout-Grafiken.adoc#,11.1.1.1c Leere
  alt-Attribute für Layout-Grafiken>>
endif::env_embedded[]
  geprüft.

* CAPTCHAs werden in Prüfschritt
ifdef::env_embedded[11.1.1.1d "Alternativen für CAPTCHAs"]
ifndef::env_embedded[]
  <<11.1.1.1d Alternativen für CAPTCHAs.adoc#,11.1.1.1d Alternativen für
  CAPTCHAs>>
endif::env_embedded[]
  geprüft.
  
== Quellen
=== Android
https://appt.org/en/docs/android/samples/accessibility-label[Appt.org: Accessibility label on Android]

=== iOS
https://appt.org/en/docs/ios/samples/accessibility-label[Appt.org: Accessibility label on iOS]

=== Anleitungen zum Erstellen guter Alternativtexte

* W3C Web Accessibility Tutorials:
  https://www.w3.org/WAI/tutorials/images/[Images Concepts]
* WebAIM: https://webaim.org/techniques/alttext/[Alternative Text]
