= Prüfschritt 11.1.4.4 Text auf 200% vergrößerbar
include::include/author.adoc[]
include::include/attributes.adoc[]

*Hinweis: Dies ist ein Entwurf. Inhalte können sich jederzeit ändern.*

== Was wird geprüft?

Die Textgröße der App soll auf bis zu 200 Prozent vergrößert werden können, ohne dass dabei Inhalt oder Funktionalität verloren gehen. 
iOS / iPadOS biteten hierfür die systemseitige Bedienungshilfe Zoom, Android nennt diese Funktion Vergrößerung. Beide bis zu 500% Zoom, also deutlich mehr als 200%. Sie heißt Zoom (iOS) bzw. Vergrößerung (Android). Gesten erlauben die Aktivierung der vergrößerten Ansicht und eine Änderung des Zoomfaktors. Der Prüfschritt ist damit grundsätzlich erfüllt, wenn bei Nutzung der App die diese Bedienungshilfen nutzbar sind.

Die Verfügbarkeit einer systemseitigen Zoomfunktion ist gut, aber das Lesen von vergrößertem Text ist bei Vergrößerung sehr mühsam, da der sichtbare Ausschnitt verschoben werden muss, um den Text zu lesen oder andere Bereiche der Ansicht über Ziehgesten in diesen Ausschnitt zu bewegen. Deshalb ist der Einsatz von Systemschriften (bei iOS Dynamit Fonts) hilfreich, die bei einer geänderten System-Einstellung der Schriftgröße die Schrift auch in der App größer darstellen. Selbst in Apps, die Systemschriften einsetzen und die eingestellte Vergrößerung übernehmen, werden meist nicht alle Textelemente dynamisch umgesetzt, da dies häufig entweder dazu führen würde, dass entweder Zusammenhang und Übersichtlichkeit durch den Umbruch von Inhalten verschlechtert wird oder dazu, dass Textinhalte abgeschnitten bzw. durch Elipsen abgekürzt werden müssten. Eine läckenlose Anwenduing des eingestellten Schriftvergrößerung aud allen Inhalten ist deshlab nicht praktikabel.
Der Einsatz von Systemschriften ist überall empfehlenswert, wo Umbrüche gut möglich sind, etwa bei Fließtexten. Die Nichtumsetzung wird kedoch in diesem Prüfschritt nicht negastiv bewertet, solange die systemseitige Zoomvergrößerung der bedineungshilfen erwartungsgemäß funktioniert.

== Warum wird das geprüft?

Nutzende sollen die Schriftgröße nach ihren Bedürfnissen einstellen können. besonders ältere Menschen aber auch Menschen mit leichten Sehbehinderungen, brauchen einen vergrößerten Text. Die geforderten 200% reichen für viele stärker sehbehinderte Menschen nicht aus. Hier muss dann ohnehin die Zooomvergrößerung genutzt werden, die stärker vergrößert. 

== Wie wird geprüft?

=== 1. Anwendbarkeit des Prüfschritts

Der Prüfschritt ist anwendbar, wenn die App-Ansicht Text enthält.

=== 2. Prüfung

==== 2.1 Prüfung der Schriftvergrößerung mit Hilfe der Betriebssystem-Einstellungen

. Zoom-Funktionalität in den Bedienungshilfen von iOS / iPadOS bzw. Android aktivieren
. App mit zu prüfender Ansicht öffnen
. Ansicht mittels der Zoomfunktion des Betriebssystems um 200% vergrößern. Wirkt sich die Funktion auf die Darstellung der App aus? Es wird nicht negativ bewertet wenn Inhalte bei Zoomvergrößerung nicht mehr voll in den Viewport pasen oder nur durc hVerscheiben des Ausschnitss erreichbar sind - nur, dass der Zoom überhaupt funktioniert. Das ist in der Regel der Fall. 

==== 2.2 Prüfung der Übernahme von systemseitigen Einstellungen vergrößerter Schrift

===== iOS
. Schriftgröße über Einstellungen / Bedienungshilfen / Anzeige & Textgröße / Größerer Text auf einen deutlich größeren Wert (ca. doppelt so groß) stellen. (Der genaue Vergößerungsfaktor wird ggf. nicht angezeigt). Wirkt sich die Vergrößerung auf Texte der App aus?

===== Android
. Schriftgröße bei Einstellungen / Eingabehilfe / Verbesserungen der Sichtbarkeit / Schriftgröße und -Stil auf einen deutlich größeren Wert (ca. doppelt so groß) stellen. (Der genaue Vergößerungsfaktor wird ggf. nicht angezeigt). Wirkt sich die Vergrößerung auf Texte der App aus?

==== 2.3 Prüfung der Schriftvergrößerung durch Bedienelemente in der App (optional)

Falls die Software eigene Bedienelemente bereithält, um die Schriftgröße zu vergrößern:

. Prüfen, ob die Schrift mit Hilfe der angebotenen Bedienelemente schrittweise vergrößert werden kann
. Prüfen, ob sich über die angebotenen Bedienelemente die Ausgangsschriftgröße wiederherstellen lässt

=== 3. Hinweise

* Je nach Gerätehersteller können Bedienungshilfen unter Android auch abweichende Namen tragen.
* Wenn die Prüfung unter 2.2 ergibt, dass die App systemseitige Nutzer-Einstellungen vergrößerter Schrift nicht übernimmt, sollte dies angemerkt werden. Der Prüfschritt ist aber dennoch erfüllt, wenn die Zoomvergrößerung funktioniert.  Die Prüfung ist dennoch sinnvoll, um Entwicklern Hinweise auf Verbesserungsmöglichkeiten zu geben. Die Unterstützung von Systemschriften / dynamic fonts ist für alle Inhaltsbereiche sinnvoll, die bei Vergrößerung problemlos umberechen können, z.B. Fließtexte. In anderen Fällen ist die Umsetzbarkeit abhängig vom generellen Layout-Konzept der Anwendung. Passen etwa fünf Reiter mit Text in eine Reiterleiste am Seitenfuß, wäre es ggf. nicht gut möglich, diese dynamisch vergrößerbar zu machen, ohne dass ein Umbruch der Reiterleiste stattfände oder Texte abgekürzt würden.
* Wenn die Prüfung unter 2.3 ergibt, dass die eigene Textvergrößerungseinstellungen der App nicht gut funktionieren, sollte dies angemerkt werden. Der Prüfschritt ist aber dennoch erfüllt, wenn die Zoomvergrößerung funktioniert.

=== 4. Bewertung

==== Erfüllt:

* Die Ansicht lässt sich mittels der systemseitigen Zoom-Funktion in den Bedienungshilfen auf 200 % vergrößern.

==== Eher erfüllt:
* Bei der App erfolgt keine Übernahme von systemseitigen Einstellungen vergrößerter Schrift bei Elementen. wo diese gut umsetzbar wäre, etwa Fließtext.
* Eigene Schriftvergrößerungsfunktionen der App weisen Probleme auf.

== Einordnung des Prüfschritts

=== Abgrenzung zu anderen Prüfkriterien

Mangelnde Vergrößerbarkeit von Schriftgrafiken:
siehe Prüfschritt
ifdef::env_embedded[11.1.4.5 "Verzicht auf Schriftgrafiken".]
ifndef::env_embedded[]
  <<11.1.4.5 Verzicht auf Schriftgrafiken.adoc#,11.1.4.5 Verzicht auf
  Schriftgrafiken>>.
endif::env_embedded[]

=== Einordnung des Prüfschritts nach WCAG 2.1

==== Guideline

* https://www.w3.org/TR/WCAG21/#distinguishable[Guideline 1.4 Distinguishable:
  Make it easier for users to see and hear content including separating
  foreground from background]

==== Success criterion

* https://www.w3.org/TR/WCAG21/#resize-text[1.4.4 Resize text (Level AA)]

==== Techniques

.General Techniques
* https://www.w3.org/WAI/WCAG21/Techniques/general/G146.html[G146: Using
  liquid layout]
* https://www.w3.org/WAI/WCAG21/Techniques/general/G178.html[G178: Providing
  controls on the Web page that allow users to incrementally change the size
  of all text on the page up to 200 percent]
* https://www.w3.org/WAI/WCAG21/Techniques/general/G179.html[G179: Ensuring
  that there is no loss of content or functionality when the text resizes and
  text containers do not change their width]

==== Failures

* https://www.w3.org/WAI/WCAG21/Techniques/failures/F69.html[F69: Failure of
  Success Criterion 1.4.4 when resizing visually rendered text up to 200
  percent causes the text, image or controls to be clipped, truncated or obscured]
* https://www.w3.org/WAI/WCAG21/Techniques/failures/F80.html[F80: Failure of
  Success Criterion 1.4.4 when text-based form controls do not resize when visually rendered text is resized up to 200%]

== Quellen


