= Prüfschritt 11.1.4.10 Inhalte brechen um
include::include/author.adoc[]
include::include/attributes.adoc[]

*Hinweis: Dies ist ein Entwurf. Inhalte können sich jederzeit ändern.*

== Was wird geprüft?

Inhalte sollen bei einer Viewport-Breite von 320 CSS Pixeln so angezeigt werden, dass alle Informationen und Funktionen verfügbar sind, ohne dass Nutzer horizontal scrollen müssen.  Die Inhalte mobiler Aps sind meist standardmäßig für die Ansicht im Hochkantformat optimiert, auch wenn die heute verbreiteten Mobilgeräte meist einen größere Viewportbreite als 320 px haben. Damit ist dieser Prüfschritt in der Regel erfüllt. 

Native Apps, auch die gängigen Browser, verfügen in der Regel nicht über die Möglichkeit, innerhalb der App die Textgröße zu ändern, wie dies über die Zoom-Funktion in Desktop-Browsern geschieht und damit oft den Umburch in eine andere Darstellung auslöst. Manche Apps zeigen einen anderen Umbruch der Inhalte, wenn das Gerät ins Querformat gedreht wird oder wenn die App auf einem Tablet mit größerer Viewportbreite angezeigt wird. Aus dem normativen Text ist jedoch keine Verpflichtung abzuleiten, dass für größere Viewportbreiten eine an diese angepasste Ansicht geboten werden muss.

Ausnahmen von die Anforderung, dass Informationen und Funktionen innerhalb der Viewportbreite vpn 320px verfügbar sind, gibt es für Inhalte, für deren Nutzung ein zweidimensionales Layout erforderlich ist und die ggf. auf Viewportbreite verkleinert nicht sinnvoll nutzbar sind, z.B.:

* Bilder
* Landkarten
* Diagramme
* Videos
* Spiele
* Präsentationen
* Datentabellen 
* Anwendungs-Schnittstellen
+
In denen die Bearbeitung von Inhalten die permanente Verfügbarkeit von
Werkzeugleisten erfordert.

*Hinweis:*
Dieser Prüfschritt beschränkt sich auf Inhalte, deren primäre
Schreibrichtung waagerecht ist, wie bei der für die meisten westlichen
Sprachen benutzten lateinischen Schrift.
Die zugrunde liegende WCAG-Anforderung gilt in ähnlicher Weise für Inhalte
mit vertikaler Schreibrichtung.

Bei Software, die für einen horizontalen Bildlauf (z. B. mit vertikalem Text)
ausgelegt ist, entspricht die Höhe des starting Viewports von 1024 px bei
400% Zoom.

== Warum wird das geprüft?

Bei mobilen Apps wird mit Systemfunktionen der Bildschirmausschnitt
vergrößert, hierbei wird jedoch Text nicht umgebrochen und der Prüfschritt
ist so nicht anwendbar.
Falls das System eine Nur-Text-Vergrößerung anbietet, sollte der Text in der
Anwendung korrekt umbrechen.

== Wie wird geprüft?

=== Anwendbarkeit des Prüfschritts

Laut EN 301 549 Version 3.1.1 ist dieser Prüfschritt auf Software anwendbar.
Wie dies jedoch umgesetzt werden soll, ist unklar.
Ggf. gibt es in zukünftigen Versionen der mobilen Betriebssysteme eine
entsprechende Bedienungshilfe zum Umbrechen von Text, die ein- und
ausgeschaltet werden kann.
Dann müssen Apps diese Systemschnittstelle unterstützen.

=== Prüfung

Wie dieser Prüfschritt bei nativer Software geprüft werden kann muss noch
geklärt werden.
Wenn vom Betriebssystem eine Bedienungshilfe zum umbrechen von Text
zur Verfügung gestellt wird, sollten Apps mit der entsprechenden Funktion
umgehen bzw. zugehörige Methoden implementieren, um diese
systemseitige Funktion zu unterstützen.

Für Hinweise zur Prüfpraxis können Sie auf GitHub
https://github.com/BIK-BITV/BIK-App-Test/issues[ein Issue] zur diesem
Prüfschritt erstellen.

=== Hinweise

Bei der alternativen Prüfung mit 1280px Viewport-Breite und 400% Zoom soll
nicht negativ bewertet werden, wenn fest positionierte Inhalte (etwa
Ausklappmenüs) aufgrund der sehr geringen verfügbaren Höhe des Viewports
nicht voll erreichbar sind.
Geprüft wird allein, ob Inhalte erfolgreich in eine Ansicht umbrechen, die
nicht horizontal gescrollt werden braucht.

Ausnahmen für die Anforderung, dass horizontales Scrollen nicht erforderlich
ist, sind Inhalte, deren Nutzung ein zweidimensionales Layout voraussetzen,
etwa Datentabellen, Bilder, Diagramme, Videos, Spiele oder
Benutzerschnittstellen mit Werkzeugleisten.

Im Prüfschritt wird nicht geprüft, ob die Zoomvergrößerung auf 400%
Textinhalte tatsächlich auf 400% oder einen geringeren Wert vergrößert.
Dies ist Gegenstand von Prüfschritt
ifdef::env_embedded[]
11.1.4.4 "Text auf 200% vergrößerbar".
endif::env_embedded[]
ifndef::env_embedded[]
<<11.1.4.4 Text auf 200% vergrößerbar.adoc#,11.1.4.4 Text auf 200%
vergrößerbar>>.
endif::env_embedded[]

// === Bewertung

== Quellen

https://www.w3.org/WAI/WCAG21/Understanding/reflow.html[Understanding Reflow]
(zur Zeit nur auf Englisch verfügbar)
