= Prüfschritt 11.1.2.2 Aufgezeichnete Videos mit Untertiteln
include::include/author.adoc[]
include::include/attributes.adoc[]

*Hinweis: Dies ist ein Entwurf. Inhalte können sich jederzeit ändern.*

== Was wird geprüft?
Wenn die Tonspur eines aufgezeichneten Videos Informationen enthält, müssen Untertitel als Alternative bereitgestellt werden.

== Warum wird das geprüft?

Filme sind in der Regel ohne den Ton nicht zu verstehen. Daher muss für Menschen mit Hörbehinderung der Inhalt der Tonspur durch Untertitel bereitgestellt werden.

Untertitel können auch für andere Nutzende hilfreich sein, zum Beispiel für Personen, die mit der Sprache des Films nicht vertraut sind.

== Wie wird geprüft?

=== 1. Anwendbarkeit des Prüfschritts

Der Prüfschritt ist anwendbar, wenn aufgezeichnete Videos mit synchroner Bild- und Tonspur vorhanden sind.

Aufgezeichnete Videos ohne Tonspur brauchen keine Untertitel, der Prüfschritt ist für sie nicht anwendbar.
Alternativen für Videos ohne Tonspur werden in Prüfschritt
ifdef::env_embedded[11.1.2.1 "Alternativen für Audiodateien und stumme Videos"]
ifndef::env_embedded[]
  <<11.1.2.1 Alternativen für Audiodateien und stumme Videos.adoc#,1.2.1
  Alternativen für Audiodateien und stumme Videos>>
endif::env_embedded[]
geprüft.

=== 2. Prüfung
==== 2.1 Prüfung von Untertiteln

. App mit zu prüfender Ansicht starten.
. Das Video in der App abspielen.
. Prüfen, ob parallel zum Video Untertitel automatisch angezeigt werden oder zugeschaltet werden können.
. Wenn Untertitel vorhanden sind, eine kurze Sequenz des Videos mit Untertiteln ansehen, um stichprobenartig festzustellen, ob die Untertitel dem hörbaren Inhalt entsprechen. Dies betrifft auch akustische Ereignisse, die für das Verständnis des Inhalts wichtig sind.

==== 2.2 Prüfung von Videos als Medienalternative

. Falls keine Untertitel vorhanden sind: Prüfen, ob das Video als ergänzende Medienalternative zu einem Text angeboten wird.
. Prüfen, ob die Beschriftung des Videos klar auf eine dazugehörige Textversion verweist und diese entweder in unmittelbarer Nachbarschaft verfügbar ist oder durch einen aussagekräftigen Link erreichbar ist.
. Prüfen, ob das Video alle wesentlichen Inhalte des Textes über den Ton transportiert.
. Wenn das Video wichtige über den Textinhalt hinausgehende Informationen trägt, ist das Video keine Medienalternative, es braucht Untertitel und muss auch auf Audiodeskription geprüft werden (siehe auch Prüfschritt 
ifdef::env_embedded[11.1.2.5 "Audiodeskription für Videos"]
ifndef::env_embedded[]
  <<11.1.2.5 Audiodeskription für Videos.adoc#,11.1.2.5 Audiodeskription für
  Videos>>
endif::env_embedded[]
).

=== 3. Bewertung

==== Erfüllt

* Aufgezeichnete Videos mit synchroner Bild- und Tonspur haben erweiterte Untertitel, die alle Informationen der Tonspur enthalten. Dazu gehört gegebenenfalls die Anzeige, wer spricht, und bedeutungstragende Tonereignisse (etwa informationstragende Geräusche, Lachen, oder Applaus).

==== Teilweise erfüllt

* Aufgezeichnete Videos mit synchroner Bild- und Tonspur haben keine Untertitel, es gibt aber im unmittelbaren Kontext des Videos eine vollständige Textalternative (Transkription) oder einen klar bezeichneten Link zu einer vollständigen Textalternative.
Wenn das Videobild Inhalte hat, die nicht in der Transkription vorkommen oder nicht adäquat darstellbar sind, kommen die Abstufungen der Bewertung von eher nicht erfüllt bis nicht erfüllt in Betracht.
* Bei Medienalternativen fehlt die direkte Nachbarschaft oder der klar bezeichnete Link auf das primäre Medium, dass die Medienalternative ersetzt.

==== Nicht erfüllt:

* Aufgezeichnete Videos sind ohne Untertitel, eine Textalternative ist ebenfalls nicht verhanden.

== Quellen
=== Allgemein
* WCAG 2.1: https://www.w3.org/WAI/WCAG21/Understanding/captions-prerecorded[Understanding SC 1.2.2 Captions (Prerecorded)]
* Appt.org: https://appt.org/en/guidelines/wcag/success-criterion-1-2-2#add-captions[Captions (Prerecorded): Add captions] (mehrere Entwicklungsumgebungen)

=== iOS
* Appt.org: https://appt.org/en/docs/ios/samples/captions[Captions on iOS]

=== Android
* Appt.org: https://appt.org/en/docs/android/samples/captions[Captions on Android]

== Einordnung des Prüfschritts

=== Abgrenzung zu anderen Prüfschritten

==== Live-Videos

Die Untertitelung von Live-Videos wird in Prüfschritt
ifdef::env_embedded[11.1.2.4 "Videos (live) mit Untertiteln"]
ifndef::env_embedded[]
  <<11.1.2.4 Videos (live) mit Untertiteln.adoc#,11.1.2.4 Videos (live) mit
  Untertiteln>>
endif::env_embedded[]
geprüft.

==== Stumme Videodateien

Bei diesem Prüfschritt geht es um die synchrone Vermittlung von visuellen und
akustischen Informationen.
Der Prüfschritt ist relevant, wenn für das Verständnis eines Elements die
parallele Wahrnehmung von Bild und Ton erforderlich ist.
Ein einfacher Alternativtext oder eine zusammenfassende Beschreibung ist dann
nicht (mehr) ausreichend.
Stumme Video-Dateien werden im Prüfschritt 
ifdef::env_embedded[11.1.2.1 "Alternativen für Audiodateien und stumme Videos"]
ifndef::env_embedded[]
  <<11.1.2.1 Alternativen für Audiodateien und stumme Videos.adoc#,11.1.2.1
  Alternativen für Audiodateien und stumme Videos>>
endif::env_embedded[]
geprüft.

==== Alternativtexte für Objekte

Alternativtexte für Multimedia-Objekte, etwa Video- oder Audio-Dateien oder
Applets, werden in Prüfschritt
ifdef::env_embedded[11.1.1.1b "Alternativtexte für Grafiken und Objekte"]
ifndef::env_embedded[]
  <<11.1.1.1b Alternativtexte für Grafiken und Objekte.adoc#,11.1.1.1b
  Alternativtexte für Grafiken und Objekte>>
endif::env_embedded[]
geprüft.

=== Einordnung des Prüfschritts nach WCAG 2.1

==== Guideline

* https://www.w3.org/TR/WCAG21/#time-based-media[Guideline 1.2 Time-based Media:
  Provide alternatives for time-based media]

==== Success criteria

* https://www.w3.org/TR/WCAG21/#captions-prerecorded[1.2.2 Captions
  (Prerecorded) (Level A)]

==== Techniques

.General Techniques
* https://www.w3.org/WAI/WCAG21/Techniques/general/G87[G87: Providing closed
  captions]
* https://www.w3.org/WAI/WCAG21/Techniques/general/G93[G93: Providing open
  (always visible) captions]

==== Failures

* https://www.w3.org/WAI/WCAG21/Techniques/failures/F8[F8: Failure of Success
  Criterion 1.2.2 due to captions omitting some dialogue or important sound
  effects]
* https://www.w3.org/WAI/WCAG21/Techniques/failures/F74[F74: Failure of SC1.2.2
  and 1.2.8 due to not labeling a synchronized media alternative to text as an
  alternative]
* https://www.w3.org/WAI/WCAG21/Techniques/failures/F75[F75: Failure of
  Success Criterion 1.2.2 by providing synchronized media without
  captions when the synchronized media presents more information than is
  presented on the page]


== Fragen zu diesem Prüfschritt

=== Gebärdensprache

Können an Stelle der Untertitel auch Filme mit gebärdensprachlicher Darstellung eingeblendet werden?

Solche Filme sind hilfreich für Personen, die über Gebärdensprache kommunizieren. Meist sind das Personen, die gehörlos geboren oder schon früh ertaubt sind. Dagegen können Personen, die erst im Alter ertaubt sind, in der Regel nicht über Gebärdensprache kommunizieren. Sie benötigen Untertitel. Gebärdensprachliche Darstellungen sind also kein Ersatz für die Untertitel.
