= Prüfschritt 11.1.4.1 Ohne Farben nutzbar
include::include/author.adoc[]
include::include/attributes.adoc[]

== Was wird geprüft?

Über Farben vermittelte Informationen sollen auch ohne Wahrnehmung der Farbe verfügbar sein, also zusätzlich durch andere Mittel (etwa Fettung oder Einrückung) hervorgehoben sein.

== Warum wird das geprüft?

Ausschließlich über Farben vermittelte Informationen sind für blinde Nutzende nicht zugänglich. Auch farbfehlsichtige Nutzende, die unter Umständen mit eigenen Farbschemata
arbeiten, können Farben nicht oder nur eingeschränkt identifizieren und unterscheiden.

== Wie wird geprüft?

=== 1. Anwendbarkeit des Prüfschritts

Der Prüfschritt ist immer anwendbar.

=== 2. Prüfung

Vermittlung von Informationen über die Farbgebung

Prüfen, ob die App-Ansicht Elemente enthält, die durch Farbgebung Informationen vermittelt.
Beispiele dafür:

* Überschriften werden farblich hervorgehoben
* Ausgewählte Menueinträge werden in einer anderen Farbe dargestellt
* Links im Fließtext werden in einer anderen Farbe dargestellt
* Eine Grafik verwendet unterschiedliche Farben für die vergleichende
  Darstellung des Kursverlaufs verschiedener Aktien
* Pflichtfelder in Formularen werden farblich gekennzeichnet (die gelb
  unterlegten Felder müssen immer ausgefüllt werden)

Solche Hervorhebungen sind positiv.
Die Vermittlung wichtiger Informationen soll sich aber nicht *ausschließlich* auf einfache Farbänderungen stützen.
Zu prüfen ist also, ob die Informationen zusätzlich noch auf einem anderen Weg vermittelt werden.
Beispiele für zusätzliche Vermittlung:

* Überschriften sind zusätzlich eingerückt oder durch eine andere Schriftgröße hervorgehoben (das ist fast immer der Fall)
* Ausgewählte Menueinträge sind zusätzlich mit einer Markierung versehen
* Links im Fließtext sind nicht nur farblich abgesetzt, sondern zusätzlich unterstrichen, gefettet, invertiert oder mit einer Markierung versehen.
  Ausnahme: Das Kontrastverhältnis zwischen Linkfarbe und umgebender Textfarbe und zwischen Linkfarbe und Hintergrund ist 3:1 oder besser.
  In diesem Fall kann im Ausgangszustand auf die zusätzliche Hervorhebung verzichtet werden. Die Links müssen dann aber bei Fokuserhalt zusätzlich hervorgehoben werden.
* Linien in Schaubildern sind zusätzlich gestrichelt oder durchgezogen
* Flächen haben unterscheidbare Muster
* Pflichtfelder im Formular sind zusätzlich mit einem Stern (mit Bedeutungserklärung am Formularbeginn) oder textlich ("Pflichtfeld") gekennzeichnet

Ebenfalls andere, zusätzliche Vermittlungswege sind am Beispiel der Hervorhebung der aktuell ausgewählten Menüoption erkennbar:

* der Breadcrumb zeigt, welche Seite ausgewählt ist
* die Überschrift ist stets gleichlautend mit der ausgewählten Menüoption

Ebenfalls nicht als einfache Farbunterschiede gelten:

* die farbige Hinterlegung von Elementen (denn eine Form kommt dazu oder
  ändert sich)
* der Austausch von Vorder- und Hintergrundfarbe (denn wenn überhaupt ein
  Unterschied von Vorder- und Hintergrund wahrgenommen wird, ist auch der
  Austausch wahrnehmbar)

== Einordnung des Prüfschritts

=== Abgrenzung zu anderen Prüfkriterien

. Abgrenzung zur Prüfung der Kontraste
+
In diesem Prüfschritt geht es nicht um die Prüfung der Kontraste.
Dies ist Aufgabe der Prüfkriterien
ifdef::env_embedded[11.1.4.3 "Kontraste von Texten ausreichend"]
ifndef::env_embedded[]
  <<11.1.4.3 Kontraste von Texten ausreichend.adoc#,11.1.4.3 Kontraste von Texten
  ausreichend>>
endif::env_embedded[]
und
ifdef::env_embedded[11.1.4.11 "Kontraste von Grafiken und Bedienelementen ausreichend".]
ifndef::env_embedded[]
  <<11.1.4.11 Kontraste von Grafiken und Bedienelementen ausreichend.adoc#,11.1.4.11
  Kontraste von Grafiken und Bedienelementen ausreichend>>.
endif::env_embedded[]

. Abgrenzung zum Prüfschritt 11.1.3.3 "Ohne Bezug auf sensoriesche Merkmale
  nutzbar"
+
In diesem Prüfschritt geht es nicht um die Prüfung von Verweisen auf
Seiteninhalte mit Hilfe der Angabe von Farben.
Die sinnesunabhängige Bereitstellung von Verweisen auf Inhalte wird im
Prüfschritt
ifdef::env_embedded[11.1.3.3 "Ohne Bezug auf sensorische Merkmale nutzbar"]
ifndef::env_embedded[]
  <<11.1.3.3 Ohne Bezug auf sensorische Merkmale nutzbar.adoc#,11.1.3.3 Ohne Bezug
  auf sensorische Merkmale nutzbar>>
endif::env_embedded[]
geprüft.

. Abgrenzung zu fehlenden Hervorhebungen
+
In diesem Prüfschritt 1.4.1a geht es um die Farbunabhängigkeit vorhandener
UI-Elemente.
+
Eine negative Bewertung ist also beispielsweise angebracht, wenn Links im Text
nur durch die Farbe (und nicht zusätzlich durch Unterstreichung, Fettung oder
vorangestellte Markierung) gekennzeichnet sind.
Wenn Links im Text überhaupt nicht gekennzeichnet sind, ist der Prüfschritt
dagegen nicht anwendbar.
Das ist dann vielmehr ein Verstoß gegen Prüfschritt
ifdef::env_embedded[11.2.4.7 "Aktuelle Position des Fokus deutlich".]
ifndef::env_embedded[]
  <<11.2.4.7 Aktuelle Position des Fokus deutlich.adoc#,11.2.4.7 Aktuelle Position
des Fokus deutlich>>.
endif::env_embedded[]
+
Entsprechend bei der Kennzeichnung der aktuellen Menüposition:
Ein App-Inhalt, der die aktuelle Position überhaupt nicht anzeigt, verstößt
somit noch nicht gegen diesen Prüfschritt 11.1.4.1.

=== Einordnung des Prüfschritts nach WCAG 2.1

==== Guidelines

* https://www.w3.org/TR/WCAG21/#distinguishable[Guideline 1.4 Distinguishable:
  Make it easier for users to see and hear content including separating
  foreground from background]

==== Success criteria

* https://www.w3.org/TR/WCAG21/#use-of-color[1.4.1 Use of Color (Level A)]

==== Techniques

.General Techniques
* https://www.w3.org/WAI/WCAG21/Techniques/general/G14.html[G14: Ensuring that
  information conveyed by color differences is also available in text]
* https://www.w3.org/WAI/WCAG21/Techniques/general/G111.html[G111: Using color
  and pattern]
* https://www.w3.org/WAI/WCAG21/Techniques/general/G182.html[G182: Ensuring
  that additional visual cues are available when text color differences are
  used to convey information]
* https://www.w3.org/WAI/WCAG21/Techniques/general/G183.html[G183: Using a
  contrast ratio of 3:1 with surrounding text and providing additional visual
  cues on focus for links or controls where color alone is used to identify
  them]
* https://www.w3.org/WAI/WCAG21/Techniques/general/G205.html[G205: Including a
  text cue for colored form control labels]

==== Failures

* https://www.w3.org/WAI/WCAG21/Techniques/failures/F13.html[F13: Failure of
  Success Criterion 1.4.1 due to having a text alternative that does not
  include information that is conveyed by color differences in the image]
* https://www.w3.org/WAI/WCAG21/Techniques/failures/F73.html[F73: Failure of
  Success Criterion 1.4.1 due to creating links that are not visually evident
  without color vision]
* https://www.w3.org/WAI/WCAG21/Techniques/failures/F81.html[F81: Failure of
  Success Criterion 1.4.1 due to identifying required or error fields using
  color differences only]

== Quellen

=== Use of Color: Understanding SC 1.4.1

[.BLOCK_LANG_EN]
--
The intent of this Success Criterion is to ensure that all users can access
information that is conveyed by color differences, that is, by the use of
color where each color has a meaning assigned to it.
If the information is conveyed through color differences in an image (or other
non-text format), the color may not be seen by users with color deficiencies.
In this case, providing the information conveyed with color through another
visual means ensures users who cannot see color can still perceive the
information.

Color is an important asset in design of Web content, enhancing its aesthetic
appeal, its usability, and its accessibility.
However, some users have difficulty perceiving color.
People with partial sight often experience limited color vision, and many
older users do not see color well.
In addition, people using text-only, limited-color or monochrome displays and
browsers will be unable to access information that is presented only in color.

Examples of information conveyed by color differences:

* "required fields are red"
* "error is shown in red"
* "Mary's sales are in red, Tom's are in blue"

Examples of indications of an action include:
using color to indicate that a link will open in a new window or that a
database entry has been updated successfully.
An example of prompting a response would be:
using highlighting on form fields to indicate that a required field had been
left blank.

Note: This should not in any way discourage the use of color on a page, or
even color coding if it is redundant with other visual indication.
--

Quelle: https://www.w3.org/WAI/WCAG21/Understanding/use-of-color.html

== Fragen zu diesem Prüfschritt

=== Besuchte Links

Häufig werden besuchte Links in einer anderen Farbe dargestellt.
Fällt das auch unter diesen Prüfschritt?

Die Unterscheidung besuchter und nicht besuchter Links ist hilfreich.
Der Benutzer kann gleich sehen, welche Seiten er schon besucht hat.
Ideal wäre es daher, wenn besuchte Links zum Beispiel zusätzlich durch eine
andere Unterstreichung markiert würden.

Aber die verfügbaren Gestaltungsmöglichkeiten sind begrenzt.
Und zu viele unterschiedliche Kennzeichnungen von Links können auch
Verwirrung stiften.

In diesem Prüfschritt des BITV-Tests wird die Kennzeichnung besuchter Links
nicht berücksichtigt, sie ist für die Bewertung nicht relevant.
