= Prüfschritt 11.1.4.3 Kontraste von Texten ausreichend
include::include/author.adoc[]
include::include/attributes.adoc[]

== Was wird geprüft?

Alle Texte der App-Ansicht sollen ausreichende Helligkeitskontraste haben.

== Warum wird das geprüft?

Wenn Vordergrund- und Hintergrundfarbe keinen ausreichenden Helligkeitsunterschied haben, haben Texte zu wenig Kontrast. Gute Kontraste sorgen dafür, dass Nutzende Texte leichter lesen können. Insbesondere Menschen, die aufgrund einer reduzierten Sehschärfe, einer Farbfehlsichtigkeit oder aufgrund des Alters eine verminderte Kontrastempfindlichkeit haben, profitieren von guten Kontrasten.

== Wie wird geprüft?

=== 1. Anwendbarkeit des Prüfschritts

Der Prüfschritt ist anwendbar, wenn die App-Ansicht Text enthält. Grafische Schriften sind ebenfalls Gegenstand des Prüfschritts.

=== 2. Prüfung
* Für die Bewertung zählt das https://www.w3.org/TR/WCAG22/#dfn-contrast-ratio[Kontrastverhältnis] (relative luminosity) nach einer in den WCAG 2.1 definierten Formel, die der https://www.bitvtest.de/bitv_test/das_testverfahren_im_detail/werkzeugliste.html#cca[Color Contrast Analyzer] handhabbar macht.

==== 2.1 Prüfung der Textkontraste der Standardversion

. App mit zu prüfender Ansicht öffnen.
. Screenshots erstellen (gegebenenfalls vorher die Zoomfunktion nutzen, um eine größere Fläche für die Kontrastmessung zur Verfügung zu haben.):
 * iOS/iPadOS: Screenshot mit der Tastenkombination Power- und Home-Taste erstellen. Bei Geräten ohne Home-Button nutzt man die Kombination von Power- und Lauter-  
   Taste.
 * Android: Screenshot mit der Tastenkombination Power- und Leiser-Taste erstellen.
. Screenshots an den PC übertragen: 
 * iOS/iPadOS und Android: Gerät mittels USB-Kabel an den Rechner anschließen und im Datei-Explorer auswählen.	
. Sind die Schriftkontraste stark genug? Screenshots am PC öffnen und im Zweifel mit dem Contrast-Analyzer untersuchen:
 * Im Bereich *Vordergrund* mit der Pipette die Vordergrundfarbe auswählen, dann im Bereich *Hintergrund* die Hintergrundfarbe.
. Für Schriftgrößen unter 24 px (beziehungsweise 18,7 px bei fetter  Schrift) prüfen, ob das Kontrastverhältnis bei 4,5:1 oder größer liegt.
. Für große Schriften ist ein Mindestkontrastverhältnis von nur 3:1 gefordert. Die Schriftgrößen-Unterscheidung ist derzeit jedoch aufgrund fehlender Werkzeuge nicht 
  oder nur ungenau möglich.

==== 2.2. Prüfung der Textkontraste der alternativen kontrastreicheren Ansicht (Styleswitcher-Prüfung)

Wenn die Kontraste der Standardversion nicht die Sollwerte erfüllt und die Ansicht eine kontrastreichere Ansicht über einen Styleswitcher anbietet:

. Screenshots erstellen und an den PC übertragen (vergleiche Prüfung der Textkontraste der Standardversion).
. Textkontrast des Styleswitcher-Schaltelements prüfen. Das Kontrastverhältnis muss 4,5:1 oder besser sein und auch die anderen Anforderungen müssen erfüllt sein. Sonst abbrechen.
. Alternative kontrastreichere Ansicht über den Styleswitcher aufrufen.
. Screenshots erstellen und an den PC übertragen.
. Textkontraste der alternativen Ansicht prüfen (entsprechend Prüfung der Textkontraste der Standardversion).

=== 3.1 Hinweise auf Messungenauigkeiten
* Screenshots geben die tatsächlichen Farben nicht immer richtig wieder (siehe https://webaim.org/discussion/mail_thread?thread=10162[Thread in Webaim Mailing List]).
* Bei Messungen mittels der Pipette des Color Contrast Analyzers kann es bei kleineren Schriften zu Fehlmessungen kommen: Der Randbreich der Schriften ist wegen des Anti-Aliasings oft näher am Kontrastwert des Hintergrundes, der Wert scheint dann ungenügend, obwohl er normativ ggf. ausreicht. Bei App-Screenshots ist es nicht wie bei Web-Angeboten möglich, vor der Messung hineinzuzoomen, um bei einer besseren Strichstärke der Schrift eine zuverlässigere Messung vorzunehmen. Ggf. ist aber bei dynamischen Schriften die Erhöhung der Schriftgröße über die Einstellungen in den Bedienungshilfen sinnvoll. Messungen im Grenzbereich der geforderten Kontrastwerte sollten diesen Unsicherheitsfaktor benennen.
* Für große und kleine Schriften gelten unterschiedliche Richtwerte. Bei Apps ist die Schriftgrößen-Unterscheidung derzeit nur bedingt anwendbar. Die Ermittlung genauer Schriftgrößen ist bei Apps aufgrund fehlender Werkzeuge nicht oder nur ungenau möglich. Prüfende Personen müssen an dieser Stelle anhand ihrer Erfahrung urteilen. Falls Ihnen geeignete Werkzeuge und Methoden bekannt sind, weisen Sie uns gerne in einem https://github.com/BIK-BITV/BIK-App-Test/issues[GitHub Issue] darauf hin.

==== 3.2 Allgemeine Hinweise
* Elemente, die unterschiedliche Zustände haben können, sollten immer ausreichend kontrastieren. Das bedeutet, auch die farblich hervorgehobene, aktuell ausgewählte
  Menüoption oder Links, die in anderen Zuständen in einer anderen Farbe dargestellt werden.
* Schwache Kontraste können zweckmäßig sein, sie können den Umgang mit einer App erleichtern. Ein Beispiel: Funktionen, die prinzipiell vorgesehen, aktuell aber nicht
  verfügbar sind, werden schwach kontrastierend dargestellt. Das ist akzeptabel, wenn das ausgeblendete Element für die Orientierung und Bedienung nicht erforderlich
  ist. Der Prüfschritt ist daher auf die Beschriftungen ausgeblendeter, deaktivierter Bedienelemente in der Regel nicht anwendbar.
* Der Farbkontrast von Textvorbelegungen von Formularfeldern erfüllt oft nicht die Mindest-Anforderung von 4,5:1.

==== 3.3 Hinweise zur Prüfung von Ansichten mit Styleswitcher

Die Kontrastprüfung auf durch Styleswitcher aufgerufenen kontrastreicheren
Ansicht erfolgt nur unter folgenden Bedingungen:

* Das Style-Switcher-Element ist am Beginn der Ansicht platziert.
* Das Schaltelement hat ein Kontrastverhältnis von mindestens 4.5:1 und erfüllt auch die anderen Anforderungen an Barrierefreiheit.
* Die alternative kontrastreichere Ansicht muss dieselben Informationen und dieselbe Funktionalität aufweisen wie die Ausgangsansicht.

=== 4. Bewertung

*Erfüllt:*

* Das Kontrastverhältnis (contrast ratio) zwischen Vorder- und Hintergrundfarbe liegt für Texte unter 18 Punkt (beziehungsweise für fette Texte unter 14 Punkt) bei 
  mindestens 4,5:1.
* Das Kontrastverhältnis (contrast ratio) zwischen Vorder- und Hintergrundfarbe liegt bei Texten in großer Schriftgröße (18 Punkt und größer, 14 Punkt und größer bei 
  fetter Schrift) bei mindestens 3:1.

* Wenn die Anforderung nur über eine alternative Ansicht erfüllt wird, erfüllt der Styleswicher selbst die Kontrastforderung von 4,5:1 und andere
 Anforderungen an Barrierefreiheit.

== Einordnung des Prüfschritts

=== Einordnung des Prüfschritts nach WCAG 2.1

==== Guideline

* https://www.w3.org/TR/WCAG21/#distinguishable[Guideline 1.4 Distinguishable:Make it easier for users to see and hear content including separating
  foreground from background]

==== Success criteria

* https://www.w3.org/TR/WCAG21/#contrast-minimum[1.4.3 Contrast (Minimum)
(Level AA)]

==== Techniques

.General Techniques
* https://www.w3.org/WAI/WCAG21/Techniques/general/G18.html[G18: Ensuring that
  a contrast ratio of at least 4.5:1 exists between text (and images of text)
  and background behind the text]
* https://www.w3.org/WAI/WCAG21/Techniques/general/G145.html[G145: Ensuring
  that a contrast ratio of at least 3:1 exists between text (and images of
  text) and background behind the text]
* https://www.w3.org/WAI/WCAG21/Techniques/general/G148.html[G148: Not
  specifying background color, not specifying text color, and not using
  technology features that change those defaults]
* https://www.w3.org/WAI/WCAG21/Techniques/general/G174.html[G174: Providing a
  control with a sufficient contrast ratio that allows users to switch to a
  presentation that uses sufficient contrast]

==== Failures

* https://www.w3.org/WAI/WCAG21/Techniques/failures/F83.html[F83: Failure of
  Success Criterion 1.4.3 and 1.4.6 due to using background images that do not
  provide sufficient contrast with foreground text (or images of text)]
* https://www.w3.org/WAI/WCAG21/Techniques/failures/F24.html[F24: Failure of
  Success Criterion 1.4.3, 1.4.6 and 1.4.8 due to specifying foreground colors
  without specifying background colors or vice versa]

== Quellen

=== W3C zum Zusammenhang zwischen px und pt:

* https://www.w3.org/TR/css3-values/#absolute-lengths[CSS Values and Units Module Level 3: 5.2 Absolute Lengths]

== Fragen zu diesem Prüfschritt

=== Subjektiver Eindruck

Das Ergebnis der WCAG 2.1 Formel zur Messung des Kontrastverhältnisses
entspricht oft nicht dem subjektiven Eindruck.
Wie zuverlässig ist es?

Zwei Punkte sind hier zu beachten:

* Der Helligkeitskontrast ist nur einer von drei Einflussgrößen für den Gesamtkontrast. Insofern ist klar, dass das Ergebnis für den Helligkeitskontrast nicht dem
  subjektiven Eindruck entspricht. Es soll gar nicht dem subjektiven Gesamteindruck entsprechen, denn schließlich geht es darum, ob die Helligkeitsunterschiede der 
  Farben für sich genommen ausreichend kontrastieren. Wenn man normalsichtig ist, entspricht der subjektive Eindruck der Graustufenansicht dagegen schon eher dem 
  Formelergebnis.
* Farben benachbarter Flächen beeinflussen die Wahrnehmung, kleine und dünne Schriften erscheinen kontrastärmer, es gibt Überstrahleffekte, möglicherweise werden die
  Kontraste durch Schriftenglättung abgeschwächt. Die Formel berücksichtigt all diese Faktoren nicht. Zumindest wenn es um Texte geht, ist dies auch angemessen. Denn 
  die genannten Einflüsse stehen nicht fest, sie hängen zum Beispiel von der gewählten Schriftgröße ab.

Für die Prüfung bedeutet das:
Wer mit der formelbasierten Bewertung von Helligkeitskontrasten noch keine Erfahrungen hat, kann sich nicht auf seinen subjektiven Eindruck verlassen. Er muss die Formel fast auf alle Farbkombinationen anwenden.
