= Prüfschritt 11.1.3.1a Strukturelemente für Überschriften
include::include/author.adoc[]
include::include/attributes.adoc[]

*Hinweis: Dies ist ein Entwurf. Inhalte können sich jederzeit ändern.*

== Was wird geprüft?

Überschriften, die zur Beschreibung von Inhalten eingesetzt werden, müssen auch semantisch als Überschriften ausgezeichnet sein. 

Die eingesetzten Überschriften sollten die strukturelle Hierarchie des Inhalts richtig wiedergeben. Aktuell können jedoch unterschiedliche Überschriftsebenen unter iOS / iPadOS und Android lediglich in WebViews mit Web-Techniken (`h1` - `h6` bzw. durch den Einsatz von ARIA-Rollen und -Attributen) realisiert werden.

In nativen Ansichten können derzeit Überschriften nicht programmatisch in Ebenen unterteilt werden. Aufgrund technischer Begrenzungen können Umsetzende nur ein UI-Element als einfache Überschrift auszeichnen.

== Warum wird das geprüft?

Visuell können Inhalte durch Überschriften strukturiert werden. Dank dieser Strukturierung weiß der Benutzer, was zusammengehört, kann die Inhalte der Ansicht leicht überblicken und gezielt auf Inhalte zugreifen, die ihn interessieren.

Nutzende, denen diese visuelle Ordnung nicht zur Verfügung steht, zum Beispiel, weil sie blind sind oder nur einen kleinen Ausschnitt der Seite sehen können, sind darauf angewiesen, dass die Struktur unabhängig von der Darstellung auf dem Bildschirm zugänglich und nutzbar ist. Die Verwendung von semantischen Überschriften ist dafür eine wichtige Voraussetzung.

So können Benutzer die Überschriften-Elemente anwenden:

* Orientierung in umfangreicheren Ansichten
* Von Überschrift zu Überschrift springen (Screenreader-Nutzende)
* Weitere Anpassungen sind denkbar, z.B. könnten Screenreader zukünftig Überschriften mit einer anderen Stimme oder Stimmhöhe vorlesen, um diese als solche hervorzuheben.

== Wie wird geprüft?

=== 1. Anwendbarkeit des Prüfschritts

Der Prüfschritt ist anwendbar, wenn es in der App Inhalte gibt, die durch visuelle Überschriften strukturiert werden. Das ist bei informationsorientierten Apps häufig der Fall.

=== 2. Prüfung

==== 2.1 Prüfung von nativen Inhalten
. App mit zu prüfender Ansicht starten.
. Screenreader starten und Fokus mit Hilfe der Wischgeste auf Überschriften setzen.
. Prüfen, ob Inhalte visuell als Überschriften zu erkennen sind und zur Strukturierung eingesetzt werden. 
. Prüfen, ob diese Überschriften ausgezeichnet sind. 
. Die Navigationseinstellung des Screenreaders auf "Überschriften" setzen. Anschließend durch alle Überschriften der Ansicht navigieren und die Ausgabe des Screenreaders prüfen. 
. Der Screenreader gibt eine korrekt ausgezeichnete Überschrift mit dem Wort "Überschrift" aus. 
. Prüfen, ob die Überschriftensauszeichnung lediglich zur Erzeugung unterschiedlicher Schriftgrößen eingesetzt wird und damit die Auszeichnung missbräuchlich erfolgt.

==== 2.2 Prüfung von WebViews
. Auf Webviews kann zwischen Überschriftsebenen unterschieden werden.
. Werden Überschriften mit den entsprechenden Web-Techniken (`h1`- `h6`, alternativ durch den Einsatz von ARIA-Rollen und -Attribute) ausgezeichnet, 
wird die entsprechende Überschriftenebene ausgegeben. Die Hierarchie der Überschriften soll dann der Gliederung der Inhalte entsprechen. 
. Der Aufruf des Rotors (iOS) bzw. von Kontextmenü / Navigation (Android) gibt einen Hinweis, ob es sich um ein Webview oder eine native Ansicht handelt. Bei Webviews werden in der Regel mehr Navigationsmöglichkeiten angezeigt.
. Prüfen, ob die Überschriftensauszeichnung lediglich zur Erzeugung unterschiedlicher Schriftgrößen eingesetzt wird und damit die Auszeichnung missbräuchlich erfolgt.

=== 3. Hinweise

* Es ist nicht die Aufgabe des Prüfschritts zu prüfen, ob Wortwahl oder Stil der Überschriften den jeweiligen Inhalten angemessen sind.

* App-Entwickler haben derzeit keine Möglichkeit unterschiedliche Überschriftsebenen in nativen Ansichten auszuzeichnen. Eine fehlende Auszeichnung von Überschriftsebenen wird daher *nicht* negativ bewertet.

* Wird vom Screenreader zusätzlich zur Rolle "Überschrift" auch die Überschriftenebene ausgegeben, handelt es sich um ein WebView, der auf HTML basiert. Überschriften sollten dann korrekt geschachtelt sein (`h1` gefolgt von `h2` gefolgt von `h3`, und so weiter), um die Gliederung der Inhalte abzubilden. Das Auslassen von Hierarchie-Ebenen muss aber kein Fehler sein, wenn dies durch die Gliederung der Inhalte gerechtfertigt ist.

=== 4. Bewertung

==== Erfüllt:

* Visuelle Überschriften auf der Seite sind auch semantisch als Überschriften umgesetzt.

==== Nicht voll erfüllt:

* Es werden Auszeichnungen für Überschriften eingesetzt. Bei WebViews (siehe "3. Hinweise") ist die Verschachtelung der Hierarchie-Ebenen jedoch irreführend und entspricht nicht der inhaltlichen Gliederung.

==== Nicht erfüllt:

* Es gibt auf der Ansicht gegliederte Inhalte. Überschriften werden nicht als solche semantisch ausgezeichnet.

== Quellen

=== iOS

* Apple Developer Documentation: https://developer.apple.com/documentation/uikit/uiaccessibility/uiaccessibilitytraits/1620170-header[
  UI Accessibility Traits / Header]
* Apple Developer Documentation: https://developer.apple.com/documentation/swiftui/text/accessibilityheading(_:)[Hierarchische Überschriften in iOS]

=== Android
* Android Developer: https://developer.android.com/reference/android/view/View#attr_android:accessibilityHeading[`android:accessibilityHeading` für UI-Elemente]
* Android Developer: https://developer.android.com/guide/topics/ui/accessibility/principles#headings_within_text[Headings within text]

=== Allgemeine Quellen (WCAG)
==== Überschriften richtig schachteln

[.BLOCK_LANG_EN]
To facilitate navigation and understanding of overall document structure,
authors should use headings that are properly nested (e.g., h1 followed by h2,
h2 followed by h2 or h3, h3 followed by h3 or h4, etc.)..

* WCAG 2.1: https://www.w3.org/WAI/WCAG21/Techniques/general/G141[G141: Organizing a page using headings]

==== Überschriften-Elemente und CSS-Auszeichnungen nicht missbrauchen

[.BLOCK_LANG_EN]
Using headings merely to change the appearance of text does not convey the
organization of the content, and may confuse users who use headings to
perceive structure or rely on them for navigation.
Conversely, while applying bold format, or even class="heading", can result in
the visual display of a heading, assistive technologies will not recognize
such text as headings.

* WCAG 2.1:  https://www.w3.org/WAI/WCAG21/Techniques/html/H42.html[H42: Using h1-h6 to identify headings]

== Einordnung des Prüfschritts

=== Einordnung des Prüfschritts nach WCAG 2.1

==== Guidelines

* https://www.w3.org/TR/WCAG21/#adaptable[Guideline 1.3 Adaptable: Create
  content that can be presented in different ways (for example simpler layout)
  without losing information or structure]

==== Success criteria

* https://www.w3.org/TR/WCAG21/#info-and-relationships[1.3.1 Info and
  Relationships (Level A)]

==== Techniques

.General Techniques
* https://www.w3.org/WAI/WCAG21/Techniques/general/G115.html[G115: Using
  semantic elements to mark up structure]
* https://www.w3.org/WAI/WCAG21/Techniques/general/G140.html[G140: Separating
  information and structure from presentation to enable different presentations]

==== Failures

* https://www.w3.org/WAI/WCAG21/Techniques/failures/F43.html[F43: Failure of
  Success Criterion 1.3.1 due to using structural markup in a way that does
  not represent relationships in the content]
* https://www.w3.org/WAI/WCAG21/Techniques/failures/F92.html[F92: Failure of
  Success Criterion 1.3.1 due to the use of role presentation on content which
  conveys semantic information]

