= Prüfschritt 11.1.3.1d Kein Strukturmarkup für Layouttabellen
include::include/author.adoc[]
include::include/attributes.adoc[]

== Was wird geprüft?

Für Layouttabellen darf keine strukturelle Tabellen-Auszeichnung verwendet werden (z. B. Zeilen- und Spaltenüberschriften). 

== Wie wird geprüft?

=== 1. Anwendbarkeit des Prüfschritts

Der Prüfschritt ist anwendbar, wenn die Software Tabellen für das Layout verwendet.

=== 2. Prüfung

. App mit zu prüfender Ansicht starten.
. Prüfen, ob es Inhalte gibt, die visuell tabellenartig gestaltet sind.
. Screenreader starten und mit Hilfe der Wischgeste durch diese Inhalte navigieren.
. Prüfen ob der Screenreader den Zusatz „Tabelle“ ausgibt. In diesem Fall darf bei einer Überschriftenzelle nicht der Zusatz "Überschrift" ausgegeben werden.

=== 3. Bewertung

*Nicht erfüllt:*

* Bei Layouttabellen gibt der Screenreader Tabellenstrukturen wie z. B. Überschriften aus.

== Einordnung des Prüfschritts

=== Einordnung des Prüfschritts nach WCAG 2.1

==== Guideline

* https://www.w3.org/WAI/WCAG21/quickref/?showtechniques=131#adaptable[Guideline
  1.3 Adaptable: Create content that can be presented in different ways (for
  example simpler layout) without losing information or structure]

==== Success criterion

* https://www.w3.org/WAI/WCAG21/quickref/?showtechniques=131#info-and-relationships[
1.3.1 Info and Relationships (Level A)]

==== Techniques

.General Techniques
* https://www.w3.org/WAI/WCAG21/Techniques/general/G115.html[G115: Using
  semantic elements to mark up structure]
* https://www.w3.org/WAI/WCAG21/Techniques/general/G140.html[G140: Separating
  information and structure from presentation to enable different presentations]
