= Prüfschritt 11.1.1.1b Textalternativen für Grafiken und Objekte
include::include/author.adoc[]
include::include/attributes.adoc[]

== Was wird geprüft?

Informative Grafiken und Bilder müssen Textalternativen haben. Die Textalternativen ersetzen das Bild, sie sollen (soweit wie möglich) die gleiche Information vermitteln wie das Bild.

Bei eingebundenen Multimedia-Objekten, Video- beziehungsweise Audio-Dateien soll die Textalternative zumindest eine beschreibende Identifizierung des Inhalts ermöglichen.

== Warum wird das geprüft?

Für blinde Benutzer sind Grafiken und Bilder nicht zugänglich. Die Textalternative tritt dann an die Stelle der Grafik, sie soll die Grafik inhaltlich ersetzen können.

Wenn Objekte (etwa Video- oder Audio-Dateien) nicht angezeigt werden können, weil sie z. B. nicht geladen werden können, sollen kurze beschreibende Textalternativen dem Nutzer eine Identifikation der Inhalte ermöglichen.

== Wie wird geprüft?

=== 1. Anwendbarkeit des Prüfschritts

Der Prüfschritt ist anwendbar, wenn informative Grafiken oder, Bilder, Video- oder Audio-Dateien oder Multimedia-Objekte vorhanden sind.

Als informative Grafiken gelten:

* grafische Schriften
* Abbildungen, die zeigen sollen, wie ein Objekt oder eine Person aussieht
* Illustrationen, die einen Gegenstand, ein Konzept oder einen Prozess vorstellen, verdeutlichen oder veranschaulichen sollen (etwa Diagramme)
* Symbole

Dekorative Grafiken und Bilder sind Grenzfälle. Sie stellen (im Unterschied zu Layoutgrafiken) etwas dar, der dargestellte Gegenstand hat auch meist einen Bezug zum Thema der App-Ansicht. Ihr Informationsgehalt und ihr Nutzen für das Verständnis ist aber nicht klar. Sie können daher als dekorativ gekennzeichnet werden, der Prüfschritt ist dann nicht anwendbar.

Wenn Logo-artige Elemente, in denen Grafik und Schrift verbunden sind, auftauchen, sind diese fast nie als bloße Schmuckgrafik anzusehen und brauchen deshalb eine Textalternative. Dies ermöglicht blinden und sehenden Nutzern, sich gemeinsam auf diese Elemente zu beziehen. Die Textalternative muss aber nicht expliziter sein als das, was für den sehenden Nutzer erkenntlich ist.

Darüber hinaus ist der Prüfschritt anwendbar, wenn informative Audio-Elemente vorhanden sind.

=== 2. Prüfung

Für eine Prüfung mit VoiceOver / iOS müssen die AI/OCR-Erkennungsfunktionen ausgeschaltet sein (siehe "3. Hinweise").

. App mit zu prüfender Ansicht starten.
. Prüfen, ob unverlinkte informationstragende Grafiken oder Multimedia-Inhalte vorhanden sind.
. Screenreader starten und Fokus auf jede informationstragende Grafik setzen.
. Prüfen, ob der Screenreader informationstragende Grafiken aussagekräftigen Alternativtext ausgibt.
. Bei komplexen Grafiken prüfen, ob der Alternativtext Inhalt knapp nennt und auf ausführliche Textalternativen im Kontext der Grafik verweist. Diese können etwa unterhalb der Grafik, in einem Ausklappbereich oder in einer verlinkten Ansicht vorgehalten werden.
. Prüfen, ob Schmuckgrafiken Alternativtexte tragen. Bei Grenzfällen (Grafiken haben einen beschreibbaren Inhalt mit Bezug zum Thema, sind aber zum Verständnis der Inhalte nicht wichtig) können sowohl Alternativtexte als das Fehlen von Alternativtext akzeptiert werden.

=== 3. Hinweise

==== Einstellungen für die Prüfung mit VoiceOver / iOS

Die AI/OCR-Erkennungsfunktionen von VoiceOver müssen ausgeschaltet sein:

* iOS 14+: Einstellungen > Bedienungshilfen > VoiceOver > VoiceOver-Erkennung. (Diese Funktion wird nur auf iPhone XS/XR-Modellen und höher unterstützt).
* iOS 13: Einstellungen > Bedienungshilfen > VoiceOver > Verbosität > Sprechen erkannt > Sprechen von erkanntem Text und Bildern


==== Angemessene Alternativtexte

Entscheidend ist: Die App soll benutzbar sein, wenn für Grafiken oder Bilder die entsprechenden Textalternativen vom Screenreader ausgegeben werden.

In der Regel bedeutet das:

* Bei Schriftgrafiken soll die Textalternative den Text der Schriftgrafik wiederholen.
* Bei Symbolen oder Zeichen (Logos) soll die Textalternative sagen, dass ein Symbol, Zeichen oder Logo abgebildet ist und die Bedeutung des Symbols oder Zeichens wiedergeben.
* Bei Gruppen von zusammengehörigen Bildern kann auch eines der Bilder die Bedeutung der Gruppe wiedergeben, die anderen sollten als dekorativ gekennzeichnet werden.
* Bei Fotos, Reproduktionen von Gemälden oder anderen Nicht-Text-Elementen, die eine spezifische Sinneserfahrung vermitteln, genügt in der Regel eine knappe Bezeichnung des abgebildeten Gegenstandes.
* Bei Diagrammen oder technischen Zeichnungen sind unter Umständen ausführlichere Erläuterungen erforderlich.
  Textalternativen sind dafür nicht geeignet, sie sollen in der Regel 80 Zeichen nicht überschreiten. In der Textalternative steht dann nur, was dargestellt ist und wo (etwa: "Details im anschließenden Text"). Die ausführliche Textalternative soll sich in Kontext des Bildes befinden. Der Kontext kann zum Beispiel ein unmittelbar folgender Inhalt (Text oder Tabelle), ein Ausklappbereich oder auch ein Link zu einer Ansicht sein, die die ausführliche Alternative enthält.
* Bei Objekten, die nicht angezeigt werden können, sollen die Textalternative oder Text im unmittelbaren Kontext des Objekts (etwa eine vorangehende Überschrift oder nachfolgende Legende) eine kurze Beschreibung oder Identifizierung bieten und, falls vorhanden, auf eine Medienalternative verweisen.

Generell gilt: Textalternativen sollen kurz sein. Ausführliche Beschreibungen von Abbildungen sollen nicht in die Textalternative, sondern im Kontext der Abbildung zur Verfügung gestellt werden.

==== Angemessenheit von Textalternativen im Kontext

Wenn die Textalternative kein angemessener Ersatz für die Grafik oder das Bild sein kann, muss geprüft werden, ob die über das Bild vermittelte Information im Kontext als Text zur Verfügung steht.

Das betrifft zum Beispiel

* Diagramme
* technische Zeichnungen
* Anfahrtspläne

Zum Kontext einer Grafik oder eines Bildes gehört: der dazugehörige (vorangehende, folgende) Text und eine im unmittelbaren Kontext des Bildes angebotene verlinkte und klar benannte Textalternative.

Eine kurze Textalternative mit Bezeichnung des Bildes ist auch bei Nutzung von Textalternativen im Kontext erforderlich. Die Textalternative sagt, dass an dieser Stelle etwas Bestimmtes abgebildet ist, sie macht klar, worauf sich die Erläuterung im Kontext bezieht.

==== Beurteilung der Angemessenheit ====

Um die Angemessenheit der Textalternative einschätzen zu können, muss die Textalternative auf die Grafik beziehungsweise das Objekt bezogen werden, zu dem sie gehört.
Erforderlich ist also die wechselnde Betrachtung von Grafik/Objekt und zugehörige Textalternative.

== Einordnung des Prüfschritts

=== Abgrenzung zu anderen Prüfkriterien

* Textalternative für verlinkte Grafiken (z.B. Bedienelemente oder 
  Teaser-Bilder)
  werden in Prüfschritt
ifdef::env_embedded[11.1.1.1a "Textalternativen für Bedienelemente"]
ifndef::env_embedded[]
  <<11.1.1.1a Alternativtexte für Bedienelemente.adoc#,11.1.1.1a Textalternativen
  für Bedienelemente>>
endif::env_embedded[]
  geprüft.

* Einfache Animationen oder Videos ohne synchronisierungsbedürftige Tonspur
  werden in Prüfschritt
ifdef::env_embedded[11.1.2.1a "Alternativen für Audiodateien und stumme Videos"]
ifndef::env_embedded[]
  <<11.1.2.1 Alternativen für Audiodateien und stumme Videos.adoc#,11.1.2.1
  Alternativen für Audiodateien und stumme Videos>>
endif::env_embedded[]
  geprüft.

* Layout-Grafiken oder dekorative Grafiken werden in
  Prüfschritt
ifdef::env_embedded[11.1.1.1c "Leere alt-Attribute für Layoutgrafiken"]
ifndef::env_embedded[]
  <<11.1.1.1c Leere alt-Attribute für Layout-Grafiken.adoc#,11.1.1.1c Leere
  alt-Attribute für Layout-Grafiken>>
endif::env_embedded[]
  geprüft.

* CAPTCHAs werden in Prüfschritt
ifdef::env_embedded[11.1.1.1d "Alternativen für CAPTCHAs"]
ifndef::env_embedded[]
  <<11.1.1.1d Alternativen für CAPTCHAs.adoc#,11.1.1.1d Alternativen für
  CAPTCHAs>>
endif::env_embedded[]
  geprüft.

=== Einordnung des Prüfschritts nach WCAG 2.1

==== Guideline

* http://www.w3.org/TR/WCAG21/#text-alternatives[Guideline 1.1 Text
  Alternatives: Provide text alternatives for any non-text
  content so that it can be changed into other forms people need, such as large
  print, braille, speech, symbols or simpler language]

==== Success Criterion

* http://www.w3.org/TR/WCAG21/#x1-1-1-non-text-content[1.1.1 Non-text Content
  (Level A)]

==== Techniques

===== General Techniques

* https://www.w3.org/WAI/WCAG21/Techniques/general/G73[G73: Providing a long
  description in another location with a link to it that is immediately adjacent
  to the non-text content]
* https://www.w3.org/WAI/WCAG21/Techniques/general/G74[G74: Providing a long
  description in text near the non-text content, with a reference to the
  location of the long description in the short description]
* https://www.w3.org/WAI/WCAG21/Techniques/general/G82[G82: Providing a text
  alternative that identifies the purpose of the non-text content]
* https://www.w3.org/WAI/WCAG21/Techniques/general/G92[G92: Providing long
  description for non-text content that serves the same purpose and presents
  the same information]
* https://www.w3.org/WAI/WCAG21/Techniques/general/G94[G94: Providing short
  text alternative for non-text content that serves the same purpose and
  presents the same information as the non-text content]
* https://www.w3.org/WAI/WCAG21/Techniques/general/G95[G95: Providing short
  text alternatives that provide a brief description of the non-text content]
* https://www.w3.org/WAI/WCAG21/Techniques/general/G100[G100: Providing the
  accepted name or a descriptive name of the non-text content]
* https://www.w3.org/WAI/WCAG21/Techniques/general/G196[G196: Using a text
  alternative on one item within a group of images that describes all items in
  the group]

==== Failures

* https://www.w3.org/WAI/WCAG21/Techniques/failures/F20[F20: Failure of
  Success Criterion 1.1.1 and 4.1.2 due to not updating text alternatives when
  changes to non-text content occur]
* https://www.w3.org/WAI/WCAG21/Techniques/failures/F30[F30: Failure of
  Success Criterion 1.1.1 and 1.2.1 due to using text alternatives that are
  not alternatives]
* https://www.w3.org/WAI/WCAG21/Techniques/failures/F65[F65: Failure of Success
Criterion 1.1.1 due to omitting the alt attribute on img elements, area
elements, and input elements of type 'image']
* https://www.w3.org/WAI/WCAG21/Techniques/failures/F67[F67: Failure of Success
  Criterion 1.1.1 and 1.2.1 due to providing long description for non-text content
  that does not serve the same purpose or does not present the same information]

== Quellen

=== Alternativtexte sollen denselben Zweck erfüllen wie das Bild

Um von Nutzen zu sein, muss der Text dieselbe Funktion bzw. denselben Zweck
erfüllen wie das Bild.
Nehmen Sie zum Beispiel ein Foto der Erde, aufgenommen aus dem Weltraum. Wenn
der Zweck des Bildes vorrangig in der Ausschmückung besteht, mag der Text
"Foto der Erde vom Weltraum aus gesehen" die benötigte Funktion erfüllen.
Wenn der Zweck des Fotos darin besteht, bestimmte Informationen über
Geographie zu illustrieren, sollte das Text-Äquivalent diese Information
enthalten.
Wenn das Foto dem Benutzer sagen soll, dass er das Bild auswählen soll, um
Informationen über die Erde zu erhalten (etwa indem er es anklickt), wäre der
äquivalente Text "Informationen über die Erde".
D.h. wenn der Text für einen Benutzer mit einer Behinderung dieselbe Funktion
oder denselben Zweck erfüllt wie das Bild für andere Benutzer, kann er als
Text-Äquivalent angesehen werden.

* Quelle: http://www.w3.org/Consortium/Offices/Germany/Trans/WAI/webinhalt.html

=== Ausführlichkeit von Alternativtexten

[.BLOCK_LANG_EN]
If possible, the short text alternative should completely convey the purpose
and information.
If it is not possible to do this in a short phrase or sentence, then the short
text alternative should provide a brief overview of the information.
A long text alternative would be used in addition to convey the full
information.

* Quelle: WCAG 2.0 Technik https://www.w3.org/TR/WCAG20-TECHS/G94.html[G94:
        Providing short text alternative for non-text content that serves the
        same purpose and presents the same information as the non-text
        content]

=== Alternativtexte für Schrift in Grafiken

[.BLOCK_LANG_EN]
When non-text content contains words that are important to understanding the
content, the alt text should include those words.
If the text in the image is more than can fit in a short text alternative then
it should be described in the short text alternative and a long text
alternative should be provided as well with the complete text.

* Quelle: WCAG 2.0 Technik https://www.w3.org/TR/WCAG20-TECHS/G94.html[G94:
        Providing short text alternative for non-text content that serves the
        same purpose and presents the same information as the non-text
        content]

=== Anleitungen zum Erstellen guter Alternativtexte

* W3C Web Accessibility Tutorials:
  https://www.w3.org/WAI/tutorials/images/[Images Concepts]
* WebAIM: https://webaim.org/techniques/alttext/[Alternative Text]

== Fragen zu diesem Prüfschritt

=== Was kann die Textalternative leisten?

Zum Beispiel die Explosionszeichnung eines Motors: sollte der gesamte Aufbau
des Motors im Alternativtext
beschrieben werden?

Die Explosionszeichnung zeigt die Lage verschiedener Teile im Motor. Alternative Vermittlungsformen sind denkbar und möglich. Zum Beispiel könnte die Lage der Teile an einem tastbaren Modell gezeigt werden. Klar ist aber, dass bei einigermaßen komplexen Gebilden die Textform nicht geeignet ist. Die Frage ist daher, was im Alternativtext sinnvoll herübergebracht werden kann. Auf jeden Fall kann die Textalternative darüber informieren, dass eine Explosionszeichnung des Motors dargestellt wird. Der blinde Benutzer weiß dann zumindest, welche Informationen ihm nicht zugänglich sind. Darüber hinaus kann es sein, dass nur ein bestimmtes Detail der gesamten Zeichnung relevant ist. Das geht aus dem Kontext hervor. Das betreffende Detail kann dann in Textform erläutert werden.

Für die Bewertung gilt: wenn der Prüfer selbst nicht sagen kann, ob oder wie der Informationsgehalt des Bildes in Textform vermittelt werden könnte, muss die Bezeichnung des dargestellten Gegenstandes in der Textalternative als hinreichend bewertet werden.

=== Textalternativen für Firmenlogos

Auf der Website ist das Firmenlogo abgebildet. Reicht es aus, wenn in der Textalternative steht, dass da das Firmenlogo abgebildet
ist? Oder sollte es auch beschrieben werden?

Auch für einen blinden Besucher kann das Aussehen des Logos interessant sein. Er unterhält sich ja mit Sehenden, weiß dann, wovon die Rede ist. Allerdings sollte die Textalternative kurz sein, der Besucher möchte nicht immer wieder diese Beschreibung hören, wenn er die Seite besucht. Sie könnte also in einer separaten, ausführlicheren Beschreibung bereitgestellt werden.

Im BITV-Test wird eine solche ausführliche Beschreibung des Firmenlogos allerdings nicht gefordert.

=== Abbildungen mit Text

Eine Abbildung enthält Text. Muss dieser Text in jedem Fall in der Textalternative bereitgestellt werden?

Nein, entscheidend ist die Funktion der Abbildung. Wenn es sich um eine Schriftgrafik handelt, dann ist die Sache meistens klar, die Abbildung ist für die Anzeige des Textes da.

Anders, wenn ein Motiv mit Text abgebildet ist. Dann muss (wie bei allen Bildern) überlegt werden, was die Leistung des Bildes ist, ob der abgebildete Text wesentlich ist. Nur dann muss der Text in der Textalternative beachtet werden.

=== Soll in der Textalternative stehen, dass es sich um ein grafisches Element handelt?

Nein, das ist nicht erforderlich. Denn Screenreader stellen anhand des Markups fest, auf was für ein Element sich die Textalternative bezieht. Im BITV-Test wird ein entsprechender Vorsatz in der Textalternative jedoch nicht negativ bewertet, er ist für die Bewertung nicht relevant.

=== Kann die Bedeutung eines Bildes auch im Kontext beschrieben werden?

Das ist in vielen Fällen sinnvoll. Wichtig ist, dass die Beschreibung dem Bild eindeutig zugeordnet werden kann. Dafür kann (und soll) dann die Textalternative des Bildes genutzt werden. Er enthält eine kurze Bezeichnung des abgebildeten, im Kontext beschriebenen Gegenstandes.

=== Was sollte in der Textalternative für Landkarten stehen?

Die Textalternative für Landkarten kann kein Äquivalent sein, eine Beschreibung in Textform kann die Karte nicht ersetzen. Nicht-visuelle Äquivalente könnten Routenbeschreibungen sein, wie sie häufig von Reiseplanern angeboten werden. Das geht aber über die Möglichkeiten der Textalternative hinaus. Die Textalternative für Karten muss sich also darauf beschränken, anzugeben, welches Gebiet auf der Karte dargestellt ist.
