= Prüfschritt 11.1.1.1a Textalternativen für Bedienelemente
include::include/author.adoc[]
include::include/attributes.adoc[]

== Was wird geprüft?

Grafische Bedienelemente müssen mit Textalternativen versehen werden. Textalternativen für verlinkte Grafiken (Menüs, Logos) oder Teaserbilder sollen das Ziel des Links bezeichnen. Textalternativen für grafische Schaltflächen (Buttons) sollen die Aktion bezeichnen, die der Button auslöst.

== Warum wird das geprüft?

Für Screenreader-Nutzende sind Grafiken nicht zugänglich. Die Textalternative tritt dann an die Stelle der Grafik, sie soll die Grafik ersetzen, diese beschreiben und insbesondere das Ziel bzw. die Aktion bezeichnen.

Entwicklerinnen und Entwickler müssen Grafiken mit passenden Text ergänzen, damit Hilfsmittelsoftware den Text anstelle der Grafik z. B. in Braille und Sprache ausgeben kann. Das UI-Element wird dabei um ein Accessibility-Label ergänzt. Bei komplexen Informations-Grafiken soll ein Textalternative oder eine andere Alternative (z.B. die tabellarische Ansicht eines Diagramms) für nicht-sehende Nutzende einen möglichst äquivalenten Informationsgehalt vermitteln.

== Wie wird geprüft?

=== 1. Anwendbarkeit des Prüfschritts

Der Prüfschritt ist anwendbar, wenn Grafiken als Bedienelemente (Menüs, Logos, Teaserbilder oder Schaltflächen) eingesetzt werden.

=== 2. Prüfung

Falls ein Bedienelement aus einer (Symbol-)Grafik sowie einem Text besteht, der den Zweck des Bedienelements wiedergibt, dann gilt dieser Text als Alternative für die Grafik. Es ist dann ggf. sinnvoll, die Grafik selbst mit einer geeigneten Technik für Screenreader zu verstecken. 

Handelt es sich dabei um eine Grafik ohne visuell sichtbaren Text (alleinstehendes Icon oder Symbol), so sollte eine Textalternative vorhanden sein, die das Ziel bzw. die Aktion, die ausgeführt wird, beschreibt. In der Praxis ist dies Text, der über ein Accessibility-Label bereitgestellt wird.

Handelt es sich um eine informationstragende Grafik, sollte diese in der Textalternative bzw. im unmittelbaren Kontext beschrieben sein. Bei interaktiven Grafiken soll (ggf. zusätzlich) das Ziel bzw. die hinterlegte Funktion angeben sein.

==== 2.1 Prüfung von Textalternativen
. App mit zu prüfender Ansicht öffnen.
. Screenreader starten und Fokus mit Hilfe der Wischgeste auf jedes grafische Bedienelement setzen.
. Prüfen, ob für die Bedienelemente Textalternativen ausgegeben werden und diese (auch) das Ziel bzw. die Funktion des Bedienelements beschreiben.
. Falls die Grafik zusammen mit aussagekräftigem Text als Bedienelement auftaucht, prüfen ob die Grafik vor dem Screenreader versteckt wird (keine unnötigen und redundanten Ausgaben durch den Screenreader aufgrund der Grafik). 
. Bei Informationstragenden Grafiken wird ein äquivalente Textalternative ausgegeben oder ist im unmittelbaren Kontext der Grafik verfügbar.

==== 2.2 Gleichwertige (äquivalente) Alternativtexte

Entscheidend ist: die App soll benutzbar sein, wenn Grafiken, oder Bilder oder Objekte durch die entsprechenden Textalternativen ersetzt
sind.

In der Regel bedeutet das:

* Bei Schriftgrafiken soll die Textalternative den Text der Schriftgrafik wiederholen.
* Bei Symbolen soll die Textalternative das Symbol nicht beschreiben, sondern ersetzen. Also zum Beispiel die Textalternative "Suchen" für ein Lupen-Symbol, das einen Dialog mit Sucheingabefeld öffnet.
* Bei Objekten, die nicht angezeigt werden können, sollen die Textalternative eine kurze Beschreibung oder Identifizierung bieten. Sinnvoll ist es, dass eine
  Begründung für das Nicht-Laden des Objekts ausgegeben wird. In diesem Fall ist es auch ausreichend, wenn das Objekt etwa durch eine Überschrift im unmittelbaren Kontext identifiziert wird.

Bei verlinkten Abbildungen gibt es folgende Möglichkeiten:

* Beschreibung des abgebildeten Gegenstandes in der Textalternative (wenn der abgebildete Gegenstand wichtig ist und daraus das Linkziel hervorgeht, zum
  Beispiel Logo)
* Ziel des Links in die Textalternative
* Beschreibung des abgebildeten Gegenstandes und Ziel des Links in der Textalternative (wenn beides wichtig ist)

Generell gilt:

* Textalternativen sollen kurz sein.
* Ausführliche Beschreibungen von Abbildungen sollen nicht in die Textalternative, sondern im Kontext der Abbildung zur Verfügung gestellt werden (etwa direkt darunter, in einem Ausklappbereich, oder auch in einem Link zu einer Ansicht, die die Alternative enthält).

=== 3. Hinweise

==== Textalternativen für redundant verlinkte Abbildungen

* Wenn eine Abbildung und ein danebenstehender Textlink auf dasselbe Ziel verweisen, muss geprüft werden, ob es sich um ein zusammengesetztes Bedienelement handelt (d. h. der Screenreader liest Grafik und Text nicht separat vor).
* Wenn es sich nicht um ein zusammengesetztes Bedienelement handelt, der Screenreader im Lesemodus also beide Elemente  nacheinander fokussiert und ausgibt, soll die Textalternative der Grafik nicht einfach die nebenstehende Beschriftung (Linktext) wiederholen. Je nach Inhalt der Abbildung kann die Textalternative dann 
** bei Schmuckgrafiken leer bleiben - das Element sollte ganz aus der Fokusreihenfolge entfernt werden
** bei verlinkten Abbildungen ggf. kurz den abgebildetem Inhalt nennen, in jedem Fall jedoch Zweck oder Ziel des Links bzw. der Funktion nennen (etwa: "öffnet vergrößerte Ansicht")
* Vorteilhaft ist in jedem Fall die Gruppierung von Grafiken und Text, wenn die gleiche Funktion bzw. das gleiche Ziel aufgerufen wird.

Dies ist Gegenstand der Prüfkriterien
ifdef::env_embedded[11.1.1.1b "Alternativtexte für Grafiken und Objekte"]
ifndef::env_embedded[]
  <<11.1.1.1b Alternativtexte für Grafiken und Objekte.adoc#,11.1.1.1b
  Alternativtexte für Grafiken und Objekte>>
endif::env_embedded[]
und
ifdef::env_embedded[11.1.1.1c "Leere alt-Attribute für Layoutgrafiken".]
ifndef::env_embedded[]
  <<11.1.1.1c Leere alt-Attribute für Layout-Grafiken.adoc#,11.1.1.1c Leere
  alt-Attribute für Layout-Grafiken>>.
endif::env_embedded[]

=== 4. Bewertung

*Nicht voll erfüllt:*

* Die Textalternative fehlt beim Link zum Seitenanfang oder bei einem anderen
  für die Benutzung der App weniger wichtigen Bedienelement.
* Textalternativen sind missverständlich, undeutlich oder extrem lang.

*Nicht erfüllt:*

* Die Textalternative für ein wichtiges Bedienelement fehlt oder er ist
  unbrauchbar.

== Einordnung des Prüfschritts

=== Abgrenzung zu anderen Prüfkriterien

Grafische Bedienelemente sind stets in diesem Prüfschritt zu bewerten.
Das gilt auch dann, wenn die Grafiken neben der Information über das Linkziel
auch noch eine andere Information vermitteln sollen.

* Einzige Ausnahme:
  Grafik und danebenstehender Text sind ein zusammengehöriger Link
  (zusammengesetztes Bedienelement).
  Die Textalternative bezieht sich dann nur auf die Grafik, die Prüfkriterien
ifdef::env_embedded[11.1.1.1b "Alternativtexte für Grafiken und Objekte"]
ifndef::env_embedded[]
  <<11.1.1.1b Alternativtexte für Grafiken und Objekte.adoc#,11.1.1.1b
  Alternativtexte für Grafiken und Objekte>>
endif::env_embedded[]
  oder
ifdef::env_embedded[11.1.1.1c "Leere alt-Attribute für Layoutgrafiken"]
ifndef::env_embedded[]
  <<11.1.1.1c Leere alt-Attribute für Layout-Grafiken.adoc#,11.1.1.1c Leere
  alt-Attribute für Layout-Grafiken>>
endif::env_embedded[]
  sind anzuwenden.

* Textalternativen für grafische Überschriften:
  siehe Prüfschritt
ifdef::env_embedded[11.1.1.1b "Alternativtexte für Grafiken und Objekte".]
ifndef::env_embedded[]
  <<11.1.1.1b Alternativtexte für Grafiken und Objekte.adoc#,11.1.1.1b
  Alternativtexte für Grafiken und Objekte>>.
endif::env_embedded[]

* CAPTCHAs werden im Prüfschritt
ifdef::env_embedded[11.1.1.1c "Alternativen für CAPTCHAs"]
ifndef::env_embedded[]
  <<11.1.1.1d Alternativen für CAPTCHAs.adoc#,11.1.1.1d Alternativen für
  CAPTCHAs>>
endif::env_embedded[]
  geprüft.

* Linktexte sind auch in Prüfschritt
ifdef::env_embedded[11.2.4.4 "Aussagekräftige Linktexte"]
ifndef::env_embedded[]
  <<11.2.4.4 Aussagekräftige Linktexte.adoc#,11.2.4.4 Aussagekräftige
  Linktexte>>
endif::env_embedded[]
  Thema.
  Dort geht es um die allgemeine Aussagekraft, in diesem Prüfschritt 11.1.1.1a
  geht es dagegen nur um die Gleichwertigkeit von Textalternative und grafischem
  Link.

=== Einordnung des Prüfschritts nach WCAG 2.1

==== Guideline

* https://www.w3.org/TR/WCAG21/#text-alternatives[Guideline 1.1 Text
  Alternatives:
  Provide text alternatives for any non-text content so that it can be changed
  into other forms people need, such as large print, braille, speech, symbols
  or simpler language.]

==== Success criterion

* http://www.w3.org/TR/WCAG21/#x1-1-1-non-text-content[1.1.1 Non-text Content]
  (Level A)

==== Techniques

.General Techniques
* https://www.w3.org/WAI/WCAG21/Techniques/general/G94[G94: Providing short
  text alternative for non-text content that serves the same purpose and
  presents the same information as the non-text content]

==== Failures

* https://www.w3.org/WAI/WCAG21/Techniques/failures/F20[F20: Failure of
  Success Criterion 1.1.1 and 4.1.2 due to not updating text alternatives when
  changes to non-text content occur]
* https://www.w3.org/WAI/WCAG21/Techniques/failures/F30[F30: Failure of
  Success Criterion 1.1.1 and 1.2.1 due to using text alternatives that are
  not alternatives]

== Quellen

=== Anleitungen zum Erstellen guter Textalternativen

* W3C Web Accessibility Tutorials:
  https://www.w3.org/WAI/tutorials/images/[Images Concepts]
* WebAIM: https://webaim.org/techniques/alttext/[Alternative Text]
