= Prüfschritt 11.1.3.5 Eingabefelder zu Nutzerdaten vermitteln den Zweck
include::include/author.adoc[]
include::include/attributes.adoc[]

== Was wird geprüft?

Eingabefelder, die sich auf die Nutzenden selbst beziehen, sollten eine semantisch eindeutige, sprachunabhängige Bestimmung ihres Zweckes ermöglichen.

In iOS/iPadOS und Android können Eingabefelder teilweise für einen bestimmten Zweck ausgezeichnet werden. Für die Eingabe einer E-Mail-Adresse kann beispielsweise dann das Betriebssystem u. a. eine optimierte Tastatur einblenden. Ob dies jedoch für die Konformität ausreicht, ist derzeit noch unklar.

== Warum wird das geprüft?

Die Festlegung des Eingabezwecks erlaubt es neuartigen Hilfsmitteln, bei Formularfeldern, welche sich auf Daten der Nutzenden beziehen, zusätzliche Informationen anzuzeigen, und zwar unabhängig vom der jeweils gewählten Beschriftung des Feldes und unabhängig von der natürlichen Sprache des Angebots.

Zusätzliche Informationen können etwa Bilder bzw. Icons sein, die über eine zukünftige assistive Technologie bereitgestellt werden könten und über bzw. vor dem jeweiligen Eingabefeld angezeigt werden, etwa wenn Nutzer eine bestimmte Tastenkombination drücken. Für Menschen, die Schwierigkeiten mit dem Lesen haben oder bevorzugt über Bilder kommunizieren, erleichtert dies eine Identifizierung von nutzerbezogenen Feldern in Formularen.

Darüber hinaus bietet die Auszeichnung des Zwecks Eingabevorschläge für das Feld, welche Nutzende einfach übernehmen können. Das erleichtert die Texteingabe.

== Wie wird geprüft?

=== 1. Anwendbarkeit des Prüfschritts

Der Prüfschritt ist anwendbar, wenn Formular-Eingabefelder vorhanden sind, die sich auf Nutzerdaten beziehen (etwa Login / Anmeldung, Kontaktformulare, oder Ansichten zum Anlegen eines Nutzerprofils).
Des Weiteren muss das Betriebssystem die Auszeichnung des Eingabezwecks unterstützen. In den Einstellungen zur Barrierefreiheit von Android und iOS müsste eine
entsprechende Einstellung auftauchen, mit der die Anzeige des Eingabezwecks ein- und ausgeschaltet werden kann. Dies ist zur Zeit (Juni 2020) nicht der Fall.

=== 2. Prüfung

Bei Apps ist die Prüfung eingeschränkt möglich. 

. Über eine Sichtprüfung feststellen, ob z.B. bei Eingabefeldern für E-Mail-Adressen auch die dafür optimierte Tastatur eingeblendet wird.
. Auf der erscheinenden Tastatur ist dann z. B. gleich das „``@``“-Zeichen und der Punkt verfügbar, ohne erst auf die Symboltastatur wechseln zu müssen.
Dies ist ein starkes Indiz dafür, dass das Eingabefeld korrekt ausgezeichnet wurde.
. Da es strittig ist, ob eine solche Auszeichnung ausreicht, muss geprüft werden, ob es möglich ist, in den Android- oder iOS- / iPadOS-Einstellungen die Anzeige des Eingabezwecks systemweit zu aktivieren.
. Daraufhin prüfen, ob die zu testende App die entsprechende Einstellung auch korrekt umsetzt.

=== 3. Hinweis

Die Anforderung gilt nur für Felder, die sich auf die Nutzenden selbst beziehen. Sie gilt nicht für Seiten bzw. Ansichten, auf denen die Eingabe von
persönlichen Daten mehrerer Personen möglich ist und die Felder für den Nutzer selbst nicht besonders gekennzeichnet sind. Ein Beispiel dafür sind Ticketbuchungsseiten / -Apps von Fluglinien. Hier sind die Eingabefelder für die Nutzenden nicht von den Feldern für Mitreisende unterscheidbar.

Auf GitHub können Sie zu diesem Prüfschritt ein
https://github.com/BIK-BITV/BIK-App-Test/issues[Issue eröffnen], falls Sie
Hinweise zu diesem Prüfschritt haben.

=== 4. Bewertung

==== Erfüllt

* Alle Eingabefelder, die sich klar auf Nutzende selbst beziehen, vermitteln den Zweck des jeweiligen Feldes. Da dies zur Zeit gegebenenfalls technisch nicht für alle Felder möglich ist, ist dieser Prüfschritt dann nicht anwendbar.

== Einordnung des Prüfschritts

=== Einordnung des Prüfschritts nach WCAG 2.1

==== Guideline

* https://www.w3.org/TR/WCAG21/#adaptable[Guideline 1.3 Adaptable: Create
  content that can be presented in different ways (for example simpler layout)
  without losing information or structure.]

==== Success criterion

* https://www.w3.org/TR/WCAG21/#identify-input-purpose[1.3.5 Identify Input
  Purpose (Level AA)]

== Quellen

* https://www.w3.org/WAI/WCAG21/Understanding/identify-input-purpose.html[
Understanding Success Criterion 1.3.5: Identify Input Purpose (zur Zeit nur auf
Englisch verfügbar)]

* Android Developer Resources: https://developer.android.com/guide/topics/text/autofill-optimize[Optimize your app for autofill (zur Zeit nur auf
Englisch verfügbar)]

* [BLOCK_LANG_EN]#Apple Developer Resources#: https://developer.apple.com/documentation/security/password_autofill/[Password AutoFill (zur Zeit nur auf
Englisch verfügbar)] Die unterstützten Arten von Autofill-Daten sind sehr begrenzt und dienen zur Zeit hauptsächlich dazu, die Tastatur dynamisch anzupassen https://developer.apple.com/documentation/uikit/uitextinputtraits/1649656-textcontenttype[textContentType (zur Zeit nur auf
Englisch verfügbar)]
