= Prüfschritt 11.1.3.2 Sinnvolle Reihenfolge
include::include/author.adoc[]
include::include/attributes.adoc[]

== Was wird geprüft?

in Software-Ansichten sollen korrekte Reihenfolgen vorherrschen z. B. folgt ein
Informationstext nach dessen Überschrift
Hier muss meist mangels Quelltextzugriff ein Blackbox-Test z. B. mittels
Screenreader durchgeführt werden.

== Warum wird das geprüft?

Screenreader lesen die Elemente, die auf dem Bildschirm in der Fläche
angeordnet sind, nacheinander vor - und zwar in der Reihenfolge, in der sie im
Quellcode stehen.
Die Reihenfolge der Elemente muss also gut verständlich und nutzbar sein.

== Wie wird geprüft?

=== Anwendbarkeit des Prüfschritts

Bei Software ist dieser Prüfschritt immer anwendbar.

=== Prüfung

Bei Software soll die Element-Reihenfolge im Wesentlichen die visuelle
Reihenfolge der Elemente abbilden.
Häufig kann dies mittels (Bluetooth-) Tastatur und aktiviertem Screenreader
getestet werden.
Da dieser Prüfschritt alle Elemente auf einer Ansicht prüft, betrifft dies
auch Nicht-Steuerelemente.
Mit dem Screenreader wandert man dazu auf das erste Element der Ansicht und
navigiert ab dort nach rechts die Elemente durch.
Hierbei wird beurteilt ob die Reihenfolge der Elemente sinnvoll und im
Wesentlichen der visuellen Reihenfolge entspricht.

=== Bewertung

*Nicht voll erfüllt:*

* Die Reihenfolge der Elemente ist nicht sinnvoll oder entspricht nicht der
Wesentlichen visuellen Folge.

== Einordnung des Prüfschritts

=== Abgrenzung von anderen Prüfkriterien

Custom controls, werden bereits in einer Reihe von bestehenden Prüfkriterien
implizit geprüft, etwa
ifdef::env_embedded[11.2.4.7 "Aktuelle Position des Fokus deutlich",]
ifndef::env_embedded[]
  <<11.2.4.7 Aktuelle Position des Fokus deutlich.adoc#,11.2.4.7 Aktuelle Position
  des Fokus deutlich>>,
endif::env_embedded[]
und
ifdef::env_embedded[11.4.1.2 "Name, Rolle, Wert verfügbar".]
ifndef::env_embedded[]
  <<11.4.1.2 Name-Rolle-Wert verfügbar.adoc#,11.4.1.2 Name, Rolle, Wert
  verfügbar>>.
endif::env_embedded[]

Die korrekte Reihenfolge im Quelltext bei dynamisch generierten oder
eingeblendeten Elementen ist Gegenstand von Prüfschritt
ifdef::env_embedded[11.2.4.3 "Schlüssige Reihenfolge bei der Tastaturbedienung".]
ifndef::env_embedded[]
  <<11.2.4.3 Schlüssige Reihenfolge bei der Tastaturbedienung.adoc#,11.2.4.3
  Schlüssige Reihenfolge bei der Tastaturbedienung>>.
endif::env_embedded[]

=== Einordnung des Prüfschritts nach WCAG 2.1

==== Guideline

* https://www.w3.org/WAI/WCAG21/quickref/?showtechniques=131#adaptable[
  Guideline 1.3 Adaptable: Create content that can be presented in different
  ways (for example simpler layout) without losing information or structure.]

==== Success criteria

* https://www.w3.org/WAI/WCAG21/quickref/?showtechniques=131#meaningful-sequence[
  1.3.2 Meaningful Sequence (Level A)]

==== Techniques

.General Techniques
* https://www.w3.org/WAI/WCAG21/Techniques/general/G57.html[G57 Ordering the
  content in a meaningful sequence]

==== Failures

* https://www.w3.org/WAI/WCAG21/Techniques/failures/F32.html[F32: Failure of
  Success Criterion 1.3.2 due to using white space characters to control
  spacing within a word]
* https://www.w3.org/WAI/WCAG21/Techniques/failures/F34.html[F34: Failure of
  Success Criterion 1.3.1 and 1.3.2 due to using white space characters to
  format tables in plain text content]

