= Prüfschritt 11.1.4.10 Inhalte brechen um
include::include/author.adoc[]
include::include/attributes.adoc[]

== Was wird geprüft?

Inhalte sollen laut Anforderung bei einer Viewport-Breite von 320 CSS Pixeln so umbrechen, dass alle Informationen und Funktionen verfügbar sind, ohne dass Nutzer horizontal scrollen müssen. Mobile Apps sind in der Regel für die Ausgabe der Inhalte auf den üblichen Viewport-Breiten der Smartphones von heute meist minimal 360 CSS Pixeln optimiert. 

Ausnahmen für den Umbruch auf die Breite von 320 CSS Pixeln gelten für Inhalte, für deren Nutzung ein zweidimensionales Layout erforderlich ist, z.B.:

* Bilder
* Landkarten
* Diagramme
* Videos
* Spiele
* Präsentationen
* Datentabellen 
* Anwendungs-Schnittstellen, in denen die Bearbeitung von Inhalten die permanente Verfügbarkeit von Werkzeugleisten erfordert.

=== Hinweis:
Dieser Prüfschritt beschränkt sich auf Inhalte, deren primäre Schreibrichtung waagerecht ist, wie bei der für die meisten westlichen Sprachen benutzten lateinischen Schrift. Die zugrunde liegende WCAG-Anforderung gilt in ähnlicher Weise für Inhalte mit vertikaler Schreibrichtung.

Bei mobilen Apps, die für einen horizontalen Bildlauf (z. B. mit vertikalem Text) ausgelegt ist, entspricht die Höhe des starting Viewports von 1024 px bei 400% Zoom.

== Warum wird das geprüft?

Bei mobilen Apps wird mit Bedienungshilfen des Betriebssystems der Bildschirmausschnitt vergrößert, hierbei wird jedoch Text nicht umgebrochen. Der Prüfschritt ist deshalb nicht in der gleichen Weise wie bei Websites anwendbar. Falls die App eine Nur-Text-Vergrößerung anbietet, sollte der Text jedoch korrekt umbrechen.

== Wie wird geprüft?

=== 1. Anwendbarkeit des Prüfschritts

Laut EN 301 549 ist dieser Prüfschritt auf Software anwendbar. Was her genau geprüft werden kann, ist zur Zeit noch unklar. In der Regel sind App-Inhalte an schmale Viewports angepasst und erfüllen damit diesen Prüfschritt.

=== 2. Prüfung

In der Regel ist diese Prüfschritt bei nativen Apps erfüllt, da nicht wie bei Websites ein eigentlicher Umbruch stattfindet. Manche Apps brechen Inhalte bei Ansicht im Querformat anders um. Eine angepasste Darstellung fürs Querformat ist sinnvoll, aber deren Fehlen kein Fehler im Sinne dieses Prüfschritts. 

=== 3. Hinweise

Von der Anforderung, dass alle Informationen und Funktionen verfügbar sind, ohne dass horizontales Scrollen notwendig ist, sind Inhalte ausgenommen, deren Nutzung ein zweidimensionales Layout voraussetzen (etwa Datentabellen, Bilder, Diagramme, Videos, Spiele oder Benutzerschnittstellen mit Werkzeugleisten).

Unklar ist noch, inwieweit in diesem Prüfschritt einstellbare Textvergrößerungen berücksichtigt werden sollten. Sind in der App Einstellungen zur Schriftvergrößerung vorhanden, sollte der Text im sichtbaren Bereich umbrechen. Das gilt bei Einstellungen von großem Text in den Bedienungshilfen auch für Texte, die dnamische Fonts unterstützen. Ggf. kommt es hierbei zu Umbrüchen innerhakb längerer Worte. Dies ist nicht als Fehler zu betrachten.


Für Hinweise zur Prüfpraxis können Sie auf GitHub https://github.com/BIK-BITV/BIK-App-Test/issues[ein Issue] zur diesem Prüfschritt erstellen.

// === 4. Bewertung

== Einordnung des Prüfschritts

=== Abgrenzung zu anderen Prüfkriterien

Im Prüfschritt wird nicht geprüft, ob die Zoomvergrößerung auf 400%
Textinhalte tatsächlich auf 400% oder einen geringeren Wert vergrößert.
Dies ist Gegenstand von Prüfschritt
ifdef::env_embedded[]
11.1.4.4 "Text auf 200% vergrößerbar".
endif::env_embedded[]
ifndef::env_embedded[]
<<11.1.4.4 Text auf 200% vergrößerbar.adoc#,11.1.4.4 Text auf 200%
vergrößerbar>>.
endif::env_embedded[]

== Quellen

https://www.w3.org/WAI/WCAG21/Understanding/reflow.html[Understanding 1.4.11 Reflow]
(zur Zeit nur auf Englisch verfügbar)
