= 11.1.1.1d Alternativen für CAPTCHAs
include::include/author.adoc[]
include::include/attributes.adoc[]

== Was wird geprüft?

In bildbasierten CAPTCHAs soll der Alternativtext des Bildes den Zweck des
CAPTCHAs beschreiben und angeben, wie eine nicht bildbasierte Alternative zu
finden ist.

Mindestens eine CAPTCHA-Alternative für ein Grafik-Captcha oder Audio-Captcha
muss vorhanden sein.

== Warum wird das geprüft?

In bildbasierten CAPTCHAs werden Bilder von Zeichenfolgen eingesetzt, welche
Nutzer als Text eingeben müssen, um bestimmte Bereiche der App zu erreichen.
Für blinde und sehbehinderte Nutzer sind solche CAPTCHAs nicht zugänglich.
Audio-Captchas sind für höreingeschränkte Nutzer nicht zugänglich.
Deshalb soll in beiden Fällen mindestens eine CAPTCHA-Alternative angeboten
werden.

Bei bildbasierten CAPCHAs soll der Alternativtext den Zweck des CAPTCHAs
beschreiben und angeben, wie CAPTCHA-Alternativen zu finden sind.

== Wie wird geprüft?

=== 1. Anwendbarkeit des Prüfschritts

Der Prüfschritt ist anwendbar, wenn CAPTCHAs vorhanden sind.

Die Leserlichkeit der Zeichenfolge in einem bildbasierten CAPTCHA ist nicht
Teil der Prüfung und wird nicht bewertet.

=== 2. Prüfung

==== 2.1 Prüfung der Alternativtexte von CAPTCHA-Bildern

. App mit zu prüfender Ansicht starten.
. Prüfen ob CAPTCHAs eingesetzt werden.
. Screenreader starten (siehe Handreichung).
. Prüfen, ob beim Antippen des CAPTCHAs eine Textalternative vom Screenreader
  ausgegeben wird und der dort hinterlegte Alternativtext den Zweck des
  CAPTCHAs beschreibt (zum Beispiel: "Geben sie die im Bild dargestellte
  Zeichenfolge ein").
  Wenn eine CAPTCHA-Alternative verfügbar ist, sollte der Alternativtext
  außerdem sagen, wie diese zu finden ist.

==== 2.2 Vorhandensein von CAPTCHA-Alternativen

Prüfen, ob im unmittelbaren Kontext des bildbasierten CAPTCHAs oder
Audio-Captchas eine Alternative angeboten wird.

=== 3. Hinweise

CAPTCHAs sind generell problematisch, da jede Form von CAPTCHA für manche
Nutzer mit Behinderungen unzugänglich ist (siehe die WCAG 2.0 Note on CAPTCHA).

=== 4. Bewertung

==== Nicht voll erfüllt:

* Alternativtexte nennen nicht den Zweck des CAPTCHAs.
* Ein Alternativ-CAPTCHA ist vorhanden, aber es wird darauf nicht im
  Alternativtext verwiesen oder es ist nicht im unmittelbaren Kontext
  zugänglich.

==== Nicht erfüllt:

* Eine Alternative zu bildbasierten CAPTCHAs oder Audio-Captchas ist nicht
  vorhanden.

== Einordnung des Prüfschritts

=== Abgrenzung zu anderen Prüfkriterien

Auch die Texteingabe des Captchas muss zugänglich gestaltet sein, damit es
insgesamt zugänglich ist.

Die Zugänglichkeit der CAPTCHA-Texteingabe wird im Prüfschritt
ifdef::env_embedded[11.3.3.2 "Beschriftungen von Formularelementen vorhanden"]
ifndef::env_embedded[]
  <<11.3.3.2 Beschriftungen von Formularelementen vorhanden.adoc#,11.3.3.2
  Beschriftungen von Formularelementen vorhanden>>
endif::env_embedded[]
geprüft.

=== Einordnung des Prüfschritts nach WCAG 2.1

==== Guideline

* https://www.w3.org/TR/WCAG21/#text-alternatives[Guideline 1.1 Text
  Alternatives]:
  Provide text alternatives for any non-text content so that it can be changed
  into other forms people need, such as large print, braille, speech, symbols
  or simpler language

==== Success Criterion

* http://www.w3.org/TR/WCAG21/#x1-1-1-non-text-content[1.1.1 Non-text Content
  (Level A)]

==== Techniques

.General Techniques
* https://www.w3.org/WAI/WCAG21/Techniques/general/G143[G143: Providing a text
  alternative that describes the purpose of the CAPTCHA]
* https://www.w3.org/WAI/WCAG21/Techniques/general/G144[G144: Ensuring that
  the Web Page contains another CAPTCHA serving the same purpose using a
  different modality]

==== Failures

* https://www.w3.org/WAI/WCAG21/Techniques/failures/F65[F65: Failure of Success
  Criterion 1.1.1 due to omitting the alt attribute on img elements, area
  elements, and input elements of type 'image']

== Quellen

=== EN 301 549 V.3.2.1 Text

==== 11.1.1.1.1 Non-text content (open functionality)

* NOTE: CAPTCHAs do not currently appear outside of the Web. However, if they do appear, this guidance is accurate.

=== Andere Quellen

* http://www.karlgroves.com/2012/04/03/captcha-less-security/[CAPTCHA-less
  Security by Karl Groves, 2012]
