= Prüfschritt 11.1.3.5 Eingabefelder zu Nutzerdaten vermitteln den Zweck
include::include/author.adoc[]
include::include/attributes.adoc[]

*Hinweis: Dies ist ein Entwurf. Inhalte können sich jederzeit ändern.*

== Was wird geprüft?

Eingabefelder, die sich auf den Nutzer selbst beziehen, sollten eine semantisch eindeutige, sprachunabhängige Bestimmung ihres Zweckes ermöglichen.

In iOS/iPadOS und Android können Eingabefelder teilweise für einen bestimmten Zweck ausgezeichnet werden, etwa für die Eingabe einer E-Mail-Adresse, für ein PIN-Code-Eingabe oder eine URL. Für solche Eingabefelder kann das Betriebssystem eine optimierte Tastatur einblenden.
Dies unterstützt die Identifizierung des Eingabezwecks, deckt sich jedoch nicht der Intention der Anforderung.

Auf GitHub können Sie zu diesem Prüfschritt ein
https://github.com/BIK-BITV/BIK-App-Test/issues[Issue eröffnen], falls Sie
Hinweise zu diesem Prüfschritt haben.

== Warum wird das geprüft?

Die Festlegung des Eingabezwecks (sobald dies möglioch ist) erlaubt es neuartigen Hilfsmitteln, bei Formularfeldern, welche sich auf Daten des Nutzers beziehen, zusätzliche Informationen anzuzeigen, und zwar unabhängig vom der jeweils gewählten Beschriftung des Feldes und unabhängig von der natürlichen Sprache des Angebots.

Zusätzliche Informationen können etwa Bilder bzw. Icons sein, die über eine zukünftige assistive Technologie bereitgestellt werden köntte und über bzw.
vor dem jeweiligen Eingabefeld angezeigt werden, etwa wenn Nutzer eine bestimmte Tastenkombination drücken. Für Menschen, die Schwierigkeiten mit dem Lesen haben oder bevorzugt über Bilder kommunizieren, erleichtert dies eine Identifizierung von nutzerbezogenen Feldern in Formularen.

Darüber hinaus bietet die Auszeichnung des Zwecks Eingabevorschläge für das Feld, welche Nutzer einfach übernehmen können, und bietet ggf. an die Art der Eingabe angepasste Tastaturen an. Das erleichtert die Texteingabe.

== Wie wird geprüft?

=== Anwendbarkeit des Prüfschritts

Der Prüfschritt ist anwendbar, wenn Formular-Eingabefelder vorhanden sind, die sich auf Nutzerdaten beziehen (etwa Login / Anmeldung, Kontaktformulare,
oder Ansichten zum Anlegen eines Nutzerprofils).
Für eine Prüfung, die Konformität buzw. Nichtkonformität feststellen würde, müsste die App bzw. Betriebssystem die Auszeichnung der Eingabezwecke unterstützen, die in Abschnitt https://www.w3.org/TR/WCAG21/#input-purposes[7. Input Purposes for User Interface Components] der WCAG festgelegt sind.
In den Einstellungen zur Barrierefreiheit von Android und iOS müsste außerdem eine Einstellung auftauchen, mit der die Anzeige des Eingabezwecks
ein- und ausgeschaltet werden kann. Beides ist zur Zeit (Juni 2022) nicht der Fall.

=== Prüfung

Bei Apps ist die Prüfung eingeschränkt möglich. Hier kann über eine Sichtprüfung z. B. festgestellt werden, ob bei Eingabefeldern für E-Mail-Adressen, Pin-Codes, URLs usw. auch die dafür optimierte Tastatur eingeblendet wird.
Auf der Tastatur für Email-Adressen erscheint dann z. B. prominent das „``@``“-Zeichen und der Punkt ist verfügbar, ohne erst auf die Symboltastatur wechseln zu müssen.

=== Hinweis

Die Anforderung gilt nur für Felder, die sich auf den Nutzer selbst beziehen. Sie gilt nicht für Seiten bzw. Ansichten, auf denen die Eingabe von
persönlichen Daten mehrerer Personen möglich ist und die Felder für den Nutzer selbst nicht besonders gekennzeichnet sind. Ein Beispiel dafür sind Ticketbuchungsseiten / -Apps von Fluglinien. Hier sind die Eingabefelder für den Nutzer nicht von den Feldern für Mitreisende unterscheidbar.

=== Bewertung

==== Erfüllt:

* Eingabefelder, die sich klar auf Nutzende selbst beziehen, unterstützen indirekt das Verständis des Zweck des Eingabezwecks, z.B. ggf. über die Anzeige einer anderen Tastatur oder Textvorschläge (Autofill).

==== Eher erfüllt: 
* Eingabefelder, die sich klar auf Nutzende selbst beziehen, generieren keine Eingabevorschläge und zeigen keine abweichende Tastatur an (etwa für E-Mail-Felder).

==== Nicht anwendbar:
* Eingabefelder beziehen sich nicht eindeutig auf die Nutzenden selbst.

== Einordnung des Prüfschritts

=== Einordnung des Prüfschritts nach WCAG 2.1

==== Guideline

* https://www.w3.org/TR/WCAG21/#adaptable[Guideline 1.3 Adaptable: Create
  content that can be presented in different ways (for example simpler layout)
  without losing information or structure.]

==== Success criterion

* https://www.w3.org/TR/WCAG21/#identify-input-purpose[1.3.5 Identify Input
  Purpose (Level AA)]

== Quellen

* https://www.w3.org/WAI/WCAG21/Understanding/identify-input-purpose.html[
Understanding Success Criterion 1.3.5: Identify Input Purpose (zur Zeit nur auf
Englisch verfügbar)]

=== Android
* Android Developer Resources: https://developer.android.com/guide/topics/text/autofill-optimize[Optimize your app for autofill (zur Zeit nur auf
Englisch verfügbar)]

=== iOS
* [BLOCK_LANG_EN]#Apple Developer Resources#: https://developer.apple.com/documentation/security/password_autofill/[Password AutoFill (zur Zeit nur auf
Englisch verfügbar)] Die unterstützten Arten von Autofill-Daten sind sehr begrenzt und dienen zur Zeit hauptsächlich dazu, die Tastatur dynamisch anzupassen. Siehe auch https://developer.apple.com/documentation/uikit/uitextinputtraits/1649656-textcontenttype[textContentType:
The semantic meaning for a text input area]. (zur Zeit nur auf Englisch verfügbar)
* https://developer.apple.com/documentation/uikit/uikeyboardtype[UIKeyBoardType: Verfügbare angepasste Tastaturen fpr bestimmte EIngabefelder]
