= Prüfschritt 11.1.3.1b Datentabellen richtig aufgebaut
include::include/author.adoc[]
include::include/attributes.adoc[]

== Was wird geprüft?

Datentabellen sind strukturell richtig aufgebaut, Zeilen- und Spaltenüberschriften sind plattformspezifisch im Programm-Code ausgezeichnet.

== Warum wird das geprüft?

Sehbehinderte und blinde Nutzende erschließen sich Datentabellen analytisch und entwickeln anhand der Spalten- und ggf. Zeilen-Überschriften eine Vorstellung vom Aufbau der Tabelle. Wenn es semantische Überschriften gibt (oft sind diese auch visuell hervorgehoben) und Zelleninhalte nur mit diesen zusammen aussagekräftig sind, sollen sie beim Navigieren der Tabellenzellen verfügbar sein. Bei jedem Wechsel zur nächsten Zelle wird dann die jeweils neue Spalten- oder Zeilenüberschrift ausgegeben. 

== Wie wird geprüft?

=== 1. Anwendbarkeit des Prüfschritts

Der Prüfschritt ist immer anwendbar, wenn Tabellen in der App-Ansicht vorhanden sind. Diese sind in nativen Apps eher selten, tauchen aber häufiger in Webviews auf.

Zur Tabellennavigation siehe Abschnitt 3. Hinweise für iOS und Android.

=== 2. Prüfung

==== 2.1 Werden Tabellen für tabellarische Daten verwendet?

. Prüfen, ob die App-Ansicht Datentabellen enthält (d.h. Daten stehen in einer logischen Beziehung zueinander und sind rasterartig organisiert).
. Alternativ mit aktiviertem Screenreader und Rotor-Einstellung "Tabelle" über vertikale Wischgesten erkunden, ob Datentabellen gefunden werden.
. Visuelle Prüfung: Erste Zelle (oben links) antippen, prüfen, ob nach Ausgabe des Inhalts, der Zeile und Spalte "Anfang der Tabelle" (iOS) oder "In Tabelle" (Android) ausgegeben wird. 
. über horizontale Wischgesten die Zellen der Tabelle linear durchlaufen. Falls Spalten-Überschriften vorhanden sind, prüfen ob diese bei Fokussierung der Datenzelle ausgegeben werden.

==== 2.2 Prüfung des Aufbaus von Tabellen

Prüfen, ob die Tabelle strukturell sinnvoll aufgebaut ist. Schwierigkeiten entstehen in den meisten Fällen dadurch, dass die Tabelle auch Layoutzwecken dient, das Tabellengitter also für die Anordnung von Inhalten auf dem Bildschirm genutzt wird. Problematisch können zum Beispiel sein:

* Eine Spalte mit Daten ist vor der Überschriftenspalte platziert
* Wechsel der Bedeutung von Zeilen oder Spalten ("ab hier ...")
* Zellen mit Erläuterungen sind in die Tabelle integriert
* Leere Zeilen werden eingefügt, um die Höhe oder den Abstand von Zeilen festzulegen
* Verschachtelungen (weitere Tabelle innerhalb einer Tabellenzelle)


Auch komplexe Tabellen sind aus einfachen Spalten und Zeilen zusammengesetzt, die Anforderungen sind so weit die selben. Hinzu kommt allerdings, dass benachbarte Zeilen oder Spalten durch übergreifende Überschriften zusammengefasst sind. Auch den Inhalt dieser zusammengefassten Bereiche muss man allgemein fassen können, wie den Inhalt der einzelnen Spalten und Zeilen.

==== 2.3 Prüfung der Auszeichnung von Tabellen

. App mit zu prüfender Ansicht öffnen.
. Prüfen, ob die App-Ansicht eine Datentabelle enthält.
. Screenreader starten und mit Hilfe der Wischgeste durch die Tabelle navigieren.
. Prüfen, ob alle Spalten- und Zeilenüberschriften zusammen mit der Datenzelle ausgegeben werden. 
. Alternativ die Zeilen- bzw. Spaltenüberschrift angetippen und prüfen, was der Screenreader ausgibt: Wenn der Screenreader "Zeilenüberschrift", "Spaltenüberschrift" oder ähnlich als Zusatz spricht, sind die entsprechenden Überschriften korrekt ausgezeichnet.

=== 3. Hinweise

==== 3. Erschließen von Tabellen in iOS
* Vor der Prüfung sicherstellen, dass "Tabellen" im Rotor als Navgationsmöglichkeit aktiviert ist.
* Mit Rotoreinstellung "Tabellen" sind Tabellen über vertikale Wischgeste erreichbar (fokussiert wird die Zelle links oben)
* iPad: Über CTR + Option + Pfeiltasten können Tabellenzellen durchlaufen werden. Dabei werden semantisch umgesetzte Spaltenüberschriften ausgegeben.
* iPad: Über Kurzbefehle (bei iOS mit Tastatur, CTR + Option + C) können Spaltenheader ausgegeben werden.


==== 3.3 Tabellen mit eingesparten Überschriften

Überschriften sind überflüssig, wenn in den Zellen neben den Einzelwerten auch deren Bedeutung angegeben ist oder wenn die Bedeutung der Einzelwerte sich von selbst versteht. Ein typisches Beispiel dafür sind Preislisten: in der linken Spalte stehen die meist selbsterklärenden Produktbezeichnungen, in der rechten Spalte steht nicht nur der Betrag, sondern auch das Währungszeichen.

Für blinde und sehbehinderte Nutzende kann der Umgang mit solchen Tabellen schwierig sein. Denn mangels Überschriften müssen sie auf den Wertebereich zugreifen, um zu
verstehen, was die Tabelle anbietet. Für normal sehende Nutzende ist das leicht, für Benutzer, die sich immer nur einen kleinen Ausschnitt der Tabelle vorlesen oder anzeigen lassen können, aber nicht.

Unproblematisch ist der Verzicht auf Überschriften, wenn zwei Bedingungen erfüllt sind:

* Der Aufbau der Tabelle ist der ersten Zeile zu entnehmen.
* Die Tabelle listet Daten auf, die zusammen gehören und eine feste Reihenfolge haben. Sie wird also normalerweise linear genutzt, wie ein Buch.

Tabellen mit eingesparten Überschriften erfüllen also den Prüfschritt, wenn sie richtig aufgebaut und linear nutzbar sind.

Bei Software ist es in der Regel nicht ohne den Quelltext möglich, die korrekte syntaktische Auszeichnung festzustellen. Hier kann dann in der Regel nur ein Test mit einem Screenreader durchgeführt werden. Dieser sagt dann an, ob es sich um eine "richtige" Tabelle handelt und kann beim Navigieren über Zeilen und Spalten ggf. auch dessen Überschriften ausgeben.


=== 4. Bewertung

==== Nicht voll erfüllt:

* Für tabellarische Daten wird keine Tabellensemantik verwendet.

== Einordnung des Prüfschritts

=== Einordnung des Prüfschritts nach WCAG 2.1

==== Guideline

* https://www.w3.org/TR/WCAG21/#adaptable[Guideline 1.3 Adaptable: Create
  content that can be presented in different ways (for example simpler layout)
  without losing information or structure]

==== Success criterion

* https://www.w3.org/TR/WCAG21/#info-and-relationships[1.3.1 Info and
  Relationships (Level A)]

==== Techniques

.General Techniques
* https://www.w3.org/WAI/WCAG21/Techniques/general/G115.html[G115: Using
  semantic elements to mark up structure]
* https://www.w3.org/WAI/WCAG21/Techniques/general/G140.html[G140: Separating
  information and structure from presentation to enable different presentations]

==== Failures

* https://www.w3.org/WAI/WCAG21/Techniques/failures/F33.html[F33: Failure of
  Success Criterion 1.3.1 and 1.3.2 due to using white space characters to create
  multiple columns in plain text content]
* https://www.w3.org/WAI/WCAG21/Techniques/failures/F34.html[F34: Failure of
  Success Criterion 1.3.1 and 1.3.2 due to using white space characters to
  format tables in plain text content]
* https://www.w3.org/WAI/WCAG21/Techniques/failures/F48.html[F48: Failure of
  Success Criterion 1.3.1 due to using the pre element to markup tabular
  information]
* https://www.w3.org/WAI/WCAG21/Techniques/failures/F91.html[F91: Failure of
  Success Criterion 1.3.1 for not correctly marking up table headers]
* https://www.w3.org/WAI/WCAG21/Techniques/failures/F92.html[F92: Failure of
  Success Criterion 1.3.1 due to the use of role presentation on content which
  conveys semantic information]

== Quellen


==== Informationen für Entwickler (iOS / iPadOS)

Personen, die Apps entwickeln, können das Protokoll
`"link:https://developer.apple.com/documentation/uikit/uiaccessibilitycontainerdatatable[
UIAccessibilityContainerDataTable]"`
zur Auszeichnung von barrierefreien Datentabellen nutzen.

=== W3C - Web Accessibility Tutorials

* https://www.w3.org/WAI/tutorials/tables/[Tables Tutorial]

=== Entwicklerressourcen

* Apple Developer:
  https://developer.apple.com/documentation/uikit/uiaccessibilitycontainerdatatable[
  UIAccessibilityContainerDataTable]
