= Prüfschritt 11.1.4.10 Inhalte brechen um
include::include/author.adoc[]
include::include/attributes.adoc[]

*Hinweis: Dies ist ein Entwurf. Inhalte können sich jederzeit ändern.*

== Was wird geprüft?

Inhalte der App sollen bei einer Viewport-Breite von 320 CSS Pixeln so angezeigt werden, dass alle Informationen und Funktionen verfügbar sind, ohne dass Nutzer horizontal scrollen müssen. Ausgenommen sind Inhalte, für deren Nutzung ein zweidimensionales Layout erforderlich ist, etwa Datentabellen oder Karten (siehe Abschnitt "Ausnahmen"). Die Inhalte mobiler Aps sind meist standardmäßig für die Ansicht im Hochkant-Format optimiert, auch wenn die heute verbreiteten Mobilgeräte hochkant meist eine etwas größere Viewportbreite als 320 CSS-Pixel haben. Damit ist dieser Prüfschritt in der Regel erfüllt.  Zu prüfen ist, ob es Inhalte gibt, die nicht in den schmalen Viewport passen, aber nicht unter die Ausnahmen zu rechnen sind.

Native Apps, auch die gängigen Browser, verfügen in der Regel nicht über die Möglichkeit, innerhalb der App den Zoomfaktor zu ändern, wie dies über die Zoom-Funktion in Desktop-Browsern geschieht. Dort führt das Hineinzoomen bei responsiven Sites zum Umburch in eine andere Darstellung. Manche Apps zeigen einen anderen Umbruch der Inhalte, wenn das Gerät ins Querformat gedreht wird oder wenn die App auf einem Tablet mit größerer Viewportbreite geladen wird. Fü rdiese ist die Ansicht nach Zoomvergrößerung auf 320 CSS-Pixel zu prüfen. 

=== Ausnahmen
Von der Anforderung ausgenommen sind Inhalte der Ansicht, für deren Nutzung ein zweidimensionales Layout erforderlich ist und die auf eine geringe Viewportbreite verkleinert nicht sinnvoll nutzbar sind, z.B.:

* Bilder
* Landkarten
* Diagramme
* Videos
* Spiele
* Präsentationen
* Datentabellen 
* Anwendungs-Schnittstellen, in denen die Bearbeitung von Inhalten die permanente Verfügbarkeit von
Werkzeugleisten erfordert.

== Warum wird das geprüft?

Alle Inhalte, die gut umbrechen können, sollen in den Viewport mit Breite von 320 CSS-Pixeln passen, um die mühsame Bedienung über horizontales Scrollen oder Verschieben über Ziehgesten zu vermeiden. Zu solchen Inhalten, die gut umbrechen können, zählen nicht nur Fließtexte, sondern z.B. auch Formulare und Menüs.

Wenn native Appps ähnlich wie Desktop-Browser eine Zoomfunktion anbieten, hilft dies sehbehinderten Nutzern, die eine vergrößerte Darstellung brauchen, z.B. um Text überhaupt lesen zu können. Wenn so eine Zoom-Funktion in der App geboten wird, wäre zu prüfen, ob nach Hineinzoomen auf eine Viewport-Breite von 320 CSS-Pixel noch alle Informationen und Funktionen verfügbar sind.

== Wie wird geprüft?

=== 1. Anwendbarkeit des Prüfschritts

Der Prüfschritt ist immer anwendbar.

Laut EN 301 549 Version 3.1.1 ist dieser Prüfschritt auf Software und damit auch auf mobile Apps anwendbar. In der Regel ist er schon dadurch erfüllt, dass alle Inhalte auf die Ausgabe innerhalb des Hochkant-Viewports optimiert sind. 

=== 2. Prüfung
==== 2.1 Standard-Hochkant-Ansicht mit Viewportbreite von 320 CSS-Pixeln
Gibt es in der Hochkant Ansicht (kleines Smartphone idealerweise eines mit Viewport-Breite von 320 CCS-Pixeln) Informationen oder Funktionen, die nicht unter die Ausnahmen falen und die nicht verfügbar sind bzw. nur über horizontzales Scropllen / Verschieben erreihbar sind? 

==== 2.2 Prüfung von Apps mit beiterem Layout und Zoomfunktion
. Vorbedingung 1: Hat die App selbst eine Zoomfunktion (es geht nicht um den Zoom bzw. die Vergrößerung über Bedienungshilfen)
. Vorbedingung 2: Stellt die App Inhalte auf Geräten mit breiteren Viewports (oder nach Drehen des Smartphones ins Querformat) in einem anderen Layout dar als auf dem Smartphones im Hochkant-Format?
. Ist eine der Vorbedingungen nicht erfüllt, wird die Prüfung sbgebrochen.
. Falls beide Vorbedingungen erfüllt sind: Die Inhalte soweit vergrößern, bis näherungsweise eine Viewport-Breite von 320 px erreicht ist (siehe dazu Hinweise unter Punkt 3.2, Vergrößerung auf Viewportbreite von 320 CSS-Pixel)
. Gibt es in der App Informationen oder Funktionen, die nun nicht mehr verfügbar sind oder abgeschnitten werden und die nicht unter die Ausnahmen fallen?

Für Hinweise zur Prüfpraxis können Sie auf GitHub
https://github.com/BIK-BITV/BIK-App-Test/issues[ein Issue] zur diesem
Prüfschritt erstellen.

=== 3. Hinweise

==== 3.1 Praktische Aspekte der Prüfung: Geräte zum Testen

* Oft wird für die Prüfung kein Gerät mit exakt 320 CSS Pixeln Viewportbreite und aktuellem Betriebssystem zur Verfügung stehen. Deshalb ist es unvermeidlich, auf einem gängigen Gerät mit etwas größerer Viewportbreite zu testen (etwa ein iPhone 13 mini, oder ein Samsung Galaxy A12, beide mit 360 CSS Pixeln Viewport-Breite).
* Werden Apps getestet, die Layouts für breitere Ansichten bieten *und* eine Zoomfunktion implementieren, ist zu prüfen, ob die Querformat-Ansicht auf dem Smartphone bereits eine abweichendes Layout bietet. Z.T. werden Apps nur in der Hochkant-Ansicht angeboten (und erfüllen damit nicht Anforderung 11.1.3.4 "Keine Beschränkung der Bildschirmausrichtung") oder sie zeigen die App-Inhlate auch im Querformat nur in einem Teil des Displays, der der Viewportbreite bei Hochkantansicht enspricht. Ggf. muss ein Tablet mit breiterem Viewport verwendet werden.

==== 3.2 Vergrößerung auf Viewportbreite von 320 CSS-Pixel
Abhängig vcom genutzten Testgerät kann die Breite von 320 px ggf. nur näherungsweise erreicht werden. Bei einer Vergrößerungsstufe von 200% wäre die Viewportbreite in CSS-Pixeln halbiert. Je nach Gerät müsste als verschieden stark vergrößert werden, um 320 CSS-Pixel zu erreichen. Bei einem iPad Air (2020) mit 1112 CSS-Pixeln Breite wäre z.B. eine Vergrößerung um 347,5% notwendig um exakt 320 CSS-Pixel Viewportbreite zu erreichen. ISt dieViewportbreite des Displays nitcht bekannt lässt diese sich in der Regel aus der physischen Auflösung des Displays und dem genutzten Pixel-Verhältnis  (pixel ratio) berechnen. Die meisten aktuellen Geräte haben heute eine pixel ratio zwischen 3 und 4. So hat etwa ein Samsung note 8 eine physische Auflösung von 1440 x 2960 Geräte-Pixeln, was bei einem Faktor 4 zu einer Auslösung von 360 x 740 CSS-Pixeln führt. Hier müsste also auf 230% vergrößert werden um näherungsweeise die Viewport-Breite von 320 CSS-Pixeln einzustellen.

==== 3.3 Lese- und Schreibrichtung
Dieser Prüfschritt beschränkt sich auf Inhalte, deren primäre Schreibrichtung waagerecht ist, wie bei der für die meisten westlichen
Sprachen benutzten lateinischen Schrift. Die zugrunde liegende WCAG-Anforderung gilt in ähnlicher Weise für Inhalte mit vertikaler Schreibrichtung.

==== 3.4 Zoomfunktion auch bei Apps?
Im Kontext mobiler Apps mit der Ausgabe auf einem meist viel kleinerem Display kommen für sehbeninderte Nutzende eher systemseitige Methoden der Textvergrößerung zum Tragen: Einmal die Einstellung größerer Schrift in den Bedienungshilfen, die sich auf die Darstellung auswirkt, wenn Entwickler in der App dynamische Fonts verwenden, und dann die Bedienungshilfen Vergrößerung (Android) bzw. Zoom (iOS), deren Nutzung nicht zu einem Umbruch der Inhalte führt. Werden Apps auf Tablets mit größeren Viewport-Breiten angezeigt, wäre die Zoomvergrößerung hier ebenso hilfreich wie auf dem Desktop. Sie wird aber von nativen Apps (einschließlich mobilen Browsern) zurzeit kaum angeboten.

==== 3.5 Angepasste Ansichten für breitere Viewports
Aus dem normativen Text ist keine Verpflichtung abzuleiten, dass für größere Viewportbreiten ein angepasstes Layout angeboten werden muss.

=== 4. Bewertung
==== Nicht erfüllt

* Die App hat eine Zoomfunktion. Beim Zoomen auf 320 CSS Pixel Viewportbreite gibt es Informationen oder Funktionen, die nicht mehr verfügbar sind oder abgeschnitten werden, und die nicht unter die Ausnahmen fallen.

== Quellen

https://www.w3.org/WAI/WCAG21/Understanding/reflow.html[Understanding Reflow]
(zur Zeit nur auf Englisch verfügbar)
