= Prüfschritt 11.1.4.11 Kontraste von Grafiken und Bedienelementen ausreichend
include::include/author.adoc[]
include::include/attributes.adoc[]

*Hinweis: Dies ist ein Entwurf. Inhalte können sich jederzeit ändern.*

== Was wird geprüft?

Die für die Identifizierung notwendige visuelle Information von
informationstragenden Grafiken und grafischen Bedienelementen sowie deren
Zuständen soll einen Kontrast von mindestens 3:1 zu angrenzenden Farben haben.

In vielen Fällen, wie etwa bei einfarbigen Icons, bedeutet das einfach, dass
der Kontrast zwischen der Farbe des Elements und der Hintergrundfarbe gemessen
wird.

Bei mehrfarbigen oder abgetönten Elementen gilt die Kontrastanforderung für
jene visuelle Information, über die das Element (oder dessen Zustand)
hinreichend klar identifizierbar ist.
Es müssen also nicht sämtliche Bereiche einer Grafik die Kontrastanforderung
erfüllen.

Wenn grafische Elemente zusätzlich eingesetzt werden, ein Text also das
Bedienelement bzw. dessen Zustand hinreichend kennzeichnet, müssen grafische
Elemente die Kontrastanforderung nicht erfüllen.

== Warum wird das geprüft?

Viele Menschen mit Sehbehinderungen brauchen gute Kontraste, um grafische
Bedienelemente bzw. deren Zustände oder Elemente in informationstragenden
Grafiken, etwa statistischen Diagrammen oder Schaubildern, wahrnehmen zu
können.
Die Forderung nach einem Minimalkontrast für informationstragende Grafiken
hilft diesen Menschen.

== Wie wird geprüft?

=== 1. Anwendbarkeit des Prüfschritts

Der Prüfschritt ist anwendbar, wenn informationstragende grafische
Bedienelemente, die nicht lediglich ergänzend (etwa zu Text) eingesetzt
werden, oder informationstragende Grafiken vorhanden sind.

Nicht anwendbar ist der Prüfschritt auf Fotos, Logos, Flaggen, Screenshots,
Diagramme mit Farben, die nicht geändert werden dürfen, und
Datenvisualisierungen mit Farbabstufungen wie etwa Heatmaps.

Ebenfalls nicht anwendbar ist der Prüfschritt auf inaktive Bedienelemente,
also solche, die zustandsabhängig für die Interaktion nicht zur Verfügung
stehen.

=== 2. Prüfung

Hinweis: Für die aufgeführten Prüfungen ist eine Sichtprüfung ausreichend,
wenn der Kontrast sehr deutlich über 3:1 liegt.
Im Zweifelsfall immer den Color Contrast Analyzer einsetzen.

Bei Prüfungen von Software-Ansichten muss mit Screenshots gearbeitet werden.
Diese werden dann regulär mit dem Contrast-Analyzer überprüft.
Falls es schwierig ist, Einzelheiten mit der Contrast-Analyzer-Pipette zu
erfassen, kann vor der Erstellung des Screenshots die entsprechende Ansicht in
der Software mit der Zoomfunktion des Systems vergrößert werden.

. Screenshots erstellen (ggf. vorher Zoomfunktion nutzen)
. Screenshots an den PC übertragen.
. Screenshots am PC öffnen und mit dem Contrast-Analyzer untersuchen.

==== 2.1 Prüfung von Bedienelementen in der Ausgangsansicht

Grafische Bedienelemente (etwa Icons) in der Ansicht identifizieren, die
keinen nebenstehenden Text haben, der dessen Bedeutung und ggf. auch
wechselnde Zustände nach Interaktion identifiziert.

Sind die Kontraste zu angrenzenden Farben klar ausreichend (3:1 oder besser)?

Bedienelemente mit Rahmen (etwa Schaltflächen oder Texteingabefelder)
identifizieren.
Wenn das Bedienelement nur über den Rahmen (oder einen Teil des Rahmens)
identifizierbar ist (der Rahmen also keinen Text oder Symbol umschließt), muss
der Rahmen einen Kontrast von mindestens 3:1 haben.

==== 2.2 Prüfung von Bedienelement-Zuständen nach Fokussierung

Bedienelemente mit einer angeschlossenen Tastatur und falls möglich der Maus
fokussieren.
Ist der Kontrast der Fokushervorhebung zu angrenzenden Farben klar ausreichend
(3:1 oder besser)?

Bei Bedienelementen, die verschiedene funktionale Zustände haben (etwa
Checkboxen, Radio-Buttons, Reiter in Registerbereichen) die verfügbaren
anderen Zustände aufrufen.
Ist der Kontrast der informationstragenden Teile der Bedienelemente zu
angrenzenden Farben klar ausreichend (3:1 oder besser)?

*Hinweis:* Ausgenommen von der Anforderung sind native, also vom Autor nicht
gestylte, Bedienelemente.

==== 2.3 Prüfung von Informationsgrafiken

Informationstragende Grafiken identifizieren, bei denen die Information nur
über die Grafik und nicht (oder nicht ausreichend) über beigefügten Text
vermittelt wird.

Wenn es in Bereichen der Grafik Farbverläufe gibt, Anteile mit einem Kontrast
von weniger als 3:1 ignorieren und bewerten, ob die Information immer noch
ausreichend vom kontrastreicheren Teil der Grafik vermittelt wird.

=== 3. Hinweise

==== 3.1 Zur Identifizierung notwendige Teile von Bedienelementen

Bei den zur Identifizierung notwendigen Teile von Bedienelementen handelt es
sich um visuell sichtbare Elemente (z.B. Element-Rahmen, aktivierter Zustand
eines Elements, informationstragender Teil eines Icons) die wichtige
Informationen enthalten, also etwa den Umriss, den Wert, oder den Zustand
eines Bedienelements anzeigen.
Beispiele:

* Die Fokushervorhebung eines Bedienelements
* Der Aktivierungszustand einer Registerkarte
* Die Ränder eines Eingabefelds oder eines Buttons
* Der Haken einer Custom-Checkbox

Visuelle Beispiele dazu finden sich im Dokument
https://www.w3.org/WAI/WCAG21/Understanding/non-text-contrast.html[
Understanding Success Criterion 1.4.11: Non-text Contrast].

==== 3.2 Vernachlässigbare Rahmen und Umrisslinien

Wenn die Farbe eines Elements (etwa die innere Hintergrundfarbe eines
Schalters oder das Segment eines Kuchendiagramms) ausreichend Kontrast zum
Hintergrund hat, auf dem sich das Element befindet, können Rahmen bzw.
Umrisslinien bei der Kontrastprüfung vernachlässigt werden.

==== 3.3 Kontrast-Differenz bei Zuständen

Nicht verlangt wird ein Kontrast von 3:1 für die Differenz zwischen verschiedenen *funktionalen Zuständen* des gleichen Bedienelements (etwa
Umschalter aktiviert/ nicht aktiviert) wenn es auch andere unterscheidende Merkmale gibt (ein Haken wird gesetzt, Ein Schalter verschiebt sich von links nach rechts, o.ä.)

Ebenfalls nicht verlangt wird hier ein Kontrast von 3:1 für die Differenz zwischen verschiedenen *Interaktions-Zuständen* des gleichen Bedienelements
(etwa fokussiert / nicht fokussiert). Wenn jedoch der Interaktions-Zustand lediglich über einen Farbwechsel angezeigt wird (also nicht auch anders, etwa durch eine Änderung der Form, Wechsel von beigestelltem Text, Umrandung oder ähnlich) dann sollte der Kontrastabstand der Zustände mindestens 3:1 betragen.
Dies ist Gegenstand der Prüfung in Prüfschritt
ifdef::env_embedded[]
11.2.4.7 "Aktuelle Position des Fokus sichtbar".
endif::env_embedded[]
ifndef::env_embedded[]
<<11.2.4.7 Aktuelle Position des Fokus deutlich.adoc#,11.2.4.7 Aktuelle Position
des Fokus deutlich>>.
endif::env_embedded[]

Verlangt wird der Kontrast dagegen für jeden einzelnen Zustand zur jeweils angrenzenden Farbe.

==== 3.4 Dark Mode Ansichten
Die Prüfung erfolgt in der Standardeinstellung des Betriebssystems. Wenn auf Wunsch des Auftraggebers ein Dark Mode mitgetestet werden soll, ist das natürlich möglich, die Ergebnisse können zusätzlich vermerkt werden. Ausschlaggebend für die Konformität ist aber die Standardansicht.
Eine Dark Mode Ansicht wird bei der Feststellung der Konformität nur berücksichtigt, wenn sie explizit als Kontrastversion in der App selbst auswählbar ist, das Bedienelement selbst alle Barrierefreiheitsanforderungen erfüllt, und die Dark Mode Ansicht nicht selbst Kontrastmängel aufweist.

==== 3.5 Berücksichtigung betriebssystemseitiger Einstellungen
Die Ansichten werde ohne die Aktivierung von betriebssystemseitigen Einstellungen wie "Kontrast erhöhen" (iOS) oder "Text mit hohem Kontrast" (Android), also mit Standard-Einstellungen getestet. Die zusätzlichen Einstellungen sind hilfreich, viele Nutzende wissen jedoch nicht, dass es sie gibt. Auch native Schalter wie iOS Switches lassen sich in der Farbe anpassen, damit sie ausreichend kontrastreich sind.


==  Einordnung des Prüfschritts
 
=== Abgrenzung von anderen Prüfschritten

In diesem Prüfschritt geht es um die Kontraste von Grafiken und grafischen
Attributen wie Umrisslinien.
Der Kontrast von Schrift, einschließlich der von Schriftgrafiken, wird in
Prüfschritt
ifdef::env_embedded[]
  11.1.4.3 "Kontraste von Texten ausreichend"
endif::env_embedded[]
ifndef::env_embedded[]
  <<11.1.4.3 Kontraste von Texten ausreichend.adoc#,11.1.4.3 Kontraste von Texten
  ausreichend>>
endif::env_embedded[]
bewertet.

=== Einordnung des Prüfschritts nach WCAG 2.1

==== Guideline

* https://www.w3.org/TR/WCAG21/#distinguishable[Guideline 1.4 Distinguishable:
  Make it easier for users to see and hear content including separating
  foreground from background]

==== Success criterion

* https://www.w3.org/TR/WCAG21/#non-text-contrast[1.4.11 Non-Text Contrast
  (Level AA)]

==== Sufficient Techniques

* https://www.w3.org/WAI/WCAG21/Techniques/general/G174[G174: Providing a
  control with a sufficient contrast ratio that allows users to switch to a
  presentation that uses sufficient contrast]
* https://www.w3.org/WAI/WCAG21/Techniques/general/G195.html[G195: Using an
  author-supplied, highly visible focus indicator]
* https://www.w3.org/WAI/WCAG21/Techniques/general/G207.html[G207: Ensuring
  that a contrast ratio of 3:1 is provided for icons]
* https://www.w3.org/WAI/WCAG21/Techniques/general/G209.html[G209: Provide
  sufficient contrast at the boundaries between adjoining colors]

==== Failures

* https://www.w3.org/WAI/WCAG21/Techniques/failures/F78[F78: Failure of
  Success Criterion 2.4.7 due to styling element outlines and borders in a way
  that removes or renders non-visible the visual focus indicator]

== Quellen

* https://www.w3.org/WAI/WCAG21/Understanding/non-text-contrast.html[
  Understanding Success Criterion 1.4.11: Non-text Contrast]
(zur Zeit nur auf Englisch verfügbar)
