= Prüfschritt 11.1.4.10 Inhalte brechen um
include::include/author.adoc[]
include::include/attributes.adoc[]

*Hinweis: Dies ist ein Entwurf. Inhalte können sich jederzeit ändern.*

== Was wird geprüft?

Inhalte der App sollen bei einer Viewport-Breite von 320 CSS Pixeln so angezeigt werden, dass alle Informationen und Funktionen verfügbar sind, ohne dass Nutzer horizontal scrollen müssen. Die Inhalte mobiler Aps sind meist standardmäßig für die Ansicht im Hochkant-Format optimiert, auch wenn die heute verbreiteten Mobilgeräte meist eine größere Viewportbreite als 320 CSS-Pixel haben. Damit ist dieser Prüfschritt in der Regel erfüllt. 

Native Apps, auch die gängigen Browser, verfügen in der Regel nicht über die Möglichkeit, innerhalb der App die Textgröße zu ändern, wie dies über die Zoom-Funktion in Desktop-Browsern geschieht. Dort führt das Hineinzoomen bei responsiven Sites zum Umburch in eine andere Darstellung. Manche Apps zeigen einen anderen Umbruch der Inhalte, wenn das Gerät ins Querformat gedreht wird oder wenn die App auf einem Tablet mit größerer Viewportbreite angezeigt wird. Aus dem normativen Text ist jedoch keine Verpflichtung abzuleiten, dass für größere Viewportbreiten eine an diese angepasste Ansicht geboten werden muss.

Ausnahmen von die Anforderung, dass Informationen und Funktionen innerhalb der Viewportbreite vpn 320px verfügbar sind, gibt es für Inhalte, für deren Nutzung ein zweidimensionales Layout erforderlich ist und die ggf. auf Viewportbreite verkleinert nicht sinnvoll nutzbar sind, z.B.:

* Bilder
* Landkarten
* Diagramme
* Videos
* Spiele
* Präsentationen
* Datentabellen 
* Anwendungs-Schnittstellen, in denen die Bearbeitung von Inhalten die permanente Verfügbarkeit von
Werkzeugleisten erfordert.

== Warum wird das geprüft?

Im Kontext von Desktop-Browsern hilft die Anforderung sehbehinderten Nutzern, die eine vergrößerte Darstellung brauchen und deshalb über den Desktop-Browser-Zoom die Inhalte vergrößern. Dadurch kommt es häufig zu einem Umbruch in eine einspaltige Ansicht bei der normativ festgelegten CSS Viewport-Breite von 320 Pixeln (beim Vergrößern veringert sich schrittweise die ausgegebene Breite in CSS-Pixeln). In der Desktop-Zoom-Ansicht sind Texte meist deutlich größer und für sehbehinderte Nutzende zum Teil nun erst lesbar. Im Kontext mobiler Apps mit meist ohnehin viel kleinerem Display kommen eher systemseitige Methoden der Textvergrößerung zum Tragen, so die Einstellung größerer Schrift, die sich auf die Darstellung auswirkt, wenn Entwickler in der App dynamische Fonts verwenden, und die Bedienungshilfe Vergrößerung (Android) bzw. Zoom (iOS), die nicht zu einem Umbruch führt. 

Werden Apps auf Tablets mit größeren Viewport-Breiten angezeigt, wäre die Zoomvergrößerung hier ebenso hilfreich wie auf dem Desktop, wird aber von nativen Apps (einschließlich mobilen Browsern) zurzeit kaum angeboten.

== Wie wird geprüft?

=== 1. Anwendbarkeit des Prüfschritts

Laut EN 301 549 Version 3.1.1 ist dieser Prüfschritt auf Software und damit für mobile Apps anwendbar. In der Regel ist er schon dadurch erfüllt, dass alle Inhalte auf die Ausgabe innerhalb des Hochkant-Viewports optimiert sind, auch wenn sie nicht "umbrechen". 

Die Prüfung ist somit beschränkt auf Apps, die ein Layout für breitere Viewports, z.B. Tablets anbieten *und* außerdem eine Zoomfunktion implementieren.

=== 2. Prüfung

. Vorbedingung 1: Hat die App eine Zoomfunktion?
. Vorbedingung 2: Stellt sie Inhalte auf Geräten mit breiteren Viewports (oder nach Drehen des Smartphones ins Querformat) in einem anderen Layout dar als auf dem Smartphones im Hochkant-Format?
. Falls beide Vorbedingungen zutreffen: die Inhalte soweit vergrößern, bis näherungsweise eine Viewport-Breite von 320 px erreicht ist.
. Gibt es in der App Informationen oder Funktionen, die nun nicht mehr verfügbar sind oder abgeschnitten werden und die nicht unter die Ausnahmen fallen?

Für Hinweise zur Prüfpraxis können Sie auf GitHub
https://github.com/BIK-BITV/BIK-App-Test/issues[ein Issue] zur diesem
Prüfschritt erstellen.

=== 3. Hinweise

==== 3.1 Praktische Aspekte der Prüfung: Geräte
Oft wird für die Prüfung kein Gerät mit exakt 320 CSS Pixeln Viewportbreite und aktuellem Betriebssystem zur Verfügung stehen. Deshalb ist es unvermeidlich, auf einem gängigen Gerät mit etwas größerer Viewportbreite zu testen (etwa ein iPhone 13 min oder ein Samsung Galaxy A12, beide mit 360 CSS Pixeln Viewport-Breite).

==== 3.2 Vergrößerung aud Viewportbreite von 320 px
Abhängig vcom genutzten Testgerät kann die Breite von 320 px kann ggf. nur näherungsweise erreicht werden. Bei einer Vergrößerungsstufe von 200% wäre die Viewportbreite in CSS-Pixeln halbiert. Je nach Gerät müsste als verschieden stark vergrößert werden, um 320 CSS-Pixel zu erreichen. Bei einem iPad Air (2020) mit 1112 CSS-Pixeln Breite wäre z.B. eine Vergrößerung um 347,5% notwendig um exakt 320 CSS-Pixel Viewportbreite zu erreichen. ISt dieViewportbreite des Displays nitcht bekannt lässt diese sich in der Regel aus der physischen Auflösung des Displays und dem genutzten Pixel-Verhältnis  (pixel ratio) berechnen. Die meisten aktuellen Geräte haben heute eine pixel ratio zwischen 3 und 4. So hat etwa sin Samsung note 8 eine physische Auflösung von 1440 x 2960 Geräte-Pixeln, was bei einem Faktor 4 zu einer Auslösung von 360 x 740 CSS-Pixeln führt. Hier müsste also auf 230% vergrößert werden um näherungsweeise die Viewport-Breite von 320 CSS-Pixeln einzustellen.

==== 3.3 Lese- und Schreibrichtung
Dieser Prüfschritt beschränkt sich auf Inhalte, deren primäre Schreibrichtung waagerecht ist, wie bei der für die meisten westlichen
Sprachen benutzten lateinischen Schrift. Die zugrunde liegende WCAG-Anforderung gilt in ähnlicher Weise für Inhalte mit vertikaler Schreibrichtung.

=== 4. Bewertung
==== Nicht erfüllt

* Es gibt Inhalte, die nicht unter die Ausnahmen fallen und nicht in den Viewport von 320px (ersatzweise 360 Pixel) passen.
* Es gibt Inhalte, die unter die Ausnahmen fallen und nicht in den Viewport von 320px (ersatzweise 360 Pixel) passen, und deren abgeschnittene Inhalte sich nicht in den Viewport bewegen lassen.

== Quellen

https://www.w3.org/WAI/WCAG21/Understanding/reflow.html[Understanding Reflow]
(zur Zeit nur auf Englisch verfügbar)
