= Prüfschritt 11.1.3.1b Datentabellen richtig aufgebaut
include::include/author.adoc[]
include::include/attributes.adoc[]

== Was wird geprüft?

Datentabellen sind strukturell richtig aufgebaut, Zeilen- und Spaltenüberschriften sind plattformspezifisch im Programm-Code ausgezeichnet.

== Warum wird das geprüft?

Visuell orientierte Personen nutzen für die Orientierung in einer Datentabelle neben den Überschriften wenn nötig auch den Wertebereich. Es ist für sie daher relativ leicht möglich, strukturelle Mängel, zum Beispiel Wechsel in der Bedeutung von Zeilen oder Spalten, zu erkennen und mit ihnen umzugehen.

Sehbehinderte und blinde Nutzende erschließen sich das Angebot von Datentabellen dagegen eher analytisch. Sie entwickeln ausgehend von den Überschriften und anderen im Kontext verfügbaren Informationen eine Vorstellung vom Aufbau der Tabelle. Bei der Navigation durch den Datenbereich wird beim Wechsel in eine angrenzende Zelle vom Screenreader z.B. die jeweilige Spaltenüberschrift ausgegeben.

Damit das möglich ist und funktioniert, müssen zwei Bedingungen erfüllt sein:

* Die Tabelle muss eine klare Struktur haben, die Bedeutung der Zeilen und Spalten muss fassbar sein und sie muss möglichst gut den Spalten- und Zeilen-Überschriften zu entnehmen sein.
* Die Überschriften müssen auffindbar sein und es muss klar sein, auf welche Daten sie sich beziehen, sie müssen also korrekt ausgezeichnet sein.

Die klare Struktur ist die Grundlage der Barrierefreiheit von Datentabellen. Es ist nicht möglich, eine mangelhaft strukturierte Datentabelle durch spezielle Auszeichnung barrierefrei zugänglich zu machen. Auf Grundlage einer klaren, nachvollziehbaren Struktur ist die korrekte Auszeichnung aber nützlich und wichtig.

Mögliche Anwendungen der Auszeichnung von Tabellenüberschriften:

* Der Screenreader informiert über die Position und Anzahl der Überschriftenreihen.
* Der Screenreader liest die (neue) Zeilen- oder Spaltenüberschrift vor, wenn der Benutzer die Tabellenzeile oder die Tabellenspalte wechselt.
* Überschriften werden in einer für den Benutzer besser geeigneten Form hervorgehoben.

== Wie wird geprüft?

=== 1. Anwendbarkeit des Prüfschritts

Der Prüfschritt ist immer anwendbar, wenn Tabellen in der App-Ansicht vorhanden sind.

=== 2 Prüfung

==== 2.1 Werden Tabellen für tabellarische Daten verwendet?

. App mit zu prüfender Ansicht öffnen.
. Prüfen, ob die App-Ansicht eine Datentabelle enthält (d.h. Daten stehen in einer logischen Beziehung zueinander und sind rasterartig organisiert).
. Screenreader starten und prüfen, ob der Screenreader beim Antippen der Tabelle "Tabelle" o.ä. ausgibt.

==== 2.2 Prüfung des Aufbaus von Tabellen

Prüfen, ob die Tabelle strukturell sinnvoll aufgebaut ist. Schwierigkeiten entstehen in den meisten Fällen dadurch, dass die Tabelle auch Layoutzwecken dient, das Tabellengitter also für die Anordnung von Inhalten auf dem Bildschirm genutzt wird. Problematisch können zum Beispiel sein:

* Eine Spalte mit Daten ist vor der Überschriftenspalte platziert
* Wechsel der Bedeutung von Zeilen oder Spalten ("ab hier ...")
* Zellen mit Erläuterungen sind in die Tabelle integriert
* Leere Zeilen werden eingefügt, um die Höhe oder den Abstand von Zeilen festzulegen
* Verschachtelungen (weitere Tabelle innerhalb einer Tabellenzelle)

===== Woran erkennt man, dass eine Datentabelle sinnvoll aufgebaut ist?

Bei einer sinnvoll aufgebauten Tabelle kann man sagen, welche Informationen in den einzelnen Spalten und Zeilen der Tabelle enthalten sind. Man kann diesen Inhalt allgemein fassen, nicht nur als eine Zusammenstellung der in den einzelnen Zellen abgelegten Werte.

Die Bedeutung der einzelnen Spalten und Zeilen kann in den Überschriften gefasst sein. Das ist aber nicht zwangsläufig so, auch eine Tabelle ohne Überschriften kann sinnvoll strukturiert sein.

Wenn aussagekräftige Spalten- oder Zeilen-Überschriften vorhanden sind, sollte man auch prüfen, ob das, was in den zugeordneten Zellen steht, den Überschriften entspricht.

Auch komplexe Tabellen sind aus einfachen Spalten und Zeilen zusammengesetzt, die Anforderungen sind so weit die selben. Hinzu kommt allerdings, dass benachbarte Zeilen oder Spalten durch übergreifende Überschriften zusammengefasst sind. Auch den Inhalt dieser zusammengefassten Bereiche muss man allgemein fassen können, wie den Inhalt der einzelnen Spalten und Zeilen.

===== Wie kann man (ohne Screenreader) prüfen, ob eine Datentabelle richtig aufgebaut ist?

Man nimmt eine beliebige Zelle und liest sie zusammen mit den zugehörigen Spalten- und Zeilenüberschriften:

* "[Überschrift(en) der Spalte] - [Überschrift(en) der Zeile]: [Inhalt der
  Zelle]"

Ist die Bedeutung der Zelle so verständlich?

Gezielt untersucht werden sollen Auffälligkeiten:

* Ist irgendwo andersartiger Inhalt vorhanden?
* Sind Zellen hervorgehoben?

Man prüft, ob auch in diesen Bereichen alle Zellen in gleicher Weise, unabhängig von ihren Nachbarzellen, nur zusammen mit den beiden
Überschriften benutzbar sind. Ist das der Fall? Dann ist die Tabelle richtig aufgebaut und per Screenreader benutzbar.

==== 2.3 Prüfung der Auszeichnung von Tabellen

. App mit zu prüfender Ansicht öffnen.
. Prüfen, ob die App-Ansicht Datentabelle enthält.
. Screenreader starten und mit Hilfe der Wischgeste durch die Tabelle navigieren.
. Prüfen, ob alle Spalten- und Zeilenüberschriften zusammen mit der Datenzelle ausgegeben werden. Alternativ die Zeilen- bzw. Spaltenüberschrift angetippen und prüfen, was der Screenreader ausgibt: Wenn der Screenreader "Zeilenüberschrift", "Spaltenüberschrift" oder ähnlich als Zusatz spricht, sind die entsprechenden Überschriften korrekt ausgezeichnet.

Die Mindestanforderung:
Offenkundige, unverzichtbare und visuell hervorgehobene Überschriften müssen ausgezeichnet sein (siehe Hinweis Woran erkennt man Zeilenüberschriften?).

=== 3. Hinweise

==== 3.1 Woran erkennt man Zeilenüberschriften?

Die visuelle Hervorhebung ist ein Erkennungsmerkmal für Überschriften. Wenn die erste Spalte einer Datentabelle visuell hervorgehoben ist, dann kann man davon ausgehen, dass die Inhalte dieser Spalte als Zeilen-Überschriften dienen sollen.

Dieser Zusammenhang lässt sich aber nicht umkehren, die visuelle Hervorhebung ist als Kriterium nicht immer ausreichend. Denn auf die Hervorhebung der Zeilenüberschriften wird manchmal aus Gestaltungsgründen verzichtet. Sehende Nutzende brauchen sie nicht unbedingt. Wenn der Inhalt einer Datenzelle nicht für sich aussagekräftig ist, beziehen sie die Zellen am linken Rand der Tabelle ein, die Position reicht ihnen als Hervorhebung.

Es ist manchmal schwierig, den Fall, dass auf die visuelle Hervorhebung aus gestalterischen Gründen verzichtet worden ist, abzugrenzen von dem Fall, dass die Inhalte der ersten Spalte tatsächlich als Überschriften nicht geeignet sind. Selbst wenn in der ersten Spalte zum Beispiel Namen von Herstellern oder Produkten stehen, ist das noch kein sicherer Anhaltspunkt für die Eignung als Überschrift. Denn Überschriften sollten eindeutig und geläufig sein, Herstellernamen sind nicht immer eindeutig, Produktnamen oft nicht geläufig.

Entwickler oder Redakteure sollten also überlegen, ob die Inhalte der ersten Spalte als Überschriften tauglich sind, ob es Sinn macht, dass ein Screenreader bei Zeilenwechseln immer den jeweiligen Inhalt der ersten Spalte zusammen mit der gerade angesteuerten Datenzelle vorliest. Wenn das der Fall ist, sollten die Zellen der ersten Spalte unbedingt als Überschriften ausgezeichnet werden. In der Regel stehen die Zeilenüberschriften der Tabelle, wenn vorhanden, in der ersten Spalte. Unter Umständen können aber auch Einträge in anderen Spalten als passende Zeilen-Überschrift ausgezeichnet sein.

Für die Prüfung gilt:

* Zellen, die keine Daten enthalten, also nur als Überschriften dienen können, müssen entsprechend ausgezeichnet werden. (Beispiel dafür: in der Randspalte steht "Länge", Breite", "Gewicht" und so weiter)
* Muss beim Zugriff auf Daten auf den Inhalt der Zeile oder Spalte Bezug genommen werden, ist es ohne Berücksichtigung der Randspalte nicht möglich,
  wenigstens einen Teil der unterschiedlichen Werte einer anderen Spalte zu interpretieren? Dann enthält die Randspalte Überschriften, sie muss entsprechend
  ausgezeichnet werden. (Beispiel: im Wertebereich der Tabelle finden sich ausschließlich Preisangaben.)
* Die Randspalte kann abweichend von der visuellen Darstellung als Überschrift ausgezeichnet werden, wenn es Sinn macht, beim Vergleich von Werten anderer
  Spalten auf sie Bezug zu nehmen. (Beispiel: Tabelle mit Produkten, Anbieter und Modellbezeichnung sind als Überschriften ähnlich brauchbar.)
* Ansonsten ist das Kriterium für die Auszeichnung aber nur die visuelle Hervorhebung. Zeilenüberschriften müssen ausgezeichnet sein, wenn sie visuell hervorgehoben sind.
  Auch wenn die Randspalte möglicherweise aus einem anderen Grund hervorgehoben ist und für die vergleichende Fassung mit den Daten in anderen Spalten eher nicht nützlich ist, soll die Auszeichnung nicht von der Darstellung auf dem Bildschirm abweichen. Gegebenenfalls muss in diesem Fall die Darstellung für den Bildschirm angepasst werden. (Beispiel dafür: in der ersten Spalte einer Tabelle mit Produkten wird die Bestellnummer angezeigt.)

Auch bei Spaltenüberschriften kann auf die visuelle Hervorhebung verzichtet werden. Die vorstehenden Regeln sind dann in der gleichen Weise auf sie anzuwenden.

==== 3.2 Tabellen mit eingesparten Überschriften

Überschriften sind überflüssig, wenn in den Zellen neben den Einzelwerten auch deren Bedeutung angegeben ist oder wenn die Bedeutung der Einzelwerte sich von selbst versteht. Ein typisches Beispiel dafür sind Preislisten: in der linken Spalte stehen die meist selbsterklärenden Produktbezeichnungen, in der rechten Spalte steht nicht nur der Betrag, sondern auch das Währungszeichen.

Für blinde und sehbehinderte Nutzende kann der Umgang mit solchen Tabellen schwierig sein. Denn mangels Überschriften müssen sie auf den Wertebereich zugreifen, um zu
verstehen, was die Tabelle anbietet. Für normal sehende Nutzende ist das leicht, für Benutzer, die sich immer nur einen kleinen Ausschnitt der Tabelle vorlesen oder anzeigen lassen können, aber nicht.

Unproblematisch ist der Verzicht auf Überschriften, wenn zwei Bedingungen erfüllt sind:

* Der Aufbau der Tabelle ist der ersten Zeile zu entnehmen.
* Die Tabelle listet Daten auf, die zusammen gehören und eine feste Reihenfolge haben. Sie wird also normalerweise linear genutzt, wie ein Buch.

Tabellen mit eingesparten Überschriften erfüllen also den Prüfschritt, wenn sie richtig aufgebaut und linear nutzbar sind.

Bei Software ist es in der Regel nicht ohne den Quelltext möglich, die korrekte syntaktische Auszeichnung festzustellen. Hier kann dann in der Regel nur ein Test mit einem Screenreader durchgeführt werden. Dieser sagt dann an, ob es sich um eine "richtige" Tabelle handelt und kann beim Navigieren über Zeilen und Spalten ggf. auch dessen Überschriften ausgeben.


==== 3.3 Informationen für Entwickler

. Bei der iOS App-Entwicklung kann das Protokoll `"link:https://developer.apple.com/documentation/uikit/uiaccessibilitycontainerdatatable[
UIAccessibilityContainerDataTable]"` zur Auszeichnung von barrierefreien Datentabellen gennutzt werden.
. Bei der Android App-Entwicklung gibt es Informationen zur Umsetzung von Datentabellen unter `"link:https://material.io/components/data-tables[https://material.io/components/data-tables]"`

=== 4. Bewertung

==== Nicht voll erfüllt:

* Für tabellarische Daten wird keine Tabellensemantik verwendet.

== Einordnung des Prüfschritts

=== Einordnung des Prüfschritts nach WCAG 2.1

==== Guideline

* https://www.w3.org/TR/WCAG21/#adaptable[Guideline 1.3 Adaptable: Create
  content that can be presented in different ways (for example simpler layout)
  without losing information or structure]

==== Success criterion

* https://www.w3.org/TR/WCAG21/#info-and-relationships[1.3.1 Info and
  Relationships (Level A)]

==== Techniques

.General Techniques
* https://www.w3.org/WAI/WCAG21/Techniques/general/G115.html[G115: Using
  semantic elements to mark up structure]
* https://www.w3.org/WAI/WCAG21/Techniques/general/G140.html[G140: Separating
  information and structure from presentation to enable different presentations]

==== Failures

* https://www.w3.org/WAI/WCAG21/Techniques/failures/F33.html[F33: Failure of
  Success Criterion 1.3.1 and 1.3.2 due to using white space characters to create
  multiple columns in plain text content]
* https://www.w3.org/WAI/WCAG21/Techniques/failures/F34.html[F34: Failure of
  Success Criterion 1.3.1 and 1.3.2 due to using white space characters to
  format tables in plain text content]
* https://www.w3.org/WAI/WCAG21/Techniques/failures/F48.html[F48: Failure of
  Success Criterion 1.3.1 due to using the pre element to markup tabular
  information]
* https://www.w3.org/WAI/WCAG21/Techniques/failures/F91.html[F91: Failure of
  Success Criterion 1.3.1 for not correctly marking up table headers]
* https://www.w3.org/WAI/WCAG21/Techniques/failures/F92.html[F92: Failure of
  Success Criterion 1.3.1 due to the use of role presentation on content which
  conveys semantic information]

== Quellen

=== W3C - Web Accessibility Tutorials

* https://www.w3.org/WAI/tutorials/tables/[Tables Tutorial]

=== Entwicklerressourcen

* Apple Developer:
  https://developer.apple.com/documentation/uikit/uiaccessibilitycontainerdatatable[
  UIAccessibilityContainerDataTable]
