= Prüfschritt 11.1.3.1d Kein Strukturmarkup für Layouttabellen
include::include/author.adoc[]
include::include/attributes.adoc[]

== Was wird geprüft?

Tabellenstruktur-Auszeichnungen wie z. B. Überschriftszellen dürfen nicht für Layouttabellen verwendet werden.

== Wie wird geprüft?

=== Anwendbarkeit des Prüfschritts

Der Prüfschritt ist anwendbar, wenn die Software Tabellen für das Layout
verwendet.

=== Prüfung

Bei Software kann in der Regel nur ein Blackbox-Test mittels Screenreader
durchgeführt werden.
Da wo eine inkorrekt eingesetzte Tabelle vermutet wird, kann mit dem SR
navigiert werden.
Der Screenreader sagt dann an, ob es sich um eine „richtige“ semantische
Tabelle handelt (ein Zusatz wie „Tabelle“ wird ausgegeben).

. Screenreader starten (siehe Handreichung)
. Zu testende App starten
. Den Bereich navigieren bzw. antippen, der für eine semantische Tabelle
  gehalten wird.
. Prüfen ob der Screenreader den Zusatz „Tabelle“ ausgibt. In diesem Fall darf z. B. bei einer Überschriftenzelle nicht der Zusatz "Überschrift" oder ähnlich ausgegeben werden.

=== Bewertung

*Nicht erfüllt:*

* Bei Layouttabellen gibt der Screenreader unnötige weitere Tabellenstrukturen aus, wie z. B. eine Überschriftenzelle.

== Einordnung des Prüfschritts

=== Einordnung des Prüfschritts nach WCAG 2.1

==== Guideline

* https://www.w3.org/WAI/WCAG21/quickref/?showtechniques=131#adaptable[Guideline
  1.3 Adaptable: Create content that can be presented in different ways (for
  example simpler layout) without losing information or structure]

==== Success criterion

* https://www.w3.org/WAI/WCAG21/quickref/?showtechniques=131#info-and-relationships[
1.3.1 Info and Relationships (Level A)]

==== Techniques

.General Techniques
* https://www.w3.org/WAI/WCAG21/Techniques/general/G115.html[G115: Using
  semantic elements to mark up structure]
* https://www.w3.org/WAI/WCAG21/Techniques/general/G140.html[G140: Separating
  information and structure from presentation to enable different presentations]
