= Prüfschritt 11.1.4.5 Verzicht auf Schriftgrafiken
include::include/author.adoc[]
include::include/attributes.adoc[]

== Was wird geprüft?

Grafiken sollen nicht für die Darstellung von Schriften verwendet werden.

== Warum wird das geprüft?

Schriftgrafiken können nicht oder nur eingeschränkt an Benutzeranforderungen angepasst werden. Ihre Farben können nicht individuell eingestellt werden, auch die
individuelle Anpassung der Schriftgröße wirkt nicht auf grafische Schriften.

== Wie wird geprüft?

=== 1. Anwendbarkeit des Prüfschritts

Der Prüfschritt ist immer anwendbar, wenn die App Schriftgrafiken enthält.

=== 2. Prüfung

. App mit zu prüfender Ansicht öffnen.
. Prüfen, ob es Elemente gibt, die wie eine Schriftgrafik aussehen. 
. Screenreader starten und mit Hilfe der Wischgeste zu Elementen navigieren, die wie vermeintliche Schriftgrafiken aussehen.
. Falls es sich um eine Schriftgrafik (also um keinen „echten“ Text) handelt, gibt der Screenreader „Bild“ oder „Grafik“ aus.

=== 3. Hinweise

In der Regel nicht negativ bewertet werden grafische Schriften auf Logos oder in Fotos.

=== 4. Bewertung

==== Nicht voll erfüllt:

* Für Schaltflächen, deren Bedeutung aus dem Kontext hervorgeht (einzelne Schaltfläche unter Eingabefeldern), werden Schriftgrafiken verwendet.

==== Nicht erfüllt:

* Für wichtige Texte, zum Beispiel Überschriften, Menüoptionen oder für Schaltflächen, deren Beschriftung gelesen werden muss, werden Schriftgrafiken
  verwendet.

== Einordnung des Prüfschritts

=== Abgrenzung zu anderen Prüfkriterien

Erfolgskriterium 1.3.1 der WCAG fordert generell die Verwendung von Markup anstelle von
Bildern, um Informationen darzustellen.
Als Beispiel wird MathML genannt.
Wesentlich wichtiger ist allerdings die (ebenfalls angesprochene) Vermeidung
der Nutzung von Bildern für Texte.
In diesem Prüfschritt wird nur die Verwendung von Grafiken für
Überschriften, "normalen" Fließtext und die Beschriftung von Bedienelementen
berücksichtigt.

=== Einordnung des Prüfschritts nach WCAG 2.1

==== Guideline

* https://www.w3.org/TR/WCAG21/#distinguishable[Guideline 1.4 Distinguishable:
  Make it easier for users to see and hear content including separating
  foreground from background]

==== Success criterion

* https://www.w3.org/TR/WCAG21/#images-of-text[1.4.5 Images of Text (Level AA)]

==== Techniques

.General Techniques
* https://www.w3.org/WAI/WCAG21/Techniques/general/G140.html[G140: Separating
  information and structure from presentation to enable different presentations]

== Quellen

https://www.paciellogroup.com/blog/2015/12/does-svg-text-pass-wcag-1-4-5-images-of-text/[
Does SVG text pass WCAG 1.4.5 (Images of Text)?] (Léonie Watson)

== Fragen zu diesem Prüfschritt

=== Schriftzeichen

Wie ist es mit der Darstellung von Schriftzeichen, die nicht auf allen Geräten zur Verfügung stehen?
Also zum Beispiel arabische Schriftzeichen: sollten dafür nicht besser Grafiken verwendet werden?

Moderne Betriebssysteme stellen die Schriftzeichen aller verbreiteten Sprachen zur Verfügung. In aller Regel sind Schriftzeichen, mit denen ein möglicher Nutzer etwas
anfangen könnte, auch installiert. Die grafische Darstellung von Schriftzeichen ist daher nur als zusätzliches Angebot sinnvoll.

Im BITV-Test wird nur geprüft, ob Text in Form von Text verfügbar ist. Zusätzliche grafische Angebote werden nicht berücksichtigt.

=== Was ist mit auf Fotos abgebildeten Schriften?

Schriftgrafiken sollen nicht verwendet werden, weil die Darstellung des Textes dann nicht mehr flexibel ist. Bei abgebildeten Schriften, also zum Beispiel bei Fotos mit Ladenschildern sind Inhalt und Darstellung zusammengehörig. Dieser Prüfschritt ist also nicht anwendbar.

Davon ausgenommen sind allerdings Abbildungen, die wie Schriftgrafiken verwendet werden, also zum Beispiel als Überschriften dienen.

=== Wie wird Text in Firmenlogos bewertet?

In diesem Prüfschritt geht es um die Verwendung von grafischen Schriften für Texte, Überschriften und Bedienelemente.
Das Firmenlogo ist nicht relevant, so lange es nicht (oder nur zusätzlich) als Überschrift oder Bedienelement eingesetzt wird.
