= Prüfschritt 11.1.4.1 Ohne Farben nutzbar
include::include/author.adoc[]
include::include/attributes.adoc[]

*Hinweis: Dies ist ein Entwurf. Inhalte können sich jederzeit ändern.*

== Was wird geprüft?

Über Farben vermittelte Informationen sollen auch ohne Wahrnehmung der Farbe verfügbar sein, also zusätzlich durch andere Mittel (etwa Fettung oder Einrückung) hervorgehoben sein.

== Warum wird das geprüft?

Ausschließlich über Farben vermittelte Informationen sind für blinde Nutzende nicht zugänglich.
Auch farbfehlsichtige Nutzende können Farben nicht oder nur eingeschränkt identifizieren und unterscheiden.

== Wie wird geprüft?

=== 1. Anwendbarkeit des Prüfschritts

Der Prüfschritt ist immer anwendbar.

=== 2. Prüfung

Prüfen, ob die App-Ansicht Elemente enthält, die durch Farbgebung Informationen vermittelt.
Beispiele dafür:

* Überschriften werden farblich hervorgehoben
* Ausgewählte Menueinträge werden in einer anderen Farbe dargestellt
* Links im Fließtext werden in einer anderen Farbe dargestellt
* Eine Grafik verwendet unterschiedliche Farben für die vergleichende Darstellung des Kursverlaufs verschiedener Aktien
* Pflichtfelder in Formularen werden farblich gekennzeichnet (die gelb unterlegten Felder müssen immer ausgefüllt werden)

Solche Hervorhebungen sind positiv.
Die Vermittlung wichtiger Informationen soll sich aber nicht *ausschließlich* auf einfache Farbänderungen stützen.
Zu prüfen ist also, ob die Informationen zusätzlich noch auf einem anderen Weg vermittelt werden.

Beispiele für zusätzliche Vermittlung:

* Überschriften sind zusätzlich eingerückt oder durch eine andere Schriftgröße hervorgehoben (das ist fast immer der Fall).
* Ausgewählte Menueinträge sind zusätzlich mit einer Markierung versehen.
* Links im Fließtext sind nicht nur farblich abgesetzt, sondern zusätzlich unterstrichen, gefettet, invertiert oder mit einer Markierung versehen.
  Ausnahme: Das Kontrastverhältnis zwischen Linkfarbe und umgebender Textfarbe ist 3:1 oder besser.
  In diesem Fall kann im Ausgangszustand auf die zusätzliche Hervorhebung verzichtet werden.
  Die Links müssen dann aber bei Fokuserhalt zusätzlich hervorgehoben werden.
* Linien in Schaubildern sind zusätzlich gestrichelt oder durchgezogen.
* Flächen haben unterscheidbare Muster.
* Pflichtfelder im Formular sind zusätzlich mit einem Stern (mit Bedeutungserklärung am Formularbeginn) oder textlich ("Pflichtfeld") gekennzeichnet.

Ebenfalls andere, zusätzliche Vermittlungswege sind am Beispiel der Hervorhebung der aktuell ausgewählten Menüoption erkennbar:

* Die Überschrift ist stets gleichlautend mit der ausgewählten Menüoption.

Ebenfalls nicht als einfache Farbunterschiede gelten:

* die farbige Hinterlegung von Elementen (denn eine Form kommt dazu oder ändert sich)
* der Austausch von Vorder- und Hintergrundfarbe (denn wenn überhaupt ein Unterschied von Vorder- und Hintergrund wahrgenommen wird, ist auch der Austausch wahrnehmbar)

=== 3. Bewertung

==== Erfüllt:

* Information wird nicht nur über die Farbe vermittelt, sondern auch über andere zusätzliche Merkmale, etwa die Form, einen Rahmen, eine Textauszeichnung oder Einrückung, oder beigestellten Text.

==== Nicht erfüllt:

* Information wird ausschließlich über Farbe vermittelt.
  Der Kontrastunterschied der für die Unterscheidung relevanten Farben liegt unter 3:1.

== Einordnung des Prüfschritts

=== Abgrenzung zu anderen Prüfkriterien

==== Abgrenzung zur Prüfung der Kontraste

In diesem Prüfschritt geht es nicht um die Prüfung der Kontraste.
Dies ist Aufgabe der Prüfkriterien
ifdef::env_embedded[11.1.4.3 "Kontraste von Texten ausreichend"]
ifndef::env_embedded[]
  <<11.1.4.3 Kontraste von Texten ausreichend.adoc#,11.1.4.3 Kontraste von Texten ausreichend>>
endif::env_embedded[]
und
ifdef::env_embedded[11.1.4.11 "Kontraste von Grafiken und Bedienelementen ausreichend".]
ifndef::env_embedded[]
  <<11.1.4.11 Kontraste von Grafiken und Bedienelementen ausreichend.adoc#,11.1.4.11 Kontraste von Grafiken und Bedienelementen ausreichend>>.
endif::env_embedded[]

Für Fließtext-Links gilt ein deutlicher Kontrast (mindestens 3,0:1) der Linkfarbe zur Farbe des umgebenden Textes , um diese Anforderung ausreichend zu erfüllen.
Es ist dann keine zusätzliche Hervorhebung nötig.
Für die Erfüllung von 9.1.4.3 Kontraste von Texten ausreichend muss jedoch gewährleistet sein, dass die Linkfarbe zum Hintergrund 4,5:1 erfüllt.

==== Abgrenzung zum Prüfschritt 11.1.3.3 "Ohne Bezug auf sensorische Merkmale nutzbar"

In diesem Prüfschritt geht es nicht um die Prüfung von Verweisen auf Seiteninhalte mit Hilfe der Angabe von Farben.
Die sinnesunabhängige Bereitstellung von Verweisen auf Inhalte wird im
Prüfschritt
ifdef::env_embedded[11.1.3.3 "Ohne Bezug auf sensorische Merkmale nutzbar"]
ifndef::env_embedded[]
  <<11.1.3.3 Ohne Bezug auf sensorische Merkmale nutzbar.adoc#,11.1.3.3 Ohne Bezug auf sensorische Merkmale nutzbar>>
endif::env_embedded[]
geprüft.

==== Abgrenzung zu fehlenden Hervorhebungen

In diesem Prüfschritt 11.1.4.1 geht es um die Farbunabhängigkeit vorhandener UI-Elemente.

Eine negative Bewertung ist also beispielsweise angebracht, wenn Links im Fließtext nur durch die Farbe (und nicht zusätzlich durch Unterstreichung, Fettung oder vorangestellte Markierung) gekennzeichnet sind und der Kontrastunterschied zum umgebenden Text weniger als 3:1 beträgt.
Wenn Links im Text überhaupt nicht gekennzeichnet sind, ist dies ein Problem für alle Nutzenden und keines der mangelnden Barrierefreiheit.
Deshalb wird dies hier nicht negativ bewertet.

Gleiches gilt für die Kennzeichnung der aktuellen Menüposition:
Wird die aktuelle Position überhaupt nicht angezeigt, ist dies kein Fehler in diesem Prüfschritt.

=== Einordnung des Prüfschritts nach WCAG 2.1

==== Guidelines

* https://www.w3.org/TR/WCAG21/#distinguishable[
  Guideline 1.4 Distinguishable: Make it easier for users to see and hear content including separating foreground from background]

==== Success criteria

* https://www.w3.org/TR/WCAG21/#use-of-color[1.4.1 Use of Color (Level A)]

==== Techniques

.General Techniques
* https://www.w3.org/WAI/WCAG21/Techniques/general/G14.html[G14: Ensuring that
  information conveyed by color differences is also available in text]
* https://www.w3.org/WAI/WCAG21/Techniques/general/G111.html[G111: Using color
  and pattern]
* https://www.w3.org/WAI/WCAG21/Techniques/general/G182.html[G182: Ensuring
  that additional visual cues are available when text color differences are
  used to convey information]
* https://www.w3.org/WAI/WCAG21/Techniques/general/G183.html[G183: Using a
  contrast ratio of 3:1 with surrounding text and providing additional visual
  cues on focus for links or controls where color alone is used to identify
  them]
* https://www.w3.org/WAI/WCAG21/Techniques/general/G205.html[G205: Including a
  text cue for colored form control labels]

==== Failures

* https://www.w3.org/WAI/WCAG21/Techniques/failures/F13.html[F13: Failure of
  Success Criterion 1.4.1 due to having a text alternative that does not
  include information that is conveyed by color differences in the image]
* https://www.w3.org/WAI/WCAG21/Techniques/failures/F73.html[F73: Failure of
  Success Criterion 1.4.1 due to creating links that are not visually evident
  without color vision]
* https://www.w3.org/WAI/WCAG21/Techniques/failures/F81.html[F81: Failure of
  Success Criterion 1.4.1 due to identifying required or error fields using
  color differences only]
