= 11.1.1.1c Nicht-Text-Inhalt – CAPTCHAs
include::include/author.adoc[]
include::include/attributes.adoc[]

== Was wird geprüft?

In bildbasierten CAPTCHAs soll die Textalternative des Bildes den Zweck des CAPTCHAs beschreiben und ggf. angeben, wo eine nicht bildbasierte Alternative zu finden ist.

Mindestens eine CAPTCHA-Alternative für ein bildbasiertes CAPTCHA muss vorhanden sein.

== Warum wird das geprüft?

In bildbasierten CAPTCHAs werden z.B. Bilder von Zeichenfolgen eingesetzt, welche Nutzende als Text eingeben müssen, um bestimmte Bereiche der App zu erreichen.
Für blinde und sehbehinderte Nutzende sind solche CAPTCHAs nicht zugänglich. Deswegen müssen Alternativen angeboten werden.

== Wie wird geprüft?

=== 1. Anwendbarkeit des Prüfschritts

Der Prüfschritt ist anwendbar, wenn bildbasierte CAPTCHAs vorhanden sind.

Die Leserlichkeit der Zeichenfolge in einem bildbasierten CAPTCHA ist nicht Teil der Prüfung und wird nicht bewertet.

=== 2. Prüfung

==== 2.1 Prüfung der Alternativtexte von CAPTCHA-Bildern

. App mit zu prüfender Ansicht starten.
. Prüfen ob bildbasierte CAPTCHAs eingesetzt werden.
. Screenreader starten und Fokus auf das CAPTCHA setzen.
. Prüfen, ob eine Textalternative vom Screenreader ausgegeben wird und der dort hinterlegte Alternativtext den Zweck des
  CAPTCHAs beschreibt (zum Beispiel: "Geben sie die im Bild dargestellte Zeichenfolge ein").
  Wenn eine CAPTCHA-Alternative verfügbar ist, sollte die Textalternative außerdem angeben, wo diese zu finden ist.

==== 2.2 Vorhandensein von CAPTCHA-Alternativen

Prüfen, ob im unmittelbaren Kontext des bildbasierten CAPTCHAs eine Alternative angeboten wird.

=== 3. Hinweise

CAPTCHAs sind generell problematisch, da jede Form von CAPTCHA für manche Nutzende mit Behinderungen unzugänglich ist (siehe die WCAG 2.0 Note on CAPTCHA).

=== 4. Bewertung

==== Nicht voll erfüllt:

* Textalternativen nennen nicht den Zweck des CAPTCHAs.
* Ein Alternativ-CAPTCHA ist vorhanden, aber es wird darauf nicht in der Textalternative verwiesen oder es ist nicht im unmittelbaren Kontext zugänglich.

==== Nicht erfüllt:

* Eine Alternative zu bildbasierten CAPTCHAs ist nicht vorhanden.

== Quellen

=== Allgemein
* http://www.karlgroves.com/2012/04/03/captcha-less-security/[CAPTCHA-less
  Security by Karl Groves, 2012]
  
  
== Einordnung des Prüfschritts

=== Abgrenzung zu anderen Prüfkriterien

Auch die Texteingabe des Captchas muss zugänglich gestaltet sein, damit es
insgesamt zugänglich ist.

Die Zugänglichkeit der CAPTCHA-Texteingabe wird im Prüfschritt
ifdef::env_embedded[11.3.3.2 "Beschriftungen von Formularelementen vorhanden"]
ifndef::env_embedded[]
  <<11.3.3.2 Beschriftungen von Formularelementen vorhanden.adoc#,11.3.3.2
  Beschriftungen von Formularelementen vorhanden>>
endif::env_embedded[]
geprüft.

=== Einordnung des Prüfschritts nach  EN 301 549 V.3.2.1

==== 11.1.1.1 Non-text content (open functionality)

* NOTE: CAPTCHAs do not currently appear outside of the Web. However, if they do appear, this guidance is accurate.

=== Einordnung des Prüfschritts nach WCAG 2.1

==== Guideline

* https://www.w3.org/TR/WCAG21/#text-alternatives[Guideline 1.1 Text
  Alternatives]:
  Provide text alternatives for any non-text content so that it can be changed
  into other forms people need, such as large print, braille, speech, symbols
  or simpler language

==== Success Criterion

* http://www.w3.org/TR/WCAG21/#x1-1-1-non-text-content[1.1.1 Non-text Content
  (Level A)]

==== Techniques

===== General Techniques

* https://www.w3.org/WAI/WCAG21/Techniques/general/G143[G143: Providing a text
  alternative that describes the purpose of the CAPTCHA]
* https://www.w3.org/WAI/WCAG21/Techniques/general/G144[G144: Ensuring that
  the Web Page contains another CAPTCHA serving the same purpose using a
  different modality]

===== Failures

* https://www.w3.org/WAI/WCAG21/Techniques/failures/F65[F65: Failure of Success
  Criterion 1.1.1 due to omitting the alt attribute on img elements, area
  elements, and input elements of type 'image']

