= Prüfschritt 11.1.4.4 Text auf 200% vergrößerbar
include::include/author.adoc[]
include::include/attributes.adoc[]

*Hinweis: Dies ist ein Entwurf. Inhalte können sich jederzeit ändern.*

== Was wird geprüft?

Die Textgröße soll um bis zu 200 Prozent vergrößert werden können, ohne dass dabei Inhalt oder Funktionalität verloren gehen. 
Sowohl iOS / iPadOS als auch Android bieten in den Bedienungshilfen eine Zoomvergrößerungsfunktion. Sie heißt Zoom (iOS) bzw. Vergrößerung (Android). Gesten erlauben die Aktivierung der vergrößerten Ansicht und eine Änderung des Zoomfaktors. Der Prüfschritt ist damit grundsätzlich erfüllt, wenn bei Nutzung der App die diese Bedienungshilfen nutzbar sind.

Die Verfügbarkeit einer systemseitigen Zoomfunktion ist gut, aber das Lesen von vergrößertem Text ist bei Vergrößerung sehr mühsam, da der sichtbare Ausschnitt verschoben werden muss, um den Text zu lesen oder andere Bereiche der Ansicht über Ziehgesten in diesen Ausschnitt zu bewegen. Deshalb ist der Einsatz von Systemschriften (bei iOS Dynamit Fonts) hilfreich, die bei einer geänderten System-Einstellung der Schriftgröße die Schrift auch in der App größer darstellen. Selbst in Apps, die Systemschriften einsetzen und die eingestellte Vergrößerung übernehmen, werden meist nicht alle Textelemente dynamisch umgesetzt, da dies häufig entweder dazu führen würde, dass entweder Zusammenhang und Übersichtlichkeit durch den Umbruch von Inhalten verschlechtert wird oder dazu, dass Textinhalte abgeschnitten bzw. durch Elipsen abgekürzt werden müssten. Eine läckenlose Anwenduing des eingestellten Schriftvergrößerung aud allen Inhalten ist deshlab nicht praktikabel.
Der Einsatz von Systemschriften ist überall empfehlenswert, wo Umbrüche gut möglich sind, etwa bei Fließtexten. Die Nichtumsetzung wird kedoch in diesem Prüfschritt nicht negastiv bewertet, solange die systemseitige Zoomvergrößerung der bedineungshilfen erwartungsgemäß funktioniert.

== Warum wird das geprüft?

Nutzende sollen die Schriftgröße nach ihren Bedürfnissen einstellen können. besonders ältere Menschen aber auch Menschen mit leichten Sehbehinderungen, brauchen einen vergrößerten Text. Die geforderten 200% reichen für viele stärker sehbehinderte Menschen nicht aus. Hier muss dann ohnehin die Zooomvergrößerung genutzt werden, die bis zu 500% vergrößert.

== Wie wird geprüft?

=== 1. Anwendbarkeit des Prüfschritts

Der Prüfschritt ist anwendbar, wenn die App-Ansicht Text enthält.

=== 2. Prüfung

==== 2.1 Prüfung der Schriftvergrößerung mit Hilfe der Betriebssystem-Einstellungen

. Zoom-Funktionalität in den Bedienungshilfen von iOS / iPadOS bzw. Android aktivieren
. App mit zu prüfender Ansicht öffnen
. Ansicht mittels der Zoomfunktion des Betriebssystems um 200% vergrößern. Ist die Funktion verfügbar? 

==== 2.2 Prüfung der Übernahme von systemseitigen Einstellungen vergrößerter Schrift

===== iOS
. Schriftgröße über Einstellungen / Bedienungshilfen / Anzeige & Textgröße / Größerer Text auf einen deutlich größeren Wert (ca. doppelt so groß) stellen. (Der genaue Vergößerungsfaktor wird ggf. nicht angezeigt). Wirkt sich die Vergrößerung auf Texte der App aus?

===== Android
. Schriftgröße bei Einstellungen / Eingabehilfe / Verbesserungen der Sichtbarkeit / Schriftgröße und -Stil auf einen deutlich größeren Wert (ca. doppelt so groß) stellen. (Der genaue Vergößerungsfaktor wird ggf. nicht angezeigt). Wirkt sich die Vergrößerung auf Texte der App aus?

==== 2.2 Prüfung der Schriftvergrößerung durch Bedienelemente in der App

Wenn die Software eigene Bedienelemente bereithält, um die Schriftgröße zu vergrößern

. Prüfen, ob die Bedienelemente für Schriftvergrößerung deutlich sichtbar im oberen Bereich der Ansicht angeboten werden.
. Prüfen, ob die Schrift mit Hilfe der auf der Ansicht angebotenen Bedienelemente schrittweise vergrößert werden kann (wie stark die Vergrößerung ist spielt dabei keine  Rolle).
. Prüfen, ob sich über die angebotenen Bedienelemente die Ausgangsschriftgröße wiederherstellen lässt.

=== 3. Hinweise

3.1 Wenn 2.1 erfüllt ist, änder diese Prüfung nicht das Ergebnis (die Anforderung ist erfüllt). Die Prüfung ist dennoch sinnvoll, um Hinweise auf Verbesserungsmöglichkeiten tzu geben. Dies betrifft alle Inhlatsbereiche, die bei Vergößerung problmlos umberechen sollten, z.B. Fließtexte.

Werden Apps getestet, kommen die Funktionen Zoomen und / oder Nur-Text-Vergrößerung des Betriebssystems zum Einsatz:

* Bietet das Betriebssystem eine normale Zoomfunktion (Vergrößerung des gesamten Bildausschnitts) an, wird diese meist eine 200%ige Vergrößerung
ermöglichen. Funktioniert die Zoomfunktion mit der zu testenden Software, ist dieser Prüfschritt bestanden.
* Falls das Betriebssystem auch eine Nur-Text-Vergrößerung anbietet, sollte diese ebenfalls getestet werden.
Probleme mit der Nur-Text-Vergrößerung sollten zumindest angemerkt werden, da diese für einige Nutzer vorteilhafter ist, als die
Vergrößerung des gesamten Bildausschnitts ist (z. B. bessere Orientierung).

Die Prüfung der Schriftvergrößerung durch ein eigenes Bedienelement in der zu testenden App-Ansicht erfolgt nur unter folgender Bedingung:

* Das Bedienelement erfüllt alle Anforderungen an Barrierefreiheit (es ist zum Beispiel tastaturbedienbar, erfüllt die Kontrastanforderungne etc.)

=== 4. Bewertung

==== Erfüllt:

* Der Bildschirminhalt (inklusive Text) lässt sich mittels der Systemfunktionen auf 200 % vergrößern, ohne dass es zu Überlappungen oder abgeschnittenen Inhalten kommt und ohne dass Funktionalitäten beeinträchtigt werden.

== Einordnung des Prüfschritts

=== Abgrenzung zu anderen Prüfkriterien

Mangelnde Vergrößerbarkeit von Schriftgrafiken:
siehe Prüfschritt
ifdef::env_embedded[11.1.4.5 "Verzicht auf Schriftgrafiken".]
ifndef::env_embedded[]
  <<11.1.4.5 Verzicht auf Schriftgrafiken.adoc#,11.1.4.5 Verzicht auf
  Schriftgrafiken>>.
endif::env_embedded[]

=== Einordnung des Prüfschritts nach WCAG 2.1

==== Guideline

* https://www.w3.org/TR/WCAG21/#distinguishable[Guideline 1.4 Distinguishable:
  Make it easier for users to see and hear content including separating
  foreground from background]

==== Success criterion

* https://www.w3.org/TR/WCAG21/#resize-text[1.4.4 Resize text (Level AA)]

==== Techniques

.General Techniques
* https://www.w3.org/WAI/WCAG21/Techniques/general/G146.html[G146: Using
  liquid layout]
* https://www.w3.org/WAI/WCAG21/Techniques/general/G178.html[G178: Providing
  controls on the Web page that allow users to incrementally change the size
  of all text on the page up to 200 percent]
* https://www.w3.org/WAI/WCAG21/Techniques/general/G179.html[G179: Ensuring
  that there is no loss of content or functionality when the text resizes and
  text containers do not change their width]

==== Failures

* https://www.w3.org/WAI/WCAG21/Techniques/failures/F69.html[F69: Failure of
  Success Criterion 1.4.4 when resizing visually rendered text up to 200
  percent causes the text, image or controls to be clipped, truncated or obscured]
* https://www.w3.org/WAI/WCAG21/Techniques/failures/F80.html[F80: Failure of
  Success Criterion 1.4.4 when text-based form controls do not resize when visually rendered text is resized up to 200%]

== Quellen

=== WCAG 2.1 über die Skalierung von Text

[.BLOCK_LANG_EN]
The scaling of content is primarily a user agent responsibility.
User agents that satisfy UAAG 1.0 Checkpoint 4.1 allow users to configure text
scale.
The author's responsibility is to create Web content that does not prevent the user
agent from scaling the content effectively.
Authors may satisfy this Success Criterion by verifying that content does not
interfere with user agent support for resizing text, including text-based
controls, or by providing direct support for resizing text or changing the
layout.
An example of direct support might be via server-side script that can be used
to assign different style sheets.

(https://www.w3.org/WAI/WCAG21/Understanding/resize-text.html[Resize text:
Understanding SC 1.4.4])

=== Die WCAG 2.1 zur Nutzung absoluter und relativer Maßeinheiten für Text

[.BLOCK_LANG_EN]
--
(...) specify text font size in em units so that user agents can scale content
effectively.
Since the em is a property of the font, it scales as the font changes size. If
a font-size is specified for the body element, all other elements inherit that
value, unless overridden by a more specific selector.

When font size is given in absolute units of measurement, such as points or
pixels, the Text Size menu commands in Internet Explorer 7 and earlier do not
resize the text.

Internet Explorer 7 only changes the text size when the CSS is defined in a
style element (...). When using inline style with the style attribute, the
text size change is not supported.
--

(WCAG 2.1 Technik https://www.w3.org/WAI/WCAG21/Techniques/css/C14.html[C14:
Using em units for font sizes])
