= Prüfschritt 11.1.4.10 Inhalte brechen um
include::include/author.adoc[]
include::include/attributes.adoc[]

*Hinweis: Dies ist ein Entwurf. Inhalte können sich jederzeit ändern.*

== Was wird geprüft?

Inhalte der App sollen bei einer Viewport-Breite von 320 CSS Pixeln so angezeigt werden, dass alle Informationen und Funktionen verfügbar sind, ohne dass Nutzer horizontal scrollen müssen. Die Inhalte mobiler Aps sind meist standardmäßig für die Ansicht im Hochkant-Format optimiert, auch wenn die heute verbreiteten Mobilgeräte meist eine größere Viewportbreite als 320 CSS-Pixel haben. Damit ist dieser Prüfschritt in der Regel erfüllt. 

Native Apps, auch die gängigen Browser, verfügen in der Regel nicht über die Möglichkeit, innerhalb der App die Textgröße zu ändern, wie dies über die Zoom-Funktion in Desktop-Browsern geschieht. Dort führt das Hineinzoomen bei responsiven Sites zum Umburch in eine andere Darstellung. Manche Apps zeigen einen anderen Umbruch der Inhalte, wenn das Gerät ins Querformat gedreht wird oder wenn die App auf einem Tablet mit größerer Viewportbreite angezeigt wird. Aus dem normativen Text ist jedoch keine Verpflichtung abzuleiten, dass für größere Viewportbreiten eine an diese angepasste Ansicht geboten werden muss.

Ausnahmen von die Anforderung, dass Informationen und Funktionen innerhalb der Viewportbreite vpn 320px verfügbar sind, gibt es für Inhalte, für deren Nutzung ein zweidimensionales Layout erforderlich ist und die ggf. auf Viewportbreite verkleinert nicht sinnvoll nutzbar sind, z.B.:

* Bilder
* Landkarten
* Diagramme
* Videos
* Spiele
* Präsentationen
* Datentabellen 
* Anwendungs-Schnittstellen, in denen die Bearbeitung von Inhalten die permanente Verfügbarkeit von
Werkzeugleisten erfordert.

== Warum wird das geprüft?

Im Kontext von Desktop-Browsern hilft die Anforderung sehbehinderten Nutzern, die eine vergrößerte Darstellung brauchen und deshalb über den Desktop-Browser-Zoom die Inhalte vergrößern. Dadurch kommt es häufig zu einem Umbruch in eine einspaltige Ansicht bei der normativ festgelegten CSS Viewport-Breite von 320 Pixeln (beim Vergrößern veringert sich schrittweise die ausgegebene Breite in CSS-Pixeln). In der Desktop-Zoom-Ansicht sind Texte meist deutlich größer und für sehbehinderte Nutzende zum Teil nun erst lesbar. Im Kontext mobiler Apps mit meist ohnehin viel kleinerem Display kommen eher systemseitige Methoden der Textvergrößerung zum Tragen, so die Einstellung größerer Schrift, die sich auf die Darstellung auswirkt, wenn Entwickler in der App dynamische Fonts verwenden, und die Bedienungshilfe Zuum oder Vergrößerung (Android) bzw. Zoom (iOS) die nicht zu einem Umbruch führt. 

Werden Apps auf Tablets mit größeren Viewport-Breiten angezeigt, wäre die Zoomvergrößerung hier ebenso hilfreich wie auf dem Desktop, wird aber von mobilen Browsern und nativen Apps zurzeit kaum angeboten.

== Wie wird geprüft?

=== 1. Anwendbarkeit des Prüfschritts

Laut EN 301 549 Version 3.1.1 ist dieser Prüfschritt auf Software und damit für mobile Apps anwendbar. In der Regel ist er schon dadurch erfüllt, dass alle Inhalte auf die Ausgabe innerhalb des Hochkant-Viewports optimiert sind, auch wenn sie nicht "umbrechen". Die Prüfung beschränkt sich somit auf Inhalte, die nicht in den Hochkant-Viewport passen (der in der Regel bei verfügbaren aktuellen Testgeräten breiter ist als die 320 CSS-Pixel der normativen Anforderung), und auf mögliche Ausnahmen von Apps, die selbst eine Zoomfunktion implementieren.

=== 2. Prüfung

. Gibt es in der App Inhalte, die bei 320px Viewportbreite nicht in den Viewport passen und als Ausnahme gelten können? Falls ja, lassen sich die Inhalte horizontal in den Viewport verschieben, etwa über scrollbare Bereiche oder zugängliche Pfeiltasten?
. Gibt es in der App Inhalte, die bei 320px Viewportbreite nicht in den Viewport passen und nicht unter die Ausnahmen fallen?
. Stellt die App Elemente oder Einstellungen für die Zoom-Vergrößerung von Inhalten bereit? Falls ja, die App auf einem Display mit größerer Viewport-Breite laden (auf einem Tablet oder im Querformat des Smartphones) und Zoom-Vergrößerung aktivieren. Falls sich Inhalte an den breiteren Display anpassen, also seine Breite für ein anderes Layout ausnutzen, sollten sie bei einer über Zoom-Vergrößerung erreichten Viewportbreite von 320 Pixeln umbrechen. Alle Inhalte und Funktionen sollten dann weiter nutzbar sein.

Für Hinweise zur Prüfpraxis können Sie auf GitHub
https://github.com/BIK-BITV/BIK-App-Test/issues[ein Issue] zur diesem
Prüfschritt erstellen.

=== 3. Hinweise

==== 3.1 Praktische Aspekte der Prüfung: Geräte
Oft wird für die Prüfung kein Gerät mit 320 CSS Pixeln Viewportbreite und aktuellem Betriebssystem zur Verfügung stehen. Deshalb ist es unvermeidlich, auf einem gängigen Gerät mit etwas größerer Viewportbreite zu testen (etwa ein iPhone 13 min oder ein Samsung Galaxy A12, beide mit 360 CSS Pixeln Viewport-Breite).

==== 3.2 Apps mit Größen-Einstellungen für Inhalte
Falls Apps selbst Einstellungen zum Vergrößern der Inhalte bieten, sollte der Umbruch funktionieren. Dies ist jedoch kaum anzutreffen. Der Dolphin-Browser (Android) bildet eine Ausnahme. Unklar ist jedoch, was für ein Vergrößerungsfaktor bei einem ohnehin schmalen Display noch realistisch ist. Dies würde von der Ausgangsgröße der Inhalte abhängen. 

==== 3.3 Lese- und Schreibrichtung
Dieser Prüfschritt beschränkt sich auf Inhalte, deren primäre Schreibrichtung waagerecht ist, wie bei der für die meisten westlichen
Sprachen benutzten lateinischen Schrift. Die zugrunde liegende WCAG-Anforderung gilt in ähnlicher Weise für Inhalte mit vertikaler Schreibrichtung.

=== 4. Bewertung
==== Nicht erfüllt

* Es gibt Inhalte, die nicht unter die Ausnahmen fallen und nicht in den Viewport von 320px (ersatzweise 360 Pixel) passen.
* Es gibt Inhalte, die unter die Ausnahmen fallen und nicht in den Viewport von 320px (ersatzweise 360 Pixel) passen, und deren abgeschnittene Inhalte sich nicht in den Viewport bewegen lassen.

== Quellen

https://www.w3.org/WAI/WCAG21/Understanding/reflow.html[Understanding Reflow]
(zur Zeit nur auf Englisch verfügbar)
