= Prüfschritt 11.1.1.1c Dekorative Grafiken
include::include/author.adoc[]
include::include/attributes.adoc[]

== Was wird geprüft?

Eine Grafik, die keine informative Funktion hat, benötigt keine Textalternative. Grafiken ohne informative Funktion sind zum Beispiel Abstandshalter,
Farbflächen, Muster, oder rein dekorative Fotos. Solche Grafiken sollen für Screenreader ausgeblendet werden.

== Warum wird das geprüft?

Der Screenreader kann Layout- oder dekorative Grafiken nicht von Informationstragenden Grafiken unterscheiden. Er gibt daher beide Grafikarten an die Nutzenden aus.
Wenn in einer Ansicht mehrere Layout- oder Schmuckgrafiken auftauchen, kann dies schnell zu vielen unbrauchbaren Ausgaben durch den Screenreader führen. Diese unnützen Ausgaben unterbrechen den Informationsfluss und sind für die Screenreader-Nutzenden sehr störend. Entwicklerinnen und Entwickler können dekorative Grafiken mit plattformspezifischen Mitteln vor dem Screenreader verbergen, um diese Störung zu vermeiden.

== Wie wird geprüft?

=== 1. Anwendbarkeit des Prüfschritts

Der Prüfschritt ist anwendbar, wenn eingebundene Grafiken für Layout-Zwecke verwendet werden.

=== 2. Prüfung

. App mit zu prüfender Ansicht starten.
. Prüfen ob Layoutgrafiken oder dekorative Grafiken eingesetzt werden.
. Screenreader starten und mit Hilfe der Wischgeste durch die App navigieren.
. Prüfen, ob bei Grafiken, die keine Information vermitteln, eine Ausgabe durch den Screenreader stattfindet.

Grafiken, die nicht informationstragend sind, sollen nicht fokussiert werden, es sollte keine Ausgabe durch den Screenreader erfolgen.

=== 3. Hinweise

Besteht ein informationstragendes Bild aus mehreren Teilen, sollte eines der Teilbilder eine Textalternative haben. Diese informiert über den Inhalt
des zusammengesetzten Bildes. Die anderen Teile des Bildes sollten vor dem Screenreader ausgeblendet sein.

=== 4. Bewertung

*Nicht voll erfüllt:*

Layout- oder Schmuck-Grafiken werden vom Screenreader ausgegeben, die Ausgabe ist jedoch kurz.

== Einordnung des Prüfschritts

=== Einordnung des Prüfschritts nach WCAG 2.1

==== Guideline

* https://www.w3.org/TR/WCAG21/#text-alternatives[Guideline 1.1 Text
  Alternatives]:
  Provide text alternatives for any non-text content so that it can be changed
  into other forms people need, such as large print, braille, speech, symbols
  or simpler language

==== Success Criterion

* http://www.w3.org/TR/WCAG21/#x1-1-1-non-text-content[1.1.1 Non-text Content
  (Level A)]

==== Techniques

.HTML Techniques
* https://www.w3.org/WAI/WCAG21/Techniques/html/H67[H67: Using null alt text
  and no title attribute on img elements for images that AT should ignore]

==== Failures

* https://www.w3.org/WAI/WCAG21/Techniques/failures/F38[F38: Failure of Success
  Criterion 1.1.1 due to omitting the alt-attribute for non-text content used
  for decorative purposes only in HTML]
* https://www.w3.org/WAI/WCAG21/Techniques/failures/F39[
  F39: Failure of Success Criterion 1.1.1 due to providing a text alternative that is not null. (e.g. `alt='spacer'` or ``alt='image'``) for images that should be ignored by assistive technology]

== Fragen zu diesem Prüfschritt

=== Aufgabe der Layout-Grafik in der Textalternative?

Warum soll man bei Layout-Grafiken nicht die jeweilige Aufgabe des Bildes, also zum Beispiel "Abstandhalter" in den Alternativtext schreiben?

Wofür sollte das gut sein? Den Abstand herstellen, also die Aufgabe des Bildes übernehmen kann die Textalternative nicht. Die Information, dass da irgendwo Abstände zwischen Elementen in der Ansicht sind, ist nutzlos. Wie die Elemente auf der Ansicht angeordnet sind, lässt sich der Tatsache, dass an irgend welchen Stellen Abstandhalter sind, auch nicht entnehmen. Solche Textalternativen haben also keinen Nutzen. Auf der anderen Seite kann es sehr störend sein, wenn der Screenreader dauernd "Abstandhalter Abstandhalter Abstandhalter ..." vorliest.
