= Prüfschritt 11.1.3.5 Eingabezweck bestimmen
include::include/author.adoc[]
include::include/attributes.adoc[]

== Was wird geprüft?

Eingabefelder, die sich auf den Nutzer selbst beziehen, sollten eine semantisch eindeutige, sprachunabhängige Bestimmung ihres Zweckes ermöglichen.

In iOS/iPadOS und Android können Eingabefelder teilweise für bestimmte spezifische Eingabe-Typen ausgezeichnet werden, etwa für die Eingabe einer E-Mail-Adresse, für eine PIN-Code-Eingabe oder für eine URL.
Für diese spezifischen Eingabefelder kann das Betriebssystem dann eine optimierte Tastatur einblenden.
Dies unterstützt die Identifizierung des Eingabezwecks, deckt jedoch nicht die volle Intention der Anforderung ab.

Auf GitHub können Sie zu diesem Prüfschritt ein
https://github.com/BIK-BITV/BIK-App-Test/issues[Issue eröffnen], falls Sie
Hinweise zu diesem Prüfschritt haben.

== Warum wird das geprüft?

Die Festlegung des Eingabezwecks (sobald dies möglich ist) würde neue Bedienungshilfen-Einstellungen ermöglichen.
Bei Formularfeldern, die sich auf Daten der Nutzenden selbstbeziehen, könnten damit zusätzliche Informationen angezeigt werden, und zwar unabhängig vom der jeweils gewählten Beschriftung des Feldes und unabhängig von der natürlichen Sprache des Angebots.

Solche zusätzlichen Informationen könnten etwa Bilder bzw. Icons sein, die über bzw. vor dem jeweiligen Eingabefeld angezeigt werden, wenn Nutzende dies voreinstellen oder definierte Befehle aufrufen.
Für Menschen, die Schwierigkeiten mit dem Lesen haben oder bevorzugt über Bilder kommunizieren, kann dies eine Identifizierung von nutzerbezogenen Feldern in Formularen erleichtern.

Darüber hinaus kann die Auszeichnung des Zwecks Eingabevorschläge für das Feld bieten, welche Nutzende einfach übernehmen können.
An die Art des Eingabefeldes angepasste Tastaturen erleichtern außerdem die Texteingabe.

== Wie wird geprüft?

=== 1. Anwendbarkeit des Prüfschritts

Der Prüfschritt ist anwendbar, wenn Formular-Eingabefelder vorhanden sind, die sich auf Nutzerdaten beziehen (etwa Login / Anmeldung, Kontaktformulare,
oder Ansichten zum Anlegen eines Nutzerprofils).
Für eine Prüfung, die Konformität bzw. Nicht-Konformität feststellen würde, müsste die App bzw. das Betriebssystem die Auszeichnung der Eingabezwecke unterstützen, die in Abschnitt https://www.w3.org/TR/WCAG21/#input-purposes[7. Input Purposes for User Interface Components] der WCAG festgelegt sind.
In den Einstellungen zur Barrierefreiheit von Android und iOS müsste außerdem eine Einstellung auftauchen, mit der die Anzeige des Eingabezwecks ein- und ausgeschaltet werden kann.
Beides ist zur Zeit (April 2023) nicht der Fall.

=== 2. Prüfung

Bei Apps ist die Prüfung eingeschränkt möglich.
Hier kann über eine Sichtprüfung z.B. festgestellt werden, ob bei Eingabefeldern für E-Mail-Adressen, Pin-Codes, URLs usw. auch die dafür optimierte Tastatur eingeblendet wird.
Auf der Tastatur für Email-Adressen erscheint dann z.B. prominent das „``@``“-Zeichen und
der Punkt ist verfügbar, ohne erst auf die Symboltastatur wechseln zu müssen.

=== 3. Hinweise

Die Anforderung gilt nur für Felder, die sich auf den Nutzer selbst beziehen.
Sie gilt nicht für Seiten bzw. Ansichten, auf denen die Eingabe von persönlichen Daten mehrerer Personen möglich ist und die Felder für den Nutzer selbst nicht besonders gekennzeichnet sind.
Ein Beispiel dafür sind Ticketbuchungsseiten / -Apps von Fluglinien.
Hier sind die Eingabefelder für den Nutzer nicht von den Feldern für Mitreisende unterscheidbar.

=== 4. Bewertung

==== Erfüllt:

* Eingabefelder, die sich klar auf Nutzende selbst beziehen, unterstützen indirekt das Verständis des Zweck des Eingabezwecks, z.B. ggf. über die Anzeige einer anderen Tastatur oder Textvorschläge (Autofill).

==== Eher erfüllt: 

* Eingabefelder, die sich klar auf Nutzende selbst beziehen, generieren keine Eingabevorschläge und zeigen keine abweichende Tastatur an (etwa für E-Mail-Felder).

==== Nicht anwendbar:

* Eingabefelder beziehen sich nicht eindeutig auf die Nutzenden selbst.

== Quellen

=== Android
* Appt.org: https://appt.org/en/docs/android/samples/input-keyboard-type[Input keyboard type on Android]
* Android Developer Resources: https://developer.android.com/guide/topics/text/autofill-optimize[Optimize your app for autofill (zur Zeit nur auf
Englisch verfügbar)]

=== iOS

* [BLOCK_LANG_EN]#Apple Developer Resources#: https://developer.apple.com/documentation/security/password_autofill/[Password AutoFill (zur Zeit nur auf
Englisch verfügbar)] Die unterstützten Arten von Autofill-Daten sind sehr begrenzt und dienen zur Zeit hauptsächlich dazu, die Tastatur dynamisch anzupassen. Siehe auch https://developer.apple.com/documentation/uikit/uitextinputtraits/1649656-textcontenttype[textContentType:
The semantic meaning for a text input area]. (zur Zeit nur auf Englisch verfügbar)
* https://developer.apple.com/documentation/uikit/uikeyboardtype[UIKeyBoardType: Verfügbare angepasste Tastaturen fpr bestimmte EIngabefelder]

=== Allgemeine Quaellen (WCAG)

* https://www.w3.org/WAI/WCAG21/Understanding/identify-input-purpose.html[
Understanding Success Criterion 1.3.5: Identify Input Purpose (zur Zeit nur auf
Englisch verfügbar)]

== Einordnung des Prüfschritts

=== Einordnung des Prüfschritts nach WCAG 2.1

==== Guideline

* https://www.w3.org/TR/WCAG21/#adaptable[Guideline 1.3 Adaptable: Create
  content that can be presented in different ways (for example simpler layout)
  without losing information or structure.]

==== Success criterion

* https://www.w3.org/TR/WCAG21/#identify-input-purpose[1.3.5 Identify Input
  Purpose (Level AA)]
