= Prüfschritt 11.1.4.10 Inhalte brechen um
include::include/author.adoc[]
include::include/attributes.adoc[]

*Hinweis: Dies ist ein Entwurf. Inhalte können sich jederzeit ändern.*

== Was wird geprüft?

Inhalte sollen bei einer Viewport-Breite von 320 CSS Pixeln so angezeigt werden, dass alle Informationen und Funktionen verfügbar sind, ohne dass Nutzer horizontal scrollen müssen.  Die Inhalte mobiler Aps sind meist standardmäßig für die Ansicht im Hochkantformat optimiert, auch wenn die heute verbreiteten Mobilgeräte meist einen größere Viewportbreite als 320 px haben. Damit ist dieser Prüfschritt in der Regel erfüllt. 

Native Apps, auch die gängigen Browser, verfügen in der Regel nicht über die Möglichkeit, innerhalb der App die Textgröße zu ändern, wie dies über die Zoom-Funktion in Desktop-Browsern geschieht und damit oft den Umburch in eine andere Darstellung auslöst. Manche Apps zeigen einen anderen Umbruch der Inhalte, wenn das Gerät ins Querformat gedreht wird oder wenn die App auf einem Tablet mit größerer Viewportbreite angezeigt wird. Aus dem normativen Text ist jedoch keine Verpflichtung abzuleiten, dass für größere Viewportbreiten eine an diese angepasste Ansicht geboten werden muss.

Ausnahmen von die Anforderung, dass Informationen und Funktionen innerhalb der Viewportbreite vpn 320px verfügbar sind, gibt es für Inhalte, für deren Nutzung ein zweidimensionales Layout erforderlich ist und die ggf. auf Viewportbreite verkleinert nicht sinnvoll nutzbar sind, z.B.:

* Bilder
* Landkarten
* Diagramme
* Videos
* Spiele
* Präsentationen
* Datentabellen 
* Anwendungs-Schnittstellen, in denen die Bearbeitung von Inhalten die permanente Verfügbarkeit von
Werkzeugleisten erfordert.

*Hinweis:* Dieser Prüfschritt beschränkt sich auf Inhalte, deren primäre Schreibrichtung waagerecht ist, wie bei der für die meisten westlichen
Sprachen benutzten lateinischen Schrift. Die zugrunde liegende WCAG-Anforderung gilt in ähnlicher Weise für Inhalte mit vertikaler Schreibrichtung.

== Warum wird das geprüft?

Bei mobilen Apps wird mit Systemfunktionen der Bildschirmausschnitt vergrößert, hierbei wird jedoch Text nicht umgebrochen und der Prüfschritt
ist so nicht anwendbar. Falls das System eine Nur-Text-Vergrößerung anbietet, sollte der Text in der Anwendung korrekt umbrechen.

== Wie wird geprüft?

=== 1. Anwendbarkeit des Prüfschritts

Laut EN 301 549 Version 3.1.1 ist dieser Prüfschritt auf Software anwendbar. Wie dies jedoch umgesetzt werden soll, ist unklar. Ggf. gibt es in zukünftigen Versionen der mobilen Betriebssysteme eine entsprechende Bedienungshilfe zum Umbrechen von Text, die ein- und ausgeschaltet werden kann. Dann müssen Apps diese Systemschnittstelle unterstützen.

=== 2. Prüfung

. Gibt es in der App Inhalte, die bei 320px Viewportbreite nicht in den Viewport passen und als Ausnahme gelten können? Falls ja, lassen sich die Inhalte horizontal in den Viewport verschieben, etwa über scrollbare Bereiche oder zugängliche Pfeiltasten?
. Gibt es in der App Inhalte, die bei 320px Viewportbreite nicht in den Viewport passen und nicht unter die Ausnahmen fallen?
. Stellt die Apps Elemente oder Einstellungen zum Vergrößern von Text bereit? Falls ja sollen Inhalte umbrechen und auch unter Vergrößerung nutzbar sein.

Für Hinweise zur Prüfpraxis können Sie auf GitHub
https://github.com/BIK-BITV/BIK-App-Test/issues[ein Issue] zur diesem
Prüfschritt erstellen.

=== 3. Hinweise
Falls für die Prüfung kein älteres Gerät mit 320 CSS Pixeln Viewportbreite zur Verfügung steht, wird auf einem gängigen Gerät mit etwas größerer Viewportbreite getestet (etwa ein iPhone 13 min oder ein Samsung Galaxy A12, beide mit it 360 CSS Pixeln).

=== 4. Bewertung
==== Nicht erfüllt
Es gibt Inhalte, die nicht unter die Ausnahmen fallen und nicht in den Viewport von 320px (ersatzweise 360 Pixel) passen.
Es gibt Inhalte, die unter die Ausnahmen fallen, nicht in den Viewport von 320px (ersatzweise 360 Pixel) passen, und sich nicht in den Viewport bewegen lassen.

== Quellen

https://www.w3.org/WAI/WCAG21/Understanding/reflow.html[Understanding Reflow]
(zur Zeit nur auf Englisch verfügbar)
