= Prüfschritt 11.2.4.7 Fokus sichtbar
include::include/author.adoc[]
include::include/attributes.adoc[]

== Was wird geprüft?

Werden Bedienelemente mit der Tastatur fokussiert, muss ein sichtbarer Tastaturfokus-Indikator vorhanden sein.
In diesem Prüfschritt wird lediglich geprüft, ob eine Fokushervorhebung sichtbar ist – nicht, ob sie ausreichend kontrastreich ist. 

iOS bietet die Möglichkeit, die Fokushervorhebung durchgängig deutlich darzustellen (Tastatursteuerung: Hoher Kontrast).

== Warum wird das geprüft?

Für Tastaturbenutzende ist es wichtig, den aktuellen Tastaturfokus klar zu erkennen – also zu sehen, welches Bedienelement bei Aktivierung (z. B. mit Enter oder der Leertaste) ausgelöst wird oder welches Element als Ausgangspunkt für eine Navigation per Pfeiltasten dient, etwa in Tab-Panels oder Auswahllisten.

Wenn eine App ausschließlich per Tastatur bedient wird, muss das fokussierte Bedienelement klar hervorgehoben sein – andernfalls ist die Navigation für visuelle Nutzer kaum möglich.

== Wie wird geprüft?

=== 1. Anwendbarkeit des Prüfschritts

Der Prüfschritt ist anwendbar, wenn die App-Ansicht interaktive Elemente enthält.

=== 2. Prüfung

. Tastatur über das Andocken einer Tastatur an ein Tablet
oder Verbindung über Bluetooth-Kopplung oder USB-Kabel anschließen.
. Zu prüfende Ansicht der App öffnen.
. Mit der Tabulatortaste zu allen interaktiven Elementen navigieren.
Wo diese weitere Auswahlen zulassen, etwa bei Tabpanels, Menüs oder Auswahllisten, 
mit den Pfeiltasten oder ggf. dem Tabulator zu Tabs bzw. Optionen navigieren. 
Ggf. ist dazu auch die Eingabe von STRG + TAB oder STRG + SHIFT + TAB notwendig.
. Prüfen, ob alle Elemente mit grafischen Veränderungen auf den Fokus reagieren 
(zum Beispiel mit Farbwechseln, Rahmen, Unterstreichungen oder eingeblendeten Symbolen). 
Versteckte Sprunglinks (wo vorhanden) sollen bei Fokuserhalt eingeblendet werden.

=== 3. Hinweise

==== 3.1 Systemfokushervorhebung

Die von mobilen Betriebssystemen vorgesehene Standard-Kennzeichnung des Tastaturfokus ist oft nicht gut sichtbar:

* iOS
   ** Die Standardhervorhebung für per Tabulator erreichbare Bereiche ist meist gut erkennbar (deutlicher farbiger Rahmen). Bei Einträgen, die innerhalb eines fokussierten Bereichs per Pfeiltasten navigiert werden, ist die Hervorhebung jedoch schlecht: hellblau auf weiß mit einem sehr geringen Kontrast von nur 1,2:1.
   ** In den iOS-Bedienungshilfen unter "Tastaturen und Texteingabe" > "Tastatursteuerung" kann die Option "Hoher Kontrast" aktiviert werden. Dadurch erhalten alle Elemente mit Tastaturfokus eine gut sichtbare, dicke schwarze Umrandung.
* Android
   ** Die Tastaturfokus-Hervorhebung ist standardmäßig hellgrau auf weiß oder ein leichte Abdunkelung auf Elementen mit eigenem farbigen Hintergrund. Das Resultat ist ein sehr geringer Kontrast von etwa 1,2:1.

Wird die unveränderte Systemfokushervorhebung durchgängig genutzt, gilt dieser Prüfschritt als erfüllt. Hintergrund ist eine Ausnahme im WCAG-Erfolgskriterium 1.4.11 (Nicht-Text Kontrast) für native Elemente: "...except for inactive components or where the appearance of the component is determined by the user agent and not modified by the author". Bei Apps bezieht sich „user agent“ auf das jeweilige Betriebssystem, also iOS oder Android.

==== 3.2 Screenreader-Fokus
Der Screenreader-Fokus sollte bei der Beurteilung der Tastaturfokus-Hervorhebung nicht berücksichtigt werden. Die Prüfung erfolgt mit angeschlossener Tastatur und ausgeschaltetem Screenreader.

=== 4. Bewertung

==== Erfüllt:
* Wird nur die native Fokushervorhebung genutzt, ist der Prüfschritt auch erfüllt, wenn die Hervorhebung schwach ist (z.B. hellgraue oder hellblaue Einfärbung), der Kontrast also unter 3:1 liegt.
* Wird eine vom Entwickler definierte Hervorhebung eingesetzt, soll diese einen Kontrast zum Hintergrund von mindestens 3:1 erfüllen. Bewertet wird dies jedoch im Prüfschritt <<11.1.4.11 Nicht-Text-Kontrast.adoc#,11.1.4.11 Nicht-Text Kontrast>>. Wird eine Hervorhebung nur über Änderung der Farbe ungesetzt, ist dies zusätzlich im Prüfschritt <<11.1.4.1 Benutzung von Farbe.adoc#,11.1.4.1 Benutzung von Farbe>> zu prüfen und zu bewerten.

==== Nicht erfüllt
* Der Prüfschritt ist nicht erfüllt, wenn auf einem interaktiven Element überhaupt kein Tastaturfokus sichtbar ist. 
Dann ist eventuell auch Prüfschritt
ifdef::env_embedded[11.2.1.1 "Tastaturbedienung"]
ifndef::env_embedded[]
  <<11.2.1.1 Tastaturbedienung.adoc#,11.2.1.1 Tastaturbedienung>>
endif::env_embedded[]
nicht erfüllt.
  
== Quellen
=== Allgemein
* Appt.org: https://appt.org/en/guidelines/wcag/success-criterion-2-4-7#add-accessibility-focus-indicator[Focus Visible: Add accessibility focus indicator] (mehrere Entwicklungsumgebungen)

=== iOS
* Appt.org: https://appt.org/en/docs/ios/samples/accessibility-focus-indicator[Accessibility focus indicator on iOS]

=== Android
* Appt.org: https://appt.org/en/docs/android/samples/accessibility-focus-indicator[Accessibility focus indicator on Android]
* Android ViewUI: https://github.com/cvs-health/android-view-accessibility-techniques/blob/0ffd2aad8f8eada9893295ac47cc9ee9bf21372d/doc/dynamicbehaviors/CustomFocusIndicators.md#L4[Custom Focus Indicators]
* Android Compose: https://github.com/cvs-health/android-compose-accessibility-techniques/blob/main/doc/interactions/CustomFocusIndicators.md[Custom Focus Indicators]

== Einordnung des Prüfschritts

=== Einordnung des Prüfschritts nach WCAG 2.1

==== Guideline

* https://www.w3.org/TR/WCAG21/#navigable[Guideline 2.4 Navigable: Provide
  ways to help users navigate, find content, and determine where they are]

==== Success criteria

* https://www.w3.org/TR/WCAG21/#focus-visible[2.4.7 Focus Visible (Level AA)]
* https://www.w3.org/TR/WCAG21/#non-text-contrast[1.4.11 Non-Text Contrast
  (Level AA)]

==== Techniques

===== General Techniques

* https://www.w3.org/WAI/WCAG21/Techniques/general/G149.html[G149: Using user
  interface components that are highlighted by the user agent when they
  receive focus]
* https://www.w3.org/WAI/WCAG21/Techniques/general/G165.html[G165: Using the
  default focus indicator for the platform so that high visibility default
  focus indicators will carry over]
* https://www.w3.org/WAI/WCAG21/Techniques/general/G195.html[G195: Using an
  author-supplied, highly visible focus indicator]

===== Failures

* https://www.w3.org/WAI/WCAG21/Techniques/failures/F55.html[F55: Failure of
  Success Criteria 2.1.1, 2.4.7, and 3.2.1 due to using script to remove focus
  when focus is received]
* https://www.w3.org/WAI/WCAG21/Techniques/failures/F78.html[F78: Failure of
  Success Criterion 2.4.7 due to styling element outlines and borders in a way
  that removes or renders non-visible the visual focus indicator]

== Fragen zu diesem Prüfschritt

=== Ist die Anzeige des Fokus nicht Sache des Betriebssystems?

Alle Betriebssysteme zeigen dem Tastaturnutzer in irgendeiner Weise, wo der
Fokus ist, wenn diese Anzeige nicht aktiv unterdrückt wird.

Dennoch ist die Anzeige des Fokus (leider) nicht allein Sache des Betriebssystems. Bei den mobilen Betriebssystmen ist die Standard.Fokushervorhebung nicht kontrastreich genug und für Menschen mit Sehbehinderungen nicht oder nur schlecht wahrnwehmbar.

Die App kann festlegen, wie die Fokushervorhebung aussehen soll. Der Fokus muss für Tastaturnutzer gut sichtbar sein.

=== Mit angeschaltetem Screenreader ist der Fokus gut. Reicht das nicht aus?
Die WCAG-Anforderung sagt tatsächlich "Any keyboard operable user interface has a mode of operation where the keyboard focus indicator is visible." Lange Zeit war bei iOS die Tastaturbedienung sogar nur möglich, wenn VoiceOver aktiviert (und ggf. stummgeschaltet) war.  VoiceOver und Talkback sind spezielle Hilfsmittel für Menschen, die eine akustische Ausgabe brauchen, und anderen Menschen meist nicht bekannt. Sie sind nicht als allgemein verfügbarer Nutzungsmodus für Tastaturnutzende zu betrachten.

=== Unsere App ist auf die mobile Nutzung unterwegs ausgelegt, da hat man doch keine Tastatur. Gilt dann dieser Prüfschritt trotzdem?
Ja, er gilt. Viele Apps für unterwegs werden auch zuhause oder am Arbeitsplatz genutzt, z.B. bei einer App für den öffentlichen Nahverkehr:

* um Reisen vorab zu planen, Wege und Anschlüsse zu recherchieren
* um Meldungen zu Baustellen, Umleitungen oder Verkehrsbehinderungen vorab zu checken
* um nutzerdefinierte Voreinstellungen vorzunehmen (z.B. häufige Ziele oder häufige Routen festlegen)
* um sich zu registrieren oder Profildaten zu ändern

Die Anforderungen an Tastaturnutzbarkeit gelten also generell. Die BITV bzw. die zugrunde liegende EN 301 549 sehen hier keine Ausnahmen vor. 
