= Prüfschritt 11.2.4.3 Schlüssige Reihenfolge bei der Tastaturbedienung
include::include/author.adoc[]
include::include/attributes.adoc[]

*Hinweis: Dies ist ein Entwurf. Inhalte können sich jederzeit ändern.*

== Was wird geprüft?

Wenn die Software mit der Tastatur bedient wird, soll die Reihenfolge, in der
Links, Formularelemente und Objekte angesteuert werden, schlüssig und
nachvollziehbar sein.

== Warum wird das geprüft?

Die Bedienung soll geräteunabhängig möglich sein. Das bedeutet: Sie muss sowohl mit einem Zeiger (Maus, Touch-Geste) als auch mit der Tastatur
möglich sein. Denn auch andere Spezialgeräte verhalten sich so wie eine Maus oder wie ein Zeiger.

Probleme gibt es meistens mit der Tastaturbedienung, denn die Mehrzahl der Nutzer arbeitet mit Touch-Gesten, daher wird oft nur an die gedacht. Auf die Tastaturbedienbarkeit angewiesen sind zum Beispiel viele motorisch eingeschränkte Menschen oder blinde Nutzer.

Durch eine nicht nachvollziehbare Reihenfolge der Bedienelemente kann die
Tastaturbedienbarkeit erheblich beeinträchtigt werden.

Manche Apps präsentieren dynamische Inhalte, etwa Rückmeldungen bei
fehlerhaften Formular-Eingaben oder Nachrichten-Teaser, die im Wechsel
angezeigt werden.
Während dynamische Änderungen der Seite für sehende Nutzer unmittelbar
wahrnehmbar sind, werden sie oft von Screenreader-Nutzern gar nicht oder erst
mit Verzögerung wahrgenommen.

Wenn nach dem starten einer App weitere Elemente in die Ansicht eingefügt
werden, soll diese Einfügung unterhalb des auslösenden Elements geschehen,
damit Screenreader hinzugefügte Elemente bemerken und vorlesen.

In manchen Fällen können sie, wenn dies im Kontext verständlich ist, auch
weiter unten in der App eingefügt oder verändert werden (also nicht direkt
nach dem auslösenden Element).

Werden Elemente an anderer Stelle, z. B. am unteren Rand der App-Ansicht,
eingefügt (das ist oft bei Modalen Dialogen der Fall), muss die App dafür
sorgen, dass eine sinnvolle Fokusreihenfolge geschaffen wird und auch blinde
Nutzer die Änderung mitbekommen.

== Wie wird geprüft?

=== 1. Anwendbarkeit des Prüfschritts

Der Prüfschritt ist anwendbar, wenn die App-Ansicht Links, Formularelemente
oder Objekte enthält.

=== 2. Prüfung

Bei Apps soll die Tab-Reihenfolge im Wesentlichen die visuelle Reihenfolge der
Steuerelemente abbilden.
Bei den meisten mobilen Systemen kann dies mittels (Bluetooth-) Tastatur
getestet werden.
Der Tastatur-Fokus wird dazu auf das erste Steuerelement gesetzt.
Zur Prüfung springt man dann mittels Tab-Taste von Steuerelement zu
Steuerelement.
Hierbei wird beurteilt ob die Tab-Reihenfolge der Elemente sinnvoll und im
Wesentlichen der visuellen Reihenfolge entspricht.
Falls dynamische Inhalte eingefügt werden können, wird geprüft, ob die
Reihenfolge nach der Einfügung noch immer sinnvoll ist.

Auf Touch-Geräten muss ggf. eine Bluetooth-Tastatur zum Einsatz kommen.

=== 3. Hinweise

Die Tabulatorreihenfolge sollte im Wesentlichen der visuellen Anordnung auf
dem Bildschirm folgen.
Kleinere Abweichungen sind kein Problem, manchmal ist es ja auch gar nicht
möglich, aus der Anordnung auf dem Bildschirm eine Reihenfolge zwingend
abzuleiten.

Die Tabulatorreihenfolge ist schwer nachzuvollziehen, wenn sie über
unsichtbare ausführbare Elemente geht.

=== 4. Bewertung

*Erfüllt:*

* Die Reihenfolge, in der Links, Formularelemente und Objekte mit der
  Tabulatortaste angesteuert werden, ist im Wesentlichen nachvollziehbar und
  schlüssig.

*Nicht voll erfüllt:*

* Die Tabulatorreihenfolge ist nicht schlüssig, sie weicht ohne
  nachvollziehbaren Grund von der visuellen Anordnung ab oder der Tastaturfokus
  ist über mehr als drei aufeinanderfolgende Stationen in der App-Ansicht nicht
  sichtbar.

*Nicht erfüllt:*

* Die Reihenfolge, in der Links, Formularelemente und Objekte mit der
  Tabulatortaste angesteuert werden, ist nicht nachvollziehbar und erschwert die
  Bedienung mit der Tastatur erheblich.
  
== Quellen
=== iOS
* Orange Accessibility Guidelines: https://a11y-guidelines.orange.com/en/mobile/ios/development/#focus-an-element[iOS developer guide - focus an element] - Code-Bispiele
* Orange Accessibility Guidelines: https://a11y-guidelines.orange.com/en/mobile/ios/development/#focus-an-element[Modify the focus area of VoiceOver] - Code-Bispiele
* Orange Accessibility Guidelines: https://a11y-guidelines.orange.com/en/mobile/ios/development/#modal-view[Modal view] - Fokus auf Inhalte modaler Dialoge reduzieren
* Appt.org: https://appt.org/en/docs/ios/samples/accessibility-focus[Accessibility focus on iOS] - how to move the focus to modals or popover views.

=== Android
* Orange Accessibility Guidelines: https://a11y-guidelines.orange.com/en/mobile/android/development/focus-navigation/[Android develop - Keyboard navigation & Switch Access]
* Appt.org: https://appt.org/en/docs/android/samples/accessibility-focus[Accessibility focus on Android] - how to move the focus to modals or popover views.


== Einordnung des Prüfschritts

=== Abgrenzung zu anderen Prüfkriterien

* In diesem Prüfschritt wird die Tabreihenfolge geprüft, die grundsätzliche
Erreichbarkeit und Auslösbarkeit von interaktiven Elementen ist Gegenstand von
Prüfschritt
ifdef::env_embedded[11.2.1.1 "Tastaturbedienung".]
ifndef::env_embedded[]
  <<11.2.1.1 Tastaturbedienung.adoc#,11.2.1.1 Tastaturbedienung>>.
endif::env_embedded[]

* Die Sichtbarkeit des Fokus ist Gegenstand von Prüfschritt
ifdef::env_embedded[11.2.4.7 "Aktuelle Position des Fokus deutlich".]
ifndef::env_embedded[]
  <<11.2.4.7 Aktuelle Position des Fokus deutlich.adoc#,11.2.4.7 Aktuelle Position
  des Fokus deutlich>>.
endif::env_embedded[]

* Geprüft wird hier die richtige Position eingeblendeter oder eingefügter
  Inhalte.
  Ob diese Inhalte selbst sinnvoll sind, wird in anderen Prüfkriterien wie
ifdef::env_embedded[11.3.3.3 "Hilfe bei Fehlern""]
ifndef::env_embedded[]
  <<11.3.3.3 Hilfe bei Fehlern.adoc#,11.3.3.3 Hilfe bei Fehlern>>
endif::env_embedded[]
  oder
ifdef::env_embedded[11.2.4.4 "Aussagekräftige Linktexte"]
ifndef::env_embedded[]
  <<11.2.4.4 Aussagekräftige Linktexte.adoc#,11.2.4.4 Aussagekräftige Linktexte>>
endif::env_embedded[]
  geprüft.
  
=== Einordnung des Prüfschritts nach WCAG 2.1

==== Guideline

* https://www.w3.org/TR/WCAG21/#navigable[Guideline 2.4 Navigable: Provide
  ways to help users navigate, find content, and determine where they are]

==== Success criterion

* https://www.w3.org/TR/WCAG21/#focus-order[2.4.3 Focus Order (Level A)]

==== Techniques

.General Techniques
* https://www.w3.org/WAI/WCAG21/Techniques/general/G59.html[G59: Placing the
  interactive elements in an order that follows sequences and relationships
  within the content]

==== Failures

* https://www.w3.org/WAI/WCAG21/Techniques/failures/F44.html[F44: Failure of
  Success Criterion 2.4.3 due to using tabindex to create a tab order that does not preserve meaning and operability]
* https://www.w3.org/WAI/WCAG21/Techniques/failures/F85.html[F85: Failure of
  Success Criterion 2.4.3 due to using dialogs or menus that are not adjacent to their trigger control in the sequential navigation order]
  
== Fragen zu diesem Prüfschritt
=== Unsere App ist auf die mobile Nutzung unterwegs ausgelegt, da hat man doch keine Tastatur. Gilt dann dieser Prüfschritt trotzdem?
Ja, er gilt. Viele Apps für unterwegs werden auch zuhause oder am Arbeitsplatz genutzt, z.B. bei einer App für den öffentlichen Nahverkehr:

* um Reisen vorab zu planen, Wege und Anschlüsse zu recherchieren
* um Meldungen zu Baustellen, Umleitungen oder Verkehrsbehinderungen vorab zu checken
* um nutzerdefinierte Voreinstellungen vorzunehmen (z.B. häufige Ziele oder häufige Routen festlegen)
* um sich zu registrieren oder Profildaten zu ändern

Die Anforderungen an Tastaturnutzbarkeit gelten also generell. Die BITV bzw. die zugrunde liegende EN 301 549 sehen hier keine Ausnahmen vor. 

