= Prüfschritt 11.2.4.3 Schlüssige Reihenfolge bei der Tastaturbedienung
include::include/author.adoc[]
include::include/attributes.adoc[]

== Was wird geprüft?

Wenn die Software mit der Tastatur oder bei eingeschaltetem Screenreader mittels Wischgesten bedient wird, soll die Reihenfolge, in der Links, Formularelemente und Objekte angesteuert werden, schlüssig und nachvollziehbar sein.

== Warum wird das geprüft?

Die Bedienung soll geräteunabhängig möglich sein. Das bedeutet: Sie muss sowohl mit einem Zeiger (Maus, Touch-Geste) als auch mit der Tastatur möglich sein. Auch adere Eingabeformen, etwa die Spracheingabe oder Schaltersteuerung, sind auf eine gute Tastaturbedienbarkeit und eine sinnvolle Fokusreihenfolge angewiesen.

Probleme gibt es meistens mit der Tastaturbedienung, denn die Mehrzahl der Nutzer arbeitet mit Touch-Gesten, daher wird oft nur an die gedacht. Auf die Tastaturbedienbarkeit angewiesen sind zum Beispiel viele motorisch eingeschränkte Menschen. Probleme gibt es häufig auch bei der Bedienung über Wischgesten, wenn der Screenreader eingeschaltet ist. Auch blinde Nutzer bauchen eine schlüssige Reihenfolge, wenn der Fokus mittels Wischgesten durch die App bewegt wird. Hierbei werden nicht nur interaktive Elemente, sondern auch statische Elemente (Texte, Überschriften) fokussiert.

Durch eine nicht nachvollziehbare Reihenfolge der Bedienelemente kann die Tastaturbedienbarkeit erheblich beeinträchtigt werden.

Manche Apps präsentieren dynamische Inhalte, etwa Rückmeldungen bei fehlerhaften Formular-Eingaben oder Nachrichten-Teaser, die im Wechsel angezeigt werden. Während dynamische Änderungen der Seite für sehende Nutzer unmittelbar wahrnehmbar sind, werden sie oft von Screenreader-Nutzern gar nicht oder erst mit Verzögerung wahrgenommen. Dynamische Änderungen können über eine sinnvolle Fokusreihenfolge (z.B.: Fehlermeldungen bei fehlenden oder inkorrekten Eingaben erscheinen direkt unterhalb des Eingabefelds) oder auch durch Statusmeldungen vermittelt werden. Bei Statusmeldungen gibt es eine Ausgabe an den Screenreader, der Fokus bleibt aber auf dem aktuellen Element.

Wenn nach dem Starten einer App weitere Elemente in die Ansicht eingefügt werden, soll diese Einfügung unterhalb des auslösenden Elements geschehen, damit Screenreader hinzugefügte Elemente bemerken und vorlesen.

In manchen Fällen können sie, wenn dies im Kontext verständlich ist, auch weiter unten in der App eingefügt oder verändert werden (also nicht direkt nach dem auslösenden Element).

Werden Elemente an anderer Stelle, z. B. am unteren Rand der App-Ansicht, eingefügt (das ist oft bei Modalen Dialogen der Fall), muss die App dafür sorgen, dass auch blinde Nutzer die Änderung mitbekommen, z.B. durch Fokusversetzung in den eingefügten oder eingeblendeten Bereich.

== Wie wird geprüft?

=== Anwendbarkeit des Prüfschritts

Der Prüfschritt ist anwendbar, wenn die App-Ansicht Links, Formularelemente oder Objekte, etwa nach Interaktion eingeblendete Menüs oder Dialoge, enthält.

=== Prüfung

Bei Apps soll die Tab-Reihenfolge im Wesentlichen die visuelle Reihenfolge der Steuerelemente abbilden.
Bei den meisten mobilen Systemen kann dies mittels (Bluetooth-) Tastatur getestet werden. Der Tastatur-Fokus wird dazu auf das erste Steuerelement gesetzt. Zur Prüfung springt man dann mittels Tab-Taste von Steuerelement zu Steuerelement. Hierbei wird beurteilt, ob die Tab-Reihenfolge der Elemente sinnvoll und im Wesentlichen der visuellen Reihenfolge entspricht.

Parallel dazu werden bei angeschaltetem Screenreader die Elemente der Ansicht mittels horizontalen Wischgesten durchlaufen. Die Reihenfolge sollte sinnvoll sein. Bei der Wischgsten-Navigation sollten sollten mehrfache Fokuspunkte auf interaktiven Elementen negativ angemerkt werden.

Falls dynamische Inhalte eingefügt werden können, wird geprüft, ob die Reihenfolge nach der Einfügung noch immer sinnvoll ist. Dies ist bei eingeblendeten Dialogen der Fall,

* wenn sich der Fokus bei Aufruf am Beginn des Dialogs befindet
* wenn der Fokus sich nur innerhalb des Dialogs bewegt, solange der Dialog sichtbar ist
* wenn der Fokus sich nach dem Schließen des Dialogs wieder an der aufrufenden Stelle befindet.

Auf Touch-Geräten muss ggf. eine angedockte oder Bluetooth-Tastatur zum Einsatz kommen.

=== Hinweise

Die Tabulatorreihenfolge und die Reihenfolge der Fokuspunkte bei der Wischgesten-Navigation sollte im Wesentlichen der visuellen Anordnung auf dem Bildschirm folgen. Kleinere Abweichungen sind kein Problem, manchmal ist es ja auch gar nicht möglich, aus der Anordnung auf dem Bildschirm eine Reihenfolge zwingend abzuleiten.

Die Tabulatorreihenfolge ist schwer nachzuvollziehen, wenn sie über unsichtbare ausführbare Elemente geht. 

Werden interaktive Elemente gar nicht erreicht, ist unter Umständen auch 11.2.1.1 Tastatur negativ zu bewerten.

=== Bewertung

*Erfüllt:*

* Die Reihenfolge, in der Links, Formularelemente und Objekte mit der Tabulatortaste und bei eingeschaltetem Screenreader mittels Wischgesten angesteuert werden, ist im Wesentlichen nachvollziehbar und schlüssig.

*Nicht voll erfüllt:*

* Die Tabulatorreihenfolge bzw. Fokusreihenfolge bei Wischgesten-Navigation ist nicht schlüssig, sie weicht ohne nachvollziehbaren Grund von der visuellen Anordnung ab oder der Tastaturfokus ist über mehr als drei aufeinanderfolgende Stationen in der App-Ansicht nicht sichtbar.

*Nicht erfüllt:*

* Die Reihenfolge, in der Links, Formularelemente und Objekte mit der Tabulatortaste angesteuert werden, ist nicht nachvollziehbar und erschwert die Bedienung mit der Tastatur erheblich.

== Einordnung des Prüfschritts

=== Abgrenzung zu anderen Prüfkriterien

* In diesem Prüfschritt wird die Tabreihenfolge geprüft, die grundsätzliche Erreichbarkeit und Auslösbarkeit von interaktiven Elementen ist Gegenstand von Prüfschritt
ifdef::env_embedded[11.2.1.1 "Tastaturbedienung".]
ifndef::env_embedded[]
  <<11.2.1.1 Tastaturbedienung.adoc#,11.2.1.1 Tastaturbedienung>>.
endif::env_embedded[]

* Die Sichtbarkeit des Fokus ist Gegenstand von Prüfschritt
ifdef::env_embedded[11.2.4.7 "Aktuelle Position des Fokus deutlich".]
ifndef::env_embedded[]
  <<11.2.4.7 Aktuelle Position des Fokus deutlich.adoc#,11.2.4.7 Aktuelle Position
  des Fokus deutlich>>.
endif::env_embedded[]

* Geprüft wird hier die richtige Position eingeblendeter oder eingefügter
  Inhalte.
  Ob diese Inhalte selbst sinnvoll sind, wird in anderen Prüfkriterien wie
ifdef::env_embedded[11.3.3.3 "Hilfe bei Fehlern""]
ifndef::env_embedded[]
  <<11.3.3.3 Hilfe bei Fehlern.adoc#,11.3.3.3 Hilfe bei Fehlern>>
endif::env_embedded[]
  oder
ifdef::env_embedded[11.2.4.4 "Aussagekräftige Linktexte"]
ifndef::env_embedded[]
  <<11.2.4.4 Aussagekräftige Linktexte.adoc#,11.2.4.4 Aussagekräftige Linktexte>>
endif::env_embedded[]
  geprüft.

=== Einordnung des Prüfschritts nach WCAG 2.1

==== Guideline

* https://www.w3.org/TR/WCAG21/#navigable[Guideline 2.4 Navigable: Provide
  ways to help users navigate, find content, and determine where they are]

==== Success criterion

* https://www.w3.org/TR/WCAG21/#focus-order[2.4.3 Focus Order (Level A)]

==== Techniques

.General Techniques
* https://www.w3.org/WAI/WCAG21/Techniques/general/G59.html[G59: Placing the
  interactive elements in an order that follows sequences and relationships
  within the content]

==== Failures

* https://www.w3.org/WAI/WCAG21/Techniques/failures/F44.html[F44: Failure of
  Success Criterion 2.4.3 due to using tabindex to create a tab order that does not preserve meaning and operability]
* https://www.w3.org/WAI/WCAG21/Techniques/failures/F85.html[F85: Failure of
  Success Criterion 2.4.3 due to using dialogs or menus that are not adjacent to their trigger control in the sequential navigation order]
