= Prüfschritt 2.1.2a Keine Tastaturfalle
include::include/author.adoc[]
include::include/attributes.adoc[]

== Was wird geprüft?

Kann der Tastaturfokus auf ein Element der Ansicht bewegt werden, muss er auch
von diesem Element wieder wegbewegt werden können.
Der Inhalt darf keine Tastaturfalle erzeugen.

Wenn mehr als Pfeil- oder Tabulatortasten oder andere
Standard-Beendigungsmethoden erforderlich sind, wird Der Benutzer auf die
benötigte Methode zum Wegbewegen des Fokus hingewiesen.

Da jeder Teil einer Software, der dieses Erfolgskriterium nicht erfüllt, die
Fähigkeit des Nnutzers beeinträchtigen kann, die gesamte Software zu
verwenden, ist dies für alle Inhalte in der Software erforderlich um dieses
Erfolgskriterium zu erfüllen.

Die Standard-Exit-Methoden können je nach Plattform variieren.
Beispielsweise ist auf vielen Desktop-Plattformen die Escape-Taste eine
Standardmethode zum Beenden bzw. schließen von Dialogen.

== Warum wird das geprüft?

Die Bedienung soll geräteunabhängig möglich sein.
Das bedeutet:
Sie muss sowohl mit Touch-Eingaben als auch mit der Tastatur möglich sein.

Auf die Tastaturbedienbarkeit angewiesen sind zum Beispiel viele motorisch
eingeschränkte oder blinde Menschen .

== Wie wird geprüft?

=== Anwendbarkeit des Prüfschritts

Der Prüfschritt ist immer anwendbar.

=== Prüfung

. Tastatur z. B. per Bluetooth anschließen.
. App starten und zu prüfende Ansicht aufrufen.
. Mit der Tabulatortaste die Links und Formularelemente durchgehen.
. Prüfen, ob alle Links und Formularelemente erreicht und wieder verlassen
  werden können.

=== Hinweise zu Tastaturfallen

Wenn die Tastaturfalle verhindert, dass man Inhalte nach der Tastaturfalle
erreicht, dann ist eventuell auch Prüfschritt
ifdef::env_embedded[2.1.1a "Ohne Maus nutzbar"]
ifndef::env_embedded[]
<<2.1.1a Ohne Maus nutzbar.adoc#,2.1.1a Ohne Maus nutzbar>>
endif::env_embedded[]
nicht erfüllt!

=== Bewertung

*Erfüllt:*

* Es gibt keine Tastaturfallen.

*Nicht erfüllt:*

* Wesentliche Inhalte und Funktionen sind aufgrund einer Tastaturfalle mit der
  Tastatur nicht erreichbar oder nicht bedienbar.

== Einordnung des Prüfschritts

=== Einordnung des Prüfschritts nach WCAG 2.1

==== Guideline

* https://www.w3.org/TR/WCAG21/#keyboard-accessible[Guideline 2.1 Keyboard
  Accessible: Make all functionality available from a keyboard.]

==== Success criteria

* https://www.w3.org/TR/WCAG21/#no-keyboard-trap[2.1.2 No Keyboard Trap
  (Level A)]

==== Techniques

.General Techniques
* https://www.w3.org/WAI/WCAG21/Techniques/general/G21.html[G21: Ensuring that
  users are not trapped in content]

==== Failures

* https://www.w3.org/WAI/WCAG21/Techniques/failures/F10[F10: Failure of
  Success Criterion 2.1.2 and Conformance Requirement 5 due to combining
  multiple content formats in a way that traps users inside one format type]
