= Prüfschritt 11.2.4.3 Schlüssige Reihenfolge bei der Tastaturbedienung
include::include/author.adoc[]
include::include/attributes.adoc[]

== Was wird geprüft?

Wenn die App mit der Tastatur bedient wird, soll die Reihenfolge, in der Links, Formularelemente und Objekte angesteuert werden, schlüssig und nachvollziehbar sein.

== Warum wird das geprüft?

Die Bedienung soll geräteunabhängig möglich sein. Das bedeutet: Sie muss sowohl mit einem Zeiger (Maus, Touch-Geste) als auch mit der Tastatur möglich sein. Auch adere Eingabeformen, etwa die Spracheingabe oder Schaltersteuerung, sind auf eine gute Tastaturbedienbarkeit und eine sinnvolle Fokusreihenfolge angewiesen.

Probleme gibt es meistens mit der Tastaturbedienung, denn die Mehrzahl der Nutzenden arbeitet mit Touch-Gesten, daher wird oft nur an sie gedacht. Auf die Tastaturbedienbarkeit angewiesen sind zum Beispiel viele motorisch eingeschränkte Menschen.

Bei einer nicht nachvollziehbaren Fokusreihenfolge laufen Nutzende Gefahr, die Orientierung zu verlieren, die Tastaturbedienbarkeit kann dadurch erheblich beeinträchtigt sein.

Manche Apps stellen Inhalte dynamisch bereit, z.B. Rückmeldungen bei fehlerhaften formular-Eingaben werden dynamisch unter dem Feld angezeigt oder Dialoge werden eingeblendet. Während diese Änderungen der Seite für sehende Nutzende unmittelbar wahrnehmbar sind, werden sie von Screenreader-Nutzenden gar nicht oder erst mit Verzögerung wahrgenommen. 

Werden der Ansicht Elemente dynamisch eingefügt, soll diese Einfügung unterhalb des auslösenden Elements geschehen, damit Screenreader hinzugefügte Elemente bemerken und vorlesen.
Ist das nicht der möglich, so muss über ein Fokusmanagement für eine nachvollziehbare Fokusreihenfolge gesorgt werden. Für einen eingeblendeten Dialog bedeutet das beispielsweise, der Fokus wird auf den Dialog gesetzt und so lange darin gehalten, bis er geschlossen wird. Anschließend ist der Fokus wieder auf dem auslösenden Element.

== Wie wird geprüft?

=== 1. Anwendbarkeit des Prüfschritts

Der Prüfschritt ist anwendbar, wenn die App-Ansicht Links, Formularelemente oder Objekte (z. B. Menüs oder Dialoge, die nach Interaktion eingebelendet werden), enthält.

=== 2. Prüfung

Die Fokusreihenfolge wird mittels angedockter oder über Bluetooth gekoppelter Tastatur getestet. Dies ist bei den meisten mobilen Systemen möglich.

. App mit zu prüfender Ansicht starten.
. Der Tastatur-Fokus auf das erste Steuerelement setzen.
. Die interaktiven Elemente der Ansicht mit der Tabulatortaste bzw. auch mit den Pfeiltasten durchlaufen. 
. Bei manchen Bereichen, etwa Auswahllisten, sind Elemente statt mit dem Tabulator ggf. mit den Pfeiltasten erreichbar. Wenn der Tabulator Bedienelenente überspringt, ist zu prüfen ob diese stattdessen mit Pfeitasten erreichbar sind. 
. Rückwärts-Tabben oder die Aktivierung der entgegengesetzten Pfeiltaste sollen die Elemente in der Regel in der gleichen Reihenfolge rückwärts durchlaufen.
. Prüfen, ob die Fokus-Reihenfolge im Wesentlichen die visuelle Reihenfolge der Steuerelemente abbildet.
. Falls dynamische Inhalte eingeblendet oder eingefügt werden können, prüfen, ob die Reihenfolge nach der Einfügung noch immer sinnvoll ist. Dies ist bei eingeblendeten Dialogen der Fall,

* wenn sich der Fokus bei Aufruf am Beginn des Dialogs befindet
* wenn der Fokus sich nur innerhalb des Dialogs bewegt, solange der Dialog sichtbar ist
* wenn der Fokus sich nach dem Schließen des Dialogs wieder an der aufrufenden Stelle befindet.

=== 3. Hinweise

Die Tabulatorreihenfolge sollte im Wesentlichen der visuellen Anordnung auf dem Bildschirm folgen. Kleinere Abweichungen sind kein Problem, manchmal ist es auch gar nicht möglich, aus der Anordnung auf dem Bildschirm eine Reihenfolge zwingend abzuleiten.

Gegebenenfalls müssen erst Bereiche mit Tabulator oder Pfeiltasten erreicht bzw. geöffnet und dann zwischen Tabulator- und Pfeiltasten-Navigation gewechselt werden. Bei einer nicht linearen (zweidimensionalen) Navigation etwa in einer Matrix bzw. Gitterstruktur, soll die Reihenfolge konsistent sein, also in der Regel der visuellen ANordnung entsprechen.

Die Tabulatorreihenfolge ist schwer nachzuvollziehen, wenn sie über unsichtbare ausführbare Elemente geht. 

Werden interaktive Elemente gar nicht erreicht, ist unter Umständen auch 11.2.1.1 Tastaturbedienung negativ zu bewerten.

=== 4. Bewertung

==== Erfüllt:

* Die Reihenfolge, in der Links, Formularelemente und Objekte mit der Tastatur angesteuert werden, ist im Wesentlichen nachvollziehbar und schlüssig, alle interaktiven Elemente sind erreichbar.

==== Nicht voll erfüllt:

* Die Fokusreihenfolge ist nicht schlüssig, sie weicht ohne nachvollziehbaren Grund von der visuellen Anordnung ab oder der Tastaturfokus ist über mehr als drei aufeinanderfolgende Stationen in der App-Ansicht nicht sichtbar.

==== Nicht erfüllt:

* Die Reihenfolge, in der Links, Formularelemente und Objekte mit der Tastatur angesteuert werden, ist nicht nachvollziehbar und erschwert die Bedienung mit der Tastatur erheblich.

== Einordnung des Prüfschritts

=== Abgrenzung zu anderen Prüfkriterien

* In diesem Prüfschritt wird die Tabreihenfolge geprüft, die grundsätzliche Erreichbarkeit und Auslösbarkeit von interaktiven Elementen ist Gegenstand von Prüfschritt
ifdef::env_embedded[11.2.1.1 "Tastaturbedienung".]
ifndef::env_embedded[]
  <<11.2.1.1 Tastaturbedienung.adoc#,11.2.1.1 Tastaturbedienung>>.
endif::env_embedded[]

* Die Sichtbarkeit des Fokus ist Gegenstand von Prüfschritt
ifdef::env_embedded[11.2.4.7 "Aktuelle Position des Fokus deutlich".]
ifndef::env_embedded[]
  <<11.2.4.7 Aktuelle Position des Fokus deutlich.adoc#,11.2.4.7 Aktuelle Position
  des Fokus deutlich>>.
endif::env_embedded[]

* Geprüft wird hier die richtige Position eingeblendeter oder eingefügter
  Inhalte.
  Ob diese Inhalte selbst sinnvoll sind, wird in anderen Prüfkriterien wie
ifdef::env_embedded[11.3.3.3 "Hilfe bei Fehlern""]
ifndef::env_embedded[]
  <<11.3.3.3 Hilfe bei Fehlern.adoc#,11.3.3.3 Hilfe bei Fehlern>>
endif::env_embedded[]
  oder
ifdef::env_embedded[11.2.4.4 "Aussagekräftige Linktexte"]
ifndef::env_embedded[]
  <<11.2.4.4 Aussagekräftige Linktexte.adoc#,11.2.4.4 Aussagekräftige Linktexte>>
endif::env_embedded[]
  geprüft.

=== Einordnung des Prüfschritts nach WCAG 2.1

==== Guideline

* https://www.w3.org/TR/WCAG21/#navigable[Guideline 2.4 Navigable: Provide
  ways to help users navigate, find content, and determine where they are]

==== Success criterion

* https://www.w3.org/TR/WCAG21/#focus-order[2.4.3 Focus Order (Level A)]

==== Techniques

.General Techniques
* https://www.w3.org/WAI/WCAG21/Techniques/general/G59.html[G59: Placing the
  interactive elements in an order that follows sequences and relationships
  within the content]

==== Failures

* https://www.w3.org/WAI/WCAG21/Techniques/failures/F44.html[F44: Failure of
  Success Criterion 2.4.3 due to using tabindex to create a tab order that does not preserve meaning and operability]
* https://www.w3.org/WAI/WCAG21/Techniques/failures/F85.html[F85: Failure of
  Success Criterion 2.4.3 due to using dialogs or menus that are not adjacent to their trigger control in the sequential navigation order]
