= Prüfschritt 11.2.4.4 Aussagekräftige Linktexte
include::include/author.adoc[]
include::include/attributes.adoc[]

== Was wird geprüft?

Ziel oder Zweck des Links sollen aus dem Linktext hervorgehen oder aus dem direkten Kontext des Links ermittelbar sein.

Falls der Link nicht auf andere App-Ansichten verweist, soll der Link über das Dateiformat des Zieldokuments informieren.

Auch wenn Links nicht auf Dokumente verweisen, sondern andere Anwendungen öffnen, sollte der Linktext auch hier einen zusätzlichen Hinweis auf das Ziel gebenb Z. B. „öffnet im Browser“ etc.

== Warum wird das geprüft?

Blinde Nutzende, die von Link zu Link navigieren, bekommen die Linktexte vorgelesen und können bei aussagekräftigen Linktexten leicht entscheiden, ob sie einem Link folgen möchten.

Falls der Linktext selbst nicht aussagekräftig ist, soll der unmittelbare Kontext für Screenreader-Nutzende wenigstens leicht ermittelbar sein.

Screenreader bieten die Möglichkeit, gezielt nur bestimmte Elemente, wie z. B. alle Links auf der Ansicht, zu durchlaufen, und ermöglichen damit einen besseren Überblick. Bei bei mehreren gleichen Linktexten wie "Weiter" oder "mehr lesen" ist das Linkziel schwerer zu ermitteln.

Bei Links zu Angeboten außerhalb der App (zum Beispiel PDF- oder Word-Dokumente) ist es für Nutzende sinnvoll zu wissen, in welchem Format Informationen angeboten werden, bevor sie einen Link aktivieren. Möglichwerweise werden zusätzliche Apps oder Plugins gebraucht und diese Apps sind vielleicht schlecht mit Screenreadern oder anderen Hilfsmittel zugänglich. Auch können bestimmte Dateiformate nicht oder nur schlecht zugänglich sein.

Nutzende wissen außerdem, was sie erwartet, wenn sie einen Link aktivieren. Sie sind nicht überrascht oder irritiert, wenn plötzlich Funktionen nicht mehr vorhanden sind oder eine andere Anwendung geöffnet wird.

== Wie wird geprüft?

=== 1. Anwendbarkeit des Prüfschritts

Der Prüfschritt ist anwendbar, wenn die App Links enthält.

=== 2. Prüfung

==== 2.1 Prüfung von Linktexten

. App mit zu prüfender Ansicht öffnen.
. Screenreader starten und Fokus mit Hilfe der Wischgeste auf die Links setzen.
. Prüfen, ob die Linktexte aussagekräftig sind, das heißt, im Linktext oder im Kontext eine Auskunft über Ziel oder Zweck des Links geben.
. Für Links, deren sichtbarer Linktext allein nicht aussagekräftig ist, mit dem Screenreader prüfen, ob der Linktext durch eine der folgenden Möglichkeiten im Kontext sinnvoll ergänzt wird:
+
* durch zusätzlichen versteckten Linktext
* durch den Alternativtext einer mit im selben Link-Element verlinkten Grafik 
* durch den Text im umschließenden Element Absatz- oder Listen-Element
* bei Links in untergeordneten Listen durch den Text des übergeordneten Listen-Elements
* durch den Text der umschließenden Tabellenzelle und der dazugehörigen Überschriftenzellen
* durch den Text der vorangehenden Überschrift
* durch einen verständlichen Link am Seitenbeginn, der Linktexte auf der Ansicht erweitert

==== 2.2 Prüfung von Links auf andere Dateiformate

Wenn Links aus der App auf externe Ressourcen wie z.B. PDF-Dateien führen:

. App mit zu testender Ansicht öffnen.
. Prüfen, ob visuell, etwa über zusätzliche Icons Auskunft über das Dateiformat gegeben wird.
. Screenreader starten und Fokus mit Hilfe der Wischgeste auf das Icon setzen.
. Prüfen, ob visuelle Information zum Dateiformat auch programmatisch bereitgestellt wird (etwa über versteckten Linktext, Alternativtext, oder geeignete ARIA-Attribute).
. Falls weder über den Linktext noch über ein entsprechend eindeutiges Icon Auskunft über das Dateiformat gegeben wird, ist das Dateiformat des Links möglicherweise für alle Nutzenden unklar. Dies ist nicht als Mangel im Sinne dieses Prüfschritts zu bewerten (sollte jedoch gegebenenfalls als allgemeines Usability-Problem angemerkt werden).

=== 3. Hinweise

* Links, deren Ziel generell für alle Nutzer unklar ist, fallen nicht unter diesen Prüfschritt.
* Verlinkte URLs und verlinkte E-Mail-Adressen vermitteln über ihr Format den Linkzweck (etwa, dass sie einen Email-Client öffnen oder auf ein externes Webangebot verlinken). URLs sind für alle Nutzer möglicherweise nicht aussagekräftig und werden deshalb hier nicht negativ bewertet.
* Bei verlinkten Grafiken wird der Linktext ggf. durch den Wert eines hinterlegten Alternativtextes bereit gestellt.
* Der Linktext kann auch aus dem Alternativtext einer oder mehrerer Grafiken und einfachem Text zusammengesetzt sein.
* Nicht aussagekräftige Links wie "mehr..", "weiter", "etc." im letzten Element einer Liste werden nur akzeptiert, wenn die Bedeutung klar aus dem Kontext der Auflistung hervorgeht.

=== 4. Bewertung

*Erfüllt:*

* Alle Links benennen im Linktext oder im direkten Kontext Linkziel oder Linkzweck.
* Alle Links auf Angebote oder Ressourcen außerhalb der App geben Auskunft über das Dateiformat oder das externe Ziel (z. B. "öffnet im Browser")

*Nicht voll erfüllt:*

* Ziel oder Zweck des Links ist nicht eindeutig oder missverständlich.

== Einordnung des Prüfschritts

=== Abgrenzung zu anderen Prüfkriterien

In diesem Prüfschritt wird nur geprüft, ob die Information über das Dateiformat überhaupt vorhanden ist. Das ist der Fall, wenn das Dateiformat in einer Grafik, im Linktext oder im zugänglichen Namen des Elements angegeben wird.

Die Zugänglichkeit und Aussaagekraft der Textalternativen für Grafiken wird im Prüfschritt 
ifdef::env_embedded[11.1.1.1a "Alternativtexte für Bedienelemente"]
ifndef::env_embedded[]
  <<11.1.1.1a Alternativtexte für Bedienelemente.adoc#,11.1.1.1a
  Alternativtexte für Bedienelemente>>
endif::env_embedded[]
geprüft.


Ist die Grafik, die Auskunft über das Dateiformat gibt, nicht im Link eingebunden (z. B. unverlinkt dem Link vorangestellt), so wird dies in Prüfschritt
ifdef::env_embedded[11.1.1.1b "Alternativtexte für Grafiken und Objekte"]
ifndef::env_embedded[]
  <<11.1.1.1a Alternativtexte für Grafiken und Objekte.adoc#,11.1.1.1b
  Alternativtexte für Grafiken und Objekte>>
endif::env_embedded[]
geprüft.

=== Einordnung des Prüfschritts nach WCAG 2.1

==== Guideline

* https://www.w3.org/TR/WCAG21/#navigable[Guideline 2.4 Navigable: Provide
  ways to help users navigate, find content, and determine where they are]

==== Success criterion

* https://www.w3.org/TR/WCAG21/#link-purpose-in-context[2.4.4 Link Purpose (In
  Context) (Level A)]

==== Techniques

.General Techniques
* https://www.w3.org/WAI/WCAG21/Techniques/general/G53.html[G53: Identifying
  the purpose of a link using link text combined with the text of the
  enclosing sentence]
* https://www.w3.org/WAI/WCAG21/Techniques/general/G91.html[G91: Providing
  link text that describes the purpose of a link]

==== Failures

* https://www.w3.org/WAI/WCAG21/Techniques/failures/F63.html[F63: Failure of
  Success Criterion 2.4.4 due to providing link context only in content that
  is not related to the link]
* https://www.w3.org/WAI/WCAG21/Techniques/failures/F89.html[F89: Failure of
  2.4.4, 2.4.9 and 4.1.2 due to using null alt on an image where the image is
  the only content in a link]

== Quellen

=== Zweck der Kontextunabhängigkeit

[.BLOCK_LANG_EN]
--
> Assistive technology has the ability to provide users with a list of links that are on the Web page. Link text that is as meaningful as possible will aid users who want to choose from this list of links. Meaningful link text also helps those who wish to tab from link to link. Meaningful links help users choose which links to follow without requiring complicated strategies to understand the page.

https://www.w3.org/WAI/WCAG21/Understanding/link-purpose-in-context.html[
WCAG 2.1, Link Purpose (In Context): Understanding SC 2.4.4]
--

=== Gruppen zusammengehöriger Links

Bei einer Gruppe zusammengehöriger Links kann im ersten Link Ziel oder Zweck
genannt werden und in den folgenden Links unterscheidende Informationen.
Die WCAG 2.1 geben folgendes Beispiel:

[.BLOCK_LANG_EN]
--
> A list of books is available in three formats: HTML, PDF, and mp3 (a recording of a person reading the book). To avoid hearing the title of each book three times (once for each format), the first link for each book is the title of the book, the second link says "PDF" and the third says, "mp3."

https://www.w3.org/WAI/WCAG21/Understanding/link-purpose-in-context.html#examples[
WCAG 2.1, Link Purpose (In Context): Understanding SC 2.4.4: Examples of Success
Criterion 2.4.4]
--

=== Aussagekraft über den Kontext

[.BLOCK_LANG_EN]
--
> Whenever possible, provide link text that identifies the purpose of the link without needing additional context.
> 
> In some situations, authors may want to provide part of the description of the link in logically related text that provides the context for the link.
In this case the user should be able to identify the purpose of the link without moving focus from the link. In other words, they can arrive on a link and find out more about it without losing their place. This can be achieved by putting the description of the link in the same sentence, paragraph, list item, the heading immediately preceding the link, or table cell as the link, or in the table header cell for a link in a data table, because these are directly associated with the link itself.

https://www.w3.org/WAI/WCAG21/Understanding/link-purpose-in-context.html[
WCAG 2.1, Link Purpose (In Context): Understanding SC 2.4.4]
--
