= Prüfschritt 11.2.4.3 Schlüssige Reihenfolge bei der Tastaturbedienung
include::include/author.adoc[]
include::include/attributes.adoc[]

*Hinweis: Dies ist ein Entwurf. Inhalte können sich jederzeit ändern.*

== Was wird geprüft?

Wenn die Software mit der Tastatur bedient wird, soll die Reihenfolge, in der
Links, Formularelemente und Objekte angesteuert werden, schlüssig und
nachvollziehbar sein.

== Warum wird das geprüft?

Die Bedienung soll geräteunabhängig möglich sein. Das bedeutet: Sie muss sowohl mit einem Zeiger (Maus, Touch-Geste) als auch mit der Tastatur
möglich sein. Denn auch andere Spezialgeräte verhalten sich so wie eine Maus oder wie ein Zeiger. Bei Apps soll die Tab-Reihenfolge im Wesentlichen die visuelle Reihenfolge der Bedienelemente abbilden.

Probleme gibt es meistens mit der Tastaturbedienung, denn die Mehrzahl der Nutzer arbeitet mit Touch-Gesten, daher wird oft nur an die gedacht. Auf die Tastaturbedienbarkeit angewiesen sind zum Beispiel viele motorisch eingeschränkte Menschen oder blinde Nutzer.

Durch eine nicht nachvollziehbare Reihenfolge der Bedienelemente kann die Tastaturbedienbarkeit erheblich beeinträchtigt werden.

Wenn in der Ansicht dynamische Elemente wie etwa modale Dialoge, Popup- bzw. Schubladen-Menüs oder Fehlermeldungen vorkommen, muss der Tastaturfokus in diese ersetzt werden. Beim Schließen dieser Elemente muss der Fokus auf das auslösende Element zurückversetzt werden.

=== Zusätzliche Bedarfe von Screenreader-Nutzenden 
Für Nutzende von Sceenreadern, die die Tastaturbediennung einsetzen, gibt es zusätzliche Probleme beim Einsatz dynamisch eingefüger Inhalte. Während solche Änderungen für sehende Nutzer unmittelbar wahrnehmbar sind, werden sie oft von Screenreader-Nutzern gar nicht wahrgenommen, wenn der Fokus nicht in diese Elemente versetzt wird.

Werden durch die Interaktion mit der App weitere Elemente in die Ansicht eingefügt, sollte diese Einfügung unterhalb des auslösenden Elements geschehen,
damit Screenreader auf die hinzugefügten Elemente stoßen und diese ausgeben. Werden Elemente an anderer Stelle, z. B. am unteren Rand der App-Ansicht, eingefügt (das ist oft bei modalen Dialogen der Fall), muss die App dafür sorgen, dass der Fokus dorthin versetzt wird und so auch blinde Nutzer die Änderung mitbekommen.

== Wie wird geprüft?

=== 1. Anwendbarkeit des Prüfschritts

Der Prüfschritt ist anwendbar, wenn die App-Ansicht Links, Formularelemente oder Objekte enthält.

=== 2. Prüfung

. Der Tastatur-Fokus wird mittels Tab-Taste von Steuerelement zu Steuerelement bewegt.
. Wenn es Bereiche oder Elemente gibt, wo der Fokus sich statt mit dem Tabulator über Pfeiltasten bewegen lässt, wird die Reihenfolge mit Pfeiltasten geprüft.
. Ist die Tab-Reihenfolge der Elemente sinnvoll und entspricht im Wesentlichen der visuellen Reihenfolge?
. Falls dynamische Inhalte (Dialoge, Popovers, Menüs) eingefügt werden: Wird der Fokus in den zusätzlichen Inhalt versetzt?
. Ist die Reihenfolge in eingefügten Inhalten sinnvoll?

=== 3. Hinweise

Die Tabulatorreihenfolge sollte im Wesentlichen der visuellen Anordnung auf dem Bildschirm folgen.
Kleinere Abweichungen sind kein Problem, manchmal ist es ja auch gar nicht möglich, aus der Anordnung auf dem Bildschirm eine Reihenfolge zwingend
abzuleiten.

In manchen Apps sind Bedienelemente nicht durchgängig mit dem Tabulator erreichbar: sobsld ein bestimmter Bereich den Fokus erhält, lassen sich Bedienelemente in diesem Bereich mit Pfeiltasten erreichen. Manche Elemente sind visuell erreichbar, wenn der Fokus mit Pfeiltasten wie in einer zweidimensionalen Matrix gezielt zu ihnen bewegt wird. Sie sind jedoch in sequenzieller Nnavigation (Pfeiltasten links und rechts) zu erreichen. Für nicht visuelle Nutzende ist dann nicht nachzuvollziehen, wie Elemente außerhalb dieser sequenziellen Reihenfolge überhaupt zu erreichen sind, selbst wenn sie mit viueller Unterstützung über eine Navigation mit Pfeiltasten mit der Tastatur erreichbar wären.

Die Tabulatorreihenfolge ist schwer nachzuvollziehen, wenn sie über unsichtbare ausführbare Elemente geht.

=== 4. Bewertung

==== Erfüllt:

* Die Reihenfolge, in der Links, Formularelemente und Objekte mit der Tabulatortaste angesteuert werden, ist im Wesentlichen nachvollziehbar und
  schlüssig.

==== Nicht voll erfüllt:

* Die Tabulator-Reihenfolge ist nicht schlüssig, sie weicht ohne nachvollziehbaren Grund von der visuellen Anordnung ab 
* Der Tastaturfokus ist über mehr als drei aufeinanderfolgende Stationen in der App-Ansicht nicht sichtbar
* Nicht alle Bedienelemente werden in sequenzieller Navigation über Tabulator oder Pfeiltasten erreicht
* Der Tastatur-Fokus wird nicht auf eingeblendete Inhalte (Dialoge, Popover, Menüs) versetzt, sondern wandert durch den abgedeckten Hintergrund
  
== Quellen
=== iOS
* Orange Accessibility Guidelines: https://a11y-guidelines.orange.com/en/mobile/ios/development/#focus-an-element[iOS developer guide - focus an element] - Code-Beispiele
* Orange Accessibility Guidelines: https://a11y-guidelines.orange.com/en/mobile/ios/development/#focus-an-element[Modify the focus area of VoiceOver] - Code-Beispiele
* Orange Accessibility Guidelines: https://a11y-guidelines.orange.com/en/mobile/ios/development/#modal-view[Modal view] - Fokus auf Inhalte modaler Dialoge reduzieren - Code-Beispiele
* Appt.org: https://appt.org/en/docs/ios/samples/accessibility-focus[Accessibility focus on iOS] - how to move the focus to modals or popover views.

=== Android
* Orange Accessibility Guidelines: https://a11y-guidelines.orange.com/en/mobile/android/development/focus-navigation/[Android develop - Keyboard navigation & Switch Access]
* Appt.org: https://appt.org/en/docs/android/samples/accessibility-focus[Accessibility focus on Android] - how to move the focus to modals or popover views.


== Einordnung des Prüfschritts

=== Abgrenzung zu anderen Prüfkriterien

* In diesem Prüfschritt wird die Tabreihenfolge geprüft, die grundsätzliche
Erreichbarkeit und Auslösbarkeit von interaktiven Elementen ist Gegenstand von
Prüfschritt
ifdef::env_embedded[11.2.1.1 "Tastaturbedienung".]
ifndef::env_embedded[]
  <<11.2.1.1 Tastaturbedienung.adoc#,11.2.1.1 Tastaturbedienung>>.
endif::env_embedded[]

* Die Sichtbarkeit des Fokus ist Gegenstand von Prüfschritt
ifdef::env_embedded[11.2.4.7 "Aktuelle Position des Fokus deutlich".]
ifndef::env_embedded[]
  <<11.2.4.7 Aktuelle Position des Fokus deutlich.adoc#,11.2.4.7 Aktuelle Position
  des Fokus deutlich>>.
endif::env_embedded[]

* Geprüft wird hier die richtige Position eingeblendeter oder eingefügter
  Inhalte.
  Ob diese Inhalte selbst sinnvoll sind, wird in anderen Prüfkriterien wie
ifdef::env_embedded[11.3.3.3 "Hilfe bei Fehlern""]
ifndef::env_embedded[]
  <<11.3.3.3 Hilfe bei Fehlern.adoc#,11.3.3.3 Hilfe bei Fehlern>>
endif::env_embedded[]
  oder
ifdef::env_embedded[11.2.4.4 "Aussagekräftige Linktexte"]
ifndef::env_embedded[]
  <<11.2.4.4 Aussagekräftige Linktexte.adoc#,11.2.4.4 Aussagekräftige Linktexte>>
endif::env_embedded[]
  geprüft.
  
=== Einordnung des Prüfschritts nach WCAG 2.1

==== Guideline

* https://www.w3.org/TR/WCAG21/#navigable[Guideline 2.4 Navigable: Provide
  ways to help users navigate, find content, and determine where they are]

==== Success criterion

* https://www.w3.org/TR/WCAG21/#focus-order[2.4.3 Focus Order (Level A)]

==== Techniques

.General Techniques
* https://www.w3.org/WAI/WCAG21/Techniques/general/G59.html[G59: Placing the
  interactive elements in an order that follows sequences and relationships
  within the content]

==== Failures

* https://www.w3.org/WAI/WCAG21/Techniques/failures/F44.html[F44: Failure of
  Success Criterion 2.4.3 due to using tabindex to create a tab order that does not preserve meaning and operability]
* https://www.w3.org/WAI/WCAG21/Techniques/failures/F85.html[F85: Failure of
  Success Criterion 2.4.3 due to using dialogs or menus that are not adjacent to their trigger control in the sequential navigation order]
  
== Fragen zu diesem Prüfschritt
=== Unsere App ist auf die mobile Nutzung unterwegs ausgelegt, da hat man doch keine Tastatur. Gilt dann dieser Prüfschritt trotzdem?
Ja, er gilt. Viele Apps für unterwegs werden auch zuhause oder am Arbeitsplatz genutzt, z.B. bei einer App für den öffentlichen Nahverkehr:

* um Reisen vorab zu planen, Wege und Anschlüsse zu recherchieren
* um Meldungen zu Baustellen, Umleitungen oder Verkehrsbehinderungen vorab zu checken
* um nutzerdefinierte Voreinstellungen vorzunehmen (z.B. häufige Ziele oder häufige Routen festlegen)
* um sich zu registrieren oder Profildaten zu ändern

Die Anforderungen an Tastaturnutzbarkeit gelten also generell. Die BITV bzw. die zugrunde liegende EN 301 549 sehen hier keine Ausnahmen vor. 

