= Prüfschritt 11.2.1.4 Tastatur-Kurzbefehle abschaltbar oder anpassbar
include::include/author.adoc[]
include::include/attributes.adoc[]

== Was wird geprüft?

Wenn Apps Tastaturkurzbefehle über Einzeltasten (Buchstaben, Zahlen, Satzzeichen oder Symbole) implementieren, können diese entweder abgeschaltet oder auf eine Tastenkombination mit Modifikator-Tasten umgestellt werden, oder sie sind nur aktiv für bestimmte Schnittstellen-Elemente (Bedienelemente), wenn diese den Fokus haben.

== Warum wird das geprüft?

Tastaturkurzbefehle ohne Modifikatortaste sind für Menschen, die am Computer oder einem mobilen Gerät die Spracheingabe benutzen, häufig problematisch.
Spracheingaben können unerwartet Befehle für Funktionen auslösen, der Nutzungskontext geht dadurch verloren.

== Wie wird geprüft?

=== 1. Anwendbarkeit des Prüfschritts

Der Prüfschritt ist anwendbar für native Apps, die eine Benutzeroberfläche bieten und den Zugriff auf Tastaturen oder ein Tastaturinterface unterstützen. Dies trifft auf die meisten Apps auf den gängigen mobilen Plattformen wie Apples iOS / iPadOS sowie Googles Android zu.

=== 2. Prüfung

. Tastatur über Bluetooth-Kopplung oder USB-Kabel anschließen.
. App mit zu prüfender Ansicht öffnen.
. Sicherzustellen, dass keine Interface-Elemente fokussiert sind.
. Mit Ausnahme der Modifikator- und Steuertasten wie STR, ALT, ENTER, Tab, Pfeiltasten und Funktionstasten F1-F12, nacheinander auf alle Tastaturtasten drücken, d. h. auf alle Nummern- Buchstaben-, Symbol- und Zeichensetzungstasten.
. Die Umschalttaste halten und die gleichen Tasten erneut betätigen.
. Falls einzelne Tasten Funktionen auslösen, prüfen, ob die App Einstellungen bereithält, um diese Tastaturkurzbefehle über Einzeltasten abzuschalten oder auf Tastaturkurzbefehle mit einer Modifikator-Taste zu mappen.

=== 3. Hinweise

Die Anforderung gilt nicht, wenn die Tastaturkurzbefehle nur aktiv sind, sobald bestimmte Interface-Elemente den Fokus haben, etwa ein Auswahllisten-Element bzw. select. Hier dient z.B. das Drücken einer Buchstabentaste zur schnellen Navigation innerhalb der Auswahllisten-Optionen.

=== 4. Bewertung

==== Erfüllt:

* Durch das Drücken der Tasten geschehen keinerlei Änderungen des Inhalts oder des Kontexts.
* Es gibt Tastatur-Kurzbefehle über Einzeltasten, aber diese sind über Einstellungen der App abschaltbar oder auf Tastenkombinationen mit Modifikator-Tasten umstellbar.

== Einordnung des Prüfschritts

=== Einordnung des Prüfschritts nach WCAG 2.1

==== Guideline

* https://www.w3.org/TR/WCAG21/#keyboard-accessible[Guideline 2.1 Keyboard
  Accessible: Make all functionality available from a keyboard]

==== Success criterion

* https://www.w3.org/TR/WCAG21/#character-key-shortcuts[2.1.4 Character Key
  Shortcuts (Level A)]

==== Sufficient Techniques

* https://www.w3.org/WAI/WCAG21/Techniques/general/G217[G217: Providing a
  mechanism to allow users to remap or turn off character key shortcuts]

==== Failures

* https://www.w3.org/WAI/WCAG21/Techniques/failures/F99[F99: Failure of
  Success Criterion 2.1.4 due to implementing character key shortcuts that cannot be turned off or remapped]


== Quellen

* https://www.w3.org/WAI/WCAG21/Understanding/character-key-shortcuts.html[
  Understanding Success Criterion 2.1.4: Character Key Shortcuts]
  (zur Zeit nur auf Englisch verfügbar)
