= Prüfschritt 11.2.4.6 Überschriften und Beschriftungen (Labels)
include::include/author.adoc[]
include::include/attributes.adoc[]

== Was wird geprüft?

Überschriften beschreiben den folgenden Inhalt, Beschriftungen sind aussagekräftig.

== Warum wird das geprüft?

Visuell werden Inhalte von App-Ansichten durch Überschriften strukturiert. Dank dieser Strukturierung wissen Nutzende, was zusammengehört, können die
Inhalte leicht überblicken und gezielt auf Inhalte zugreifen, die sie interessieren.

Wenn Formularelemente aussagekräftig beschriftet sind, wissen Nutzende, was eingegeben werden soll oder ausgewählt werden kann. Zusätzliche Hinweise zum Eingabeformat helfen, Fehler zu vermeiden.

== Wie wird geprüft?

=== 1. Anwendbarkeit des Prüfschritts

Der Prüfschritt ist anwendbar, wenn es in der App-Ansicht Inhalte gibt, die durch Überschriften strukturiert werden können und wenn die Ansicht
Formularelemente enthält.

=== 2. Prüfung

. App mit zu prüfender Ansicht starten.
. Prüfen, ob Überschriften im Zusammenhang mit dem folgenden Text aussagekräftig sind.
. Prüfen, ob Beschriftungen von Formularelementen aussagekräftig sind.
. Wenn Formularelemente eine Gruppenbeschriftung haben: Sind Gruppenbeschriftung und Beschriftung des Formularelements im Zusammenhang aussagekräftig?

=== 3. Hinweise
==== 3.1 Hinweise zu Fachausdrücken
Besonders in fachspezifischen Apps gibt es Beschriftungen und Überschriften mit Fachausdrücken, Abkürzungen oder Codes, die nicht gemeinverständlich sind, aber der Zielgruppe bekannt sind. Die Verwendung diese Fachausdrücke bringt Vorteile mit (Wiedererkennbarkeit, Präzision, Kürze), kann aber auch dazu führen, dass sie nicht allgemein aussagekräftig sind: sie müssen erlernt werden. Das ist bei Fachanwendungen vertretbar und sollte nicht zu einer negativen Bewertung führen.

==== 3.2 Hinweise für die Teamprüfung
Mit aktiviertem Screenreader können mittels der horizontalen Wischgeste Überschriften und Formularelemente mit ihren Beschriftungen durchlaufen werden. Häufig sind in Apps visuelle Überschriften nicht programmatisch als Überschriften, sondern als einfacher Text umgesetzt. Es ist sogar möglich, diese Überschriften überhaupt nicht vom Screenreader erreicht und ausgegeben werden können. Auch für solche Überschriften wird die Aussagekraft in diesem Prüfschitt beurteilt. Mängel der programmatischen Emittelbarkeit werden nicht hier, sondern in Prüfschritt 11.1.3.1a "Strukturelemente für Überschriften" bewertet.

Blinde Prüfende sollten beim Durchlaufen der Ansichten zusammen mit der sehenden Assistenz festhalten, welche Inhalte visuell als Überschriften umgesetzt sind und demnach auf Aussagekraft hin zu prüfen sind. Sind Inhalte programmatisch als Überschrift umgesetzt, die visuell gar nicht als Überschrift hervorgehoben sind, ist dieser Mangel nicht hier, sondern in Prüfschritt 11.1.3.1a "Strukturelemente für Überschriften" zu bewerten.

Ähnliches gilt für Beschriftungen von Formular-Elementen. Häufig sind Beschriftungen nicht programmatisch den Formularelementen zugeordnet, sondern stehen einfach davor oder danach. Dann fokussiert die Wischgeste die Beschriftung unabhängig vom Formularelement. Das Formularelement hat dann entweder keine programmatisch ermittelbare Beschriftung oder diese wiederholt die getrennte Beschriftung (oder ist ggf. auch abweichend). Solche Mängel sind Gegenstand des Prüfschritts 11.1.3.1d "Beschriftung von Formularelementen programmatisch ermittelbar". In diesem Prüfschritt wird lediglich die Aussagekraft beurteilt.

=== 4. Bewertung
==== Erfüllt:

* Überschriften passen zu den ihnen folgenden Inhalten, Beschriftungen von Formularelementen sind aussagekräftig.

==== Teilweise erfüllt oder schlechter:
* Überschriften oder Beschriftungen sind obskur oder schwer verständlich (z.B. unübersetzt)
* Durch Flüchtigkeits- oder Kopierfehler haben Formularelemente unrichtige, nicht zutreffende Beschriftungen
* Bestimmte Eingabeformate sind für valide Eingaben erforderlich, werden aber nicht über zusätzliche Beschriftungen vermittelt

== Einordnung des Prüfschritts

=== Abgrenzung von anderen Prüfschritten

* In diesem Prüfschritt geht es um die Aussagekraft von Überschriften und
  Beschriftungen.
  Die programmatische Ermittelbarkeit durch wssistive Technologien wid in den
  Prüfschritten
ifdef::env_embedded[11.1.3.1a "Strukturelemente für Überschriften"]
ifndef::env_embedded[]
  <<11.1.3.1a Strukturelemente für Überschriften.adoc#,11.1.3.1a Strukturelemente
  für Überschriften>>
endif::env_embedded[]
  und
ifdef::env_embedded[11.1.3.1d "Beschriftung von Formularelementen programmatisch ermittelbar"]
ifndef::env_embedded[]
  <<11.1.3.1d Beschriftung von Formularelementen programmatisch ermittelbar.adoc#,
  11.1.3.1d Beschriftung von Formularelementen programmatisch ermittelbar>>
endif::env_embedded[]
  geprüft.

=== Einordnung des Prüfschritts nach WCAG 2.1

==== Guideline

* https://www.w3.org/TR/WCAG21/#navigable[Guideline 2.4 Navigable: Provide
  ways to help users navigate, find content, and determine where they are]

==== Success criterion

* https://www.w3.org/TR/WCAG21/#headings-and-labels[2.4.6 Headings and Labels
  (Level A)]

==== Techniques

.General Techniques
* https://www.w3.org/WAI/WCAG21/Techniques/general/G130.html[G130: Providing
  descriptive headings]
* https://www.w3.org/WAI/WCAG21/Techniques/general/G131.html[G131: Providing
  descriptive labels]
