= Prüfschritt 11.2.1.1 Tastaturbedienung
include::include/author.adoc[]
include::include/attributes.adoc[]

== Was wird geprüft?

Die App soll auch ohne Maus- und Touch-Eingaben, also ausschließlich mit der Tastatur zu benutzen sein.

== Warum wird das geprüft?

Die Bedienung der App soll geräteunabhängig möglich sein. Das bedeutet: Sie muss mit der Tastatur möglich sein. Denn auch andere Hilfsmittel oder Eingabemethoden (etwa Spracheingabe) brauchen die Tastatur bzw. setzten die Tastaturbedienbarkeit voraus. Auf die Tastaturbedienbarkeit angewiesen sind zum Beispiel viele motorisch eingeschränkte oder blinde Menschen.

Bei Apps gibt es häufig Probleme bei der Tastaturbedienung, denn die Mehrzahl der Nutzenden von iOS / iPadOS und Android arbeitet mit Touch-Eingaben, daher wird oft nur an diese gedacht.

== Wie wird geprüft?

=== 1. Anwendbarkeit des Prüfschritts

Der Prüfschritt ist anwendbar für native Apps, die eine Benutzeroberfläche bieten und den Zugriff auf Tastaturen oder ein Tastaturinterface unterstützen.
Dies trifft auf die meisten Apps auf den gängigen mobilen Plattformen wie Apples iOS / iPadOS sowie Googles Android zu.

=== 2. Prüfung

. Tastatur über Bluetooth-Kopplung oder USB-Kabel anschließen.
. App mit zu prüfender Ansicht öffnen.
. Mit der Tabulatortaste die Links und Formularelemente durchgehen. Wo sich Elemente nicht mit dem Tabulator erreichen lassen, prüfen, ob sie über die Pfeiltasten erreichbar sind.
. Prüfen, ob alle wesentlichen Funktionen über die Tastatur erreicht und aktiviert werden können. In der Regel heißt das, das Elemente fokussiert und dann über die Eingabe- oder Leertaste aktiviert werden können. Wo Elemente nicht erreichbar oder aktivierbar sind, stehen äquivalente Wege zum Auslösen der Funktion über die Tastatur zur Verfügung.
. Falls die Ansicht Elemente enthält, die wie Bedienelemente aussehen, jedoch nicht über Tabulatortaste oder Pfeiltasten angesteuert werden, prüfen, ob diese Elemente auf Touch-Eingaben reagieren (zum Beispiel Navigation zu anderen Ansichten, Funktionsaufrufe, Vergrößerung, Einblenden von weiteren Inhalten).
. Falls die Ansicht scrollbare Bereiche enthält, sollen nicht sichtbare Inhalte dieser Bereiche auch über die Tastatur erreichbar sein.

=== 3. Hinweise

==== 3.1 Allgemeine Hinweise

Unwesentlich können zum Beispiel Funktionen sein, die schon von der Plattform (Betriebssystem) selbst angeboten werden (beispielsweise "Fenster schließen").

Die prüfende Person muss mit der Funktionsweise der eingesetzten Browser und Betriebssysteme vertraut sein, sie muss wissen, welche Tasten und Tastenkombinationen für die Tastaturbedienung vorgesehen sind.

Die Nutzung per Tastatur muss nicht genau der Nutzung per Touch-Eingabe entsprechen. Es ist beispielsweise kein Mangel, wenn per Maus über Ausklappmenüs in einem Schritt tiefe Links aufgerufen werden können, per Tastatur aber für den Aufruf der betreffenden Seiten/Ansichten mehrere Schritte erforderlich sind.

Für diesen Prüfschritt spielt die Reihenfolge, in der interaktive Elemente und Formularelemente angesteuert werden, keine Rolle. 

Manche Elemente sind nur in nicht-linearer Navigation, z.B. durch eine Abfolge von Pfeiltasten erreichbar. So ist ein Element oben rechts von der aktuellen Fokusposition gegebnenfalls. nur fokussierbar, wenn man erst zweimal die Pfeiltaste nach oben und dann die nach rechts betätigt. Dieser Prüfschritt 11.2.1.1 ist dann zwar erfüllt, nicht jedoch der Prüfschritt 11.2.4.3 "Schlüssige Reihenfolge bei der Tastaturbedienung", denn der Weg zum Erreichen des prinzipiell fokussierbaren Elements ist nur zwei-dimensional und visuell verständlich, nicht linear.

==== 3.2 Hinweis zu Drag-and-Drop

Für wichtige Bedienfunktionen, die mittels Drag-and-Drop bedienbar sind, müssen auch tastaturnutzbare Alternativen angeboten werden.

=== 4. Bewertung

==== Erfüllt:

* Alle wesentlichen Inhalte und Funktionen sind im Prinzip mit der Tastatur erreichbar und bedienbar.

==== Nicht erfüllt:

* Wesentliche Inhalte und Funktionen sind mit der Tastatur nicht erreichbar oder nicht bedienbar.

== Einordnung des Prüfschritts

=== Abgrenzung zu anderen Prüfkriterien

Dieser Prüfschritt betrifft die Auslösbarkeit von Funktionen und Links auch über die Tastatur.

* Tastaturfallen sind Gegenstand von Prüfschritt
ifdef::env_embedded[11.2.1.2 "Keine Tastaturfalle"]
ifndef::env_embedded[]
  <<11.2.1.2 Keine Tastaturfalle.adoc#,11.2.1.2 Keine Tastaturfalle>>
endif::env_embedded[]
* Die Fokushervorhebung ist Gegenstand von Prüfschritt
ifdef::env_embedded[11.2.4.7 "Aktuelle Position des Fokus deutlich"]
ifndef::env_embedded[]
  <<11.2.4.7 Aktuelle Position des Fokus deutlich.adoc#,11.2.4.7 Aktuelle Position
  des Fokus deutlich>>
endif::env_embedded[]
* Die sinnvolle Fokusreihenfolge wird in
ifdef::env_embedded[11.2.4.3 "Schlüssige Reihenfolge bei der Tastaturbedienung"]
ifndef::env_embedded[]
<<11.2.4.3 Schlüssige Reihenfolge bei der Tastaturbedienung.adoc#,11.2.4.3
Schlüssige Reihenfolge bei der Tastaturbedienung>>
endif::env_embedded[]
bewertet

=== Einordnung des Prüfschritts nach WCAG 2.1

==== Guideline

* https://www.w3.org/TR/WCAG21/#keyboard-accessible[Guideline 2.1 Keyboard
  Accessible: Make all functionality available from a keyboard.]

==== Success criteria

* https://www.w3.org/TR/WCAG21/#keyboard[2.1.1 Keyboard (Level A)]

==== Techniques

.General Techniques
* https://www.w3.org/WAI/WCAG21/Techniques/general/G90.html[G90: Providing
  keyboard-triggered event handlers]
* https://www.w3.org/WAI/WCAG21/Techniques/general/G202.html[G202: Ensuring
  keyboard control for all functionality]

==== Failures

* https://www.w3.org/WAI/WCAG21/Techniques/failures/F42.html[F42: Failure of
  Success Criterion 1.3.1 and 2.1.1 due to using scripting events to emulate links in a way that is not programmatically determinable]
* https://www.w3.org/WAI/WCAG21/Techniques/failures/F54.html[F54: Failure of
  Success Criterion 2.1.1 due to using only pointing-device-specific event
  handlers (including gesture) for a function]
* https://www.w3.org/WAI/WCAG21/Techniques/failures/F55.html[F55: Failure of
  Success Criteria 2.1.1, 2.4.7, and 3.2.1 due to using script to remove focus
  when focus is received]

== Quellen

=== Die WCAG 2.1 zur Tastaturbedienbarkeit

[.BLOCK_LANG_EN]
--
If all functionality can be achieved using the keyboard, it can be
accomplished by keyboard users, by speech input (which creates keyboard
input), by mouse (using on-screen keyboards), and by a wide variety of
assistive technologies that create simulated keystrokes as their output.
No other input form has this flexibility or is universally supported and
operable by people with different disabilities, as long as the keyboard input
is not time-dependent.

Note that providing universal keyboard input does not mean that other types of
input should not be supported.
Optimized speech input, optimized mouse/pointer input, etc., are also good.
The key is to provide keyboard input and control as well.

Some devices do not have native keyboards for example, a PDA or cell phone.
If these devices have a Web browsing capability, however, they will have some
means of generating text or "keystrokes."
This guideline uses the term "keyboard interface" to acknowledge that Web
content should be controlled from keystrokes that may come from a
keyboard, keyboard emulator, or other hardware or software that generates
keyboard or text input.
--

(https://www.w3.org/WAI/WCAG21/Understanding/keyboard.html[Keyboard
Accessible: Understanding Guideline 2.1])

=== Weitere Ressourcen

[BLOCK_LANG_EN]
* Android Developer:
  https://developer.android.com/training/keyboard-input/navigation[Support
  keyboard navigation]
