= Prüfschritt 2.4.4a Aussagekräftige Linktexte
include::include/author.adoc[]
include::include/attributes.adoc[]

== Was wird geprüft?

Ziel oder Zweck des Links sollen aus dem Linktext hervorgehen oder aus dem
direkten Kontext des Links ermittelbar sein.

Falls Links nicht auf andere Ansichten der App verweisen, soll der Link über
das Dateiformat des Zieldokuments informieren.

Wenn Links in Anwendungen nicht erwartbar auf Ressourcen außerhalb der
Software verweisen, sollte der Linktext auch hier einen zusätzlichen Hinweis
auf das Ziel(format) geben.
Z. B. „öffnet in Browser“ etc.

== Warum wird das geprüft?

Blinde Nutzer, die von Link zu Link tabben / navigieren, bekommen die
Linktexte vorgelesen und können bei aussagekräftigen Linktexten leicht
entscheiden, ob sie einem Link folgen möchten.

Falls der Linktext selbst nicht aussagekräftig ist, soll der unmittelbare
Kontext für Screenreader-Nutzer wenigstens leicht ermittelbar sein.

Screenreader bieten die Möglichkeit der Auflistung bzw.
direkter Anspringbarkeit sämtlicher Links der App-Ansicht und damit auch
einen schnellen Überblick, selbst wenn die Software ansonsten schlecht
zugänglich ist.
Diese Technik funktioniert allerdings nicht, wenn alle Linktexte gleich sind
und nicht ausreichend Auskunft über das Linkziel geben.

Für Angebote außerhalb der App (zum Beispiel PDF- oder Word-Dokumente)
benötigt der Benutzer zusätzliche Apps oder Plugins, die aber nicht jeder
installiert hat.
Manche Apps arbeiten schlecht mit Screenreadern oder anderen Hilfsanwendungen
zusammen, manche Dateiformate sind nicht oder nur schlecht zugänglich.
Für viele Benutzer ist es wichtig zu wissen, in welchem Format
Informationen angeboten werden, bevor sie einen Link aktivieren.

Ein weiterer Grund, weshalb die Vorab-Information über den Typ des Links
wichtig ist: Der Benutzer weiß dann, was auf ihn zukommt.
Er ist nicht überrascht oder irritiert, wenn plötzlich Funktionen nicht mehr
vorhanden sind oder der E-Mail-Client geöffnet wird.

== Wie wird geprüft?

=== Anwendbarkeit des Prüfschritts

Der Prüfschritt ist anwendbar, wenn die Software Links enthält.

=== Prüfung

==== Prüfung von Linktexten

. Anwendung mit zu testender Ansicht öffnen.
. Prüfen, ob die Linktexte aussagekräftig sind, das heißt, im Linktext oder
  im Kontext eine Auskunft über Ziel oder Zweck des Links geben.
. Für Links, deren sichtbarer Linktext allein nicht aussagekräftig ist
  (z. B. "mehr" oder "weiterlesen"), prüfen, ob der Linktext durch eine der
  folgenden Möglichkeiten im Kontext sinnvoll ergänzt wird:
+
  * durch einen verständlichen Link am Beginn der Software-Ansicht, der
    Linktexte auf der Seite erweitert
  * durch den Alternativtext einer verlinkten Grafik, entsprechend Software
    mit Screenreader testen
  * durch den Text der umschließenden Tabellenzelle und der dazugehörigen
    Überschriftenzellen, entsprechend Software mit Screenreader testen
  * durch den Text der vorangehenden Überschrift, entsprechend Software mit
    Screenreader testen

==== Prüfung von Links auf andere Dateiformate

Bei der Prüfung von Software müssen die Links stichprobenartig auf externe
Ressourcen wie PDF-Dateien geprüft werden.
hier muss zusätzlich geprüft werden, ob im Kontext des Links ein Hinweis auf
das Ziel(format) gegeben wird z. B. mittels PDF-Symbols oder Überschriften,
die das Ziel eindeutig kennzeichnen.

=== Hinweise

Bei verlinkten Grafiken ist der Linktext der Wert des Alternativtextes

Der Linktext kann auch aus dem Alternativtext einer oder mehrerer Grafiken und
einfachem Text zusammengesetzt sein.

Nicht aussagekräftige Links wie "mehr..", "weiter", "etc." im letzten Element
einer Liste werden nur akzeptiert, wenn die Bedeutung klar aus dem Kontext der
Auflistung hervorgeht.

Bei Software kann mit aktiviertem Screenreader geprüft werden, was dieser bei
verlinkten Grafiken ausgibt.

=== Bewertung

*Erfüllt:*

* Alle Links benennen im Linktext oder im direkten Kontext Linkziel oder
  Linkzweck.
* Alle Links auf Angebote / Ressourcen außerhalb der App geben Auskunft über
  das Dateiformat oder das externe Ziel. (öffnet im Browser, …)

*Nicht voll erfüllt:*

* Ziel oder Zweck des Links ist nicht eindeutig oder missverständlich.

== Einordnung des Prüfschritts

=== Abgrenzung zu anderen Prüfkriterien

Die Aussaagekraft der Alternativtexte für Grafiken wird geprüft in:

* Prüfschritt
ifdef::env_embedded[1.1.1a "Alternativtexte für Bedienelemente"]
ifndef::env_embedded[]
<<1.1.1a Alternativtexte für Bedienelemente.adoc#,1.1.1a Alternativtexte für
Bedienelemente>>
endif::env_embedded[]

In diesem Prüfschritt wird nur geprüft, ob die Information über das
Dateiformat überhaupt vorhanden ist.
Das ist der Fall, wenn das Dateiformat in einer Grafik, im Linktext oder im
accessible name des Elements angegeben wird.

Nicht geprüft wird, ob die Information auch gut zugänglich ist.
Dafür reicht die alleinige Anzeige als Grafik nicht aus.
Wenn das Dateiformat mit einer Grafik angezeigt wird, muss geprüft werden, ob
diese Information auch als Text verfügbar ist.

* Alternativer Text für blinde Nutzer:
  Prüfschritt
  <<1.1.1a Alternativtexte für Bedienelemente.adoc#,1.1.1a Alternativtexte für
  Bedienelemente>>

=== Einordnung des Prüfschritts nach WCAG 2.1

==== Guideline

* https://www.w3.org/TR/WCAG21/#navigable[Guideline 2.4 Navigable: Provide
  ways to help users navigate, find content, and determine where they are]

==== Success criterion

* https://www.w3.org/TR/WCAG21/#link-purpose-in-context[2.4.4 Link Purpose (In
  Context) (Level A)]

==== Techniques

.General Techniques
* https://www.w3.org/WAI/WCAG21/Techniques/general/G53.html[G53: Identifying
  the purpose of a link using link text combined with the text of the
  enclosing sentence]
* https://www.w3.org/WAI/WCAG21/Techniques/general/G91.html[G91: Providing
  link text that describes the purpose of a link]

==== Failures

* https://www.w3.org/WAI/WCAG21/Techniques/failures/F63.html[F63: Failure of
  Success Criterion 2.4.4 due to providing link context only in content that
  is not related to the link]
* https://www.w3.org/WAI/WCAG21/Techniques/failures/F89.html[F89: Failure of
  2.4.4, 2.4.9 and 4.1.2 due to using null alt on an image where the image is
  the only content in a link]

== Quellen

=== Zweck der Kontextunabhängigkeit

[.BLOCK_LANG_EN]
--
Assistive technology has the ability to provide users with a list of links
that are on the Web page.
Link text that is as meaningful as possible will aid users who want to choose
from this list of links.
Meaningful link text also helps those who wish to tab from link to link.
Meaningful links help users choose which links to follow without requiring
complicated strategies to understand the page.
--

Quelle:
https://www.w3.org/WAI/WCAG21/Understanding/link-purpose-in-context.html[
Link Purpose (In Context): Understanding SC 2.4.4]

=== Gruppen zusammengehöriger Links

Bei einer Gruppe zusammengehöriger Links kann im ersten Link Ziel oder Zweck
genannt werden und in den folgenden Links unterscheidende Informationen.
Die WCAG 2.1 geben folgendes Beispiel:

[.BLOCK_LANG_EN]
A list of books is available in three formats: HTML, PDF, and mp3 (a recording
of a person reading the book).
To avoid hearing the title of each book three times (once for each format),
the first link for each book is the title of the book, the second link says
"PDF" and the third says, "mp3."

Quelle:
https://www.w3.org/WAI/WCAG21/Understanding/link-purpose-in-context.html#examples[
Link Purpose (In Context): Understanding SC 2.4.4: Examples of Success
Criterion 2.4.4]

=== Aussagekraft über den Kontext

[.BLOCK_LANG_EN]
--
Whenever possible, provide link text that identifies the purpose of the link
without needing additional context.

In some situations, authors may want to provide part of the description of the
link in logically related text that provides the context for the link.
In this case the user should be able to identify the purpose of the link
without moving focus from the link.
In other words, they can arrive on a link and find out more about it without
losing their place.
This can be achieved by putting the description of the link in the same
sentence, paragraph, list item, the heading immediately preceding the link, or
table cell as the link, or in the table header cell for a link in a data
table, because these are directly associated with the link itself.
--

Quelle:
https://www.w3.org/WAI/WCAG21/Understanding/link-purpose-in-context.html[
Link Purpose (In Context): Understanding SC 2.4.4]
