= Prüfschritt 11.2.4.7 Fokus sichtbar
include::include/author.adoc[]
include::include/attributes.adoc[]

== Was wird geprüft?

Werden Bedienelementen mit der Tastatur fokussiert, 
dann soll sich der Tastaturfokus-Indikator deutlich vom Hintergrund abheben (mindestens 3:1 Kontrastabstand).
Der Fokus-Indikator muss außerdem einen Kontrastunterschied von mindestens 3:1 zwischen fokussiertem und nicht fokussiertem Zustand haben. 
Meist ist das einfach der Kontrast zwischen dem Fokus-Indikator und dem Hintergrund. 
Wenn jedoch die Fokussierung durch die Änderung der Farbe einer Schaltfläche angezeigt wird, 
ist es der Kontrast zwischen der Farbe der Fläche im fokussierten und im nicht fokussierten Zustand. 

Versteckte Sprunglinks sollen bei Fokuserhalt eingeblendet werden.

== Warum wird das geprüft?

Für Tastaturbenutzende ist es wichtig, zu sehen, wo sich der Tastaturfokus gerade befindet, 
welches Bedienelement also ausgelöst wird, wenn es aktiviert wird (z.B. über ENTER oder Leertaste) 
oder welches Element Ausgangspunkt einer Pfeiltasten-Auswahl wird (etwa bei tab panels oder Auswahllisten).

Wenn Apps allein durch die Tastatur bedient werden, 
muss das fokussierte Bedienelement für den Nutzende deutlich hervorgehoben sein. 
Eine Tastaturbedienung ist für visuelle Nutzer sonst kaum möglich.
Apps haben in den Standardeinstellungen eine zu schwache Fokushervorhebung. 


Die von mobilen Betriebssystemen vorgesehene Kennzeichnung des Tastaturfokus ist oft nicht gut sichtbar:

=== iOS
* Die Standard-Hervorhebung von über Tabulator erreichbaren Bereichen ist recht gut (deutlicher farbiger Rahmen),
bei über Pfeiltasten erreichbaren Einträgen innerhalb fokussierter Bereiche ist die Hervorhebung aber schlecht:
hellblau auf weiß mit einem sehr geringen Kontrast von nur 1,2:1. 
* In den Bedienungshilfen-Einstellungen von iOS lässt sich jedoch unter "Tastaturen und Texteingabe" > "Tastatursteuerung" die Option "Hoher Kontrast" einstellen. 
Damit werden alle Elemente, die überhaupt den Tastaturfokus bekommen, sehr deulich über dicke schwarze Umrandung hervorgehoben. 

=== Android
* Die Standard-Hervrhebung ist hellgrau auf weiß oder ein leichte Abdunkelung auf Elementen mit egenem farbigen Hintergrund. Das Resultat ist ein sehr geringer Kontrast von etwa 1,2:1.

Der Kontrast zum nichtaktivierten Zustand des Elements sollte mindestens 3:1 betragen. Diese wäre für nicht native Foushervorhebung (etwa wenn ein Entwicker-definierter Farbwechsel bei Fokussierung von Elementen stattfindet) bei mindestens 3:1 liegen. Die native, von Entwicklerin unveränderte Tastaturfokushervorhebung fällt dagegen unter eine Ausnahme im Erfolgskriterium 1.4.11 (Nicht-Text Kontrast) für native Elemente: "except for inactive components or where the appearance of the component is determined by the user agent and not modified by the author".

Es wid also hier nur geprüft, ob überhaupt eine Fokushervorhebung bei Fokuserhalt sichtbar ist - nicht, ob diese ausreichend kontrastreich ist. Die Bewertung des Fokuskontrastes von entwicker-definierten Fokushervorhebungen fällt unter den Prüfschritt 11.1.4.11 Nicht-Text Kontrast.


== Wie wird geprüft?

=== 1. Anwendbarkeit des Prüfschritts

Der Prüfschritt ist anwendbar, wenn die App-Ansicht interaktive Elemente enthält.

=== 2. Prüfung

. Tastatur über das Andocken einer Tastatur an ein Tablet
oder Verbindung über Bluetooth-Kopplung oder USB-Kabel anschließen.
. Zu prüfende Ansicht der App öffnen.
. Mit der Tabulatortaste zu allen interaktiven Elementen navigieren.
Wo diese weitere Auswahlen zulassen, etwa bei Tabpanels, Menüs oder Auswahllisten, 
mit den Pfeiltasten oder ggf. dem Tabulator zu Tabs bzw. Optionen navigieren.
. Prüfen, ob alle Elemente mit grafischen Veränderungen auf den Fokus reagieren 
(zum Beispiel mit Farbwechseln, Unterstreichungen oder eingeblendeten Symbolen). 
Versteckte Sprunglinks sollen bei Fokuserhalt eingeblendet werden.

=== 3. Hinweise
==== 3.1 Allgemeine Hinweise
* Es kann davon ausgegangen werden, dass sehbehinderte Tastaturnutzende betriebssystemseitige Einstellungen zu verbesserten Darstellung des Tastaturfokus (wo vorhanden)  nutzen, wenn die Standardhervorhebung für sie nicht ausreichend ist. In iOS wird die Option "Hoher Kontrast" an der gleichen Stelle geboten, wo überhaupt die Tastatursteuerung aktiviert wird.

==== 3.1  Hinweise für die Team-Prüfung
Der Screenreader-Fokus sollte bei der Beurteilung der Tastaturfokus-Hervorhebung nicht berücksichtigt werden. Die Prüfung erfolgt mit verbundener Tastatur und ausgeschaltetem Screenreader.

=== 4. Bewertung

==== Erfüllt:
* Wird nur die native Fokushervorhebung genutzt, ist der Prüfschritt auch erfüllt, wenn die Hervorhebung schwach ist (z.B. hellgraue oder hellblaue Einfärbung), der Komntrast also unter 3:1 liegt.
* Wird ein Entwickler-defineirte Hervorhaebung (etw aÄnderugn der Fabe bei Fokuserhalt) eongesetzt, soll der Kontrast zum Hintergrund und zum nicht fokussierten Zustand mindestens 3:1 betragen. Bewertet wird dies im Prüfdschritt 11.1.4.11 Nicht-Text Kontrast.

==== Nicht erfüllt
* Der Prüfschritt ist nicht erfüllt, wenn überhaupt kein Tastaturfokus sichtbar ist. 
Dann ist eventuell auch Prüfschritt
ifdef::env_embedded[11.2.1.1 "Tastaturbedienung"]
ifndef::env_embedded[]
  <<11.2.1.1 Tastaturbedienung.adoc#,11.2.1.1 Tastaturbedienung>>
endif::env_embedded[]
nicht erfüllt.
  
== Quellen
=== Allgemein
* Appt.org: https://appt.org/en/guidelines/wcag/success-criterion-2-4-7#add-accessibility-focus-indicator[Focus Visible: Add accessibility focus indicator] (mehrere Entwicklungsumgebungen)

=== iOS
* Appt.org: https://appt.org/en/docs/ios/samples/accessibility-focus-indicator[Accessibility focus indicator on iOS]

=== Android
* Appt.org: https://appt.org/en/docs/android/samples/accessibility-focus-indicator[Accessibility focus indicator on Android]
* Android ViewUI: https://github.com/cvs-health/android-view-accessibility-techniques/blob/0ffd2aad8f8eada9893295ac47cc9ee9bf21372d/doc/dynamicbehaviors/CustomFocusIndicators.md#L4[Custom Focus Indicators]
* Android Compose: https://github.com/cvs-health/android-compose-accessibility-techniques/blob/main/doc/interactions/CustomFocusIndicators.md[Custom Focus Indicators]

== Einordnung des Prüfschritts

=== Einordnung des Prüfschritts nach WCAG 2.1

==== Guideline

* https://www.w3.org/TR/WCAG21/#navigable[Guideline 2.4 Navigable: Provide
  ways to help users navigate, find content, and determine where they are]

==== Success criteria

* https://www.w3.org/TR/WCAG21/#focus-visible[2.4.7 Focus Visible (Level AA)]
* https://www.w3.org/TR/WCAG21/#non-text-contrast[1.4.11 Non-Text Contrast
  (Level AA)]

==== Techniques

===== General Techniques

* https://www.w3.org/WAI/WCAG21/Techniques/general/G149.html[G149: Using user
  interface components that are highlighted by the user agent when they
  receive focus]
* https://www.w3.org/WAI/WCAG21/Techniques/general/G165.html[G165: Using the
  default focus indicator for the platform so that high visibility default
  focus indicators will carry over]
* https://www.w3.org/WAI/WCAG21/Techniques/general/G195.html[G195: Using an
  author-supplied, highly visible focus indicator]

===== Failures

* https://www.w3.org/WAI/WCAG21/Techniques/failures/F55.html[F55: Failure of
  Success Criteria 2.1.1, 2.4.7, and 3.2.1 due to using script to remove focus
  when focus is received]
* https://www.w3.org/WAI/WCAG21/Techniques/failures/F78.html[F78: Failure of
  Success Criterion 2.4.7 due to styling element outlines and borders in a way
  that removes or renders non-visible the visual focus indicator]

== Fragen zu diesem Prüfschritt

=== Ist die Anzeige des Fokus nicht Sache des Betriebssystems?

Alle Betriebssysteme zeigen dem Tastaturnutzer in irgendeiner Weise, wo der
Fokus ist, wenn diese Anzeige nicht aktiv unterdrückt wird.

Dennoch ist die Anzeige des Fokus (leider) nicht allein Sache des Betriebssystems. Bei den mobilen Betriebssystmen ist die Standard.Fokushervorhebung nicht kontrastreich genug und für Menschen mit Sehbehinderungen nicht oder nur schlecht wahrnwehmbar.

Die App kann festlegen, wie die Fokushervorhebung aussehen soll. Der Fokus muss für Tastaturnutzer gut sichtbar sein.

=== Mit angeschaltetem Screenreader ist der Fokus gut. Reicht das nicht aus?
Die WCAG-Anforderung sagt tatsächlich "Any keyboard operable user interface has a mode of operation where the keyboard focus indicator is visible." Lange Zeit war bei iOS die Tastaturbedienung sogar nur möglich, wenn VoiceOver aktiviert (und ggf. stummgeschaltet) war.  VoiceOver und Talkback sind spezielle Hilfsmittel für Menschen, die eine akustische Ausgabe brauchen, und anderen Menschen meist nicht bekannt. Sie sind nicht als allgemein verfügbarer Nutzungsmodus für Tastaturnutzende zu betrachten.

=== Unsere App ist auf die mobile Nutzung unterwegs ausgelegt, da hat man doch keine Tastatur. Gilt dann dieser Prüfschritt trotzdem?
Ja, er gilt. Viele Apps für unterwegs werden auch zuhause oder am Arbeitsplatz genutzt, z.B. bei einer App für den öffentlichen Nahverkehr:

* um Reisen vorab zu planen, Wege und Anschlüsse zu recherchieren
* um Meldungen zu Baustellen, Umleitungen oder Verkehrsbehinderungen vorab zu checken
* um nutzerdefinierte Voreinstellungen vorzunehmen (z.B. häufige Ziele oder häufige Routen festlegen)
* um sich zu registrieren oder Profildaten zu ändern

Die Anforderungen an Tastaturnutzbarkeit gelten also generell. Die BITV bzw. die zugrunde liegende EN 301 549 sehen hier keine Ausnahmen vor. 
