= Prüfschritt 11.2.2.1 Zeitbegrenzungen anpassbar
include::include/author.adoc[]
include::include/attributes.adoc[]

*Hinweis: Dies ist ein Entwurf. Inhalte können sich jederzeit ändern.*

== Was wird geprüft?

App-Ansichten werden ohne Zeitbegrenzung angezeigt, die Zeitbegrenzung ist abschaltbar, oder sie kann verlängert werden. 

Dies betrifft etwa:

* zeitbegrenzte Dialoge, welche Nutzer zu Entscheidungen auffordern
* Online-Transaktionen mit begrenzter Session-Dauer und automatischem Ausloggen bei längerer Inaktivität
* das automatische Neu-Laden von Inhalten oder die zeitverzögerte Weiterleitung zu einer anderen Ansicht

Für jedes von der App festgelegte Zeitlimit gilt mindestens eine der folgenden Bedingungen:

* *Ausschalten:* Der Benutzer kann das Zeitlimit ausschalten, bevor er darauf stößt
* *Anpassen:* Der Benutzer kann das gesetzte Zeitlimit auf mindestens den zehnfachen Wert der Standard-Einstellung anpassen 
* *Verlängern:* Der Benutzer wird vor Ablauf der Zeit gewarnt und erhält mindestens 20 Sekunden Zeit, um das Zeitlimit mit einer einfachen Aktion (z.B. "Drücken Sie die Leertaste") zu verlängern.

*Ausnahmen:*

* *Echtzeit-Ausnahme:* Das Zeitlimit ist ein erforderlicher Bestandteil eines Echtzeitereignisses (z.B. einer Auktion), und es ist keine Alternative zum
  Zeitlimit möglich
* *Wesentliche Ausnahme:* Das Zeitlimit ist wesentlich und eine Verlängerung würde die Aktivität ungültig machen
* *20-Stunden-Ausnahme:* Das Zeitlimit ist länger als 20 Stunden

== Warum wird das geprüft?
Die Anforderung stellt sicher, dass Nutzende Aufgaben ohne Zeitbegrenzungen oder unerwartete Änderungen des Inhalts oder des Kontexts ausführen können. Wenn Zeitbegrenzungen sich nicht abschalten oder verlängern lassen, können Nutzer, die mehr Zeit für Eingaben brauchen, Online-Transaktionen oft nicht
rechtzeitig abschließen. Eine andere Form der Zeitbegrenzung ist die Auto-Aktualisierung von Inhalten durch das Neu-Laden einer Ansicht. Für Screenreader-Nutzer bedeutet Auto-Aktualisierung, dass das Vorlesen der Inhalte plötzlich unterbrochen wird und unvermittelt von vorne beginnt. Der Lese- bzw. Nutzungskontext geht verloren.

Bei zeitverzögerten Weiterleitungen sollen Nutzer etwas lesen, bevor sie automatisch auf eine andere Ansicht weitergeleitet werden.
Die kurz zwischendurch angezeigte Ansicht ist für viele Nutzende nicht zugänglich und die Tatsache der Weiterleitung damit nicht verständlich.

== Wie wird geprüft?

=== 1. Anwendbarkeit des Prüfschritts

Die Prüfung auf Auto-Aktualisierung und Weiterleitung ist immer anwendbar.

Die Prüfung auf Abschaltbarkeit oder Verlängerbarkeit von Zeitbegrenzungen ist nur anwendbar auf Ansichten mit Transaktionen, welche üblicherweise aus
datenschutzrechtlichen oder sicherheitsrelevanten Gründen Zeitbegrenzungen unterliegen (etwa beim Online-Banking oder Online-Shops).

=== 2. Prüfung

==== 2.1 Auto-Aktualisierung und Weiterleitung

Prüfen auf Auto-Aktualisierung durch Neu-Laden der Ansicht und Weiterleitung auf andere Ansicht.

Falls das Neuladen von Inhalten oder die Weiterleitung auf eine neue Ansicht visuell nicht nachzuvollziehen ist, kann die entsprechende Ansicht mit einem Screenreader untersucht werden. Wenn Inhalte neu geladen werden oder eine Weiterleitung stattfindet, bricht der Screenreader typischerweise das Vorlesen der Ansicht ab und beginnt von vorne. Dies ist ein starkes Indiz für das Neuladen von Inhalten oder die Verwendung von Weiterleitungen in der App.

==== 2.2 Prüfung auf Abschaltbarkeit oder Verlängerbarkeit von Zeitbegrenzungen

===== 2.2.1 Die Zeitbegrenzung wird angezeigt

Software-Ansichten mit Transaktionen können Zeitbegrenzungen auf verschiedene Weise anzeigen:

* Die verbleibende Zeitspanne (Session-Dauer) einer Transaktion wird angezeigt. Jede Interaktion setzt die Session-Dauer automatisch zurück.
* Rechtzeitig vor Ablauf der Zeit erscheint ein Dialog zum Verlängern der Zeitbegrenzung.
* Ein Kontrollelement erlaubt das Abschalten oder Verlängern der Zeitbegrenzung. Nutzer haben genügend Zeit, das Kontrollelement vor dem Ablauf der Zeit zu finden.

===== 2.2.2 Nicht unmittelbar sichtbare Zeitbegrenzungen

Wenn zu erwarten ist, dass die auf der Ansicht angebotene Transaktion eine Zeitbegrenzung hat, aber weder eine laufende Anzeige der Session-Dauer noch ein Kontrollelement zum Abschalten oder Verlängern angeboten werden:

. App-Ansicht mit Transaktionen, die üblicherweise eine begrenzte Session-Dauer haben (Online-Banking, Bezahlvorgänge von ShopsSoftware aufrufen und Daten eingeben.
. die Software für 20 Minuten nicht nutzen.
. Nach Ablauf der 20 Minuten prüfen, ob die Ansicht noch verfügbar ist und Daten erfolgreich abgeschickt werden können.
. Wenn die Ansicht nach 20 Minuten mitteilt, dass die Transaktionsdauer abgelaufen und die Session beendet worden ist, Software erneut laden und abwarten, ob auf der Ansicht ein Dialog erscheint, der rechtzeitig (mindestens 20 Sekunden vor Ablaufen der Zeit) eine Verlängerungsmöglichkeit der Zeitbegrenzung bietet.

=== 3. Hinweise

Dieser Prüfschritt bezieht sich nur auf vom Inhalt hervorgerufene Zeitbegrenzungen (sowohl serverseitig als auch clientseitig). Externe Zeitbegrenzungen, etwa des Betriebssystems, sind in der Regel nicht im Einflussbereich des Autors und damit nicht Gegenstand der Prüfung.

=== 4. Bewertung

==== Nicht erfüllt:

* Die Ansicht wird periodisch aktualisiert und veranlasst den Screenreader den
  Inhalt erneut vorzulesen oder dessen Fokus wird verschoben.
* Es gibt eine verzögerte Weiterleitung auf eine andere Ansicht.
* Der Ablauf einer Zeitbegrenzung wird nicht angezeigt.
  Erst mit dem Abschicken des Formulars wird darüber informiert, dass die
  Sessiondauer überschritten wurde.

==== Nicht voll erfüllt:

* Die Zeitbefristung der Session wird angezeigt und Nutzer-Aktivitäten setzen
  die Frist zurück, es gibt jedoch spätestens 20 Sekunden vor Ablauf der Frist
  keinen Dialog, der darüber informiert und Möglichkeiten zur Verlängerung bietet.
* Für das Auffinden des Kontrollelements zum Abschalten der Zeitbegrenzung
  steht nicht genug Zeit zur Verfügung.

== Einordnung des Prüfschritts

=== Abgrenzung von anderen Prüfkriterien

Dieser Prüfschritt 11.2.2.1 betrifft Zeitbegrenzungen, welche die ganze Ansicht
betreffen,
unabhängig davon, ob die zeitbegrenzten Inhalte bewegt sind (also
ablenken) oder nicht.
Geprüft wird, ob solche Zeitbegrenzungen abschaltbar oder verlängerbar sind.

* Der Prüfschritt
ifdef::env_embedded[11.2.2.2 "Bewegte Inhalte abschaltbar"]
ifndef::env_embedded[]
  <<11.2.2.2 Bewegte Inhalte abschaltbar.adoc#,11.2.2.2 Bewegte Inhalte
  abschaltbar>>
endif::env_embedded[]
  betrifft dagegen bewegte
  oder autoaktualisierte Inhalte, die Nutzer ablenken oder durch ihren
  vorgegebenen zeitlichen Ablauf für bestimmte Nutzer schwierig wahrnehmbar
  sind.
  Hier wird geprüft, ob Nutzer die Möglichkeit haben, bewegte oder
  autoaktualisierte Inhalte anzuhalten oder auszublenden.

* Wenn es ein Kontrollelement oder einen dokumentierten Tastaturbefehl gibt,
  um Zeitbegrenzungen abzuschalten oder zu verlängern, wird in diesem
  Prüfschritt lediglich geprüft, ob Nutzer genügend Zeit haben, diesen
  Mechanismus zu finden und zu nutzen.
  In anderen Prüfkriterien wird geprüft, ob der Mechanismus selbst
  zugänglich und verständlich ist (etwa in
ifdef::env_embedded[11.2.1.1 "Tastaturbedienung"]
ifndef::env_embedded[]
  <<11.2.1.1 Tastaturbedienung.adoc#,11.2.1.1 Tastaturbedienung>>
endif::env_embedded[]
  oder
ifdef::env_embedded[11.1.3.1d "Beschriftung von Formularelementen programmatisch ermittelbar").]
ifndef::env_embedded[]
  <<11.1.3.1d Beschriftung von Formularelementen programmatisch ermittelbar.adoc#,
  11.1.3.1d Beschriftung von Formularelementen programmatisch ermittelbar>>).
endif::env_embedded[]

=== Einordnung des Prüfschritts nach WCAG 2.1

==== Guideline

* https://www.w3.org/TR/WCAG21/#enough-time[Guideline 2.2 Enough Time: Provide
  users enough time to read and use content.]

==== Success criteria

* https://www.w3.org/TR/WCAG21/#timing-adjustable[2.2.1 Timing Adjustable
  (Level A)]

==== Techniques

.General Techniques

* https://www.w3.org/WAI/WCAG21/Techniques/general/G133.html[G133: Providing a
  checkbox on the first page of a multipart form that allows users to ask for
  longer session time limit or no session time limit]
* https://www.w3.org/WAI/WCAG21/Techniques/general/G180.html[G180: Providing
  the user with a means to set the time limit to 10 times the default time limit]
* https://www.w3.org/WAI/WCAG21/Techniques/general/G198.html[G198: Providing a
  way for the user to turn the time limit off]

==== Failures

* https://www.w3.org/WAI/WCAG21/Techniques/failures/F40[F40: Failure of
  Success Criterion 2.2.1 and 2.2.4 due to using meta redirect with a time limit]
* https://www.w3.org/WAI/WCAG21/Techniques/failures/F41[F41: Failure of
  Success Criterion 2.2.1, 2.2.4, and 3.2.5 due to using meta refresh with a
  time-out]
* https://www.w3.org/WAI/WCAG21/Techniques/failures/F58[F58: Failure of
  Success Criterion 2.2.1 due to using server-side techniques to automatically
  redirect pages after a time-out]

== Fragen zu diesem Prüfschritt

=== Kontrollelement für Zeitbegrenzung und Auto-Aktualisierung

Wie kann durch ein Kontrollelement in der Ansicht sichergestellt werden, dass der Benutzer eine Zeitbegrenzung oder Autoaktualisierung auf Wunsch
abschalten kann?

Wichtig ist, dass die Autoaktualisierung oder das Ende der Zeitbegrenzung nicht erfolgt, bevor der Benutzer auf ein entsprechendes Kontrollelement zum
Abschalten gestoßen ist. Daher sollte die Schaltfläche oder der Link zum Abschalten oder Verlängern am Beginn der Ansicht angezeigt werden, damit er von Menschen mit verschiedensten Behinderungen auch gefunden und aktiviert werden kann.

Dennoch ist nicht sicher, dass Benutzer die Option zum Abschalten der Autoaktualisierung oder Zeitbegrenzung finden und verstehen.
