= Prüfschritt 11.2.1.1 Tastatur
include::include/author.adoc[]
include::include/attributes.adoc[]

== Was wird geprüft?

Die App soll auch ohne Maus- oder Touch-Eingaben, also ausschließlich mit der Tastatur, zu benutzen sein.

== Warum wird das geprüft?

Die Bedienung der App soll geräteunabhängig möglich sein. Das bedeutet: Sie muss mit der Tastatur möglich sein. Denn auch andere Hilfsmittel oder Eingabemethoden (etwa Spracheingabe) brauchen die Tastatur bzw. setzten die Tastaturbedienbarkeit voraus. Auf die Tastaturbedienbarkeit angewiesen sind zum Beispiel viele motorisch eingeschränkte oder blinde Menschen.

== Wie wird geprüft?

=== 1. Anwendbarkeit des Prüfschritts

Der Prüfschritt ist anwendbar für native Apps, die eine Benutzeroberfläche bieten und den Zugriff auf Tastaturen oder ein Tastaturinterface unterstützen.
Dies trifft auf die meisten Apps auf den gängigen mobilen Plattformen wie Apples iOS / iPadOS sowie Googles Android zu.

=== 2. Prüfung

. Tastatur über Bluetooth-Kopplung oder USB-Kabel anschließen.
. App mit zu prüfender Ansicht öffnen.
. Mit der Tabulatortaste die Links und Formularelemente durchgehen. Wo sich Elemente nicht mit dem Tabulator erreichen lassen, prüfen, ob sie mit den Pfeiltasten erreichbar sind.
. Prüfen, ob alle wesentlichen Funktionen über die Tastatur erreicht und aktiviert werden können. In der Regel heißt das, das Elemente fokussiert und dann über die Eingabe- oder Leertaste aktiviert werden können. Wo Elemente nicht erreichbar oder aktivierbar sind, prüfen, ob äquivalente Wege zum Auslösen der Funktion über die Tastatur zur Verfügung stehen.
. Falls die Ansicht Elemente enthält, die wie Bedienelemente aussehen, jedoch nicht über Tabulatortaste oder Pfeiltasten angesteuert werden, prüfen, ob diese Elemente auf Touch-Eingaben reagieren (zum Beispiel Navigation zu anderen Ansichten, Funktionsaufrufe, Vergrößerung, Einblenden von weiteren Inhalten). Wenn ja, müssen sie auch mit der Tastatur fokussier- und aktivierbar sein.
. Falls die Ansicht scrollbare Bereiche enthält, sollen nicht sichtbare Inhalte dieser Bereiche auch über die Tastatur erreichbar sein, ohne das dazu der Bildschirm berührt werden muss.
.. iOS: Falls Seitenbereiche mit Textinhalten ohne interaktive Elemente nicht erreicht werden: Prüfen, ob nach Aktivieren von Tastaturgesten (Tab + G) alle Textinhalte über die vertikalen Pfeiltasten erreichbar sind.

=== 3. Hinweise

==== 3.1 Allgemeine Hinweise
Die prüfende Person muss mit der Funktionsweise der eingesetzten Browser und Betriebssysteme vertraut sein, sie muss wissen, welche Tasten und Tastenkombinationen für die Tastaturbedienung vorgesehen sind.

Für diesen Prüfschritt spielt die Reihenfolge, in der interaktive Elemente und Formularelemente angesteuert werden, keine Rolle. 

Manche Elemente sind nur in nicht-linearer Navigation, z.B. durch eine Abfolge von Pfeiltasten erreichbar. So ist ein Element oben rechts von der aktuellen Fokusposition gegebenenfalls nur fokussierbar, wenn man erst zweimal die Pfeiltaste nach oben und dann die nach rechts betätigt. Dieser Prüfschritt 11.2.1.1 ist dann zwar erfüllt, nicht jedoch der Prüfschritt 11.2.4.3 "Schlüssige Reihenfolge bei der Tastaturbedienung", denn der Weg zum Erreichen des prinzipiell fokussierbaren Elements ist nur zwei-dimensional und visuell verständlich, nicht linear.

==== 3.2 Hinweis zu Drag-and-Drop

Für wichtige Bedienfunktionen, die mittels Drag-and-Drop bedienbar sind, müssen auch tastaturnutzbare Alternativen angeboten werden.

=== 4. Bewertung

==== Erfüllt:

* Alle wesentlichen Inhalte und Funktionen sind mit der Tastatur erreichbar und bedienbar.

==== Nicht erfüllt:

* Wesentliche Inhalte und Funktionen sind mit der Tastatur nicht erreichbar oder nicht bedienbar.

== Quellen

[BLOCK_LANG_EN]
* Android Developer:
  https://developer.android.com/training/keyboard-input/navigation[Support
  keyboard navigation]

== Einordnung des Prüfschritts

=== Abgrenzung zu anderen Prüfkriterien

Dieser Prüfschritt betrifft die Fokussierbarkeit und Aktivierbarkeit von interaktiven Elementen mit der Tastatur.

* Tastaturfallen sind Gegenstand von Prüfschritt
ifdef::env_embedded[11.2.1.2 "Keine Tastaturfalle"]
ifndef::env_embedded[]
  <<11.2.1.2 Keine Tastaturfalle.adoc#,11.2.1.2 Keine Tastaturfalle>>
endif::env_embedded[]
* Die Fokushervorhebung ist Gegenstand von Prüfschritt
ifdef::env_embedded[11.2.4.7 "Aktuelle Position des Fokus deutlich"]
ifndef::env_embedded[]
  <<11.2.4.7 Aktuelle Position des Fokus deutlich.adoc#,11.2.4.7 Aktuelle Position
  des Fokus deutlich>>
endif::env_embedded[]
* Die sinnvolle Fokusreihenfolge wird in
ifdef::env_embedded[11.2.4.3 "Schlüssige Reihenfolge bei der Tastaturbedienung"]
ifndef::env_embedded[]
<<11.2.4.3 Schlüssige Reihenfolge bei der Tastaturbedienung.adoc#,11.2.4.3
Schlüssige Reihenfolge bei der Tastaturbedienung>>
endif::env_embedded[]
bewertet

=== Einordnung des Prüfschritts nach WCAG 2.1

==== Guideline

* https://www.w3.org/TR/WCAG21/#keyboard-accessible[Guideline 2.1 Keyboard
  Accessible: Make all functionality available from a keyboard.]

==== Success Criterion

* https://www.w3.org/TR/WCAG21/#keyboard[2.1.1 Keyboard (Level A)]

==== Techniques

===== General Techniques

* https://www.w3.org/WAI/WCAG21/Techniques/general/G90.html[G90: Providing
  keyboard-triggered event handlers]
* https://www.w3.org/WAI/WCAG21/Techniques/general/G202.html[G202: Ensuring
  keyboard control for all functionality]

===== Failures

* https://www.w3.org/WAI/WCAG21/Techniques/failures/F42.html[F42: Failure of
  Success Criterion 1.3.1 and 2.1.1 due to using scripting events to emulate links in a way that is not programmatically determinable]
* https://www.w3.org/WAI/WCAG21/Techniques/failures/F54.html[F54: Failure of
  Success Criterion 2.1.1 due to using only pointing-device-specific event
  handlers (including gesture) for a function]
* https://www.w3.org/WAI/WCAG21/Techniques/failures/F55.html[F55: Failure of
  Success Criteria 2.1.1, 2.4.7, and 3.2.1 due to using script to remove focus
  when focus is received]

== Fragen zu diesem Prüfschritt
=== Unsere App ist auf die mobile Nutzung unterwegs ausgelegt, da hat man doch keine Tastatur. Gilt dann dieser Prüfschritt trotzdem?
Ja, er gilt. Viele Apps für unterwegs werden auch zuhause oder am Arbeitsplatz genutzt, z.B. bei einer App für den öffentlichen Nahverkehr:

* um Reisen vorab zu planen, Wege und Anschlüsse zu recherchieren
* um Meldungen zu Baustellen, Umleitungen oder Verkehrsbehinderungen vorab zu checken
* um nutzerdefinierte Voreinstellungen vorzunehmen (z.B. häufige Ziele oder häufige Routen festlegen)
* um sich zu registrieren oder Profildaten zu ändern

Die Anforderungen an Tastaturnutzbarkeit gelten also generell. Die BITV bzw. die zugrunde liegende EN 301 549 sehen hier keine Ausnahmen vor. 
