= Prüfschritt 11.2.5.7 Ziehbewegungen
include::include/author.adoc[]
include::include/attributes.adoc[]


== Was wird geprüft?

Ist eine Ziehbewegung (z. B. "Drag and Drop") für das Ausführen einer Funktion nötig, 
muss die Bedienung auch mit einer einfachen Zeiger (ohne Ziehbewegung) möglich sein. 
Ausnahme: Das Ziehen ist unerlässlich oder die Funktion wird von der zugrundeliegenden Plattform bestimmt (etwa beim Scrollen / Verschieben der Ansicht)

== Warum wird das geprüft?

Selbst die einfachste Ziehbewegung erfordert eine recht präzise Steuerung des Zeigers (z. B. Maus oder Finger). 
Dies kann für Nutzende, die Probleme mit der Feinmotorik haben oder Hilfsmittel verwenden, 
die eine Zeigerbewegung über Sprachbefehle oder andere Eingaben simulieren, schwierig bis unmöglich sein. 
Es muss daher eine alternative Methode für Eingabe mittels einfachem Zeiger an einem Ort (also ohne Ziehbewegung) zur Verfügung gestellt werden. 
Ein Beispiel für eine alternative Methode: Nach Aktivierung eines Elements über einfaches Antippen (oder Klicken, bei Verwendung einer Maus) erlaubt 
ein Aktions-Menü die Auswahl des Zielorts.

== Wie wird geprüft

=== 1. Anwendbarkeit des Prüfschritts

Der Prüfschritt ist anwendbar, wenn Funktionen mit Hilfe von Ziehbewegungen (Ziehen und Ablegen, Verschieben) auf der Ansicht vorhanden sind.

=== 2. Prüfung

. Prüfen, ob Funktionen vorhanden sind, die über Ziehbewegungen ausgeführt werden 
(z. B. das Ziehen von Elementen in andere Container oder das Verschieben von Schiebereglern).
. Wenn eine solche Funktion über Ziehbewegungen vorhanden ist: 
Kann die gleiche Funktion auch ohne Ziehbewegung ausgeführt werden? 
Dies kann auf verschiedene Weise umgesetzt werden, zum Beispiel:

  * Nach Aktivierung eines Elements über einfachen Zeiger, ggf. auch über ein längeres Halten (long press) öffnet ein Aktions-Menü die Auswahl des Zielorts mit einfachen Zeigereingaben.
  * Nach Aktivierung eines Elements über einfachen Zeiger erscheinen im Kontext des Elements Pfeile, 
  die ein schrittweises Verschieben des Elements erlauben.
  * Ein einfaches Tippen oder Klicken auf die gewünschte Position eines Schiebereglers auf der Regler-Achse (groove) 
  führt zum Versetzen der Position des Reglerknopfes (thumb).
  * Die Funktion kann auch über numerische Eingaben eines Wertes über die virtuelle Tastatur ausgeführt werden.

=== 3. Hinweise

*	Bei einer Ziehbewegung ist nur der Anfangs- und Endpunkt der Bewegung von Bedeutung, der Pfad dazwischen ist beliebig.
*	Der Prüfschritt 2.5.7 "Ziehbewegungen" verlangt eine Alternative für die Aktivierung der jeweiligen Funktion über einfache Zeiger-Eingaben, 
unabhängig von der Tastaturbedienbarkeit, die parallel in Prüfschritt 9.2.1.1 geprüft wird. 
Wenn die jeweilige Funktion mittels Tastatureingabe verfügbar ist, ist dies also nicht automatisch eine Alternative, 
es sei denn, diese Alternative (etwa ein Ausklapp-Menü zum Verschieben eines ausgewählten Elements) 
ist vollständig ebenso über einfache Zeigereingaben bedienbar.
*	Das vom Browser unterstützte Scrollen / Verschieben einer Ansicht fällt nicht in den Anwendungsbereich.

=== 4. Bewertung

==== Nicht erfüllt

Für das Ausführen einer Funktion mit Ziehbewegung gibt es keine alternative Methode, die Funktion nur über Eingaben mittels einfachem Zeiger ohne Ziehbewegung oder Zeigergeste auszuführen.

== Einordnung des Prüfschritts

=== Abgrenzung zu anderen Prüfschritten

* Prüfschritt 11.2.1.1 Ohne Maus nutzbar prüft, ob alle Funktionen auch mit der Tastatur bedienbar sind. 
* Prüfschritt 11.2.5.7 Ziehbewegungen prüft hingegen, ob die Bedienung über eine Ziehbewegung
auch mit einer Eingabe mittels einfachem Zeiger ohne Ziehbewegung oder Zeigergeste oder eine Folge von solchen einfachen Eingaben möglich ist (zum Beispiel Klicken oder Tippen), 
denn eine funktionierende Tastaturbedienung bedeutet nicht zwangsläufig, 
dass die Ziehfunktion auch über einfache Zeigeraktionen ausführbar ist.
* Prüfschritt 2.5.7 bezieht sich auf *Ziehbewegungen* (nur der Anfangs- und Endpunkt der Bewegung von Bedeutung, der Pfad dazwischen ist beliebig). 
Prüfschritt 2.5.1 Alternativen für komplexe Zeigergesten behandelt *Zeigergesten,* 
d.h. pfadbasierte Gesten (eine bestimmte Richtung, d. h. ein bestimmter Pfad ist für die Ausführung nötig) und *Mehrpunktgesten* (z. B. Zwei-Finger-Spreizgeste).

=== Einordnung des Prüfschritts nach WCAG 2.2

==== Guidelines

* https://www.w3.org/TR/WCAG22/#input-modalities[2.5 Input Modalities]

==== Success Criterion

* https://www.w3.org/TR/WCAG22/#dragging-movements[2.5.3 Dragging Movements) (Level AA)]

==== Techniques

===== Sufficient Techniques

* https://www.w3.org/WAI/WCAG22/Techniques/general/G219[G219: Ensuring that a single pointer alternative is available for dragging movements that operate on content]

===== Failures

* https://www.w3.org/WAI/WCAG22/Techniques/failures/F108[F108: Failure of Success Criterion 2.5.X Dragging due to not providing a single pointer method for the user to operate a function that does not require a dragging movement]
