= Prüfschritt 11.2.4.11 Fokus nicht verdeckt (Minimum)
include::include/author.adoc[]
include::include/attributes.adoc[]

== Was wird geprüft?
Der Tastaturfokus eines Bedienelements darf nicht nicht vollständig von anderen Inhalten (z. B. fest positionierten Bereichen) überlagert sein. Zumindest ein Teil des Bedienelements (und damit meist auch ein Teil der Fokushervorhebung) muss noch sichtbar sein.

Blenden Nutzende zusätzliche Inhalte durch eine Aktion ein, kommt es vor  dass diese Inhalte andere Elemente der Ansicht verdecken, wenn diese den Fokus erhalten. Nutzende müssen dann in der Lage sein, das fokussierte Bedienelement sichtbar zu machen, ohne den Tastaturfokus zu verschieben (z. B. mithilfe der Esc-Taste, um den geöffneten Inhalt zu schließen).

== Warum wird das geprüft?

Für sehende Menschen, die auf Tastaturbedienung angewiesen sind, ist es wichtig, wahrnehmen zu können, welches Bedienelement aktuell fokussiert ist. Das gilt auch für Menschen, die ein Gerät nutzen, das über die Tastaturschnittstelle bedient wird, wie zum Beispiel Schaltersteuerung oder Spracheingabe. Die fokussierte Bedienelement ist der Ort, an dem die Interaktion auf der Seite stattfindet. Wenn der Benutzer das Element nicht sehen kann, weiß er möglicherweise nicht, wie er weiter vorgehen soll, oder er könnte sogar denken, das System reagiere nicht mehr.

Beim Navigieren auf der Seite darf es daher nicht zu Situationen kommen, in denen fest positionierte Inhalte (z.B. Kopf- und Fußbereiche) das fokussierte Element vollständig verdecken.

== Wie wird geprüft?

=== 1. Anwendbarkeit des Prüfschritts

Der Prüfschritt ist anwendbar, wenn die Ansicht interaktive Elemente enthält,
die mit der Tastatur (mit TAB, SHIFT + TAB, STRG + TAB, oder auch mittels Pfeiltasten) fokussiert werden können. 
Ist die Fokussierung zwar technisch möglich, aber es kein Tastaturfokus ist sichtbar, ist ggf. auch Prüfschritt <<11.2.4.7 Fokus sichtbar>> nicht erfüllt.

=== 2. Prüfung
. Alle Bedienelemente nacheinander mit der Tastatur fokussieren. 
Häufig werden Bedienelemente linear (also über TAB oder Pfeiltaste nach rechts) erreicht, 
in manchen Fällen aber sind sie jedoch nur über nicht-lineare Eingaben (etwa SHIFT + STRG + TAB oder die Nutzung von Pfeiltaste nach oben) erreichbar. 
In der Regel ändert sich der Scrollzustand der Ansicht, wenn der Fokus über den sichtbaren Bereich hinaus bewegt wird.
. Prüfen, ob es zu Situationen kommt, wo ein mit der Tastatur fokussiertes Bedienelement vollständig verdeckt wird 
(zum Beispiel durch einen fest positionierte Kopf- oder Fußbereich, 
durch einen nicht-modalen Dialog oder andere von Nutzenden eingeblendeten Inhalten). 
. Wenn aktiv eingeblender Inhalt ein Bedienelement verdeckt, prüfen, 
ob das Bedienelement sichtbar gemacht werden kann, ohne den Tastaturfokus zu verschieben, etwa durch
* Verwenden der Escape-Taste (zum Schließen eines Dialogs oder Popups) 
* Bei Fehlen der Escape-Tast ggf. auch über entsprechende Tastatureingaben, etwa Control + [ auf dem iPad
* Verwenden einer Taste zum Scrollen, bei iOS etwa über TAB + G zum Aktivieren von Tastaturgesten, gefolgt vom Einsatz der Pfeiltasten
* Drücken einer Taste zum Hin- und Herwechseln zwischen der Fokusposition der Ansicht und dem eingeblendeten Inhalt.

=== 3. Hinweise
* Wenn ein Bedienelement bei Fokussierung teilweise (d. h. nicht vollständig) verdeckt wird, also noch Teile der Komponente sichtbar sind, ist das kein Fehler im Sinne dieser Anforderung, selbst wenn die Fokushervorhebung selbst verdeckt ist. Es zählt die teilweise Sichtbarkeit des fokussierten Elements.
* Wenn das Interface so konfigurierbar ist, dass Nutzende Symbolleisten und nicht-modale Dialoge verschieben können, werden nur die Anfangspositionen der von Nutzenden verschiebbaren Inhalte für die Prüfung und Erfüllung dieser Anforderung berücksichtigt.

=== 4. Bewertung

==== Nicht erfüllt

* Der Tastaturfokus landet bei Durchlaufen fokussierbarer Elemente hinter fest positionierten Bereichen (meist Kopf- oder Fußbereich),
das Element ist vollständig verdeckt.

