= Prüfschritt 11.2.4.7 Aktuelle Position des Fokus deutlich
include::include/author.adoc[]
include::include/attributes.adoc[]

== Was wird geprüft?

Werden Bedienelementen mit der Tastatur fokussiert, dann soll sich der Tastaturfokus deutlich von der
ausgewählten Hintergrundfarbe abheben.

Versteckte Sprunglinks sollen bei Fokuserhalt eingeblendet werden.

== Warum wird das geprüft?

Für Tastaturbenutzende ist es wichtig, zu sehen, wo sich der Tastaturfokus gerade befindet, welches Bedienelement also ausgelöst wird, wenn sie die Enter-Taste drücken.

Wenn Apps allein durch die Tastatur bedient werden, muss das fokussierte Bedienelement für den Nutzende deutlich hervorgehoben sein. Eine sichere Bedienung der Anwendung ist für visuelle Nutzer andernfalls kaum möglich ist.

Die vom Betriebssystem vorgesehene Kennzeichnung des Tastaturfokus hebt sich von dunklen Seitenhintergründen meist nicht so gut ab. Das muss dann durch eine entsprechende Gestaltung des Fokusindikators ausgeglichen werden.

== Wie wird geprüft?

=== 1. Anwendbarkeit des Prüfschritts

Der Prüfschritt ist anwendbar, wenn die App-Ansicht interaktive Elemente enthält.

=== 2. Prüfung

. Tastatur über Bluetooth-Kopplung oder USB-Kabel anschließen.
. Zu prüfende Ansicht der App öffnen.
. Mit der Tabulatortaste zu allen interaktiven Elementen navigieren.
. Prüfen, ob sie mit grafischen Veränderungen auf den Fokus reagieren (zum Beispiel mit
  Farbwechseln, Unterstreichungen oder eingeblendeten Symbolen). Versteckte Sprunglinks sollen bei Fokuserhalt eingeblendet werden.
. Wenn die Fokushervorhebung ausschließlich über einen Farbwechsel geschieht, prüfen, ob der Kontrastabstand zwischen fokussiertem und unfokussiertem Zustand mindestens 3:1 beträgt.
. Bei Bedienelementen, die sich im Fokus nicht verändern, prüfen, ob der
  Tastaturfokus (Systemkranz) an dieser Stelle vor hellem Hintergrund dargestellt ist, also gut zu erkennen ist.
  In Zweifelsfällen gemäß Prüfschritt
ifdef::env_embedded[11.1.4.3 "Kontraste von Texten ausreichend"]
ifndef::env_embedded[]
  <<11.1.4.3 Kontraste von Texten ausreichend.adoc#,11.1.4.3 Kontraste von Texten
  ausreichend>>
endif::env_embedded[]
  ermitteln, ob die Farbe Schwarz vor dem gewählten Hintergrund ausreichend
  kontrastiert.

=== 3. Hinweise

* Der Prüfschritt ist nicht erfüllt, wenn überhaupt kein Tastaturfokus sichtbar ist.
Dann ist eventuell auch Prüfschritt
ifdef::env_embedded[11.2.1.1 "Tastaturbedienung"]
ifndef::env_embedded[]
  <<11.2.1.1 Tastaturbedienung.adoc#,11.2.1.1 Tastaturbedienung>>
endif::env_embedded[]
nicht erfüllt! (bzw. Ohne Touch-Gesten bedienbar?)

=== 4. Bewertung

==== Erfüllt:

Die Fokussierung interaktiver Elemente ist visuell wahrnehmbar:

* Rahmen, Unterstreichung, Farbumkehr, Formänderungen oder zusätzliche Markierungen werden bei Tastaturfokussierung eingesetzt.

* Wenn die Fokussierung von Links oder Buttons nur über die Änderung der Text- oder Hintergrundfarbe vermittelt wird, beträgt deren Kontrastabstand zum unfokussierten Zustand mindestens 3:1.

*  Wenn nur der System-Tastaturfokus angezeigt wird, ist dieser vor gestalteten Hintergründen ausreichend sichtbar, er erfüllt den Prüfschritt
ifdef::env_embedded[11.1.4.3 "Kontraste von Texten ausreichend".]
ifndef::env_embedded[]
  <<11.1.4.3 Kontraste von Texten ausreichend.adoc#,11.1.4.3 Kontraste von Texten
  ausreichend>>.
endif::env_embedded[]

*Nicht voll erfüllt:*

* Sprunglinks bleiben bei Fokuserhalt versteckt.

*Nicht erfüllt:*

* Der System-Fokus wird unterdrückt, bei Tastaturnutzung wird kein Fokus
  angezeigt.

== Einordnung des Prüfschritts

=== Einordnung des Prüfschritts nach WCAG 2.1

==== Guideline

* https://www.w3.org/TR/WCAG21/#navigable[Guideline 2.4 Navigable: Provide
  ways to help users navigate, find content, and determine where they are]

==== Success criteria

* https://www.w3.org/TR/WCAG21/#focus-visible[2.4.7 Focus Visible (Level AA)]
* https://www.w3.org/TR/WCAG21/#non-text-contrast[1.4.11 Non-Text Contrast
  (Level AA)]

==== Techniques

.General Techniques
* https://www.w3.org/WAI/WCAG21/Techniques/general/G149.html[G149: Using user
  interface components that are highlighted by the user agent when they
  receive focus]
* https://www.w3.org/WAI/WCAG21/Techniques/general/G165.html[G165: Using the
  default focus indicator for the platform so that high visibility default
  focus indicators will carry over]
* https://www.w3.org/WAI/WCAG21/Techniques/general/G195.html[G195: Using an
  author-supplied, highly visible focus indicator]

==== Failures

* https://www.w3.org/WAI/WCAG21/Techniques/failures/F55.html[F55: Failure of
  Success Criteria 2.1.1, 2.4.7, and 3.2.1 due to using script to remove focus
  when focus is received]
* https://www.w3.org/WAI/WCAG21/Techniques/failures/F78.html[F78: Failure of
  Success Criterion 2.4.7 due to styling element outlines and borders in a way
  that removes or renders non-visible the visual focus indicator]

== Fragen zu diesem Prüfschritt

=== Ist die Anzeige des Fokus nicht Sache des Betriebssystems?

Alle Betriebssysteme zeigen dem Tastaturnutzer in irgendeiner Weise, wo der
Fokus ist, wenn diese Anzeige nicht aktiv unterdrückt wird.

Dennoch ist die Anzeige des Fokus nicht allein Sache des Betriebssystems.
Die App legt fest, wie sie aussehen soll.
Sie ändert etwa die Farben fokussierter Bedienelemente und Hintergründe von
Bedienelementen oder setzt andere Gestaltungselemente ein.
In dieser von der App festgelegten Umgebung muss der Fokus für Tastaturnutzer
gut sichtbar sein.
