= Prüfschritt 11.2.1.2 Keine Tastaturfalle
include::include/author.adoc[]
include::include/attributes.adoc[]

*Hinweis: Dies ist ein Entwurf. Inhalte können sich jederzeit ändern.*

== Was wird geprüft?

Kann der Tastaturfokus auf ein Element der Ansicht bewegt werden, muss er auch von diesem Element wieder wegbewegt werden können. Der Inhalt darf keine Tastaturfalle erzeugen.

Wenn mehr als Pfeil- oder Tabulatortasten oder andere Standard-Beendigungsmethoden erforderlich sind, gibt es für Nutzende einen Hinweis auf die benötigte Methode zum Wegbewegen des Fokus.


== Warum wird das geprüft?

Die Bedienung soll geräteunabhängig möglich sein. Das bedeutet: Sie muss sowohl mit Touch-Eingaben als auch mit der Tastatur möglich sein.

Auf die Tastaturbedienbarkeit angewiesen sind zum Beispiel viele motorisch eingeschränkte oder blinde Menschen.

== Wie wird geprüft?

=== 1. Anwendbarkeit des Prüfschritts

Der Prüfschritt ist immer anwendbar.

=== 2. Prüfung

. Tastatur über Bluetooth-Kopplung oder USB-Kabel anschließen.
. App mit zu prüfender Ansicht öffnen.
. Mit der Tabulatortaste durch alle interaktiven Elemente und Formularelemente navigieren.
. Prüfen, ob alle interaktiven Elemente und Formularelemente erreicht und wieder verlassen werden können.

=== 3. Hinweise

Wenn die Tastaturfalle verhindert, dass man Inhalte nach der Tastaturfalle
erreicht, dann ist eventuell auch Prüfschritt
ifdef::env_embedded[11.2.1.1 "Tastaturbedienung"]
ifndef::env_embedded[]
  <<11.2.1.1 Tastaturbedienung.adoc#,11.2.1.1 Tastaturbedienung>>
endif::env_embedded[]
nicht erfüllt.

=== 4. Bewertung

==== Erfüllt:

* Es gibt keine Tastaturfallen.

==== Nicht erfüllt:

* Wesentliche Inhalte und Funktionen sind aufgrund einer Tastaturfalle mit der Tastatur nicht erreichbar oder nicht bedienbar.

== Einordnung des Prüfschritts

=== Einordnung des Prüfschritts nach WCAG 2.1

==== Guideline

* https://www.w3.org/TR/WCAG21/#keyboard-accessible[Guideline 2.1 Keyboard
  Accessible: Make all functionality available from a keyboard.]

==== Success criteria

* https://www.w3.org/TR/WCAG21/#no-keyboard-trap[2.1.2 No Keyboard Trap
  (Level A)]

==== Techniques

.General Techniques
* https://www.w3.org/WAI/WCAG21/Techniques/general/G21.html[G21: Ensuring that
  users are not trapped in content]

==== Failures

* https://www.w3.org/WAI/WCAG21/Techniques/failures/F10[F10: Failure of
  Success Criterion 2.1.2 and Conformance Requirement 5 due to combining
  multiple content formats in a way that traps users inside one format type]
  
== Fragen zu diesem Prüfschritt
=== Unsere App ist auf die mobile Nutzung unterwegs ausgelegt, da hat man doch keine Tastatur. Gilt dann dieser Prüfschritt trotzdem?
Ja, er gilt. Viele Apps für unterwegs werden auch zuhause oder am Arbeitsplatz genutzt, z.B. bei einer App für den öffentlichen Nahverkehr:

* um Reisen vorab zu planen, Wege und Anschlüsse zu recherchieren
* um Meldungen zu Baustellen, Umleitungen oder Verkehrsbehinderungen vorab zu checken
* um nutzerdefinierte Voreinstellungen vorzunehmen (z.B. häufige Ziele oder häufige Routen festlegen)
* um sich zu registrieren oder Profildaten zu ändern

Die Anforderungen an Tastaturnutzbarkeit gelten also generell. Die BITV bzw. die zugrunde liegende EN 301 549 sehen hier keine Ausnahmen vor. 
