= Prüfschritt 11.3.3.2 Beschriftungen von Formularelementen vorhanden
include::include/author.adoc[]
include::include/attributes.adoc[]

*Hinweis: Dies ist ein Entwurf. Inhalte können sich jederzeit ändern.*

== Was wird geprüft?

Beschriftungen von Formularelementen sind vorhanden.

Die Beschriftung von Formularelementen soll vor (das heißt links neben oder
über) dem zugehörigen Eingabefeld angeordnet werden.
Nur die Beschriftung von Checkboxes und Radiobuttons kann (und sollte
normalerweise) rechts neben dem zugehörigen Eingabefeld angeordnet werden.

Wenn für die Eingabe ein bestimmtes Format verlangt wird, so sind die
Anweisungen für alle Benutzer lesbar.

== Warum wird das geprüft?

Wenn Beschriftungen zur Verfügung gestellt werden, wissen Nutzer, welche
Eingaben erwartet werden und Fehler können vermieden werden.

Die Anordnung von Beschriftungen direkt vor oder über dem Eingabefeld
entspricht den üblichen Gestaltungskonventionen.
Auch in ausschnitthaften Ansichten (etwa in Vergrößerungssoftware) wird
schnell klar, welche Beschriftung zu welchem Feld gehört.

== Wie wird geprüft?

=== Anwendbarkeit des Prüfschritts

Der Prüfschritt ist anwendbar, wenn die App-Ansicht Formularelemente enthält.

=== Prüfung

. App mit zu prüfender Ansicht öffnen.
. Sind Beschriftungen vorhanden ?
. Sind alle Formularelemente beschriftet?
. Sind Pflichtfelder in label- oder legend-Elementen klar angezeigt, Wenn zur
  Anzeige Symbole wie etwa ein Sternchen (*) genutzt werden, muss deren
  Bedeutung am Beginn des Formulars erklärt sein
. Wenn Eingabefelder ein bestimmtes Eingabeformat vorgeben, wird dieses vor
  dem Eingabefeld klar beschrieben? (Beispiele wären "Format der
  Datumseingabe: TT.MM.JJJJ" oder
  "Telefonnummer: Nur Zahlen ohne Leerstellen oder Bindestriche eingeben".)
. Sind Beschriftungen richtig positioniert?

=== Hinweise

Bei kombinierten Eingabeelementen hat nicht immer jedes Element eine
zugeordnete Beschriftung.
In diesem Fall sollen Elemente mit einem unsichtbaren erklärenden Label
versehen werden, welches dann von einem Screenreader ausgegeben werden kann.
Beispiel: In einem Formular werden für die Eingabe eines Datums drei
Auswahllisten angeboten (Tag, Monat und Jahr).
Die drei Auswahllisten haben eine gemeinsame Beschriftung:
Datum.
Die Auswahllisten für Tag, Monat und Jahr sind jeweils mit einem unsichtbaren
erklärenden Label für Hilfstechnologien versehen.

Wenn ein einfaches Suchformular nur aus einem Eingabefeld und einem Button
besteht, ist oftmals keine sichtbare Beschriftung notwendig.
Hier ist es ausreichend, wenn Eingabefeld und Button direkt nebeneinander
positioniert sind, das Eingabefeld eine sinnvolle Textvorbelegung hat oder die
Beschriftung des Buttons die Funktion eindeutig kennzeichnet (etwa "Suchen").
Das unbeschriftete Eingabefeld mit Textvorbelegung muss in solchen Fällen
ein aussagekräftiges verstecktes Label haben, da für Screenreader-Nutzer der
nachfolgende Button nicht gleichermaßen als Beschriftung taugt.

Es kann sinnvoll sein, dass bei Formularen Hinweise zum Eingabeformat oder zu
ausgelösten Aktionen einmal am Beginn des Formulars stehen statt vor jedem
einzelnen Eingabefeld.

=== Bewertung

*Nicht erfüllt:*

* Wichtige Formularelemente (z.B. die Sucheingabe) sind ohne Beschriftung, auch
  angrenzende Elemente erklären nicht die Funktion.

*Nicht voll erfüllt:*

* Beschriftungen werden nur als Formularfeld-Vorbelegung bereitgestellt.

== Quellen

=== Allgemein
* Appt.org: https://appt.org/en/guidelines/wcag/success-criterion-3-3-2#use-input-labels[Labels or Instructions: Use input labels] (mehrere Entwicklungsumgebungen)

=== iOS
* Orange Accessibility Guidelines: https://a11y-guidelines.orange.com/en/mobile/ios/development/#element-trait[iOS Developer Guide: Element trait]
* Orange Accessibility Guidelines: https://a11y-guidelines.orange.com/en/mobile/ios/development/#grouping-elements[iOS Developer Guide: Grouping elements]

=== Android
* Orange Accessibility Guidelines: https://a11y-guidelines.orange.com/en/mobile/android/development/form/[Android develop - Input screen: Explicitly label input fields]
* Orange Accessibility Guidelines: https://a11y-guidelines.orange.com/en/mobile/android/development/vocal-navigation/#group-the-elements[Group the elements]


== Einordnung des Prüfschritts

=== Einordnung des Prüfschritts nach WCAG 2.1

==== Guideline

* https://www.w3.org/WAI/WCAG21/quickref/?showtechniques=334#input-assistance[
  Guideline 3.3 Input Assistance: Help users avoid and correct mistakes]

==== Success criterion

* https://www.w3.org/WAI/WCAG21/quickref/?showtechniques=334#labels-or-instructions[
  3.3.2 Labels or Instructions (Level A)]

==== Techniques

.General Techniques
* https://www.w3.org/WAI/WCAG21/Techniques/general/G13.html[G13: Describing
  what will happen before a change to a form control that causes a change of
  context to occur is made]
* https://www.w3.org/WAI/WCAG21/Techniques/general/G89.html[G89: Providing
  expected data format and example]
* https://www.w3.org/WAI/WCAG21/Techniques/general/G131.html[G131: Providing
  descriptive labels]
* https://www.w3.org/WAI/WCAG21/Techniques/general/G162.html[G162: Positioning
  labels to maximize predictability of relationships]
* https://www.w3.org/WAI/WCAG21/Techniques/general/G184.html[G184: Providing
  text instructions at the beginning of a form or set of fields that describes
  the necessary input]

==== Failures

* https://www.w3.org/WAI/WCAG21/Techniques/failures/F82.html[F82: Failure of
  Success Criterion 3.3.2 by visually formatting a set of phone number fields
  but not including a text label]
