= Prüfschritt 11.3.3.3 Vorschlag bei Fehler
include::include/author.adoc[]
include::include/attributes.adoc[]

*Hinweis: Dies ist ein Entwurf. Inhalte können sich jederzeit ändern.*

== Was wird geprüft?

Wenn ein Formular Fehlermeldungen erzeugt, müssen diese verständlich sein und Hinweise geben, wie der Fehler zu korrigieren ist.

== Warum wird das geprüft?

Bei Formulareingaben kommt es öfters zu Fehlern: Nutzer verschreiben sich oder überspringen benötigte Eingaben.

Wenn das Angebot Nutzereingaben überprüft, sollen die ausgegebenen Fehlermeldungen hilfreich sein und es den Nutzern erleichtern, Eingaben zu korrigieren.

== Wie wird geprüft?

=== Anwendbarkeit des Prüfschritts

Der Prüfschritt ist anwendbar, wenn die App-Ansicht Formulare enthält, welche bei inkorrektem Ausfüllen Fehlermeldungen erzeugen. Dies kann schon während der Eingabe oder erst nach dem Abschicken des Formulars geschehen.

=== Prüfung

Formular unvollständig oder fehlerhaft ausfüllen, etwa durch das Leerlassen von Pflichtfeldern oder das Eingeben syntaktisch nicht korrekter Email-Adressen.

Falls das Abschicken des Formulars eine Fehlermeldung erzeugt: Prüfen, ob Fehlermeldungen oder Korrekturvorschläge verständlich und sinnvoll sind.

Fehlermeldungen oder Korrekturvorschläge können auf verschiedene Weise zur Verfügung gestellt werden, z.B.:

* Bei Neuanzeige des Formulars werden am Beginn der Ansicht Fehler beschrieben
* Korrekturvorschläge werden nahe der betroffenen Eingabefelder angezeigt und mit einer geeigneten Technik verknüpft

=== Hinweise

Wenn eine Fehlermeldung auf einer neuen Ansicht ausgegeben wird, wird diese wie ein Zustand der Ansicht unter der Ausgangsansicht mitgeprüft. Geprüft wird auch die Erfüllung anderer relevanter Prüfkriterien.

Bei komplizierten Formaten, z.B. Datum, hilft eine Angabe, in welcher Weise das Datum eingegeben werden soll (z.B. tt.mm.jjjj), um Fehler zu vermeiden.

Wenn Formulare keine Fehlermeldungen erzeugen, ist dies nicht negativ zu bewerten.

=== Bewertung

*Nicht erfüllt:*

* Fehlermeldungen sind unklar oder irreführend

== Quellen
=== Allgemein
* Appt.org: https://appt.org/en/guidelines/wcag/success-criterion-3-3-3#provide-solutions-for-errors[Error Suggestion: Provide solutions for errors] (mehrere Entwicklungsumgebungen)

== Einordnung des Prüfschritts

=== Abgrenzung von anderen Prüfkriterien

* Die Identifizierung und Benennung des Fehlers ist Gegenstand des Prüfschritts
ifdef::env_embedded[11.3.3.1 "Fehlererkennung".]
ifndef::env_embedded[]
  <<11.3.3.1 Fehlererkennung.adoc#,11.3.3.1 Fehlererkennung>>.
endif::env_embedded[]
Hier geht es um die Angemessenheit und Verständlichkeit der Fehlermeldung(en) selbst.

=== Einordnung des Prüfschritts nach WCAG 2.1

==== Guideline

* https://www.w3.org/WAI/WCAG21/quickref/?showtechniques=334#input-assistance[Guideline 3.3 Input Assistance: Help users avoid and correct mistakes]

==== Success criterion

* https://www.w3.org/WAI/WCAG21/quickref/?showtechniques=334#error-suggestion[3.3.3 Error Suggestion (Level AA)]

==== Techniques

.General Techniques
* https://www.w3.org/WAI/WCAG21/Techniques/general/G83.html[G83: Providing
  text descriptions to identify required fields that were not completed]
* https://www.w3.org/WAI/WCAG21/Techniques/general/G84.html[G84: Providing a
  text description when the user provides information that is not in the list
  of allowed values]
* https://www.w3.org/WAI/WCAG21/Techniques/general/G85.html[G85: Providing 
   text description when user input falls outside the required format or values]
* https://www.w3.org/WAI/WCAG21/Techniques/general/G177.html[G177: Providing
  suggested correction text]
