= Prüfschritt 11.3.2.2 Keine unerwartete Kontextänderung bei Eingabe
include::include/author.adoc[]
include::include/attributes.adoc[]

== Was wird geprüft?

Nutzereingaben auf Formularen sollen nicht zu unerwarteten Kontext-Änderungen
führen.
Alle Kontextänderungen müssen unterhalb des auslösenden Elements geschehen
und sollen klar nachvollziehbar sein, der Fokus soll nicht versetzt werden.

== Warum wird das geprüft?

Unerwartete und unangekündigte Kontextänderungen bei einer Auswahl in
Formularen (etwa eine Checkbox oder ein Radio-Button, deren Auswahl eine neue
Ansicht in einer Anwendungssoftware aufruft, oder eine Auswahlliste ohne
Submit-Button, die bei Änderung reagiert) können die Orientierung von
Nutzern beeinträchtigen.
Kontextänderungen auf der Ansicht selbst können Nutzer ablenken und
verwirren oder auch unbemerkt bleiben und dadurch für Verwirrung sorgen
(plötzlich sind Inhalte verändert).
Sie sollten deshalb erwartet und klar nachvollziehbar sein.

Wenn Kontextänderungen auf derselben Ansicht nicht unterhalb des Elements
stattfinden, das sie auslöst, werden sie von blinden Nutzer häufig nicht
wahrgenommen.

== Wie wird geprüft?

=== Anwendbarkeit des Prüfschritts

Der Prüfschritt ist anwendbar, wenn die Ansicht in der Software
Formularelemente enthält.

=== Prüfung

. App mit zu prüfender Ansicht starten
. Formularelemente (Checkboxes, Radio Buttons, Auswahllisten)
  ausprobieren, Werden unerwartete und nicht angekündigte Kontextänderungen
  erzeugt?
. Überprüfen, ob Inhaltsänderungen hervorgerufen werden (etwa Einblendungen
  zusätzlicher Formularfelder). Sind die Inhaltsänderungen begrenzt und gut
  nachvollziehbar oder werden vor dem auslösenden Element angekündigt bzw. erklärt?
. Prüfen, ob Inhaltsänderungen unterhalb des Elements, das sie auslöst,
  hervorgerufen werden.
. Prüfen, ob durch Formulareingaben hervorgerufene Kontextänderungen (etwa
  dynamisch eingeblendete Elemente) den aktuellen Fokus versetzen

=== Hinweise

Auftretende modale Dialoge müssen dabei barrierefrei sein.

Dynamische Änderungen etwa die automatische Einblendung von Vorschlägen
unterhalb des Texteingabefelds einer Such-Funktion, sollen nicht den aktuellen
Fokus versetzen.

*Zur Abgrenzung von Kontextänderungen und Inhaltsänderungen:*

Klare Kontextänderungen (changes of context) sind laut WCAG 2.1 etwa Sprünge
zu anderen Seiten und das Öffnen neuer Fenster, aber auch das dynamische
Laden von neuen Inhalten auf der selben Seite, wenn diese Inhalte wie eine neue
Seite wirken oder Inhalte in stark veränderter Anordnung erscheinen.
Auch das Auslösen von Sprunglinks zu Ankern auf derselben Seite ist als
Kontextänderung zu betrachten.

Davon abgrenzen muss man bloße Inhaltsänderungen (in den WCAG 2.1:
changes of content). Diese liegen vor, wenn etwa die Auswahl in einer
Auswahlliste (select) die Inhalte einer darunter befindlichen Auswahlliste
dynamisch aktualisiert (etwa: die Wahl eines Kontinents aktualisiert eine
Auswahlliste mit Ländern).
Auch das Ausklappen zusätzlicher Formularbereiche unterhalb des auslösenden
Elements kann als Inhaltsänderung gelten, wenn Fokus und Scrollstatus der
Seite unverändert bleiben.

Ob Änderungen unerwartet sind oder nicht, lässt sich nur aus dem
Gesamtkontext heraus bestimmen.

Vergleiche: WCAG 2.1, Appendix A:
https://www.w3.org/TR/WCAG21/#dfn-change-of-context[Glossary: changes of
context]

=== Bewertung

*Nicht voll erfüllt:*

* Die Interaktion mit Formularelementen führt zu unerwarteten und nicht
  angekündigten Kontextänderungen.

*Nicht erfüllt:*

* Formulare werden automatisch abgeschickt, wenn der Fokus das Formular
  verlässt.
* Das Ändern des Status einer Checkbox oder eines Radio-Buttons löst
  automatisch eine unerwartete Kontextänderung aus (öffnet etwa ein neues
  Fenster).

== Einordnung des Prüfschritts

=== Abgrenzung von anderen Prüfkriterien

* Die Verwendung von Submit-Buttons, die in den Techniken
  https://www.w3.org/WAI/WCAG21/Techniques/general/G80.html[G80]
  und H32 dem
  Success Criterion
  link:++https://www.w3.org/TR/WCAG21/#on-input++[On input]
  zugeordnet ist, wird nur indirekt im Prüfschritt
ifdef::env_embedded[11.2.1.1 "Tastaturbedienung"]
ifndef::env_embedded[]
  <<11.2.1.1 Tastaturbedienung.adoc#,11.2.1.1 Tastaturbedienung>>
endif::env_embedded[]
  geprüft.

=== Einordnung des Prüfschritts nach WCAG 2.1

==== Guideline

* https://www.w3.org/TR/WCAG21/#predictable[Guideline 3.2 Predictable: Make
  Web pages appear and operate in predictable ways]

==== Success criterion

* https://www.w3.org/TR/WCAG21/#on-input[3.2.2 On Input] (Level A)

==== Techniques

.General Techniques
* https://www.w3.org/WAI/WCAG21/Techniques/general/G80.html[G80: Providing a
  submit button to initiate a change of context using a technology-specific
  technique listed below]
+
  Hinweis: Die Technik G80 ist SC 3.2.2 zugeordnet, wird aber nur indirekt
  geprüft.

* https://www.w3.org/WAI/WCAG21/Techniques/general/G13.html[G13: Describing
  what will happen before a change to a form control that causes a change of context to occur is made]

==== Failures

* https://www.w3.org/WAI/WCAG21/Techniques/failures/F36.html[F36: Failure of
  Success Criterion 3.2.2 due to automatically submitting a form and
  presenting new content without prior warning when the last field in the form
  is given a value]
* https://www.w3.org/WAI/WCAG21/Techniques/failures/F37.html[F37: Failure of
  Success Criterion 3.2.2 due to launching a new window without prior warning
  when the status of a radio button, check box or select list is changed]
