= Prüfschritt 11.4.1.2 Name, Rolle, Wert verfügbar
include::include/author.adoc[]
include::include/attributes.adoc[]

== Was wird geprüft?

Alle Bedienelemente einer App (also etwa Tasten, oder Formularelemente wie Checkboxen oder Eingabefelder) müssen semantische Informationen (Name, Rolle, Wert) programmatisch bereitstellen. Dies ermöglicht Hilfsmitteln wie Screenreadern, die Bedeutung und Funktion der Elemente zu kommunizieren. Nutzende können auf diese Weise die Elemente verstehen und bedienen. Bei nativen Elementen, also solchen, die mit den Standardelementen der Entwicklungsumgebungen umgesetzt sind, ist dies in der Regel ohne weiteres Zutun gegeben. 

Werden Bedienelemente selbst erstellt (das heißt, es werden keine Standardelemente verwendet), müssen semantische Informationen wie Name, Rolle und Wert gegebenenfalls explizit definiert werden, damit die entsprechenden Informationen an die Hilfsmittel übergeben und in der Folge den Nutzenden ausgegeben werden.

Bei Software werden dazu die Accessibility-Schnittstellen des jeweiligen Betriebssystems genutzt.

== Warum wird das geprüft?

Für sehende Nutzende ist die Bedeutung von Bedienelementen in der Regel intuitiv verständlich. Dies ist insbesondere der Fall, wenn sie in einer konventionellen, also üblichen Weise umgesetzt sind und ein Abgleich mit bereits gespeicherten Erfahrungen stattfinden kann. Beispiele wären etwa eine Menü-Taste aus drei horizontalen Strichen (das sogenannte "Hamburger"-Icon) oder ein Lupen-Icon zum Auslösen einer Suche. Bei vielen Tasten und Eingabefeldern macht die Beschriftung das Element verständlich. 

Menschen, die eine Webseite nicht-visuell nutzen, sind darauf angewiesen, dass Informationen zur Bedeutung eines Elements, deren Beschriftung und Zustand (Name, Rolle, Wert) auf einer abstrakten Ebene zur Verfügung stehen und assistive Technologien diese nutzen können. Man bezeichnet das auch als programmatische Ermittelbarkeit. Wenn ein Element - etwa ein grafischer Menü-Schalter - erreicht wird, sollte an Screenreader-Nutzende ausgegeben werden: "Navigation, Taste, reduziert". "Navigation" ist der hinterlegte Name, "Taste" die Rolle, und "reduziert" der Wert bzw. Zustand. Nutzende wissen dann, dass die Aktivierung dieses Elements ein Navigation einblenden wird. 

Wenn Bedienelemente mit den von der Entwicklungsumgebung bereitgestellten Standard-Schnittstellen-Elementen umgesetzt werden, sind Rollen und Zustände in der Regel ohne weiteres Zutun programmatisch verfügbar. So sollten in iOS etwa Textfelder über das Standardelement `UITextField` umgesetzt werden und Schalter als `UIButton`.

Werden keine Standardelemente genutzt und die Bedienelemente selbst gebaut (etwa eine Grafik wird als Schalter eingesetzt), gibt es je nach Plattform geeignete Wege, um Namen, Rollen (die Art des Bedienelements) und Werte bzw. typisches Verhalten des Elements programmatisch zu setzen. Wenn das geschieht, ist die Semantik auch bei nicht-visueller Nutzung (beispielsweise beim Einsatz des systemseitigen Screenreaders) verfügbar. Bei IOS dienen zur Hinterlegung eines Namens das Attribut https://developer.apple.com/documentation/objectivec/nsobject/1615181-accessibilitylabel[`AccessibilityLabel`] und zur Definition der Rolle und des Zustandes die https://developer.apple.com/documentation/objectivec/nsobject/uiaccessibility/accessibility_traits[Accessibility Traits]. Bei Android leistet dies das https://developer.android.com/guide/topics/ui/accessibility/apps#describe-ui-element[`contentDescription`]-Attribut.

== Wie wird geprüft?

=== 1. Anwendbarkeit des Prüfschritts

Der Prüfschritt ist immer anwendbar, wenn die App Bedienelemente einsetzt. Aus Sicht der prüfenden Person ist nicht immer zu erkennen, ob Standardelemente der Entwicklungsumgebungen verwendet werden (und damit quasi von Haus aus zugänglich sind) oder von Entwicklerinnen und Entwicklern selbst definiert wurden. Eine Sichtprüfung reicht deshalb *nicht* aus. Bedienelemente müssen mit dem Screenreader fokussiert und aktiviert werden, um festzustellen, ob die jeweiligen Namen, Rollen und Werte vom Screenreader ausgegeben und auch Zustandsänderungen richtig kommuniziert werden.

=== 2. Prüfung

Für eine Prüfung mit VoiceOver / iOS müssen die AI/OCR-Erkennungsfunktionen ausgeschaltet sein (siehe "3. Hinweise").

. App mit zu prüfender Ansicht öffnen.
. Screenreader starten und Fokus mit Hilfe der Wischgeste auf jedes interaktive Element setzen.
. Prüfen, ob der Name, die Rolle und der Wert des Bedienelements vom Screenreader korrekt ausgegeben wird (siehe auch "3. Hinweise").
. Gegebenenfalls prüfen, ob der geänderte Wert des Elements (Zustand) nach Eingabe korrekt ausgegeben wird.

=== 3. Hinweise
Der Name identifiziert und bezeichnet ein Element näher. Nutzende von Spracheingabe-Software können beispielsweise eine Schaltfläche mit Hilfe des zugänglichen Namens (der Beschriftung) gezielt ansprechen und bedienen. Ein Screenreader gibt den zugänglichen Namen aus, wenn er das Element fokussiert. Er ist meist gleichlautend mit dem Label des Bedienelements. Z. B. "Nachname" für ein Eingabefeld.

Beispiele für Rollen sind u.a. "Taste" bzw. "Schaltfläche", "Eingabefeld" bzw. "Bearbeitungsfeld", "Suchfeld", "Ausklappliste", und "Markierungsfeld" bzw. "Kästchen".

Der Wert beschreibt z. B. den Inhalt des Bedienelements z. B. "Müller" bei einem Eingabefeld für Nachnamen. Er vermittelt aber auch den Zustand eines Elements (sofern es unterschiedliche Zustände haben kann), z. B. "ausgewählt" für ein ausgewählten Listeneintrag oder eine angekreuzte Checkbox.

==== Einstellungen für die Prüfung mit VoiceOver / iOS

Die AI/OCR-Erkennungsfunktionen von VoiceOver müssen ausgeschaltet sein:

- iOS 14+: Einstellungen > Bedienungshilfen > VoiceOver > VoiceOver-Erkennung. (Diese Funktion wird nur auf iPhone XS/XR-Modellen und höher unterstützt).

- iOS 13: Einstellungen > Bedienungshilfen > VoiceOver > Verbosität > Sprechen erkannt > Sprechen von erkanntem Text und Bildern.

=== 4. Bewertung

*Nicht erfüllt:*

Wichtige Bedienelemente sind mit mit benutzerdefinierten Bedienelementen (Custom Controls) umgesetzt, auf eine Nachbildung der Semantik für die Barrierefreiheitsschnittstellen des Systems, wurde verzichtet. Name, Rolle, Wert werden vom Screenreader nicht korrekt ausgegeben.

== Einordnung des Prüfschritts

=== Abgrenzung von anderen Prüfkriterien

In diesem Prüfschritt geht es nicht um die Bewertung der
  Tastaturbedienbarkeit  von selbsterstellten Bedienelementen.
  Dies ist Gegenstand von Prüfschritt
ifdef::env_embedded[11.2.1.1 "Tastaturbedienung".]
ifndef::env_embedded[]
  <<11.2.1.1 Tastaturbedienung.adoc#,11.2.1.1 Tastaturbedienung>>.
endif::env_embedded[]

=== Einordnung des Prüfschritts nach WCAG 2.1

==== Guideline

* https://www.w3.org/TR/WCAG21/#compatible[Guideline 4.1 Compatible]:
  Maximize compatibility with current and future user agents, including
  assistive technologies.

==== Success criterion

* https://www.w3.org/TR/WCAG21/#name-role-value[4.1.2 Name, Role, Value
  (Level A)]

==== Techniques

.General Techniques
* https://www.w3.org/WAI/WCAG21/Techniques/general/G10.html[G10: Creating
  components using a technology that supports the accessibility API features
  of the platforms on which the user agents will be run to expose the names
  and roles, allow user-settable properties to be directly set, and provide
  notification of changes]
* https://www.w3.org/WAI/WCAG21/Techniques/general/G108.html[G108: Using
  markup features to expose the name and role, allow user-settable properties
  to be directly set, and provide notification of changes]
* https://www.w3.org/WAI/WCAG21/Techniques/general/G135.html[G135: Using the
  accessibility API features of a technology to expose names and roles, to
  allow user-settable properties to be directly set, and to provide
  notification of changes]

==== Failures

* https://www.w3.org/WAI/WCAG21/Techniques/failures/F15.html[F15: Failure of
  Success Criterion 4.1.2 due to implementing custom controls that do not use
  an accessibility API for the technology, or do so incompletely]
* https://www.w3.org/WAI/WCAG21/Techniques/failures/F20.html[F20: Failure of
  Success Criterion 1.1.1 and 4.1.2 due to not updating text alternatives when
  changes to non-text content occur]
* https://www.w3.org/WAI/WCAG21/Techniques/failures/F59.html[F59: Failure of
  Success Criterion 4.1.2 due to using script to make div or span a user
  interface control in HTML]
* https://www.w3.org/WAI/WCAG21/Techniques/failures/F79.html[F79: Failure of
  Success Criterion 4.1.2 due to the focus state of a user interface component
  not being programmatically determinable or no notification of change of
  focus state available]

== Quellen

=== Ressourcen für Entwickler

==== iOS Developer: ====

* https://developer.apple.com/documentation/uikit/uiaccessibility/uiaccessibilitytraits[UIAccessibilityTraits]
* https://developer.apple.com/documentation/swiftui/accessibilitytraits[AccessibilityTraits]

==== Android Developer: ====
* https://developer.android.com/guide/topics/ui/accessibility/apps[Make apps more accessible]
* https://developer.android.com/reference/android/accessibilityservice/package-summary[android.accessibilityservice]
* https://medium.com/google-developer-experts/state-descriptions-on-android-b2029283871f[State Descriptions on Android]
