= Prüfschritt 11.4.1.1 Korrekte Syntax
include::include/author.adoc[]
include::include/attributes.adoc[]

*Hinweis: Dies ist ein Entwurf. Inhalte können sich jederzeit ändern.* 

== Was wird geprüft?
Es wird nur geprüft, ob die App über Markup-Sprachen umgesetzte Inhalte enthält (in der Regel sind dies Webviews). In diesem Fall ist der Prüfschritt automatisch erfüllt. Gibt es nur native Inhalte (keine Webviews) ist der Prüfschritt nicht anwendbar.

Eine inhaltliche Prüfung findet nicht statt.

Das veraltete Erfolgskriterium hinter diesem Prüfschritt verlangte, dass Inhalte, die über Markup-Sprachen umgesetzt werden, folgende Anforderungen erfüllen:

* sie besitzen vollständige Start- und Endtags
* sie sind gemäß Spezifikation korrekt verschachtelt
* sie enthalten keine doppelten Attribute
* alle ihre IDs sind eindeutig, außer dort wo die Spezifikationen etwas anderes erlauben

Native Inhalte von Apps fallen nicht unter diese Anforderung. Sie wäre anwendbar auf Inhalte in Webviews, ist dort aber in der Regel nicht überprüfbar. 

== Warum wird das geprüft?

Es wird inhaltlich nicht geprüft. Die Prüfung der zugrundeliegenden Erfolgskriteriums selbst wird nicht länger als sinnvoll erachtet, da die modernen, in Webviews transparent genutzten User Agents (Browser) Syntax-Fehler auf einheitliche Weise automatisch korrigieren und Probleme, die Verletzungen des HTML Content Models auftreten, in anderen Prüfschritten identifiziert und bewertet werden können. Eine praktische Prüfung ist im Kontexts nativer Apps nicht möglich, es sei denn, die HTML-Quellen von Webviews wären dokumentiert würden außerhalb der App in einem Verfahren für Web-Zugänglichkeit geprüft. 

== Wie wird geprüft?

=== Anwendbarkeit des Prüfschritts:
Der Prüfschritt ist prinzipiell nur anwendbar, wenn die App Inhlate in Markup-Sprachen (Webviews) enthält.

=== Prüfung
Es wird lediglich geprüft, ob die App Webviews enthält. Ist das der Fall, ist der Prüfschritt erfüllt.
Sind keine Webviews vorhansden, ist der Prüfschritt nicht anwendbar.

=== Hinweise

* Wenn nicht eindeutig festzustellen ist, ob de iApp Webviews enthäht, sollte der Prüfschritt mit "nicht anwendbar" bewertet werden.

=== Bewertung

==== Erfüllt:
* Die App enthält Webviews. Der Prüfschritt ist dann immer erfüllt.

==== Nicht anwendbar:
* Die App enthält keine Webviews (Inhalte in Markup-Sprachen).


== Einordnung des Prüfschritts

=== Einordnung des Prüfschritts nach WCAG 2.1

==== Guideline

* https://www.w3.org/TR/WCAG21/#compatible[Guideline 4.1 Compatible: Maximize
  compatibility with current and future user agents, including assistive
  technologies]

==== Success criterion

* https://www.w3.org/TR/WCAG21/#parsing[4.1.1 Parsing (Level A)]

==== Techniques

.General Techniques
* https://www.w3.org/WAI/WCAG21/Techniques/general/G192.html[G192: Fully
  conforming to specifications]

==== Failures

* https://www.w3.org/WAI/WCAG21/Techniques/failures/F70.html[F70: Failure of
  Success Criterion 4.1.1 due to incorrect use of start and end tags or
  attribute markup]
* https://www.w3.org/WAI/WCAG21/Techniques/failures/F77.html[F77: Failure of
  Success Criterion 4.1.1 due to duplicate values of type ID]

== Quellen

[.BLOCK_LANG_EN]
Validation will usually eliminate ambiguities (and more) because an essential
step in validation is to check for proper use of that technology's markup (in
a markup language) or code (in other technologies).
Validation does not necessarily check for full conformance with a
specification but it is the best means for automatically checking content
against its specification.

(https://www.w3.org/WAI/WCAG21/Techniques/general/G134[WCAG 2.1
  Technik G134: Validating web pages])
