= Prüfschritt 11.4.1.1 Syntaxanalyse
include::include/author.adoc[]
include::include/attributes.adoc[]

== Was wird geprüft?
Es wird nur geprüft, ob die App über Markup-Sprachen umgesetzte Inhalte enthält (in der Regel sind dies Webviews). In diesem Fall ist der Prüfschritt automatisch erfüllt. Gibt es nur native Inhalte (keine Webviews) ist der Prüfschritt nicht anwendbar.

Eine inhaltliche Prüfung findet nicht statt.

Das veraltete Erfolgskriterium hinter diesem Prüfschritt verlangte, dass Inhalte, die über Markup-Sprachen umgesetzt werden, folgende Anforderungen erfüllen:

* sie besitzen vollständige Start- und Endtags
* sie sind gemäß Spezifikation korrekt verschachtelt
* sie enthalten keine doppelten Attribute
* alle ihre IDs sind eindeutig, außer dort wo die Spezifikationen etwas anderes erlauben

Native Inhalte von Apps fallen nicht unter diese Anforderung. Sie wäre prinzipiell anwendbar auf Inhalte in Webviews innerhalb nativer Apps, ist dort aber in der Regel nicht überprüfbar. 

== Warum wird das geprüft?

Es findet keine inhaltliche Prüfung statt. Die Prüfung der zugrundeliegenden Erfolgskriteriums selbst wird nicht länger als sinnvoll erachtet, da die modernen, in Webviews transparent genutzten User Agents (die Browser) Syntax-Fehler auf einheitliche Weise automatisch korrigieren und Probleme, die durch Verletzungen des HTML Content Models auftreten, in anderen Prüfschritten identifiziert und bewertet werden können. Eine praktische Prüfung ist im Kontexts nativer Apps wegen fehlendem Quelltextzugang und fehlenden Validierungsmöglichkeiten durch Prüfer ohne Zugang zur Entwicklungsumgebung nicht möglich, es sei denn, die HTML-Quellen von Webviews wären dokumentiert und würden außerhalb der App in einem Verfahren für Web-Zugänglichkeit geprüft. 

== Wie wird geprüft?

=== 1. Anwendbarkeit des Prüfschritts:
Der Prüfschritt ist prinzipiell nur anwendbar, wenn die App Inhalte in Markup-Sprachen (in der Regel in Webviews) enthält.

=== 2. Prüfung
Es wird lediglich geprüft, ob die App Webviews enthält. Ein sicheres Anzeichen dafür ist die Ausgabe "Webview" bei Fokussierung von Webview-Inhalten, ein weiteres Anzeichen die Ausgabe von Elementen, die in nativen Apps in der Regel nicht vorkommen, z.B. Überschriften auf verschiedenen Ebenen. 

=== 3. Hinweise

Wenn nicht eindeutig festzustellen ist, ob die App Webviews enthält, sollte der Prüfschritt mit "nicht anwendbar" bewertet werden.

=== 4. Bewertung

==== Erfüllt:
* Die App enthält Webviews. 

==== Nicht anwendbar:
* Die App enthält keine Webviews (Inhalte in Markup-Sprachen wie HTML).

== Quellen
=== Allgemein
* Appt.org: https://appt.org/en/guidelines/wcag/success-criterion-4-1-1[Parsing: Make use of linting] (mehrere Entwicklungsumgebungen)

== Einordnung des Prüfschritts

=== Einordnung des Prüfschritts nach WCAG 2.1

==== Guideline

* https://www.w3.org/TR/WCAG21/#compatible[Guideline 4.1 Compatible: Maximize
  compatibility with current and future user agents, including assistive
  technologies]

==== Success Criterion

* https://www.w3.org/TR/WCAG21/#parsing[4.1.1 Parsing (Level A)]

==== Techniques

===== General Techniques

* https://www.w3.org/WAI/WCAG21/Techniques/general/G192.html[G192: Fully
  conforming to specifications]

===== Failures

* https://www.w3.org/WAI/WCAG21/Techniques/failures/F70.html[F70: Failure of
  Success Criterion 4.1.1 due to incorrect use of start and end tags or
  attribute markup]
* https://www.w3.org/WAI/WCAG21/Techniques/failures/F77.html[F77: Failure of
  Success Criterion 4.1.1 due to duplicate values of type ID]
