= 11.5.2.5 Programmatisch ermittelbare UI-Elemente
include::include/author.adoc[]
include::include/attributes.adoc[]

*Hinweis: Dies ist ein Entwurf. Inhalte können sich jederzeit ändern.*

== Was wird geprüft?

Die Eigenschaften von Bedienelementen der App sollen programmatisch ermittelbar sein.
Dann können die zum Beispiel von einen Screenreader sinnvoll ausgegeben werden.

Im Einzelnen sollen die folgenden Eigenschaften programmatisch ermittelbar sein:

* *Name (name)* des Bedienelements: Dies kann die Beschriftung sein z.B. "Senden", "Bestellen", Sortieren" usw. Bei Icons (Menü mit Hamburger-Icon, Suchen-Lupe, Filter-Symbol usw.) soll der Name die Funktion bezeichen, also "Menü", "Suchen", "Filtern"
* *Rolle (role)* des Bedienelements: Diese gibt den Typ des Bedienelements, z. B. "Taste" (iOS) bzw. Schaltfläche" (Android) oder "Textfeld" (iOS) bzw. "Bearbeitungsfeld" (Android)
* *Zustand (state)* oder Wert des Bedienelements: Zum Beispiel "aktiviert"/"nicht aktiviert", "ein"/"aus", ausgewählt / nicht ausgewählt, "67 Prozent"
* *Grenzen (boundary)* der Werte eines Bedienelements, z. B. "Prozent" (n von 100) oder Preisspanne 300 - 500
* *Beschreibung (description)* des Bedienelements: Dies kann eine zusätzliche Beschreibung des Elements sein

Insbesondere der Status und die Bedienelement-Grenzen (boundaries) sollten nur dann vermittelt werden, wenn diese auch visuell durch das Bedienelement vermittelt werden

== Warum wird das geprüft?

Von Bedienelementen visuell vermittelte Informationen sollen auch programmatisch verfügbar sein, damit Hilfsmittel wie Screenreader die Informationen ausgeben können.

== Wie wird das geprüft?

=== 1. Anwendbarkeit des Prüfschritts

Der Prüfschritt ist anwendbar, wenn in der App-Ansicht Bedienelemente eingesetzt werden, die nicht vom Betriebssystem bereitgestellt werden (Custom controls, von Entwicklern definierte Bedienelemente).
Eine Sichtprüfung reicht dabei nicht aus, da rein visuell nicht mit Sicherheit festgestellt werden kann, ob es sich um ein Custom Control handelt.

=== 2. Prüfung

Die Anforderung wird durch den Prüfschritt
ifdef::env_embedded[11.4.1.2 "Name, Rolle, Wert verfügbar"]
ifndef::env_embedded[]
<<11.4.1.2 Name-Rolle-Wert verfügbar.adoc#,11.4.1.2 Name, Rolle, Wert verfügbar>>
endif::env_embedded[]
abgedeckt.
Dabei müssen Grenzen von Bedienelementen berücksichtigt werden (z. B. Wertebereich eines Eingabefelds).
Diese Begrenzungen müssen ebenfalls programmatisch verfügbar sein und dementsprechend vom Screenreader vorgelesen werden.

== Einordnung des Prüfschritts

=== Einordnung des Prüfschritts nach EN 301 549 V3.1.1

11.5.2.5 Object information

== Quellen

[.BLOCK_LANG_EN]
=== 11.5.2.5 Object information

____
[.BLOCK_LANG_EN]
--
Where the software provides a user interface it shall, by using the services as described in clause 11.5.2.3, make the user interface elements' role, state(s), boundary, name, and description programmatically determinable by assistive technologies.
--
____

(Aus EN 301 549 V3.1.1 Abschnitt 11.5.2.5 "Object information")
