= Prüfschritt 11.5.2.13 Fokusverfolgung, Texteinfügemarke und Textauswahl
include::include/author.adoc[]
include::include/attributes.adoc[]

== Was wird geprüft?

Informationen und Mechanismen für die Fokusverfolgung, Texteinfügemarke und Textauswahl müssen für die Hilfsmitteltechnologie programatisch verfügbar sein.

== Warum wird das geprüft?

Wenn die App grundsätzlich die Auswahl von Text zulässt, etwa zum Kopieren oder Editieren von Texteingaben, sollen die dazugehörigen Funktionen wie die Bestimmung der Textauswahl auch für Hilfsmittelnutzer verfügbar sein.

Informationen und Mechanismen für die Fokusverfolgung, Texteinfügemarke und Textauswahl müssen für die Hilfsmitteltechnologie programmatisch verfügbar sein.

== Wie wird geprüft?

=== 1. Anwendbarkeit des Prüfschritts

Der Prüfschritt ist anwendbar, wenn die App Texteingaben vorsieht oder Textbestandteile der App ausgewählt und kopiert werden können.

=== 2. Prüfung

* Wird die Fokusposition innerhalb von Textfeldern oder auswählbaren Textbestandteilen der App vom Screenreader ausgegeben?
* Unterstützt der Inhalt, soweit verfügbar, die vom System und Screenreader vorgesehenen Mechanismen der Textauswahl hinsichtlich der Ansage (an welcher Position befindet sich die Texteinfügemarke, welcher Text ist markiert)?

==== 2.1 Textauswahl in iOS / VoiceOver
* VoiceOver aktivieren
* Ein Textfeld mit Textinhalt durch Doppeltippen aktivieren. Es wird in der Regel "Einfügemarke am Ende" angesagt.
* Wenn kein Text im Feld vorhanden ist, etwas Text eingeben.
* Den VoiceOver-Rotor auf "Textauswahl" stellen. 
* Ggf. über vertikales Wischen auf "Zeichenauswahl" stellen.
* Steht der Cursor am Ende, soll horizontales Wischen nach links die Auswahl um je ein weiteres Zeichen erweitern. Steht der Cursor am Anfang, geschieht die Auswahl über horizontales Wischen nach rechts. Die Auswahl wird ausgegeben. 

==== 2.2 Textauswahl in Android / TalkBack
* TalkBack aktivieren
* Der Bearbeitungsmodus wird durch 2-Finger-Doppeltippen und Halten aktiviert.
* Die Fokusposition wird in der Regel mit den Lautstärketasten des Geräts versetzt.
* Über das lokale Kontextmenü (Wischen nach oben und dann nach rechts) können Optionen zum Textauswahl-Modus, zum Kopieren usw. aufgerufen werden.

== Einordnung des Prüfschritts

=== Abgrenzung zu anderen Prüfschritten

Die Textauswahl kann je nach Screenreader und Betriebssystem unterschiedlich sein. In diesem Prüfschritt geht es darum, dass die aktuelle Position des Fokus vom Screenreader augegeben werden kann und dass der gerade markierte Text ausgegeben werden kann. In 11.5.2.14 wird dagegen bewertet, ob die Position des Fokus und die Markierung des Texts geändert werden kann.

== Quellen
* https://support.google.com/accessibility/android/answer/6151827?hl=en#zippy=%2Cversion-up%2Cversion-lower[Google-Hilfe zu TalkBack-Gesten]
* https://bbc.github.io/accessibility-news-and-you/accessibility-and-testing-with-talkback.html[BBC Accessibility and Testing with TalkBack]
* https://seeingdifferentuk.blogspot.com/2015/06/selecting-copying-and-pasting-with.html[Blogbeitrag SeeingDifferent zu Auswahl, Kopieren, Einfügen mit VoiceOver in iOS]

=== Auszug EN 301 549

[.BLOCK_LANG_EN]
==== 11.5.2.13 Tracking of focus and selection attributes 

[.BLOCK_LANG_EN]
Where software provides a user interface it shall, by using the services as
described in clause 11.5.2.3, make information and mechanisms necessary to
track focus, text insertion point, and selection attributes of user interface
elements programmatically determinable by assistive technologies.
