= Prüfschritt 11.5.2.7 Werte
include::include/author.adoc[]
include::include/attributes.adoc[]

*Hinweis: Dies ist ein Entwurf. Inhalte können sich jederzeit ändern.*

== Was wird geprüft?

Falls für Formularelemente minimale oder maximale Eingabewerte festgelegt sind und visuell vermittelt werden, muss diese Information auch programmatisch verfügbar sein.

== Warum wird das geprüft?
Informationen über minimale oder maximale Eingabewerte, die visuell vermittelt werden, sollen für nicht-visuelle Nutzende auch programmatisch ermittelbar sein, um erfolglose Eingaben unzulässiger Werte zu vermeiden.

== Wie wird geprüft?
=== 1. Anwendbarkeit des Prüfschritts
Der Prüfschritt ist auf Ansichten mit Formularen anwendbar.

=== 2. Prüfung
. Formulare visuell auf Vorhandensein von Feldern oder Reglern für numerische Eingaben überprüfen.
. Gibt es visuell vermittelte Begrenzungen der Eingabewerte? Wenn diese visuell verfügbar sind, etwa über Legenden, Beschriftungen oder Textvorbelegungen, müssen minimale bzw. maximale Werte auch für Screenreader ermittelbar sein.
. Elemente mit dem Screenreader fokussieren. Visuell verfügbare minimale bzw. maximale Eingabe-Werte und der aktuell eingestellte Wert sollen vom Screenreader ausgegeben werden.

=== 3. Hinweise
Eingabe-Grenzen können auch implizit vermittelt werden. So ist etwa bei Reglern, die nach dem Wert "Prozent" ausgeben, klar, dass Werte auf den Bereich von 0% - 100% eingegrenzt sind.

=== 4. Bewertung
==== Erfüllt:
Bei Fokussierung des Eingabefelds oder des Reglers werden Grenzen explizit oder mittelbar (etwa über die Ausgabe von Prozent) ausgegeben.

==== Eher erfüllt:
Eine getrennt fokussierbare, vom Screenreader ausgegebene Beschriftung unmittelbar vor dem Eingabefeld oder Regler informiert über minimale bzw. maximale Eingabe-Werte.

== Quellen

=== Auszug EN 301 549

[.BLOCK_LANG_EN]
==== 11.5.2.7 Values 
____
[.BLOCK_LANG_EN]
Where the software provides a user interface, it shall, by using the services as described in clause 11.5.2.3, make the current value of a user interface
element and any minimum or maximum values of the range, if the user interface element conveys information about a range of values, programmatically
determinable by assistive technologies.
____
