= Prüfschritt 11.5.2.7 Minimale und maximale Werte programmatisch ermittelbar
include::include/author.adoc[]
include::include/attributes.adoc[]

== Was wird geprüft?

Falls für Formularelemente minimale oder maximale Eingabewerte vorgegeben sind, muss diese Information auch dem Screenreader zur Verfügung stehen, damit Hilfsmittel-Nutzende programmatisch ebenfalls über die Grenzen der Eingabemöglichkeiten in Kenntnis gesetzt werden. Beispiele: 
* Bei einem Kaufvorgang, etwa für ein Konzertticket, kann bei "Anzahl" maximal die Zahl 5 eingegeben werden.
* Die Mindest-Spendensumme bei einem Hilfswerk ist 5 Euro.
* Ein Datumsfeld "Geburtsdatum" erlaubt nur Eingaben von Geburtsdaten, die älter als 18 Jahre sind, weil nur Volljährige den Dienst nutzen können.

== Warum wird das geprüft?
Wenn für sehende Nutzende Minimalwerte und Maximalwerte für Schnittstellen-Elemente definiert wurden, soll diese Grenzen auch für Hilfsmittelnutzende zur Verfügung stehen. Diese Grenzen transportieren häufig wichtige Informationen (z.B. Mindestdauer oder Maximaldauer bei der Buchung eines Services, Minimalbetrag einer Spende, Maximalbetrag einer Überweisung) die allen zur Verfügung stehen sollen. Die Verfügbarkeit der Information über minimale oder maximale Eingabewerte sorgt dafür, dass von Hilfsmittelnutzenden nicht erfolglos Eingaben außerhab des gültigen Bereichs versucht werden.

== Wie wird das geprüft?
=== 1. Anwendbarkeit des Prüfschritts
Der Prüfschritt ist immer anwendbar, wenn für Schnittstellenelemente sichtbar oder programmatisch minimale und/oder maximale Eingabewerte festgelegt wurden.

=== 2. Prüfung
. Screenreader aktivieren
. Formularelemente, für die visuell oder programmatisch, etwy durch clientseitige Überprüfung von Eingaben mittels JavaScript,  minimale und/oder maximale Werte für die Eingabe festgelegt wurden, fokussieren.  Werden diese Eingabegrenzen vom Screenreader ausgegeben?

=== 3. Hinweise

=== 4. Bewertung




== Quellen

=== Auszug EN 301 549

[.BLOCK_LANG_EN]
==== 11.5.2.7 Values 

[.BLOCK_LANG_EN]
Where the software provides a user interface, it shall, by using the services
as described in clause 11.5.2.3, make the current value of a user interface
element and any minimum or maximum values of the range, if the user interface
element conveys information about a range of values, programmatically
determinable by assistive technologies.
