= 11.5.2.17 Bearbeitung von Text und anderen Werten
include::include/author.adoc[]
include::include/attributes.adoc[]

== Was wird geprüft?
Die Prüfung erfolgt im Wesentlichen in der gleichen Weise wie beim Prüfschritt 11.4.1.2 "Name, Rolle, Wert verfügbar". Hier wird bewertet, ob sich Werte von Bedienelementen und modifizierbarer Text, etwa bei Eingabefeldern, auch bei aktivierten Hilfsmitteln modifizieren lassen.

== Warum wird das geprüft?

Hilfsmittel-Nutzenden soll es möglich sein, alle Werte von Bedienelementen zu ändern, die sich ohne die Nutzung von Hilfsmitteln ändern lassen.

== Wie wird das geprüft?

=== 1. Anwendbarkeit des Prüfschritts

Der Prüfschritt ist immer anwendbar, wenn die App Bedienelemente einsetzt, bei denen sich Werte (z.B. Zustände oder Textinhalte) ändern lassen. Aus Sicht der prüfenden Person ist nicht immer zu erkennen, ob Standardelemente der Entwicklungsumgebungen verwendet werden (und damit quasi von Haus aus zugänglich sind) oder von Entwickler:innen selbst definiert wurden. Eine Sichtprüfung reicht deshalb *nicht* aus. Bedienelemente müssen mit dem Screenreader fokussiert werden und der Wert muss geändert werden, um festzustellen, ob Zustandsänderungen auch bei aktiviertem Screenreader möglich sind.

=== 2. Prüfung

. App mit zu prüfender Ansicht öffnen.
. Screenreader starten und Fokus mit Hilfe der Wischgeste auf jedes interaktive Element setzen.
. Prüfen, ob sich Werte von Elementen (Zustände) mit aktiviertem Screenreader ändern lassen: Checkboxen bzw. Umschalter lassen sich aktivieren/deaktivieren, Werte in Schiebereglern lassen sich erhöhen oder verringern, Text in Texteingabefeldern lässt sich ändern, Ausklappbereiche lassen sich öffnen und schließen, usw.
. Dass geänderte Werte nach Eingabe korrekt ausgegeben werden, wird in Prüfschritt 11.4.1.2 erfasst (für Fokusposition und Textauswahl außerdem in Prüfschritt 11.5.2.13).

=== 3. Hinweise

==== 3.1 Prüfung zugänglicher alternativer Versionen

Wenn ein Bedienelement vorhanden sind, das sich in der Nutzung ohne Screenreader aktivieren lässt, für Screenreader jedoch nicht programmatisch verfügbar ist, ist zu prüfen, ob es im Kontext eine äquivalente zugängliche Möglichkeit für die Aktivierung der unterlegten Funktion gibt. Beispiel: Ein Schieberegler ist für Screenreader nicht programmatisch ermittelbar, es gibt darunter jedoch eine zugängliches Bedienelement, über das der Wert eingestellt werden kann. Wenn Elemente programmatisch verfügbar sind, müssen sie auch bedienbar sein, also Änderungen des Werts unterstützen.

==== 3.2 Hinweise zur Teamprüfung

Bei der Beurteilung, ob sich Werte erfolgreich ändern lassen, ist ggf. sehende Assistenz nötig, nämlich dann, wenn sich ein Wert bei Aktivierung mit eingeschaltetem Screenreader zwar ändert, der geänderte Wert selbst aber nicht programmatisch ermittelbar ist. Dies ist dann ein Mangel, der im Prüfschritt 11.4.1.2 "Name, Rolle, Wert verfügbar" zu erfassen wäre. 

=== 4. Bewertung

==== Erfüllt:

Werte von Bedienelementen (einschließlich Textinhalte editierbarer Textfelder) lassen sich mit aktiviertem Screenreader über die vorgesehenen Eingabe-Methoden der jeweiligen Plattform modifizieren.

== Einordnung des Prüfschritts

=== Einordnung des Prüfschritts nach EN 301 549 V3.1.1

11.5.2.17 Modifications of values and text

== Quellen

[.BLOCK_LANG_EN]
=== 11.5.2.17 Modifications of values and text

[.BLOCK_LANG_EN]
--
Where permitted by security requirements, software that provides a user interface shall, by using the services as described in clause 11.5.2.3, allow assistive technologies to modify values and text of user interface elements using the input methods of the platform, where a user can modify these items without the use of assistive technology.

NOTE 1:
In some cases the security requirements imposed on a software product may forbid external software from interfering with the ICT product and so this requirement would not apply.
Examples of systems under strict security requirements are systems dealing with intelligence activities, cryptologic activities related to national security, command and control of military forces.

NOTE 2:
Assistive technologies may be required to maintain the same level of security as the standard input mechanisms supported by the platform.
--

(Aus EN 301 549 V3.1.1 Abschnitt 11.5.2.17 "Modifications of values and text")
