= Prüfschritt 11.5.2.12 Verfügbare Aktionen ausführbar
include::include/author.adoc[]
include::include/attributes.adoc[]

== Grundlage des Prüfschritts

Dieser Prüfschritt basiert auf den Kriterien der EN 301 549 Abschnitt
11.5.2.12 Execution of available actions.

== Was wird geprüft?
Die im Prüfschritt
ifdef::env_embedded[11.5.2.11 "Aktionen programmatisch ermittelbar"]
ifndef::env_embedded[]
  <<11.5.2.11 Aktionen programmatisch ermittelbar.adoc#,11.5.2.11 Aktionen
  programmatisch ermittelbar>>
endif::env_embedded[]
genannten Aktionen müssen auch mittels Hilfstechnologie ausführbar sein.

== Wie wird geprüft?

Die angebotenen Aktionen für ein Element werden testweise mittels
Screenreader ausgeführt.

== Quellen

=== Auszug EN 301 549

[.BLOCK_LANG_EN]
==== 11.5.2.12 Execution of available actions 

[.BLOCK_LANG_EN]
--
Where permitted by security requirements, software that provides a user
interface shall, by using the services as described in clause 11.5.2.3, allow
the programmatic execution of the actions exposed according to clause
11.5.2.11 by assistive technologies. 

*NOTE 1:*
In some cases the security requirements imposed on a software product may
forbid external software from interfering with the ICT product.
Examples of systems under strict security requirements are systems dealing
with intelligence activities, cryptologic activities related to national
security, command and control of military forces. 

*NOTE 2:*
Assistive technologies may be required to maintain the same level of security
as the standard input mechanisms supported by the platform.
--
