= 11.5.2.17 Bearbeitung von Text und anderen Werten
include::include/author.adoc[]
include::include/attributes.adoc[]

== Was wird geprüft?
Die Prüfung erfolgt im Wesentlichen in der gleichen Weise wie beim Prüfschritt 11.4.1.2 "Name, Rolle, Wert verfügbar". Hier wird bewertet, ob sich Werte von Bedienelementen und modifizierbarer Text, etwa bei Eingabefeldern, auch bei aktivierten Hilfsmitteln modifizieren lassen.

== Warum wird das geprüft?
Bedienelemente sollen nicht nur ihren Namen, ihre Rolle und ihren Wert programmatisch zur Verfügung stellen, es soll Hilfsmittel-Nutzenden auch möglich sein, Werte von Bedienelementen zu ändern.

== Wie wird das geprüft?

=== 1. Anwendbarkeit des Prüfschritts

Der Prüfschritt ist immer anwendbar, wenn die App Bedienelemente einsetzt. Aus Sicht der prüfenden Person ist nicht immer zu erkennen, ob Standardelemente der Entwicklungsumgebungen verwendet werden (und damit quasi von Haus aus zugänglich sind) oder von Entwicklerinnen und Entwicklern selbst definiert wurden. Eine Sichtprüfung reicht deshalb *nicht* aus. Bedienelemente müssen mit dem Screenreader fokussiert und aktiviert werden, um festzustellen, ob die jeweiligen Namen, Rollen und Werte vom Screenreader ausgegeben und auch Zustandsänderungen richtig kommuniziert werden.

=== 2. Prüfung

Für eine Prüfung mit VoiceOver / iOS müssen die AI/OCR-Erkennungsfunktionen ausgeschaltet sein (siehe "3. Hinweise").

. App mit zu prüfender Ansicht öffnen.
. Screenreader starten und Fokus mit Hilfe der Wischgeste auf jedes interaktive Element setzen.
. Prüfen, ob der Name, die Rolle und der Wert des Bedienelements vom Screenreader korrekt ausgegeben wird (siehe auch "3. Hinweise").
. Prüfen, ob sich Werte von Elementen (Zustände) mit aktiviertem Screenreader ändern lassen: Checkboxen bzw. Umschalter lassen sich aktivieren/deaktivieren, Werte in Schiebereglern lassen sich erhöhen oder verringern, Text in Texteingabefeldern lässt sich ändern, Ausklappbereiche lassen sich öffnen und schließen, usw.
. Dass geänderte Werte nach Eingabe korrekt ausgegeben werden, wird in Prüfschritt 11.4.1.2 erfasst (für Fokusposition und Textauswahl außerdem in Prüfschritt 11.5.2.13).

=== 3. Hinweise

Die Prüfung ist weitgehend identisch mit der Prüfung in 11.4.1.2. Hier richtet sich das Augenmerk aber darauf, dass Wertänderungen bei aktiviertem Screenreader überhaupt möglich sind.

=== 4. Bewertung

==== Erfüllt:

Werte von Bedienelementen und Textinhalte editierbarer Textfelder lassen sich mit aktiviertem Screenreader über gestische Eingaben modifizieren.

== Einordnung des Prüfschritts

=== Einordnung des Prüfschritts nach EN 301 549 V3.1.1

11.5.2.17 Modifications of values and text

== Quellen

[.BLOCK_LANG_EN]
=== 11.5.2.17 Modifications of values and text

____
[.BLOCK_LANG_EN]
--
Where permitted by security requirements, software that provides a user interface shall, by using the services as described in clause 11.5.2.3, allow assistive technologies to modify values and text of user interface elements using the input methods of the platform, where a user can modify these items without the use of assistive technology.

NOTE 1:
In some cases the security requirements imposed on a software product may forbid external software from interfering with the ICT product and so this requirement would not apply.
Examples of systems under strict security requirements are systems dealing with intelligence activities, cryptologic activities related to national security, command and control of military forces.

NOTE 2:
Assistive technologies may be required to maintain the same level of security as the standard input mechanisms supported by the platform.
--
____

(Aus EN 301 549 V3.1.1 Abschnitt 11.5.2.17 "Modifications of values and text")
