= Prüfschritt 11.5.2.10 Text
include::include/author.adoc[]
include::include/attributes.adoc[]

*Hinweis: Dies ist ein Entwurf. Inhalte können sich jederzeit ändern.*

== Was wird geprüft?

Wenn eine App Text enthält, soll der Text für Screenreader-Nutzende zugänglich sein. Wenn Apps die Bearbeitung von Text bieten und die Auszeichnung von Texten unterstützen (etwa die Setzung der Textattribute fett oder kursiv), sollen diese Textattribute auch für Hilfsmittelnutzende verfügbar sein.

Außerdem müssen Screenreader-Nutzende herausfinden können, welche Informationen gerade auf dem Display angezeigt werden (Viewport).

== Warum wird das geprüft? 

Texte in einer App müssen nicht nur sichtbar, sondern auch für Hilfsmittel-Nutzende zugänglich sein. Wenn eine App Möglichkeiten der Textverarbeitung bietet, sollen  Hilfsmittel-Nutzende Textattribute erkennen, also auslesen können.

Die App soll sowohl sequenziell als auch über direkte Touchberührung bedienbar sein, z.B. wenn der Ort von Bedienelementen bekannt ist und so die Navigation abgekürzt werden kann. Dafür ist es wichtig, dass sequenziell erreichte Inhalte auch im Viewport angezeigt werden, so dass sie über Touch erreichbar sind.

Wenn screenreader-fokussierte Inhalte auch gleichzeitig im Viewport sichtbar sind, erleichtert das auch die Kommunikation mit sehenden Nutzenden, zum Beispiel in einem schulischen oder Ausbildungskontext.

== Wie wird geprüft?

=== 1. Anwendbarkeit des Prüfschritts

Der Prüfschritt ist anwendbar, wenn Apps Texte enthalten. Die zusätzliche Prüfung der Textauszeichnung ist für Elemente anwendbar, für die Apps Textbearbeitungsfunktionen bieten.

=== 2. Prüfung

==== 2.1 Prüfung der Textausgabe

. Screenreader aktivieren
. Vom Beginn der Ansicht bis zum Ende alle Textinhalte  mit Wischgesten durchlaufen
. Prüfen, ob alle sichtbaren Elemente auch vom Screenreader ausgegeben werden
. Prüfen, ob im Fortgang der Fokusversetzung über Wischgeste die Ansicht ggf. scrollt, um die Inhalte bei Fokussierung im Viewport anzuzeigen. 
(Der Screenreader-Fokus sollte immer im Viewport sichtbar bleiben).
. Auf Geräten mit Touch-Display können die sichtbaren Textinhalte angetippt werden, die Ausgabe des Screenreaders sollte dem sichtbaren Textinhalt entsprechen. 

==== 2.2 Prüfung der Textauszeichnung

Falls die Software grundsätzlich Möglichkeiten bietet, Text-Attribute zu ändern (z.B. Text zu fetten, kursiv zu setzen oder zu unterstreichen) prüfen, ob es Möglichkeiten gibt, diese Textattribute mittels Screenreader auszulesen. Dies ist meist nur bei Textbearbeitungsprogrammen der Fall. 

===== 2.2.1 Prüfung der Textauszeichnung in iOS / VoiceOver

. Gibt es editierbaren Text mit Optionen, Text-Attribute zu ändern? Falls ja:
.. Über Rotor-Option 'Textauswahl' über horizontale Wischgeste einen kleinen Textbereich mit gesetztem Textattribut (etwa Fettung) auswählen.
.. Im Rotor schauen, ob die Option "Aktionen" und darin (vertikale Wischgeste) die Option "Textformat" verfügbar ist.  Diese durch Doppeltippen aufrufen.
.. Alternativ kann auch ein Pop-Up-Menü zur Auswahl von Bearbeitungsoptionen ("Ausschneiden" / "Kopieren", usw.) einschließlich "Format" erscheinen. Hier würde dann etwa "Fett / Umschalttaste / ein" ausgegeben, um den gefetteten Zustand des ausgewählten Textes auszugeben.
.. Prüfen, ob das Textformat richtig ausgegeben wird.
. Falls nein, Prüfung abbrechen.

===== 2.2.2 Prüfung Textauszeichnung in Android

. Gibt es editierbaren Text mit Optionen, Text-Attribute zu ändern? Falls ja:
.. Auswählen: "Talkback-Menü" (mit drei Fingern tippen)  > "Bearbeitungsoptionen" > "Auswahlmodus starten oder beenden".
.. Mit vertikalen Wischgesten Text auswählen.
.. Wenn in der App vorhanden, Bedienelement für Textauszeichnung fokussieren (etwa "B" für "fett") und überprüfen, ob der Zustand richtig ausgegeben wird. 
.. Über Talkback-Menü > Aktionen > "Formatierung der aktuellen Auswahl vorlesen" prüfen, ob der Stil des Textes korrekt ausgegeben wird.
. Falls nein, Prüfung abbrechen.

=== 3. Bewertung
==== Nicht erfüllt:
* Sichbbare informative Text-Inhalte werden nicht vom Screenreasder ausgegeben.
* Screenreader-fokussierte Inhalte werden nicht im Viewport angezeigt.


== Quellen

=== Auszug EN 301 549 V.3.2.1

[.BLOCK_LANG_EN]
==== 11.5.2.10 Text 
____

[.BLOCK_LANG_EN]
Where the software provides a user interface it shall, by using the services as described in clause 11.5.2.3, make the text contents, text attributes, and the boundary of text rendered to the screen programmatically determinable by assistive technologies.
____
