= Prüfschritt 11.5.2.7 Minimale und maximale Werte programmatisch ermittelbar
include::include/author.adoc[]
include::include/attributes.adoc[]

*Hinweis: Dies ist ein Entwurf. Inhalte können sich jederzeit ändern.*

== Was wird geprüft?

Falls für Formularelemente minimale oder maximale Eingabewerte vorgegeben sind, muss diese Information auch programmatisch verfügbar sein, damit Screenreader-Nutzende ebenfalls über die Grenzen der Eingabemöglichkeiten in Kenntnis gesetzt werden.

== Wie wird geprüft?
=== 1. Anwendbarkeit des Prüfschritts
Der Prüfschritt ist auf Ansichten mit Formularen anwendbar.

=== 2. Prüfung
. Formularelemente mit numerischen Eingabefeldern und Schieberegler zum Einstellen von Werten identifizieren
. Gibt es visuell vermittelte Begrenzungen der Eingabewerte? Wenn diese visuell verfügbar sind, etwa über Legenden, Beschriftungen oder Textvorbelegungen, müssen sie auch für Screenreader ermittelbar sein.
. Elemente mit dem Screenreader fokussieren. Der aktuell eingestellte Wert und die Grenzen sollen vom SR ausgegeben werden.

=== 3. Hinweise
Eingabegrenzen können auch implizit vermittelt werden. So ist etwa bei Reglern mit Prozentwerten klar, dass Werte auf den Bereich von 0% - 100% eingegrenzt sind.

== Quellen

=== Auszug EN 301 549

[.BLOCK_LANG_EN]
==== 11.5.2.7 Values 

[.BLOCK_LANG_EN]
Where the software provides a user interface, it shall, by using the services as described in clause 11.5.2.3, make the current value of a user interface
element and any minimum or maximum values of the range, if the user interface element conveys information about a range of values, programmatically
determinable by assistive technologies.
