= 11.5.2.14 Programmatisch steuerbare Texteinfügemarke und Selektion
include::include/author.adoc[]
include::include/attributes.adoc[]

== Was wird geprüft?

Bei Interface-Elementen der App, die Texteingaben und Textbearbeitung vorsehen, muss die Position des Fokus bzw. der Texteinfügemarke und sowie die Textauswahl auch für Hilfsmitteltechnologien änderbar sein. Geprüft wird dies mithilfe der integrierten Screenreader VoiceOver (iOS) und TalkBack (Android) und der Aktivierung der jeweiligen Gesten-Befehle für Fokusversetzung und Textauswahl. 

Ob die geänderte Cursor-Position bzw. Textauswahl programmatisch ausgegeben wird, ist Gegenstand des Prüfschritts 11.5.2.13. Beide Prüfschritte gehören eng zusammen, die Prüfung ist im Wesentlichen identisch.


== Warum wird das geprüft?

Die Textbearbeitung und die dazugehörigen Funktionen wie die Positionierung des Cursors und die Festlegung der Textauswahl sollen auch für Hilfsmittel-Nutzende verfügbar sein.

== Wie wird das geprüft?

=== 1. Anwendbarkeit des Prüfschritts

Der Prüfschritt ist nur auf Interface-Elemente anwendbar, die die Eingabe und Bearbeitung von Text vorsehen. In der Regel sind dies einzeilige oder mehrzeilige Textfelder in Formularen, oder auch editierbare Felder in Lückentexten.

=== 2. Prüfung

* Lässt sich mit aktiviertem Screenreader innerhalb von Textfeldern die Fokusposition ändern und die Textauswahl ändern (erweitern / verringern)?
* Unterstützt der Inhalt, soweit verfügbar, die vom System und Screenreader vorgesehenen Mechanismen für die Änderung der Fokusposition und der Textauswahl?

==== 2.1 iOS / VoiceOver

* Sicherstellen, dass in den VoiceOver-Einstellungen unter "Rotor" die Optionen "Zeichen" und "Textauswahl" aktiviert sind. Dann VoiceOver aktivieren.
* Ein Textfeld über horizontale Wischgeste fokussieren und durch Doppeltippen aktivieren. Es wird in der Regel "Einfügemarke am Ende" angesagt. (Doppeltippen ändert die Cursorposition von Ende zu Anfang und umgekehrt.) Wenn kein Text im Textfeld vorhanden ist, etwas Text eingeben.

===== 2.1.1 Prüfung Fokusversetzung in iOS / VoiceOver

* Den VoiceOver-Rotor auf "Zeichen" stellen.
* Steht der Cursor am Anfang, soll vertikales Wischen nach unten die Cursor-Position um ein Zeichen nach rechts verschieben. Das Zeichen vor dem Cursor wird ausgegeben. Steht der Cursor am Ende, soll vertikales Wischen nach oben die Cursor-Position um ein Zeichen nach links verschieben. Das Zeichen nach dem Cursor wird ausgegeben. 

===== 2.1.2 Textauswahl in iOS / VoiceOver

* Den VoiceOver-Rotor auf "Textauswahl" stellen. Ggf. über vertikales Wischen die Textauswahl auf "Zeichenauswahl" stellen.
* Steht der Cursor am Ende, soll horizontales Wischen nach links die Auswahl um je ein weiteres Zeichen erweitern. Steht der Cursor am Anfang, geschieht die Auswahl über horizontales Wischen nach rechts. Die Auswahl wird ausgegeben. 
* Alternative Auswahl über Spreizgeste: Die Textauswahl lässt sich über die Spreizgeste (Pinch Zoom) erweitern bzw. verringern.

====  2.2 Android / TalkBack

* TalkBack aktivieren
* Ein Textfeld über horizontale Wischgeste fokussieren und ggf. durch Doppeltippen aktivieren (ist der Bearbeitungsmodus aktiv, wird "in Bearbeitung" ausgegeben). Wenn kein Text im Textfeld vorhanden ist, etwas Text eingeben. (Die Cursorposition lässt sich über das Talkback-Menü (Haken-Wischgeste noch oben, dann nach rechts) und dann Auswahl von "Aktionen" ändern: "Cursor an den Anfang verschieben" an bzw. "Cursor ans Ende verschieben").


===== 2.2.1 Prüfung Fokusversetzung in Android / Talkback

* Über eine Dreifinger-Wischgeste die Einstellung "Zeichen" wählen. Die Cursorposition sollte sich nun über eine vertikale Einfinger-Wischgeste durch nach-Unten-Wischen nach rechts und durch Nach-Oben-Wischen nach links verschieben lassen.

===== 2.2.2 Prüfung Textauswahl in Android / Talkback

* Der Bearbeitungsmodus wird durch 2-Finger-Doppeltippen und Halten aktiviert bzw. wieder deaktiviert. Eine Alternative ist die Auswahl über das Talkback-Menü (Haken-Wischgeste noch oben, dann nach rechts; Auswahl von "Aktionen"; Auswahl von "Auswahlmodus starten oder beenden").
* Der Text lässt sich nun durch vertikale Wischgesten zeichenweise oder auch wortweise auswählen. Über die vertikale Dreifinger-Wischgeste lässt sich der jeweilige Auswahlmodus ändern.

=== 3. Hinweise

* Die Hinweise beziehen sich auf die aktuellen Betriebssystem- und Screenreader-Versionen zum Zeitpunkt der Aktualisierung des Prüfschritts (Android 13 / iOS 16). Ggf. ändern sich die Gesten für die Versetzung des Fokus und die Auswahl von Text mit neuen Versionen von VoiceOver und TalkBack. Es wird empfohlen, ggf. die aktuelle Dokumentation zu den Bedienungshilfen zu konsultieren.
* Manche Android-Geräte bzw. ältere Talkback-Versionen unterstützten auch die Verschiebung der Cursor-Position über die physischen Tasten am Geräterand zum Lauter/Leiser-Stellen des Tons. 

=== 4. Bewertung

==== Erfüllt:

Bei aktiviertem Screenreader lässt sich die Fokusposition gezielt versetzen, die Text-Auswahl lässt sich gezielt ändern (erweitern / verringern).

== Einordnung des Prüfschritts

=== Einordnung des Prüfschritts nach EN 301 549 V3.1.1

11.5.2.14 Modification of focus and selection attributes

== Quellen
* https://support.google.com/accessibility/android/answer/6151827?hl=en#zippy=%2Cversion-up%2Cversion-lower[Google-Hilfe zu TalkBack-Gesten]
* https://bbc.github.io/accessibility-news-and-you/accessibility-and-testing-with-talkback.html[BBC Accessibility and Testing with TalkBack]
* https://seeingdifferentuk.blogspot.com/2015/06/selecting-copying-and-pasting-with.html[Blogbeitrag SeeingDifferent zu Auswahl, Kopieren, Einfügen mit VoiceOver in iOS]

=== Auszug EN 301 549

[.BLOCK_LANG_EN]
==== 11.5.2.14 Modification of focus and selection attributes

[.BLOCK_LANG_EN]
--
Where permitted by security requirements, software that provides a user interface shall, by using the services as described in clause 11.5.2.3, allow assistive technologies to programmatically modify focus, text insertion point, and selection attributes of user interface elements where the user can modify these items.

NOTE 1:
In some cases the security requirements imposed on a software product may forbid external software from interfering with the ICT product and so this requirement would not apply.
Examples of systems under strict security requirements are systems dealing with intelligence activities, cryptologic activities related to national security, command and control of military forces.

NOTE 2:
Assistive technologies may be required to maintain the same level of security as the standard input mechanisms supported by the platform.
--

(Aus EN 301 549 V3.1.1 Abschnitt 11.5.2.14 "Modification of focus and selection attributes")
