= Prüfschritt 11.5.2.7 Minimale und maximale Werte programmatisch ermittelbar
include::include/author.adoc[]
include::include/attributes.adoc[]

== Grundlage des Prüfschritts

Dieser Prüfschritt basiert auf den Kriterien der EN 301 549 Abschnitt
11.5.2.7 Values.

== Was wird geprüft?

Falls für Formularelemente minimale oder maximale Eingabewerte vorgegeben
sind, muss diese Information auch dem Screenreader zur Verfügung stehen,
damit der Screenreader-Nutzer ebenfalls über die Grenzen der
Eingabemöglichkeiten in Kenntnis gesetzt werden kann.

== Wie wird geprüft?

Die Formularelemente müssen auf Eingrenzungen der Eingabewerte geprüft
werden, falls diese generell ersichtlich sind, müssen diese Eingabegrenzen
auch mittels Screenreader angesagt werden.
Hierzu wird das Formular mit dem Screenreader durchgegangen, die Grenzen
sollen dabei vom SR angesagt werden.

== Quellen

=== Auszug EN 301 549

[.BLOCK_LANG_EN]
==== 11.5.2.7 Values 

[.BLOCK_LANG_EN]
Where the software provides a user interface, it shall, by using the services
as described in clause 11.5.2.3, make the current value of a user interface
element and any minimum or maximum values of the range, if the user interface
element conveys information about a range of values, programmatically
determinable by assistive technologies.
