= 11.5.2.8 Programmatisch ermittelbare Beschriftungen
include::include/author.adoc[]
include::include/attributes.adoc[]

== Was wird geprüft?

UI-Elemente, die durch andere UI-Elemente beschriftet werden, sollen diese Beschriftung programmatisch ermittelbar zur Verfügung stellen.
Ein Eingabefeld, das lediglich durch einen nebenstehenden Button beschriftet wird, soll zum Beispiel selbst die Beschriftung, die es durch den Button erhält, programmatisch zur Verfügung stellen.
Diese Art der Beschriftung taucht zum Beispiel häufig bei Suchfunktionen auf: Ein Button folgt auf ein Eingabefeld, nur der Button ist mit "Suchen" beschriftet.
Programmatisch ermittelbar ist die Beschriftung des Eingabefelds in diesem Fall, wenn die Beschriftung "Suchen" beim Antippen des Eingabefelds mit aktiviertem Screenreader vorgelesen wird.

== Warum wird das geprüft?

Screenreader geben die Elemente auf dem Bildschirm nacheinander aus,  eine visuell vermittelte Verbindung von Bedienelementen und Beschriftungen können Nutzer dieser assistiven Software nicht immer in vergleichbarer Weise herstellen. 
In manchen Screenreader-Navigationsmodi werden bestimmte Elemente gezielt durchlaufen, etwa nur Steuerelemente. Wird ein Element, etwa ein Eingabefeld, auf diese Weise fokussiert, soll die programmatisch zugeordnete oder hinterlegte Beschriftung ausgegeben werden.
Bedienelemente müssen daher auch die Zuordnung der Beschriftung visuell klar ist, eine programmatisch ermittelbare Beschriftung haben, um eine effiziente Bedienung zu ermöglichen.

Damit die Beschriftungsinformation nicht doppelt durch den Entwickler gepflegt werden muss (sichtbare Beschriftung und Accessibility-Label), soll das Bedienelement ohne Beschriftung programmatisch auf dessen Beschriftung verweisen.
Sobald sich die Beschriftung ändert, erhält das Bedienelement ohne sichtbare Beschriftung ebenfalls den neuen Text und kann diesen als Accessibility-Label an das System melden.
Der Screenreader kann somit beim Antippen des Bedienelements ohne sichtbare Beschriftung ein passendes Label ausgeben.
Diese Art, ein Accessibility-Label bereitzustellen ist robuster als die separate Pflege von sichtbarer Beschriftung und einem Accessibility-Label.

== Wie wird das geprüft?

=== 1. Anwendbarkeit des Prüfschritts

Der Prüfschritt ist anwendbar, wenn Bedienelemente eingesetzt werden, die lediglich durch andere Bedienelemente auf der Ansicht beschriftet werden.

=== 2. Prüfung

. Screenreader starten
. Bedienelemente mit nebenstehender Beschriftung mit dem Screenreader fokussieren. Es sollte jeweils die nebenstehende sichtbare Beschriftung oder eine gleichwertige programmatisch hinterlegte Beschriftung ausgegeben werden.

=== 3. Hinweise

Ob das vom Screenreader ausgegebene Accessibility-Label wirklich vom beschriftenden Element stammt oder getrennt als AccessibilityLabel hinterlegt ist, kann nicht festgestellt werden.
Hier kann nur geprüft werden, ob das Accessibility-Label, für das Bedienelement ohne sichtbare Beschriftung, gleichlautend zur Beschriftung des beschriftenden Elements ist.

=== 4. Bewertung

==== Erfüllt:

* Bei Fokussierung von Bedienelementen mit nebenstehender Beschriftung wird diese Beschiftung als Name ausgegeben.
* Ein gleichwertiger, programmatisch hinterlegter Name wird bei Fokussierung des Bedienelements ausgegeben. 

== Einordnung des Prüfschritts

=== Abgrenzung des Prüfschritts

In Prüfschritt 11.2.5.3 "Sichtbare Beschriftung Teil des zugänglichen Namens" wird geprüft, ob die sichtbare Beschriftung im programmatisch ermittelbaren Namen des Bedienelements vorkommt. Es kann also Fälle geben, wo dieser Prüfschritt erfüllt ist, da statt der Verknüpfung der sichtbaren Beschriftung eine hinterlegte gleichwertige Beschriftung programmatisch ermittelbar ist, jedoch Prüfschritt 11.2.5.3 nicht erfüllt wäre, wenn die exakte Zeichenfolge der sichtbaren Beschriftung nicht im programmatisch ermittelbaren Namen vorkommt.

=== Einordnung des Prüfschritts nach EN 301 549 V3.1.1

11.5.2.8 Label relationships

== Quellen

[.BLOCK_LANG_EN]
=== 11.5.2.8 Label relationships

____
[.BLOCK_LANG_EN]
--
Where the software provides a user interface it shall expose the relationship that a user interface element has as a label for another element, or of being labelled by another element, using the services as described in clause 11.5.2.3, so that this information is programmatically determinable by assistive technologies.
--
____

(Aus EN 301 549 V3.1.1 Abschnitt 11.5.2.8 "Label relationships")
