= Prüfschritt 11.5.2.10a Textinhalte und –Attribute zugänglich
include::include/author.adoc[]
include::include/attributes.adoc[]

== Grundlage des Prüfschritts

Dieser Prüfschritt basiert auf dem Kriterium 11.5.2.10 Text der EN 301 549.

== Was wird geprüft?

Textinhalte in der Software sind generell für den Screenreader zugänglich. Textattribute sind verfügbar, wenn dies generell von der Software vorgesehen ist.
Beispiele für Textattribute sind fett, kursiv oder unterstrichen. In einer Textverarbeitung müssen diese Attribute z. B. auch für den Screenreader-Nutzer ausgegeben werden können.

Außerdem müssen Screenreader-Nutzer herausfinden können, welche Informationen gerade auf dem Display angezeigt werden (Viewport).

== Wie wird geprüft?
=== Prüfung Textausgabe

. Screenreader aktivieren
. Vom Beginn der Ansicht bis zum Ende alle Textinhalte  mit Wischgesten durchaufen
. Prüfen, ob alle sichtbaren Elemente auch vom Screenreader ausgegeben werden
. Auf Geräten mit Touch-Display können die sichtbaren Txtinhalte angetippt werden, die Ausgabe des Screenreaders sollte den sichtbaren Textinhalt enthalten. 

=== Prüfung Textauszeichnung
Falls die Software Möglichkeiten bietet beim Editieren von Text Attriute zu ändern (z.B. Tet zu fetten oder zu unterstreichen) prüfen, ob es  Möglichkeiten gibt, diese Textattribute mittels Screenreader zu setzen und auszulesen. Dies ist meist nur bei Textbearbeitungsprogrammen der Fall. 

==== Prüfung in iOS / VoiceOver

. Gibt es editierbaren Text? Falls ja:
.. Über Rotor-Option 'Textauswahl' über horizontale Wischgeste einen kleinen Textbereich mit gesetztem Textattribut (etwa Fettung) auswählen
.. Im Rotor schauen, ob die Option "Aktionen" und darin (vertikale Wischgeste) die Option "Textformat" verfügbar ist.  Diese durch Doppeltippen aufrufen.
.. Gesetztes Textformat auswählen, prüfen, ob es sich ändern lässt (z.B. über VoiceOver die Auswahl "fett" für den ausgewählten Text entfernen und wieder setzen). 
. Falls nein, Prüfung abbrechen.

==== Prüfung in Android

(folgt)

== Quellen

=== Auszug EN 301 549

[.BLOCK_LANG_EN]
==== 11.5.2.10 Text 

[.BLOCK_LANG_EN]
Where the software provides a user interface it shall, by using the services
as described in clause 11.5.2.3, make the text contents, text attributes, and
the boundary of text rendered to the screen programmatically determinable by
assistive technologies.
