= Prüfschritt 11.5.2.11 Aktionen programmatisch ermittelbar
include::include/author.adoc[]
include::include/attributes.adoc[]

== Grundlage des Prüfschritts

Dieser Prüfschritt basiert auf den Kriterien der EN 301 549 Abschnitt
11.5.2.11 List of available actions.

== Was wird geprüft?

Wenn für ein Element in derSoftware Aktionen durchgeführt werden können,
müssen diese auch für den Screenreader-Nutzer ersichtlich sein.

== Wie wird geprüft?

Prüfen, welche Aktionen grundsätzlich für ein Element durchführbar sind
und mittels Screenreader prüfen, ob die Aktionen auch  hier angeboten werden.
Ein Beispiel für ein Element mit verschiedenen Aktionen ist ein Listeneintrag
in der Mail-App, hier können  die einzelnen Mails in der Liste z. B. u. a.
durch Wischgesten gelöscht und archiviert werden.

== Quellen

=== EN 301 549 v.3.2.1

[.BLOCK_LANG_EN]
==== 11.5.2.11 List of available actions 

[.BLOCK_LANG_EN]
Where the software provides a user interface it shall, by using the services as
described in clause 11.5.2.3, make a list of available actions that can be
executed on a user interface element, programmatically determinable by
assistive technologies.
