= 11.5.2.16 Programmatisch steuerbare Stati und Eigenschaften
include::include/author.adoc[]
include::include/attributes.adoc[]

== Was wird geprüft?
Interaktive Elemente, die verschiedene Zustände haben (z.B. an- und ausgeschaltet) sollen auch mit eingeschaltetem Screenreader bedienbar sein. Für Standard-Elemente ist dies in der Regel gegeben. Das Augenmerk bei der Prüfung liegt deshalb hauptsächlich auf Custom-Elementen und Custom-Widgets. Beispiele: 

* eine Custom-Checkbox lässt sich markieren
* ein Ausklappmenü oder ein Ausklappbereich lässt sich öffnen und schließen
* die Reiter eines Tabpanels lassen sich fokussieren bzw. aktivieren (die zum Tab gehörenden Panel werden angezeigt)
* ein Schalter lässt sich aktivieren/deaktivieren und zeigt dann den jeweiligen Zustand an

== Warum wird das geprüft?
Selbst-gestaltete interaktive Elemente (Custom-Elemente und -Widgets) sollen sich auch von Hilfsmittel-Nutzenden gut bedienen lassen.

== Wie wird das geprüft?

=== 1. Anwendbarkeit des Prüfschritts
Der Prüfschritt ist immer anwendbar, wenn die Seite interaktive Elemente enthält, die verschiedene Zustände haben können.

=== 2. Prüfung
Die Prüfung folgt im wesentlichen der Prüfung in 11.4.1.2 Name, Rolle, Wert. Nicht nur bei der initialen Fokussierung sollen zugänglicher Name, Rolle und Wert von Elementen und Widgets ausgegeben werden. Generell verfügbare Zustände müssen sich auch bei eingeschaltetem Screenreader ändern lassen.

=== 3. Hinweise
In der Regel kann die Bewertung bei Prüfgschritt 11.4.1.2 hier übernommen werden. Kann bei eingeschaltetem Screenreader der Wert nicht geändert werden, sind sowohl Prüfschritt 11.4.1.2 als auch dieser Prüfschritt nicht erfüllt. Dieser Prüfschritt betrachtet die Möglichkeit, den Wert wirksam zu ändern, nicht die Ausgabe des (geänderten) Wertes. Dies ist Gegenstand von Prüfschritt 11.4.1.2 "Name Rolle Wert verfügbar".

=== 4. Bewertung

==== Erfüllt:
Alle Werte interaktiver Elemente lassen sich mit aktiviertem Screenreader ändern.

== Einordnung des Prüfschritts

=== Einordnung des Prüfschritts nach EN 301 549 V3.1.1

11.5.2.16 Modifications of states and properties

== Quellen

[.BLOCK_LANG_EN]
=== 11.5.2.16 Modifications of states and properties

____
[.BLOCK_LANG_EN]
--
Where permitted by security requirements, software that provides a user interface shall, by using the services as described in clause 11.5.2.3, allow assistive technologies to programmatically modify states and properties of user interface elements, where the user can modify these items.

NOTE 1:
In some cases the security requirements imposed on a software product may forbid external software from interfering with the ICT product and so this requirement would not apply.
Examples of systems under strict security requirements are systems dealing with intelligence activities, cryptologic activities related to national security, command and control of military forces.

NOTE 2:
Assistive technologies may be required to maintain the same level of security as the standard input mechanisms supported by the platform.
--
____

(Aus EN 301 549 V3.1.1 Abschnitt 11.5.2.16 "Modifications of states and properties")
