= Prüfschritt 11.5.2.9 Eltern-Kind-Beziehungen programmatisch ermittelbar
include::include/author.adoc[]
include::include/attributes.adoc[]


== Was wird geprüft?

Visuell dargestellte Hierarchien (Eltern-Kind Beziehungen) sollten grundsätzlich auch für den Screenreader-Nutzer erfahrbar sein.
Der Einsatz programmatisch ermittelbarer hierarchischer Strukturen ist allerdings bei Apps recht beschränkt. So finden sich Überschriften in nativen Apps bislang meist nur auf einer Ebene, auch wenn unter iOS / iPadOS seit Version 15.0 Überschriften-Hierarchien möglich sind. 

Die am häufigsten anzutreffende programmatisch ermittelbare Hierarchie, sowohl bei Android als auch iOS, ist die von Tab-Leisten (Tabs für die Navigation zu App-Bereichen) bzw. Werkzeugleisten (Toolbars) zum Aufruf von Funktionen. 

Wenn Einträge in Navigations-Menüs bei Aktivierung Untermenüs in einem akkordion-artigen Einblendbereich oder einer weiteren Ansicht aufrufen, kann diese Hierarchie über den Ausklapp-Zustand der Menüeinträge vermittelt werden: so wird etwa bei erweiterbaren Menüeinträgen der iOS-Pages-App "reduziert" ausgegeben. Ein anderes Beispiel ist das Menü der iOS-Guardian-App. Dieses Pattern ist jedoch selbst bei iOS- und Android System-Apps selten genutzt: meist erfolgt lediglich die Ausgabe "Schalter", das Untermenü ersetzt das Hauptmenü, ein Zurück-Schalter führt zum Hauptmenü zurück. Die Vermittlung der Eltern-Kind Hierarchie lässt sich deshalb schwerlich generell bei Navigationsmenüs von Apps einfordern.

Andere visuell listenartige oder kachelartige Strukturen wie Listen treten meist als Ansammlungen von Tasten bzw. Schaltern auf und vermitteln programmatisch weder die visuell erfahrbare Eltern-Kind Beziehung noch die Anzahl von Kindelementen oder deren Position in der Gruppe. Elemente mit Rollen wie "Popup-Fenster" (Android), "Liste" (Android) oder "Auswahl" (iOS) nennen bei Aufruf die Eltern-Rolle, nicht jedoch Anzahl und oder die relative Position fokussierter Kind-Elemente. Unter iOS lassen sich gelegentlich hierarchische Indices über die Rotor-Option "Wert anpassen" mittels vertikaler Wischgesten navigieren - so etwa etwa der Abschnittsindex in der iOS-App Kontakte.

== Warum wird das geprüft?

Wenn hierarchische Interface-Strukturen und damit Eltern-Kind Beziehungen progammatisch verfügbar sind, haben nicht-visuelle Nutzende einen besseren Überblick über das Interface und seine Strukturen. iOS-Beispiel: Eine Tablist sagt bei Fokussierung des Kind-Tabs die Position des Tabs und die Anzahl der Tabs im Eltern-Element an. Da die programmatische Ermittelbarkeit von Eltern-Kind Beziehungen in Apps generell selten ist und über die Auszeichung von Tablisten hinaus kaum anzutreffen ist, wird das Fehlen programmatisch ermittelbarer Hierarchien zurzeit auch nur hier negativ bewertet.

== Wie wird geprüft?

Mittels Screenreader prüfen, ob Tablists und Toolbars die Position des Elements sowie die Gesamt-Anzahl vermitteln. Nicht negativ zu bewerten ist, wenn das Elternelement selbst nicht benannt ist bzw. bei der Fokussierung eines Kindelementes nicht der Name oder Rolle des Elternelements ausgegeben wird. Für andere hierarchische Konstrukte (Listviews, Tables, Collections) ist eine solche Ausgabe nicht standardmäßg unterstützt und deshalb nicht zu erwarten.

== Quellen

* https://developer.apple.com/documentation/swiftui/text/accessibilityheading(_:)[accessibilityHeading(_:) Hierarchische Überschriften in iOS]

=== Auszug EN 301 549

[.BLOCK_LANG_EN]
==== 11.5.2.9 Parent-child relationships 

[.BLOCK_LANG_EN]
Where the software provides a user interface it shall, by using the services as
described in clause 11.5.2.3, make the relationship between a user interface
element and any parent or children elements programmatically determinable by
assistive technologies.
