= 11.5.2.8 Programmatisch ermittelbare Beschriftungen
include::include/author.adoc[]
include::include/attributes.adoc[]

*Hinweis: Dies ist ein Entwurf. Inhalte können sich jederzeit ändern.*

== Was wird geprüft?

Bedienelemente, die durch daneben stehende Labels bzw. Texte beschriftet werden, sollen diese Beschriftung programmatisch ermittelbar zur Verfügung stellen oder selbst eine gleichwertige hinterlegte Beschriftung tragen.
Diese Art der Beschriftung taucht zum Beispiel häufig bei Formularfeldern auf.
Programmatisch ermittelbar ist die Beschriftung des Eingabefelds in diesem Fall, wenn die Beschriftung "Suchen" beim Fokussieren des Eingabefelds mit aktiviertem Screenreader vorgelesen wird. Auch ein Antippen des Elements führt zu dieser Ausgabe.

== Warum wird das geprüft?

Screenreader geben die Elemente auf dem Bildschirm nacheinander aus. Den visuellen Zusammenhang zwischen Bedienelement und Beschriftung können Screenreader-Nutzende nicht immer in vergleichbarer Weise herstellen. So werden in manchen Screenreader-Navigationsmodi bestimmte Elemente gezielt durchlaufen, etwa nur Steuerelemente. Wird ein Element, etwa ein Eingabefeld, auf diese Weise fokussiert, soll die programmatisch zugeordnete oder hinterlegte Beschriftung ausgegeben werden. Bedienelemente müssen daher, auch wenn die Zuordnung der Beschriftung visuell klar ist, eine programmatisch ermittelbare Beschriftung haben, um eine effiziente Bedienung zu ermöglichen.

== Wie wird das geprüft?

=== 1. Anwendbarkeit des Prüfschritts

Der Prüfschritt ist anwendbar, wenn Bedienelemente eingesetzt werden, die lediglich durch andere Bedienelemente auf der Ansicht beschriftet werden.

=== 2. Prüfung

. Screenreader starten
. Bedienelemente mit nebenstehender Beschriftung mit dem Screenreader fokussieren. Es sollte jeweils die nebenstehende sichtbare Beschriftung (oder eine gleichwertige programmatisch hinterlegte Beschriftung) ausgegeben werden.

=== 3. Hinweise

* Im Wesentlichen gleicht die Prüfung in diesem Prüfschritt der Prüfung in Prüfschritt 11.1.3.1e "Beschriftung von Formularelementen programmatisch ermittelbar". In der Regel kann einfach auf diesen Prüfschritt verwiesen werden und die gleiche Bewertung vergeben werden.
* Damit die Beschriftungsinformation nicht doppelt gepflegt werden muss (sichtbare Beschriftung und Accessibility-Label), sollten Bedienelemente ohne Beschriftung programmatisch auf deren nebenstehende Beschriftung verweisen. Sobald sich die Beschriftung ändert, erhält das Bedienelement ohne sichtbare Beschriftung dann ebenfalls ein aktualisiertes Accessibility-Label. So kann beim Fokussieren des Bedienelements ohne sichtbare Beschriftung die aktuelle Beschriftung ausgeben werden. Diese Art, ein Accessibility-Label bereitzustellen, ist robuster als die separate Pflege von sichtbarer Beschriftung und einem Accessibility-Label.
* Ob das vom Screenreader ausgegebene Accessibility-Label wirklich vom beschriftenden Element stammt oder getrennt als AccessibilityLabel hinterlegt ist, kann nicht festgestellt werden, wenn beide gleichlautend sind.
* Es wird hier nicht negativ bewertet, wenn die programmatische und die sichtbare Beschriftung nicht identisch sind bzw. die sichtbare Beschriftung nicht im zugänglichen Namen enthalten ist. Dies ist Gegenstand von Prüfschritt 11.2.5.3 "Sichtbare Beschriftung Teil des zugänglichen Namens".

=== 4. Bewertung

==== Erfüllt:

* Bei Fokussierung von Bedienelementen mit nebenstehender Beschriftung wird diese Beschiftung als Name ausgegeben.
* Ein gleichwertiger, programmatisch hinterlegter Name wird bei Fokussierung des Bedienelements ausgegeben. 

== Quellen
=== Allgemein
* Appt.org: https://appt.org/en/guidelines/wcag/success-criterion-1-3-1#group-elements[Group Elements] (mehrere Entwicklungsumgebungen)

=== iOS
=== Android

== Einordnung des Prüfschritts

=== Abgrenzung des Prüfschritts

In Prüfschritt 11.2.5.3 "Sichtbare Beschriftung Teil des zugänglichen Namens" wird geprüft, ob die sichtbare Beschriftung im programmatisch ermittelbaren Namen des Bedienelements vorkommt. Es kann also Fälle geben, wo dieser Prüfschritt erfüllt ist, da statt der Verknüpfung der sichtbaren Beschriftung eine hinterlegte gleichwertige Beschriftung programmatisch ermittelbar ist, jedoch Prüfschritt 11.2.5.3 nicht erfüllt wäre, wenn die exakte Zeichenfolge der sichtbaren Beschriftung nicht im programmatisch ermittelbaren Namen vorkommt.

=== Einordnung des Prüfschritts nach EN 301 549 V3.1.1

==== 11.5.2.8 Label relationships
____
[.BLOCK_LANG_EN]
--
Where the software provides a user interface it shall expose the relationship that a user interface element has as a label for another element, or of being labelled by another element, using the services as described in clause 11.5.2.3, so that this information is programmatically determinable by assistive technologies.
--
____
