= 11.5.2.15 Programmatisch ermittelbare Änderungsmitteilung
include::include/author.adoc[]
include::include/attributes.adoc[]

== Was wird geprüft?
Wenn sich bei Bedienelementen oder Statusanzeigen Werte von programmatisch ermittelbaren Attributen ändern, sollen Screenreader diese Zustandsänderung ausgeben. Ändern sich durch Nutzereingaben visuell Werte an anderen Stellen als auf dem aktuell fokussierten Element, sollten diese über programmatisch ermittelbare Statusmeldungen ausgegeben werden. Beispiele: 

* Direkt nach Aktivierung einer Custom-Checkbox oder eines Switches wird der Zustand ausgegeben (etwa ausgeschaltet/eingeschaltet, ausgewählt/nicht ausgewählt, ausgewählt / zum Auswählen doppeltippen, oder An/Aus)
* Direkt nach Aktivierung einer einer Einstellungsoption wird der eingestellte Wert ausgegeben
* Direkt nach Aktivierung des Reiters eines Tabpanels wird vor dem Namen des jeweiligen Reiters "Auswahl" ausgegeben
* Direkt nach dem Ändern des Wertes eines interaktiven Reglers (z.B zur Einstellung von Lautstärke, Preisspanne, Zeitraum usw.) wird der geänderte Wert ausgegeben
* Direkt nach dem Setzen eines Filters für eine Suchergebnisliste wird die geänderte Anzahl an Fundstellen ausgegeben.

== Warum wird das geprüft?
Zustandsänderungen, die für Nutzende visuell verfügbar sind, sollen auch für nicht-visuelle Nutzende programmatisch ermittelbar sein und zurückgemeldet werden.

== Wie wird das geprüft?

=== 1. Anwendbarkeit des Prüfschritts
Der Prüfschritt ist anwendbar, wenn die Ansicht interaktive Bedienelemente hat, die durch Eingaben von Nutzenden ihren Wert ändern können oder den Wert einer sichtbaren Ausgabe auf der gleichen Ansicht ändern (etwa über einen geänderten Status). Beispiele sind Checkboxen, Radio-Inputs, Auswahllisten, Umschalter.

=== 2. Prüfung

Die Prüfung folgt im Wesentlichen der Prüfung in 9.4.1.2 Name, Rolle, Wert und 9.4.1.3 Statusmeldungen.

. Bedienelemente und Bearbeitungsoptionen werden mit dem Screenreader und dokumentierten Gesten aktiviert, Werte werden geändert.
. Erfolgt nach Änderung direkt eine Ausgabe der geänderten Werte bzw. Zustände?
. Sind (geänderte) Werte gar nicht programmatisch ermittelbar, ist neben "9.4.1.2 Name, Rolle, Wert verfügbar" auch dieser Prüfschritt nicht erfüllt. 
. Sind geänderte Werte zwar prinzipiell programmatisch korrekt ermittelbar, aber ohne dass der Wert unmittelbar nach der Eingabe ausgegeben wird, ist dieser Prüfschritt ggf. nicht erfüllt (vergl. aber 3. Hinweise). 
. Werden visuell verfügbare Statusmeldungen oder Statusänderungen nicht direkt nach der Änderung ausgegeben, ist nicht nur der Prüfschritt 9.4.1.3 Statusmeldungen, sondern auch dieser Prüfschritt nicht erfüllt.

=== 3. Hinweise

Bei der Bewertung der Ausgabe geänderter Werte sind die Unterstützung der jeweiligen Bedienelemente durch Hilfsmittel / User Agents zu berücksichtigen. Abhängig von der jeweiligen Nutzungs-Umgebung kann es sein, dass bestimmte Zustandsänderungen nicht ausgegeben werden, obwohl sie semantisch korrekt umgesetzt wurden. Sind diese Bedienelemente in mehreren anderen Umgebungen ausreichend unterstützt, ist die fehlende Änderungsmitteilung nicht als Mangel / Nichterfüllung dieses Prüfschritts zu betrachten (sollte aber dennoch angemerkt werden).

=== 4. Bewertung

==== Erfüllt:

Geänderte Werte werden nach der Interaktion mit Bedienelementen ausgegeben.

== Einordnung des Prüfschritts

=== Einordnung des Prüfschritts nach EN 301 549 V3.1.1

11.5.2.15 Change notification

== Quellen

[.BLOCK_LANG_EN]
=== 11.5.2.15 Change notification

____
[.BLOCK_LANG_EN]
--
Where software provides a user interface it shall, by using the services as described in clause 11.5.2.3, notify assistive technologies about changes in those programmatically determinable attributes of user interface elements that are referenced in requirements 11.5.2.5 to 11.5.2.11 and 11.5.2.13.
--
____

(Aus EN 301 549 V3.1.1 Abschnitt 11.5.2.15 "Change notification")
