= Prüfschritt 11.5.2.6 Zeile, Spalte und Kopfzeilen
include::include/author.adoc[]
include::include/attributes.adoc[]

== Was wird geprüft?

Werden Datentabellen in der App eingesetzt, sollen dessen Zeilen- und Spalten programmatisch ermittelbar sein.
Diese Anforderung wird durch den Prüfschritt
ifdef::env_embedded[11.1.3.1b "Datentabellen richtig aufgebaut"]
ifndef::env_embedded[]
<<11.1.3.1b Datentabellen richtig aufgebaut.adoc#,11.1.3.1b Datentabellen richtig aufgebaut>>
endif::env_embedded[]
abgedeckt.

== Warum wird das geprüft?

Sehbehinderte und blinde Nutzende erschließen sich Datentabellen analytisch und entwickeln anhand der Spalten- und ggf. Zeilen-Überschriften eine Vorstellung vom Aufbau der Tabelle. Wenn es solche semantischen Überschriften gibt (oft sind diese auch visuell hervorgehoben) und Zelleninhalte nur mit diesen zusammen aussagekräftig sind, sollen sie beim Navigieren der Tabellenzellen verfügbar sein. Bei jedem Wechsel zur nächsten Zelle wird dann die jeweils neue Spalten- oder Zeilenüberschrift ausgegeben.

== Wie wird das geprüft?

=== 1. Anwendbarkeit des Prüfschritts

Der Prüfschritt ist immer anwendbar, wenn Tabellen in der App-Ansicht vorhanden sind.

=== 2. Prüfung

Die Prüfung erfolgt in Prüfschritt
ifdef::env_embedded[11.1.3.1b "Datentabellen richtig aufgebaut"]
ifndef::env_embedded[]
<<11.1.3.1b Datentabellen richtig aufgebaut.adoc#,11.1.3.1b Datentabellen richtig aufgebaut>>.
endif::env_embedded[]
Ergebnisse werden in diesen Prüfschritt übertragen.

== Einordnung des Prüfschritts

=== Einordnung des Prüfschritts nach EN 301 549 V3.1.1

[.BLOCK_LANG_EN]
==== 11.5.2.6 Row, column, and headers

____
[.BLOCK_LANG_EN]
--
Where the software provides a user interface it shall, by using the services as described in clause 11.5.2.3, make the row and column of each cell in a data table, including headers of the row and column if present, programmatically determinable by assistive technologies.
--
____

