= 11.5.2.16 Programmatisch steuerbare Stati und Eigenschaften
include::include/author.adoc[]
include::include/attributes.adoc[]

== Was wird geprüft?

== Warum wird das geprüft?

== Wie wird das geprüft?

=== 1. Anwendbarkeit des Prüfschritts
Der Prüfschritt ist anwendbar, wenn die zu prüfende Ansicht Bedienelemente hat, deren Zustände und Eigenschaften sich von Nutzenden ändern lassen. 

=== 2. Prüfung
.Bedienelemente auf der Ansicht ermitteln, bie denen sich von Nutzenden Zustände oder Eigenschaften ändern lassen.
.Mit dem eingesetzten Screenreader Bedienelemente fokussieren.
.Prüfen, ob sich Werte und Eigenschaften ändern lassen und der geänderte Wert vom Screenreader auch ausgelesen werden kann. 

=== 3. Hinweise
Im wesentlichen spiegelt dieser Prüfschritt die Bewertung von 11.4.1.2 Name, Rolle, Wert wider. In den meisten Fällen kann hier auf die Bewertung in diesem Prüfschritt verwiesen werden.

Die Erreichbarkeit von Bedienelementen mit der Tastatur ist nicht Gegenstand dieses Prüfschritts. Bei nativen Apps wird Wischgesten-Navigation eingesetzt, um Beldienelemente zu kokussieren und deren Wert zu ändern. Hierbei sind auch Navigationsmodi einzusetzen, die die Änderugn des Werts etwa druch vertikale Wisdchbewegungen im jeweiligen Modus erlauben.

Es wird nicht geprüft, ob ein initialer Wert ausgegeben wird. Nach Interaktion mit dem Bedienelement soll der eingestellte Wert aber ausgelesen werden können. Beispiele sind:
* Eine Umsetzung einer Leiste mit Reitern gibt bei  Fokussierung den aktuell ausgewählten Reiter aus
* Checkboxen lässt sich mit dem Screenreader bedienen und geben korrekt den jeweils gesetzten Wert aus
* Bei einer Combobox, die dynamisch generierte Optionen in einer Ausklappliste erzeugt, lassen sich die Optionen erreichen und auswählen, der geänderte Wert der Combobox wid vom Screenreader bei Fokussierung ausgegeben

=== 4. Bewertung

==== Erfüllt:
Alle Werte und Eigenschaften, die 

== Einordnung des Prüfschritts

=== Einordnung des Prüfschritts nach EN 301 549 V3.1.1

11.5.2.16 Modifications of states and properties

== Quellen

[.BLOCK_LANG_EN]
=== 11.5.2.16 Modifications of states and properties

____
[.BLOCK_LANG_EN]
--
Where permitted by security requirements, software that provides a user interface shall, by using the services as described in clause 11.5.2.3, allow assistive technologies to programmatically modify states and properties of user interface elements, where the user can modify these items.

NOTE 1:
In some cases the security requirements imposed on a software product may forbid external software from interfering with the ICT product and so this requirement would not apply.
Examples of systems under strict security requirements are systems dealing with intelligence activities, cryptologic activities related to national security, command and control of military forces.

NOTE 2:
Assistive technologies may be required to maintain the same level of security as the standard input mechanisms supported by the platform.
--
____

(Aus EN 301 549 V3.1.1 Abschnitt 11.5.2.16 "Modifications of states and properties")
