= Prüfschritt 11.5.2.13 Fokusverfolgung, Texteinfügemarke und Textauswahl
include::include/author.adoc[]
include::include/attributes.adoc[]

== Grundlage des Prüfschritts

Dieser Prüfschritt basiert auf den Kriterien der EN 301 549 Abschnitt
11.5.2.13 Tracking of focus and selection attributes.

== Was wird geprüft?

Informationen und Mechanismen für die Fokusverfolgung, Texteinfügemarke und
Textauswahl müssen für die Hilfsmitteltechnologie programatisch verfügbar
sein.

== Wie wird geprüft?

* Wird die Fokusposition vom Screenreader ausgegeben?
* Unterstützt der Inhalt, soweit verfügbar, die vom System und Screenreader vorgesehenen Mechanismen der Textauswahl (Ansage der Position Texteinfügemarke, Ansage markierter Text)?

== Quellen

=== Auszug EN 301 549

[.BLOCK_LANG_EN]
==== 11.5.2.13 Tracking of focus and selection attributes 

[.BLOCK_LANG_EN]
Where software provides a user interface it shall, by using the services as
described in clause 11.5.2.3, make information and mechanisms necessary to
track focus, text insertion point, and selection attributes of user interface
elements programmatically determinable by assistive technologies.
