= x07 Inhalte vom aktuellen Bildschirmausschnitt programmatisch ermittelbar
include::include/author.adoc[]
include::include/attributes.adoc[]

== Grundlage des Prüfschritts

Dieser Prüfschritt basiert auf den Kriterien der EN 301 549 Abschnitt
11.5.2.10 Text.

== Was wird geprüft?

Der Screenreader-Nutzer muss herausfinden können, welche Informationen gerade
auf dem Display angezeigt werden (Viewport).

== Wie wird geprüft?

In der Software werden verschiedene Ansichten geprüft.
Dabei wird mit eingeschaltetem SR überprüft, ob die Sichtbaren Elemente auch
vom Screenreader ausgegeben werden.
Auf Geräten mit Touch-Display können die Sichtbaren Elemente angetippt
werden, die Ausgabe vom SR sollte dann mit dem zu sehenden Element
übereinstimmen.

== Quellen

=== Auszug EN 301 549

[.BLOCK_LANG_EN]
==== 11.5.2.10 Text 

[.BLOCK_LANG_EN]
Where the software provides a user interface it shall, by using the services
as described in clause 11.5.2.3, make the text contents, text attributes, and
the boundary of text rendered to the screen programmatically determinable by
assistive technologies.
