= Prüfschritt 11.5.2.12 Ausführung der verfügbaren Handlungen
include::include/author.adoc[]
include::include/attributes.adoc[]

*Hinweis: Dies ist ein Entwurf. Inhalte können sich jederzeit ändern.*

== Was wird geprüft?
Die im Prüfschritt
ifdef::env_embedded[11.5.2.11 "Aktionen programmatisch ermittelbar"]
ifndef::env_embedded[]
  <<11.5.2.11 Aktionen programmatisch ermittelbar.adoc#,11.5.2.11 Aktionen
  programmatisch ermittelbar>>
endif::env_embedded[]
genannten Aktionen müssen auch mittels Hilfstechnologie ausführbar sein.

Wenn in der App Funktionen (bzw. Aktionen) ermittelbar sind, müssen diese auch für Screenreader-Nutzende aktivierbar sein.

* Ein Beispiel für ein Element mit verschiedenen Aktionen ist ein Listeneintrag in einer Mail-App. Während die primäre Aktion die jeweilige Mail anzeigt, können für die einzelnen Mails in der Liste auch weitere Aktioben, wie Löschen, Markieren oder Archivieren, aufgerufen werden, z.B. durch vertikale Wischgesten. Wenn eine solche Aktion ausgegeben wird, muss sie auch mit dem Screenreader aktivierbar sein, z.B  Doppeltippen.
* Ein anders Beispiel: Eine Liste von gruppierten Inhalten - etwa eine Nahverkehrsverbindung mit Abfahrtszeit, Fahrtdauer, Verkehrsmittel, und Ticketpreis - wird als ein Fokuspunkt vom Screenreader erreicht. Doppeltipp-Aktivieren geht zu einer Detail-Ansicht der Verbindung. Über den Aufruf einer hinterlegten Aktion, zum Beispiel über vertikale Wischgesten, wird eine Ticken-Kaufen-Ansicht ausgegeben, die in der Ansicht ohne Screenreader durch Antippen des Preises erreicht wird. Diese muss nach Ausgabe der Aktion auch aktivierbar sein, etwa durch Doppeltippen.
* Ein drittes Beispiel: Bei Fokussierung von Text in Eingabefeldern gibt es Bearbeitungsoptionen (z.B. Text auswählen, Kopieren, Ausschneiden, Einfügen). Diese Funktionen müssen nach Ausgabe auch für Screenreader-Nutzende aktivierbar sein.

== Warum wird das geprüft?
Screenreader-Nutzende sollen den gleichen Funktionsumfang zur Verfügung haben wir andere Nutzende. Dazu gehören nicht nur die primären Funktionen, etwa Aufrufen einer Detailansicht, sondern auch sekundäre Funktionen wie Löschen, Markieren, Liken, Ablegen, Verschieben, Teilen oder Editieren.

== Wie wird geprüft?

=== 1. Anwendbarkeit des Prüfschritts
Der Prüfschritt ist anwendbar, wenn die Ansicht interaktive Elemente enthält bei denen vom Screenreader über die Rolle (Link, Schalter) oder die Ansage einer sekundären Funktion (Details aufrufen, Markieren, Löschen, Bearbeiten, usw.) eine Funktion ermittelbar ist.

=== 2. Prüfung

==== 2.1 iOS
. Die Prüfung ergänzt den in Prüfschritt 11.5.2.11 beschriebenen Ablauf. Alle von Voiceover ausgegebenen Aktionen müssen auch aktivierbar sein, in der Regel durch Doppeltippen an beliebiger Stelle auf dem Display.
. Wird die programmatisch verfügbare Funktion nach Aktivierung auch ausgeführt? 

==== 2.2 Android

. Die Prüfung ergänzt den in Prüfschritt 11.5.2.11 beschriebenen Ablauf. Alle von Talkback ausgegebenen Aktionen müssen auch aktivierbar sein, zum Beispiel durch Doppeltippen an beliebiger Stelle auf dem Display.
. Manchmal sind mehrere Aktivierungsgesten verfügbar die bei Fokussierung des Elements ausgegeben werden, etwa "Zum Auswählen doppeltippen, Zum Tickets kaufen doppeltippen und halten".
. Wird die programmatisch verfügbare Funktion nach der entsprechenden Aktivierung auch ausgeführt? 

=== 3. Hinweise

==== 3.1 Hinweise zur Teamprüfung

Hier ist bei der Teamprüfung (nicht-visuelle Prüfende mit sehender Assistenz) bei Aktiverung ggf. visuell zu überprüfen, ob die Interaktion erfolgreich war, wenn dies mit dem Screenreader nicht unmittelbar nachvollziehbar ist (etwa durch Meldung eines geänderten Zustands).

== Quellen

=== Auszug EN 301 549 V.3.2.1

[.BLOCK_LANG_EN]
==== 11.5.2.12 Execution of available actions 
____

[.BLOCK_LANG_EN]
--
Where permitted by security requirements, software that provides a user
interface shall, by using the services as described in clause 11.5.2.3, allow
the programmatic execution of the actions exposed according to clause
11.5.2.11 by assistive technologies. 

*NOTE 1:*
In some cases the security requirements imposed on a software product may
forbid external software from interfering with the ICT product.
Examples of systems under strict security requirements are systems dealing
with intelligence activities, cryptologic activities related to national
security, command and control of military forces. 

*NOTE 2:*
Assistive technologies may be required to maintain the same level of security
as the standard input mechanisms supported by the platform.
--
____
