= Prüfschritt 11.5.2.11 Aktionen programmatisch ermittelbar
include::include/author.adoc[]
include::include/attributes.adoc[]

== Was wird geprüft?

Die verfügbaren Aktionen von Bedienelementen sollen auch für Screenreader-Nutzer ermittelbar sein.

== Warum wird geprüft?

Der Funktionsumfang von Apps muss auch für Screenreader-Nutzer vollständig ermittelbar sein. 

== Wie wird geprüft?

Prüfen, welche Aktionen grundsätzlich für ein Bedienelement ausführbar sind und mittels Screenreader prüfen, ob die Aktionen auch hier angeboten werden.
So muss bei einer Checkbox die Rolle und der Auswahlzustand ermittelbar sein, bei einer Auswahlliste die auswählbaren Optionen und die aktuell auwählbare Option. Ein Beispiel für ein Element mit verschiedenen Aktionen ist ein Listeneintrag in der Mail-App. Hier können die einzelnen Mails in der Liste z.B.
durch Wischgesten gelöscht oder auch archiviert werden.

== Quellen

=== Auszug EN 301 549

[.BLOCK_LANG_EN]
==== 11.5.2.11 List of available actions 

[.BLOCK_LANG_EN]
Where the software provides a user interface it shall, by using the services as
described in clause 11.5.2.3, make a list of available actions that can be
executed on a user interface element, programmatically determinable by
assistive technologies.
