= 11.5.2.14 Programmatisch steuerbare Texteinfügemarke und Selektion
include::include/author.adoc[]
include::include/attributes.adoc[]

== Was wird geprüft?

Bei Interface-Elementen der App, die Texteingaben und Textbearbeitung vorsehen, muss die Position des Fokus bzw. der Texteinfügemarke und sowie die Textauswahl auch für Hilfsmitteltechnologien änderbar sein. Geprüft wird dies mithilfe der integrierten Screenreader VoiceOver (iOS) und TalkBack (Android) und der Aktivierung der jeweiligen Gesten-Befehle für Fokusversetzung und Textauswahl. 

Ob die geänderte Cursor-Position bzw. Textauswahl programmatisch ausgegeben wird, ist Gegenstand des Prüfschritts 11.5.2.13. Beide Prüfschritte gehören eng zusammen, die Prüfung ist im Wesentlichen identisch.


== Warum wird das geprüft?

Die Textbearbeitung und die dazugehörigen Funktionen wie die Positionierung des Cursors und die Festlegung der Textauswahl sollen auch für Hilfsmittel-Nutzende verfügbar sein.

== Wie wird das geprüft?

=== 1. Anwendbarkeit des Prüfschritts

Der Prüfschritt ist nur auf Interface-Elemente anwendbar, die die Eingabe und Bearbeitung von Text vorsehen. In der Regel sind dies einzeilige oder mehrzeilige Textfelder in Formularen, oder auch editierbare Felder in Lückentexten.

=== 2. Prüfung

* Lässt sich mit aktiviertem Screenreader innerhalb von Textfeldern die Fokusposition ändern und die Textauswahl ändern (erweitern / verringern)?
* Unterstützt der Inhalt, soweit verfügbar, die vom System und Screenreader vorgesehenen Mechanismen für die Änderung der Fokusposition und der Textauswahl?

==== 2.1 iOS / VoiceOver

* Sicherstellen, dass in den VoiceOver-Einstellungen unter "Rotor" die Optionen "Zeichen" und "Textauswahl" aktiviert sind. Dann VoiceOver aktivieren.
* Ein Textfeld über horizontale Wischgeste fokussieren und durch Doppeltippen aktivieren. Es wird in der Regel "Einfügemarke am Ende" angesagt. (Doppeltippen ändert die Cursorposition von Ende zu Anfang und umgekehrt.) Wenn kein Text im Textfeld vorhanden ist, etwas Text eingeben.

== 3. Hinweise

Die Textauswahl kann je nach Screenreader und Betriebssystem unterschiedlich sein. In diesem Prüfschritt geht es darum, dass die Position des Fokus und die Markierung des Texts geändert werden kann. In 11.5.2.13 wird dagegen bewertet, ob die aktuelle Position des Fokus vom Screenreader augegeben werden kann und dass der gerade markierte Text ausgegeben werden kann.

=== Android / TalkBack

* Der Bearbeitungsmodus wird durch 2-Finger-Doppeltippen und Halten aktiviert.
* Die Fokusposition wird in der Regel mit den Lautstärketasten des Geräts versetzt.
* Über das lokale Kontextmenü (Wischen nach oben und dann nach rechts) können Optionen zum Textauswahl-Modus, zum Kopieren usw. aufgerufen werden

=== iOS / VoiceOver

* Durch Doppeltippen wird die Einfügemarke bei wiederholter Anwendung zwischen Anfang und Ende des Texts hin und her verschoben.
* Im Rotor eine der Optionen Zeichen/Wörter einstellen. Anschließend durch Streichen mit einem Finger von oben nach unten bzw. unten nach oben die Fokusposition versetzen.
* Text-Auswahl: Zoom-Geste (Pinch bzw. Finger auseinander ziehen / zusammen ziehen) anwenden, entsprechend werden Zeichen/Worte markiert.
* Kopieren/Einfügen (u. ä.): Im Rotor die Option Bearbeiten wählen. Anschließend durch Streichen mit einem Finger von oben nach unten die zugehörige Option auswählen und doppeltippen.

=== 4. Bewertung

==== Erfüllt:

* Eingabefeld vorhanden, die Texteinfügemarke lässt sich mit aktiviertem Screenreader versetzen und Text lässt sich markieren
* Fokus zwischen Bedienelementen lässt sich mit aktiviertem Screenreader versetzen

== Einordnung des Prüfschritts

=== Einordnung des Prüfschritts nach EN 301 549 V3.1.1

11.5.2.14 Modification of focus and selection attributes

== Quellen
* https://support.google.com/accessibility/android/answer/6151827?hl=en#zippy=%2Cversion-up%2Cversion-lower[Google-Hilfe zu TalkBack-Gesten]
* https://bbc.github.io/accessibility-news-and-you/accessibility-and-testing-with-talkback.html[BBC Accessibility and Testing with TalkBack]
* https://seeingdifferentuk.blogspot.com/2015/06/selecting-copying-and-pasting-with.html[Blogbeitrag SeeingDifferent zu Auswahl, Kopieren, Einfügen mit VoiceOver in iOS]

=== Auszug EN 301 549

[.BLOCK_LANG_EN]
==== 11.5.2.14 Modification of focus and selection attributes

[.BLOCK_LANG_EN]
--
Where permitted by security requirements, software that provides a user interface shall, by using the services as described in clause 11.5.2.3, allow assistive technologies to programmatically modify focus, text insertion point, and selection attributes of user interface elements where the user can modify these items.

NOTE 1:
In some cases the security requirements imposed on a software product may forbid external software from interfering with the ICT product and so this requirement would not apply.
Examples of systems under strict security requirements are systems dealing with intelligence activities, cryptologic activities related to national security, command and control of military forces.

NOTE 2:
Assistive technologies may be required to maintain the same level of security as the standard input mechanisms supported by the platform.
--

(Aus EN 301 549 V3.1.1 Abschnitt 11.5.2.14 "Modification of focus and selection attributes")
