= 11.5.2.16 Programmatisch steuerbare Stati und Eigenschaften
include::include/author.adoc[]
include::include/attributes.adoc[]

== Was wird geprüft?

== Warum wird das geprüft?

== Wie wird das geprüft?

=== 1. Anwendbarkeit des Prüfschritts

=== 2. Prüfung

=== 3. Hinweise

=== 4. Bewertung

==== Erfüllt:

== Einordnung des Prüfschritts

=== Einordnung des Prüfschritts nach EN 301 549 V3.1.1

11.5.2.16 Modifications of states and properties

== Quellen

[.BLOCK_LANG_EN]
=== 11.5.2.16 Modifications of states and properties

____
[.BLOCK_LANG_EN]
--
Where permitted by security requirements, software that provides a user interface shall, by using the services as described in clause 11.5.2.3, allow assistive technologies to programmatically modify states and properties of user interface elements, where the user can modify these items.

NOTE 1:
In some cases the security requirements imposed on a software product may forbid external software from interfering with the ICT product and so this requirement would not apply.
Examples of systems under strict security requirements are systems dealing with intelligence activities, cryptologic activities related to national security, command and control of military forces.

NOTE 2:
Assistive technologies may be required to maintain the same level of security as the standard input mechanisms supported by the platform.
--
____

(Aus EN 301 549 V3.1.1 Abschnitt 11.5.2.16 "Modifications of states and properties")
