= 11.6.2 Keine Störung von Barrierefreiheitsfunktionen
include::include/author.adoc[]
include::include/attributes.adoc[]

*Hinweis: Dies ist ein Entwurf. Inhalte können sich jederzeit ändern.*

== Was wird geprüft?
Barierefreiheitsfunktionen des Betriebssystems wie Screenreader, Zoom, oder Sprachsteuerung sollen nicht durch Funktionen der App gestört werden - es sei denn, Nutzende erwarten oder aktivieren solche App-Funktionen in der Nutzung der App.

Ein mögliches positives Beispiel wäre eine Scan-App, die bei aktiviertem Screenreader beim Scannen von Dokumenten mit der Kamera über die Sprachausgabe Ausrichtungshinweise gibt. Solange diese App-Funktion aktiv ist, wäre die Screenreader-Ausgabe anderer auf der gleichen Ansicht verfügbarer Elemente dann evtl. gestört. Für blinde Nutzer wären solche Ausrichtungshinweise wohl als implizit gewünschtes Verhalten zu betrachten. Sie sollten sich dann jedoch in den Einstellungen auch deaktivieren lassen.

Ein weiteres positives Beispiel ist der Pinzetten-Geste zum Hinein- und Hinauszoomen, etwa in die Bildvorschau Kamera-Apps. Wird die Vergrößerungsfunktion aktiert, verändert die Pinzetten-Geste nicht den Zoomfaktor der Kamera (und würde dadurch die Bedienungshilfe stören) sondern vergößert die gesamte Ansicht einschließlich andere Bedienelemente unterhalb der Bildvorschau. Erst wenn die Bedienungshilfe Vergrößerung (ggf. vorübergehend) deaktiviert wird, ist die gleiche Geste auf App-Ebene, also in der Bildvorschau, wirksam.

== Warum wird das geprüft?
Wenn Funktionen der App die Nutzung von Barrierefreiheitsfunktionen stören oder unmöglich machen, ist eine Nutzung nicht oder nur schwer möglich.

== Wie wird das geprüft?

=== 1. Anwendbarkeit des Prüfschritts
Der Prüfschritt ist immer anwendbar.

=== 2. Prüfung
. In den Bedienungshilfen Screenreader aktivieren. Ist die Nutzung mit den dokumentierten Gesten möglich?
. In den Bedienungshilfen Zoom (iOS) bzw. Vergrößerung (Android) aktivieren. Ist die Nutzung mit den Dokumentierten Gesten möglich?

=== 3. Hinweise
Es wird hier nicht geprüft, ob alle Bedienelemente zugänglich bzw. richtig ausgezeichnet sind, sondern ob Barrierefreiheitsfunktionen grundsätzlich ohne Störung zur Verfügung stehen. 
Mögliche Störungen wären etwa das automatische Abspielen von Audio, das die Ausgabe des Screenreaders überlagert und damit schlecht verständlich macht, oder die Verwendung von Gesten durch der App, die für die Aktivierung der Barrierefreiheitsfunktion eingesetzt werden (etwa die Dreifinger-Doppeltipp-Geste zur Aktivierung des iOS Zooms).

=== 4. Bewertung

==== Erfüllt:
Barrierefreiheitsfunktionen lassen sich störungsfrei nutzen (es sei denn, die störende Funktion der App wird Nutzenden explizit aktiviert).

== Einordnung des Prüfschritts

=== Einordnung des Prüfschritts nach EN 301 549 V3.1.1

11.6.2 No disruption of accessibility features

== Quellen

[.BLOCK_LANG_EN]
=== 11.6.2 No disruption of accessibility features

____
[.BLOCK_LANG_EN]
--
Where software provides a user interface it shall not disrupt those documented accessibility features that are defined in platform documentation except when requested to do so by the user during the operation of the software.
--
____

(Aus EN 301 549 V3.1.1 Abschnitt 11.6.2 "No disruption of accessibility features")
