= 11.6.2 Keine Störung von Barrierefreiheitsfunktionen
include::include/author.adoc[]
include::include/attributes.adoc[]

*Hinweis: Dies ist ein Entwurf. Inhalte können sich jederzeit ändern.*

== Was wird geprüft?
Barierefreiheitsfunktionen des Betriebssystems wie Screenreader, Zoom, oder Sprachsteuerung sollen nicht durch Funktionen der App gestört werden - es sei denn, Nutzende erwarten oder aktivieren solche App-Funktionen in der Nutzung der App.

Ein  positives Beispiel ist eine Scan-App, die bei aktiviertem Screenreader beim Scannen von Dokumenten mit der Kamera über die Sprachausgabe Ausrichtungshinweise gibt. Solange diese App-Funktion aktiv ist, wäre die Screenreader-Ausgabe anderer ggf. auf der gleichen Ansicht verfügbarer Elemente evtl. gestört. Für blinde Nutzer sind solche Ausrichtungshinweise aber als implizit gewünschtes und erwartetes Verhalten zu betrachten. Die Funktion sollte sich jedoch in den App-Einstellungen auch deaktivieren lassen.

Ein weiteres positives Beispiel ist die zwei-Finger-Pinzetten-Geste zum Hinein- und Hinauszoomen, etwa in die Bildvorschau von Kamera-Apps. Wird die Vergrößerung in den Bedienungshilfen aktiviert, ändert die Pinzetten-Geste nicht mehr auf App-Ebene den Zoomfaktor der Kamera (und würde dadurch die Bedienungshilfe aushebeln) sondern vergrößert die gesamte Ansicht einschließlich andere Bedienelemente unterhalb der Bildvorschau. Erst wenn die Bedienungshilfe Vergrößerung (ggf. vorübergehend) deaktiviert wird, ist die gleiche Geste auf App-Ebene, also in der Bildvorschau, wirksam.

Ein hypothetisches negatives Beispiel: Eine App nimmt aufd einer Ansicht automatisch über das Geräte-Mikrophon Ton auf. Die Sprachsteuerung von Bedienelementen auf dieser Ansicht ist dadurch nicht mehr möglich. Würde die Audio-Aufnahme von Nutzenden explizit aktiviert, wäre die Störung der Sprachsteuerungs-Funktion zu akzeptieren. 

== Warum wird das geprüft?
Wenn Funktionen der App die Nutzung von Barrierefreiheitsfunktionen stören oder unmöglich machen, ist eine Nutzung für manche Menschen möglicherweise nicht oder nur schwer möglich.

== Wie wird das geprüft?

=== 1. Anwendbarkeit des Prüfschritts
Der Prüfschritt ist immer anwendbar.

=== 2. Prüfung
. In den Bedienungshilfen den Screenreader aktivieren. Ist die Nutzung mit den dokumentierten Screenreader-Gesten möglich?
. In den Bedienungshilfen Zoom (iOS) bzw. Vergrößerung (Android) aktivieren. Ist die Nutzung mit den für Zoom bzw. Vergößerung dokumentierten Gesten möglich?

=== 3. Hinweise
Es wird hier nicht geprüft, ob alle Bedienelemente zugänglich bzw. richtig ausgezeichnet sind, sondern nur, ob Barrierefreiheitsfunktionen grundsätzlich ohne Störung zur Verfügung stehen. Mögliche Störungen wären etwa das automatische Abspielen von Audio-Hinweisen, -Sprachausgaben oder -Aufzeichnungen, welche die Ausgabe des Screenreaders überlagern und damit schlecht verständlich machen, oder die Verwendung von Gesten in der App, die durch Bedienungshilfen eingesetzt werden (etwa die Dreifinger-Doppeltipp-Geste zur Aktivierung des iOS Zooms).

Die Gesten, die durch Bedienungshilfen genutzt werden, ändern sich ggf. mit neuen Versionen der Betriebssysteme und sind zum Teil auch über Einstellungen in den Betriebssystemen konfigurierbar. Dadurch kann es zu Konflikten kommen, die nicht immer für App-Entwickler voraussehbar sind. Bei der Bewertung von Gestenkonflikten sollte also  die Anpassbarkeit von Gesten sowohl auf Betriebssystem-Ebene als auch auf App-Ebene berücksichtigt werden.

=== 4. Bewertung

==== Erfüllt:
Barrierefreiheitsfunktionen lassen sich störungsfrei nutzen (es sei denn, die störende Funktion der App wird Nutzenden explizit aktiviert).

== Einordnung des Prüfschritts

=== Einordnung des Prüfschritts nach EN 301 549 V3.1.1

11.6.2 No disruption of accessibility features

== Quellen

[.BLOCK_LANG_EN]
=== 11.6.2 No disruption of accessibility features

____
[.BLOCK_LANG_EN]
--
Where software provides a user interface it shall not disrupt those documented accessibility features that are defined in platform documentation except when requested to do so by the user during the operation of the software.
--
____

(Aus EN 301 549 V3.1.1 Abschnitt 11.6.2 "No disruption of accessibility features")
