= Prüfschritt 11.7 Benutzerdefinierte Einstellungen
include::include/author.adoc[]
include::include/attributes.adoc[]

== Was wird geprüft?

Die App soll Systemweite Einstellungen berücksichtigen. Im Einzelnen sind dies:

* Messeinheiten
* Farben (z. B. Darkmode)
* Kontraste
* Schriftarten
* Schriftgrößen
* Darstellung des Fokuscursors

Die App kann darüberhinaus eigene Werte für diese Einstellungen anbieten, die systemweiten Einstellungen müssen jedoch voreingestellt sein.

== Warum wird das geprüft?

Wenn Menschen eigene Einstellungen im Betriebssystem vornehmen, zum Beispiel weil sie größere Schrift oder eigene angepasste Farbeinstellungen brauchen, sollen diese vom Webangebot wo immer möglich respektiert und übernommen werden.

== Wie wird geprüft?

=== Anwendbarkeit des Prüfschritts

Der Prüfschritt ist nahezu immer anwendbar.
Die einzige Ausnahme besteht, wenn die App komplett isoliert vom Betriebssystem läuft, z. B. innerhalb einer virtuellen Maschine.

=== Prüfung

==== Farben

Wenn das Betriebssystem Optionen für die Darstellung von Farben anbietet, müssen diese in der zu prüfenden App übernommen werden.
Für die Prüfung werden entsprechende Systemeinstellungen verändert und die zu prüfende App neu gestartet. Die Änderungen sollten dann in allen Ansichten der App sichtbar sein.

===== iOS / iPadOS

. Einstelungen öffenen (Einstellungne > Bedienungshilfen > Anzeige und Textgröße)
* "Farben umkehren" aktivieren.
* App neu starten und prüfen, ob die Einstellungen übernommen werden.

. Einstellungen öffnen (Einstellungen > Anzeige und Hilligeit)
* Erscheinungsbild "Dunkel" aktivieren.
* App neu starten und prüfen, ob die Einstellungen übernommen werden.


===== Android

. Einstellungen öffnen (Einstellungen > Bedienungshilfen)
die App unterstützt:
. Die Einstellungen "Farbumkehr", "Farbkorrektur" und "Dunkles Design" aktivieren.
. Nach der jeweiligen Einstellung App neu starten und prüfen, ob die Einstellungen übernommen werden.


==== Schriftart und Schriftgröße

Die Darstellung von Fließtexten richtet sich nach den Einstellungen im System. Für die Prüfung werden die systemweiten Einstellungen verändert und die zu prüfende App neugestartet.

===== iOS / iPadOS
. Einstellungen öffnen (Bedienungshilfen > Anzeige & Textgröße)
. Die Einstellungen "Fetter Text" und "Größerer Text" aktivieren.
. Nach der jeweiligen Einstellung App neu starten und prüfen, ob die Einstellungen übernommen werden.

===== Android

. Einstellungen öffnen (Einstellungen > Bedienungshilfen)
. Die Einstellungen "Schriftgröße" und "Fettdruck" aktivieren.
. App neu starten und prüfen, ob die Einstellungen übernommen werden.

==== Hinweise

Wenn einer der o. g. Einstellungen in iOS / iPadOS oder Android nicht zu finden ist und somit vom Nutzer nicht angepasst werden kann, wird diese Einstellung bei der Prüfung nicht berücksichtigt.

Die Schriftart und -Größe muss sich nur in Fließtexten an den systemweiten Einstellungen richten. Es wird nicht verlangt, dass Bedienelemente der App dynamische Veränderungen dieser Einstellungen unterstützen, da hier das Layout der App verändert
würde.

Bei Hinweisen können Sie auf GitHub https://github.com/BIK-BITV/BIK-App-Test/issues[ein Issue zu diesem Prüfschritt erstellen].
== Quellen

[.BLOCK_LANG_EN]
=== 11.7 User preferences

[.BLOCK_LANG_EN]
--
Where software is not designed to be isolated from its platform, and provides
a user interface, that user interface shall follow the values of the user
preferences for platform settings for:
units of measurement, colour, contrast, font type, font 
size, and focus cursor except where they are overridden by the user.

NOTE 1:
Software that is isolated from its underlying platform has no access to user
settings in the platform and thus cannot adhere to them.

NOTE 2:
For web content, the underlying platform is the user agent.

NOTE 3:
This does not preclude the software from having additional values for a
setting as long as there is one mode where the application will follow the
system settings even if more restricted.
--

(Aus EN 301 549 V3.1.1 Abschnitt 11.7 "User preferences")
