= Prüfschritt 11.8.5 Vorlagen
include::include/author.adoc[]
include::include/attributes.adoc[]

== Was wird geprüft?

Wenn die Software ein Autorenwerkzeug ist und Vorlagen für die Dokumente, die
es erstellt, anbietet, soll mindestens eines der Vorlagen die Kriterien
für Web- oder Nicht-Web-Dokumente erfüllen (je nach Dokumententyp).
Die entsprechenden Kriterien sind in der EN 301 549 im Kapitel 9 und 10 zu
finden.

Die für die Barrierefreiheit optimierten Vorlagen sollen dabei eindeutig als
solche zu identifizieren sein.

== Warum wird das geprüft?
Vorlagen helfen Autoren dabei, eine semantische Ausgabe zu erzeugen. 

== Wie wird geprüft?

=== 1. Anwendbarkeit des Prüfschritts

Der Prüfschritt ist anwendbar, wenn die Ansicht der App Teil eines Autorenwerkzeugs ist 
und Vorlagen für die Dokumente, die es erstellt, anbietet. 
Das App-Test-Verfahren prüft jedoch keine Dokumente. 
Im Rahmen dieses Verfahrens können lediglich Autorenwerkzeuge getestet werden, 
deren Ausgabe in der gleichen App stattfindet (z. B. Kommentarfunktion in einer Social-Media-App).

Für komplexere Werkzeuge, dessen Ausgaben nicht nur in der App selbst stattfinden, 
muss ggf. ein zusätzlicher Prüfauftrag außerhalb des BIK App-Tests erteilt werden, da hier die Ausgabe-Dateien bzw -Formate auf Barrierefreiheit geprüft werden müssen.

=== 2. Prüfung

. Zu prüfende Ansicht der App öffnen.
. Prüfen, ob das Autorenwerkzeug wahlweise verschiedene Vorlagen für die Erstellung von Inhalten anbietet.
. Prüfen, ob bei Vorhandensein alternativer Vorlagen, welche die Erstellung barrierefreier Inhalte unterstützen, diese deutlich als solche markiert sind. (Wenn es nur eine Vorlage gibt, muss diese nicht extra als barrierefreiheits-unterstützend markiert sein).
. Testausgaben mit der barrierefreiheits-unterstützenden Vorlagen erstellen, ansonsten Standardvorlage nutzen.
. Testausgaben auf Barrierefreiheit prüfen (Mängel sind zusätzlich bei den sonstigen anwendbaren Prüfschritten einzutragen).

=== 3. Hinweise

Für die Prüfpraxis sind weitere Hinweise notwendig, auf GitHub können Sie https://github.com/BIK-BITV/BIK-App-Test/issues[dazu ein Issue eröffnen].

== Einordnung des Prüfschritts

=== Einordnung des Prüfschritts nach EN 301 549 V.3.2.1

[.BLOCK_LANG_EN]
==== 11.8.5 Templates

____
[.BLOCK_LANG_EN]
When an authoring tool provides templates, at least one template that supports
the creation of content that conforms to the requirements of clauses 9 (Web)
or 10 (Non-web documents) as applicable shall be available and identified as
such.
____

