= Prüfschritt 11.8.1 Inhaltstechnologie
include::include/author.adoc[]
include::include/attributes.adoc[]

== Was wird geprüft?
Wenn Autorenwerkzeuge Zielformate erzeugen, etwa Webseiten oder Dokumente, sollen die für die barrierefreie Nutzung notwendigen Informationen vom erzeugten Zielformat unterstützt werden. Genauer beschrieben ist das in den Anforderungen 11.8.2 bis 11.8.5.

Ein Beispiel eines Autorenwerkzeugs ist eine native App zur Texterstellung und Bearbeitung. Aber auch eine Kommentarfunktion in einer App lässt sich als ein (stark reduzuertes) Autorenwerkzeug betrachten.

Es soll möglich sein, im Autorenwerkzeug semantische Auszeichungen für das Zielformat vorzunehmen.

* Ein Beispiel: Wenn das Zielformat Überschriften enthält, sollen diese im Autorenwerkzeug auch semantisch definiert werden können (nicht etwa nur durch Festlegung von Schriftgröße, Fettung usw.). 

* Ein anderes Beispiel: Wenn im Zielformat Bilder erscheinen, soll das Autorenwerkzeug in der Lage sein, bei der Erstellung für diese Alternativtexte zu hinterlegen. 

Das Gleiche gilt für andere Arten von Inhalten, wie Listen oder Tabellen. Das Autorensystem soll in der Lage sein, die für die barrierefreie Nutzung wichtigen Informationen in Form von geeigneten semantischen Auszeichnungen (z.B. als HTML-Mark-Up) im Zielformat zu erzeugen.

== Warum wird das geprüft?
Autorensysteme sollen Inhalte in den jeweiligen Zielformaten erzeugen, die barrierefrei zugänglich sind, damit Menschen mit Behinderungen diese einfach nutzen können. Dafür ist die passende semantische Auszeichnung von Inhalten wie Überschriften, Bildern, Tabellen, Listen usw. wichtig.

== Wie wird das geprüft?

=== 1. Anwendbarkeit des Prüfschritts
Der Prüfschritt ist anwendbar, wenn die App ein Autorenwerkzeug ist oder Elemente eines Autorenwerkzeugs integriert und das Zielformat in der App selbst  angezeigt wird bzw. darin aufrufbar ist (auch etwa als HTML-Datei innerhalb eines Webviews). 

Der Dokumententyp, den die Software erstellt, muss grundsätzlich für die Barrierefreiheit optimierbar sein, ansonsten ist dieser Prüfschritt nicht anwendbar. Für externe Zielformate, etwa PDF, muss ggf. eine getrennte Prüfung vorgenommen werden.

Umfangreiche Textverarbeitungen, die Dokumente erzeugen und anzeigen, welche auch außerhalb der App geladen werden können, sind ggf. im App-Test allein nicht bzw. nicht ausreichend prüfbar, da nicht alle semantischen Auszeichnungen in der App-Umgebung überprüft werden können.

=== 2. Prüfung
. Vom Autorenwerkzeug generiertes Zielformat überprüfen. 
. Wenn hier visuell Informationen vorhanden sind, sollen diese auch bei Nutzung des Screenreaders ausgegeben werden.

=== 3. Hinweise
Die genauere Prüfung der semantischen Auszeichnung erfolgt in Prüfschritten 11.8.2 bis 11.8.5.

=== 4. Bewertung

==== Erfüllt:
Visuell verfügbare Inhalte des Zielformats sind auch mit dem Screenreader voll zugänglich.

== Einordnung des Prüfschritts

=== Einordnung des Prüfschritts nach EN 301 549 V3.2.1

[.BLOCK_LANG_EN]
==== 11.8.1 Content technology

____
[.BLOCK_LANG_EN]
--
Authoring tools shall conform to clauses 11.8.2 to 11.8.5 to the extent that information required for accessibility is supported by the format used for the output of the authoring tool.
--
____
