= Prüfschritt 11.8.5 Vorlagen
include::include/author.adoc[]
include::include/attributes.adoc[]

== Was wird geprüft?

Wenn die Ansicht der App Teil eines Autorenwerkzeugs ist und Vorlagen bzw. Eingabemasken für die Dokumente, die es erstellt, anbietet, soll mindestens eine der angebotenen Vorlagen die Erstellung barrierefreier Web- oder Nicht-Web-Dokumente ermöglichen (je nach Dokumententyp).

Falls es alternative Vorlagen gibt, sollten für die Barrierefreiheit optimierte Vorlagen eindeutig als solche zu identifizieren sein.

== Warum wird das geprüft?

(folgt)

== Wie wird geprüft?

=== 1. Anwendbarkeit des Prüfschritts

Der Prüfschritt ist anwendbar, wenn die Ansicht der App Teil eines Autorenwerkzeugs ist und Vorlagen für die Dokumente, die es erstellt, anbietet. Das App-Test-Verfahren prüft jedoch keine Dokumente. Im Rahmen dieses Verfahrens können lediglich Autorenwerkzeuge getestet werden, dessen Ausgabe in der gleichen App stattfindet (z. B. Kommentarfunktion in einer Social-Media-App).

Für komplexere Werkzeuge, dessen Ausgaben nicht nur in der App selbst stattfinden, muss ein extra Auftrag erteilt werden, da hier die Ausgabe-Dateien bzw -Formate auf Barrierefreiheit geprüft werden müssen.

=== 2. Prüfung

. Zu prüfende Ansicht der App öffnen.
. Prüfen, ob das Autorenwerkzeug wahlweise verschiedene Vorlagen für die Erstellung von Inhalten anbietet.
. Prüfen, ob bei Vorhandensein alternativer Vorlagen, welche die Erstellung barrierefreier Inhalte unterstützen, diese deutlich als solche markiert sind. (Wenn es nur eine Vorlage gibt, muss diese nicht extra als barrierefreiheits-unterstützend markiert sein).
. Testausgaben mit der barrierefreiheits-unterstützenden Vorlagen erstellen, ansonsten Standardvorlage nutzen.
. Testausgaben auf Barrierefreiheit prüfen (Mängel sind zusätzlich bei den sonstigen anwendbaren Prüfschritten einzutragen).
  
=== 3. Hinweise
  
Für die Prüfpraxis sind weitere Hinweise notwendig, auf GitHub können Sie https://github.com/BIK-BITV/BIK-App-Test/issues[dazu ein Issue eröffnen].

== Einordnung des Prüfschritts

=== Einordnung des Prüfschritts nach EN 301 549 V3.1.1

1.8.5 Templates

== Quellen

[.BLOCK_LANG_EN]
=== 11.8.5 Templates

[.BLOCK_LANG_EN]
When an authoring tool provides templates, at least one template that supports
the creation of content that conforms to the requirements of clauses 9 (Web)
or 10 (Non-web documents) as applicable shall be available and identified as
such.

(Aus EN 301 549 V3.1.1 Abschnitt 11.8.5 "Templates")
