= Prüfschritt 11.8.4 Reparaturunterstützung
include::include/author.adoc[]
include::include/attributes.adoc[]

== Was wird geprüft?

Wenn Autorenwerkzeuge Funktionen zur Erkennung von Barrierefreiheits-Fehlern bei der Erstellung von Dokumenten bieten, dann sollen Vorschläge zur Behebung dieser Fehler verfügbar sein.

== Warum wird das geprüft?
Autorenwerkzeuge sollen Inhalte in den jeweiligen Zielformaten erzeugen, die barrierefrei zugänglich sind, damit Menschen mit Behinderungen diese einfach nutzen können. Wenn Autorenwerkzeuge Fehler erkennen können, sollen sie über geeignete Vorschläge den Autor:innen helfen, die Barrierefreiheit des erzeugten Zielformats verbessern.

== Wie wird geprüft?

=== 1. Anwendbarkeit des Prüfschritts

Der Prüfschritt ist anwendbar, wenn die Ansicht der App Teil eines Autorenwerkzeugs ist oder eine Autorenfunktion enthält (etwa eine Kommentarfunktion). Barrierefreiheits-Fehler in den erstellten Dokumenten bzw. Inhalten können aufgezeigt werden (z.B. "Bitte vergeben Sie eine Überschrift" oder "Wenn Sie ein informationstragendes Bild einfügen, vergeben Sie bitte einen passenden Alternativtext").

=== 2. Prüfung

. Mit der Autorenfunkiton Inhalte erstellen und dabei vorhandene Auszeichnungsmöglichkeiten nicht nutzen, z.B.:

* Vorhandene Felder für Überschriften leer lassen, Überschriftenauszeichung von Text-Editoren nicht nutzen

* Bilder einfügen, ohne einen Alternativtext festzulegen

* In ein E-Mail-Adressen-Feld eine fehlerhafte E-Mail-Adresse eingeben

. Inhalt sichern oder abschicken und prüfen, ob eine Überprüfung auf Fehler stattfindet.

. Falls eine Fehlerprüfung stattfindet (z.B. wenn das Sichern oder Abschicken nicht möglich ist bzw. fehlerhafte oder fehlende Eingaben grafisch hervorgehoben werden), prüfen, ob Hinweise für die Korrektur der Fehler gegeben werden.

=== 3. Hinweise

Der Begriff "Dokumente" wird dabei weit gefasst und umfasst Web- und
Nicht-Web-Dokumente.
Siehe dazu auch Kapitel 9 (Web-Inhalte) und Kapitel 10 (Nicht-Web-Inhalte) der
EN 301 549.

Für die Prüfpraxis sind weitere Hinweise notwendig, auf GitHub können Sie
https://github.com/BIK-BITV/BIK-App-Test/issues[dazu ein Issue eröffnen].

== Einordnung des Prüfschritts

=== Einordnung des Prüfschritts nach EN 301 549 V3.1.1

11.8.4 Repair assistance

== Quellen

[.BLOCK_LANG_EN]
=== 11.8.4 Repair assistance

[.BLOCK_LANG_EN]
--
If the accessibility checking functionality of an authoring tool can detect
that content does not meet a requirement of clauses 9 (Web) or 10 (Non-web
documents) as applicable, then the authoring tool shall provide repair
suggestion(s). 

NOTE:
This does not preclude automated and semi-automated repair which is possible
(and encouraged) for many types of content accessibility problems. 
--

(Aus EN 301 549 V3.1.1 Abschnitt 11.8.4 "Repair assistance")
