= Prüfschritt 11.8.2 Erstellung barrierefreier Inhalte
include::include/author.adoc[]
include::include/attributes.adoc[]

== Was wird geprüft?

Wenn es sich bei der zu testenden Software um ein Autorenwerkzeug handelt, soll
die Anwendung die Erstellung von barrierefreien Dokumenten erlauben und den
Nutzer dabei unterstützen.

== Warum wird das geprüft?

Für Nutzende von Hilfsmitteln, die eine programmatische Ermittelbarkeit von Informationen brauchen, ist es wichtig, dass Autorenwerkzeuge dies bei der Erzeugung von Inhalten unterstützen. Wenn zum Beispiel ein Kommentar-Eingabefeld die Vergabe einer Überschrift erlaubt, sollte diese auf der erzeugten (bzw. aktualisierten) Seite auch als Überschrift ausgezeichnet sein, damit Hilfsmittel-Nutzer diese semantische Information auswerten können (zum Beispiel zum Navigieren von Kommentar zu Kommentar).

Die Prüfung bezieht sich auf die Ausgabe des jeweiligen Autorenwerkzeugs.

Der Dokumententyp, den die Software erstellt, muss grundsätzlich für die Barrierefreiheit
optimierbar sein, ansonsten ist dieser Prüfschritt nicht anwendbar.

Die Ausgabe des Autorenwerkzeugs muss innerhalb der App dargestellt werden, 
es können lediglich integrierte Werkzeuge wie z. B. Kommentareditoren getestet werden. 
Umfangreiche Autorenwerkzeuge, wie z. B. Textverarbeitungen, können mit dem App-Test-Verfahren derzeit nicht geprüft werden, 
da hier dann auch die Barrierefreiheit der durch das Tool generierten Dateien geprüft werden müsste.

== Wie wird geprüft?

=== 1. Anwendbarkeit des Prüfschritts

Der Prüfschritt ist anwendbar, wenn die Ansicht der App Teil eines Autorenwerkzeugs ist. 
Ebenfalls anwendbar ist der Prüfschritt auf Kommentarfunktionen, die die Strukturierung von Kommentaren erlauben.

=== 2. Prüfung

. In der Ansicht der App mittels Autorenwerkzeug (z. B. Kommentarfunktion) eine Ausgabe generieren (und ggf. freigegeben).
. Die erzeugte Ausgabe prüfen. Alle für die Ansicht anwendbaren Prüfschritte sind anzuwenden.

=== 3. Hinweise

Das Autorenwerkzeug darf für die Erstellung von barrierefreien Dokumenten von
anderen Werkzeugen abhängen, um spezifische Kriterien zu erfüllen.
Das könnte z.B. ein zusätzliches Werkzeug für die Erstellung von Untertiteln
sein.

Das Autorenwerkzeug darf für die Erstellung von barrierefreien Dokumenten von anderen Werkzeugen abhängen, 
um spezifische Kriterien zu erfüllen. Das könnte z. B. ein zusätzliches Werkzeug für die Erstellung von Untertiteln sein.

Nur jene Auszeichnungsmängel in der Ausgabe können als Fehler bewertet werden, 
für die es bei der Eingabe Möglichkeiten der Auszeichnung gibt. 
Wenn also z.B. ein Kommentarfeld lediglich als `textarea` ohne weitere Auszeichnungsmöglichkeit umgesetzt ist 
und Nutzende deshalb textbasierte Techniken zur Gestaltung verwenden (z.B. Listen über Zeilenumbrüche und Spiegelstriche), 
wäre das Fehlen von Listen-Markup im ausgegebenen Kommentar nicht als Fehler zu bewerten. 

== Einordnung des Prüfschritts

=== Einordnung des Prüfschritts nach EN 301 549 V.3.2.1

[.BLOCK_LANG_EN]
=== 11.8.2 Accessible content creation

[.BLOCK_LANG_EN]
____
Authoring tools shall enable and guide the production of content that conforms
to clauses 9 (Web content) or 10 (Non-Web content) as applicable.

NOTE:
Authoring tools may rely on additional tools where conformance with specific
requirements is not achievable by a single tool.
For example, a video editing tool may enable the creation of video files for
distribution via broadcast television and the web, but authoring of caption
files for multiple formats may be provided by a different tool.
____
