= Prüfschritt 11.8.2 Barrierefreie Erstellung von Inhalten
include::include/author.adoc[]
include::include/attributes.adoc[]

*Hinweis: Dies ist ein Entwurf. Inhalte können sich jederzeit ändern.*

== Was wird geprüft?

Wenn es sich bei der zu testenden Software um ein Autorenwerkzeug handelt, soll
die Anwendung die Erstellung von barrierefreien Dokumenten erlauben und den
Nutzer dabei unterstützen.

== Warum wird das geprüft?
Autorensysteme sollen Inhalte in den jeweiligen Zielformaten erzeugen, die barrierefrei zugänglich sind, damit Menschen mit Behinderungen diese einfach nutzen können. Dafür ist die passende semantische Auszeichnung von Inhalten wie Überschriften, Bildern, Tabellen, Listen usw. wichtig.

== Wie wird geprüft?

=== Anwendbarkeit des Prüfschritts

Der Prüfschritt ist anwendbar, wenn die App ein Autorenwerkzeug ist oder Elemente eines Autorenwerkzeugs integriert und das Zielformat in der App selbst  angezeigt wird bzw. darin aufrufbar ist (auch etwa als HTML-Datei innerhalb eines Webviews). 

Der Dokumententyp, den die Software erstellt, muss grundsätzlich für die Barrierefreiheit optimierbar sein, ansonsten ist dieser Prüfschritt nicht anwendbar. Für externe Zielformate, etwa PDF, muss ggf. eine getrennte Prüfung vorgenommen werden.

Umfangreiche Textverarbeitungen, die Dokumente erzeugen und anzeigen, welche auch außerhalb der App geladen werden können, sind ggf. im App-Test allein nicht bzw. nicht ausreichend prüfbar, da nicht alle semantischen Auszeichnungen in der App-Umgebung überprüft werden können.

=== Prüfung

Für die Praxis fehlt noch eine praktikable Methode, Für  Hinweise dazu können
Sie auf GitHub
https://github.com/BIK-BITV/BIK-App-Test/issues[ein Issue zu diesem Prüfschritt erstellen].

In der App wird mittels des Autorenwerkzeugs (z. B. Kommentarfunktion) eine
Ausgabe generiert.
Die Ansicht der App, in der die Ausgabe angezeigt wird, muss dann bei der
Prüfung berücksichtigt werden.
Alle für die Ansicht anwendbaren Prüfschritte sind anzuwenden.

==== Hinweise

Das Autorenwerkzeug darf für die Erstellung von barrierefreien Dokumenten von
anderen Werkzeugen abhängen, um spezifische Kriterien zu erfüllen.
Das könnte z. B. ein zusätzliches Werkzeug für die Erstellung von Untertiteln
sein.

== Quellen

[.BLOCK_LANG_EN]
=== 11.8.2 Accessible content creation

[.BLOCK_LANG_EN]
--
Authoring tools shall enable and guide the production of content that conforms
to clauses 9 (Web content) or 10 (Non-Web content) as applicable.

NOTE:
Authoring tools may rely on additional tools where conformance with specific
requirements is not achievable by a single tool.
For example, a video editing tool may enable the creation of video files for
distribution via broadcast television and the web, but authoring of caption
files for multiple formats may be provided by a different tool.
--

(Aus EN 301 549 V3.1.1 Abschnitt 11.8.2 "Accessible content creation")
