= Prüfschritt 11.8.3 Erhaltung von Barrierefreiheitsinformationen bei Transformation
include::include/author.adoc[]
include::include/attributes.adoc[]

== Was wird geprüft?

Wenn die App ein Autorenwerkzeug ist und Umstrukturierungen oder Funktionen zur Umcodierung bietet, dann werden die Informationen zur Zugänglichkeit im umstrukturierten oder umcodierten Zielformat übernommen, soweit gleichwertige Mechanismen für Barrierefreiheits-Informationen bzw. semantische Auszeichnungen im Zielformat möglich sind.

== Warum wird das geprüft?

Menschen mit Behinderung benötigen semantische Auszeichnungen (zum Beispiel durch Überschriften oder richtig aufgebaute Datentabellen), um Inhalte effektiv zu nutzen. Werden diese Auszeichnungen bei Transformationen entfernt oder korrumpiert, leidet die Benutzbarkeit der Dokumente.

== Wie wird geprüft?

=== 1. Anwendbarkeit des Prüfschritts

Der Prüfschritt ist anwendbar, wenn die App ein Autorenwerkzeug ist und Umstrukturierungen oder Funktionen zur Umcodierung bietet.

==== 1.1 Restrukturierungen

Restrukturierungen sind Transformationen, bei denen die strukturellen Merkmale sich ändern (z.B. Linearisierung von Tabellen, Aufteilen eines Dokuments in Seiten oder wenn einzelne PDF-Dokumente in eine Datei zusammengeführt werden). Der Dokumententyp bzw. die Technologie bleibt gleich.

==== 1.2 Rekodierungstransformationen 

Umcodierungen sind Transformationen, bei denen die Technologie bzw. der Dokumententyp geändert wird. Dies kann z.B. die Umwandlung eines HTML-Dokuments in ein PDF sein.

=== 2. Prüfung

. Ansicht mit Information im Ausgangsformat öffnen. Wenn z. B. ein Autorenwerkzeug eine Umkodierungs-Transformation von HTML nach PDF bietet, wäre das etwa eine HTML-Datei in einem Webview.
. Ansicht in das Zielformat umgewandeln.
. Zielformat überprüfen. Je nach Dokumententyp erfordert dies Überprüfungen, die nicht im Rahmen des BITV-Tests selbst vorgenommen werden können. Ein Beispiel wäre die Transformation eines HTML-Dokuments in ein PDF-Dokument:

* Sind alle Überschriften aus der Quelle übernommen worden?
* Sind die Alternativtexte der Grafiken in der PDF-Datei enthalten?
* Wurde die Tabellenauszeichnung korrekt übersetzt?

== 3. Hinweise

Die Schritte müssen für jedes Ausgang- und Zielformat, das die App für die Transformation unterstützt, wiederholt werden.

Auch wenn die App lediglich die Struktur der Information im Ausgangsformat verändert, muss sichergestellt werden, dass das Zielformat noch alle für die Barrierefreiheit relevanten Informationen enthält.

Für Hinweise dazu können Sie auf GitHub https://github.com/BIK-BITV/BIK-App-Test/issues[ein Issue zu diesem Prüfschritt erstellen].

== Quellen

[.BLOCK_LANG_EN]
=== 11.8.3 Preservation of accessibility information in transformations

[.BLOCK_LANG_EN]
--
If the authoring tool provides restructuring transformations or re-coding
transformations, then accessibility information shall be preserved in the
output if equivalent mechanisms exist in the content technology of the output. 

NOTE 1:
Restructuring transformations are transformations in which the content
technology stays the same, but the structural features of the content are
changed (e.g. linearizing tables, splitting a document into pages). 

NOTE 2:
Re-coding transformations are transformations in which the technology used to
encode the content is changed.
--

(Aus EN 301 549 V3.1.1 Abschnitt 11.8.3 "Preservation of accessibility
information in transformations")
