= Prüfschritt 12.1.1 Barrierefreiheits- und Kompatibilitätsfunktionen
include::include/author.adoc[]
include::include/attributes.adoc[]

*Hinweis: Dies ist ein Entwurf. Inhalte können sich jederzeit ändern.*

== Was wird geprüft?

Wenn technische Dokumentation für die App bereitgestellt wird, 
soll diese vorhandene Funktionen für Barrierefreiheit und Kompabilität 
auflisten und deren Nutzung erklären.
Dies gilt generell für Dokumentation sowohl innerhalb als auch außerhalb der App.

Zur Dokumentation zählen auch Informationen zur Kompatibilität mit assistiven Technologien - 
etwa, wenn sich bestimmte Inhalte nur eingeschränkt 
oder gar nicht mit bestimmten assistiven Technologien nutzen lassen.

== Wie wird geprüft?

=== Anwendbarkeit des Prüfschritts

* Der Prüfschritt ist nur anwendbar, wenn technische Dokumentation (bzw. Produktdokumentation) für die App bereitgestellt wird. 
Strukturierte Informationen zu inhaltlichen Themen der App, 
wie sie z.B. in FAQs (Frequently Asked Questions) bereitgestellt werden, 
gelten nicht als technische Dokumentation. 

* Dieser Prüfschritt ist im App-Testverfahren nur für den Teil der Dokumentation prüfbar, 
der in die App integriert ist 
und sich auf die Dokumentation von Barrierefreiheit und Kompatibilität bezieht. 

* Dokumentation, die ausschließlich außerhalb der App bereitgestellt wird,
kann nicht im Rahmen dieses Prüfverfahrens mitgetestet werden.
Dokumentation außerhalb der App muss dann in einem separaten Auftrag geprüft werden.

=== Prüfung
Alle für die Barrierefreiheit relevanten Informationen zur App 
sowie bereitgestellte Funktionen für Barrierefreiheit
sollen in der Dokumentation aufgelistet und erklärt werden.
Die Dokumentation kann dabei mit der Software mitgeliefert werden oder separat
verfügbar sein.

Wenn vorhanden, kann die Dokumentation, die sich auf Barrierefreiheit bezieht, zum Beispiel Folgendes sein:

* Die Barrierefreiheitserklärung nach EU-Richtlinie 2016/2102
* Informationen zur Kompatibilität mit assistiven Technologien
* spezielle Tastenkombinationen für die Nutzung mit assistiven Technologien
* Einzelheiten zu bestimmten Funktionen für Barrierefreiheit, 
sofern sie in der App implementiert sind und nicht über die System-Umgebung (etwa iOS- oder Android-Bedienungshilfen) bereitgestellt werden, etwa:
** Vorlesefunktion
** Kontrastumschalter oder Schalter für Farbschemata
** Aktivierung von verbesserter Maus- oder Tastaturfokus-Hervorhebung
** Vergrößerungsfunktion 
** Anpassung von Textabständen
** Deaktivierung von Bewegungen oder automatischen Audios
** Besondere Bedienungsarten mit Tastatur oder Tastaturkürzeln

Die Software soll, wenn möglich, Metadaten für die unterstützten
Barrierefreiheitsfunktionen und Kompatibilität maschinenlesbar, 
in geeigneten Formaten, bereitstellen.

Für die Prüfpraxis sind weitere Hinweise notwendig, auf GitHub können Sie
https://github.com/BIK-BITV/BIK-App-Test/issues[dazu ein Issue eröffnen].

== Quellen
* Zurzeit keine Quellen.

== Einordnung des Prüfschritts

=== Einordnung des Prüfschritts nach EN 301 549 V.3.2.1

[.BLOCK_LANG_EN]
==== 12.1.1 Accessibility and compatibility features

[.BLOCK_LANG_EN]
--
Product documentation provided with the ICT whether provided separately or
integrated within the ICT shall list and explain how to use the accessibility
and compatibility features of the ICT. 

NOTE 1:
Accessibility and compatibility features include accessibility features that
are built-in and accessibility features that provide compatibility with
assistive technology. 

NOTE 2:
It is best practice to use WebSchemas/Accessibility 2.0 [i.38] to provide meta
data on the accessibility of the ICT.

NOTE 3:
The accessibility statement and help pages are both examples of the provision
of product information.
--
