= Prüfschritt 12.1.1 Dokumentation von Kompatibilität und Barrierefreiheit
include::include/author.adoc[]
include::include/attributes.adoc[]

== Was wird geprüft?

Die Dokumentation der App soll vorhandene zusätzliche Eigenschaften und Funktionen in Bezug auf Barrierefreiheit auflisten und deren Nutzung erklären, sofern diese als Teil der App selbst implementiert wurden. Auch Informationen zur (möglicherweise eingeschränkten) Kompatibilität mit assistiven Technologien zählen dazu.

== Warum wird das geprüft?

Wenn Angebote bestimmte Barrierefreiheitsfunktionen enthalten, sollten diese gut dokumentiert sein, denn viele Nutzende werden ohne ausdrückliche Hinweise diese Funktionen nicht erkennen oder nutzen können.

== Wie wird geprüft?

=== 1. Anwendbarkeit des Prüfschritts

Dieser Prüfschritt ist anwendbar, wenn eine Dokumentation vorhanden ist und wenn der Teil der Dokumentation, der sich mit Barrierefreiheit und Kompatibilität beschäftigt in die App integriert
ist.

Dokumentation, die ausschließlich außerhalb der App bereitgestellt wird, kann nicht im Rahmen dieses Prüfverfahrens mitgetestet werden. Die entsprechende Dokumentation muss dann in einem separaten Auftrag geprüft werden.

=== 2. Prüfung

Alle für die Barrierefreiheit relevanten Informationen zur App sollen in der Dokumentation aufgelistet und erklärt werden.
Die Dokumentation kann dabei in der App integriert sein oder separat verfügbar sein.

Die Dokumentation muss dabei z. B. folgende Informationen enthalten, sofern relevant:

* Barrierefreiheitserklärung nach EU-Richtlinie 2016/2102
* Einzelheiten zu Funktionen für die Barrierefreiheit
** Vorlesefunktion
** Kontrastumschalter, Schalter für Farbschemata, Aktivierung verbesserter
   Maus-/Tastaturfokus
** Vergrößerungsfunktion
** Anpassung von Textabständen
** Deaktivierung von Bewegungen oder automatischen Audios
** Besondere Bedienungsarten mit Tastatur / Tastenkombinationen
* Informationen zur Kompatibilität mit assistiven Technologien
* Spezielle Tastenkombinationen für die Nutzung mit assistiven Technologien
* Verzeichnisse für Abkürzungen

Es wird empfohlen, Metadaten für die unterstützten Barrierefreiheitsfunktionen und Kompatibilität maschienenlesbar, in geeigneten Formaten, bereitstellen.

== 3. Hinweise

* Das Fehlen von zusätzlichen Barrierefreiheits-Funktionen wird nicht negativ bewertet. Wenn sie eingesetzt werden, müssen sie aber dokumentiert sein.

* Es wird nur die Dokumentation von Barrierefreiheits-Funktionen verlangt, sofern diese als Teil der App implementiert werden. 

Für die Prüfpraxis sind weitere Hinweise notwendig, auf GitHub können Sie
https://github.com/BIK-BITV/BIK-App-Test/issues[dazu ein Issue eröffnen].

== Einordnung des Prüfschritts

=== Einordnung des Prüfschritts nach EN 301 549 V3.1.1

12.1.1 Accessibility and compatibility features

== Quellen

[.BLOCK_LANG_EN]
=== 12.1.1 Accessibility and compatibility features

[.BLOCK_LANG_EN]
--
Product documentation provided with the ICT whether provided separately or
integrated within the ICT shall list and explain how to use the accessibility
and compatibility features of the ICT. 

NOTE 1:
Accessibility and compatibility features include accessibility features that
are built-in and accessibility features that provide compatibility with
assistive technology. 

NOTE 2:
It is best practice to use WebSchemas/Accessibility 2.0 [i.38] to provide meta
data on the accessibility of the ICT.

NOTE 3:
The accessibility statement and help pages are both examples of the provision
of product information.
--

(Aus EN 301 549 V3.1.1 Abschnitt 12.1.1 "Accessibility and compatibility
features")
