= Prüfschritt 12.1.1 Dokumentation von Kompatibilität und Barrierefreiheit
include::include/author.adoc[]
include::include/attributes.adoc[]

== Grundlage des Prüfschritts

Grundlage des Prüfschritts ist die Tabelle A.2 im Annex A der EN 301 549
V3.1.1.
In dieser Tabelle wird auf Abschnitt
12.1.1 "Accessibility and compatibility features" verwiesen.

== Was wird geprüft?

Die Dokumentation der App soll, wenn vorhanden, besondere Eigenschaften und Funktionen in Bezug auf Barrierefreiheit auflisten und deren Nutzung erklären. Dazu zählen auch Informationen zur Kompatibilität mit assistiven Technologien.

== Warum wird das geprüft? 

== Wie wird geprüft?

=== 1. Anwendbarkeit des Prüfschritts

Dieser Prüfschritt ist anwendbar, wenn es Dokumentation zur Barrierefreiheit und Kompatibilität gibt, und diese Dokumentation in die App integriert ist. Dokumentation, die ausschließlich außerhalb der App bereitgestellt wird, kann nicht im Rahmen dieses Prüfverfahrens mitgetestet werden. Die entsprechende Dokumentation muss dann in einem separaten Auftrag geprüft werden.

=== 2. Prüfung

Wenn es für die Barrierefreiheit relevante Funktionen oder Einstellungsmöglichkeiten gibt, sollen diese in der Dokumentation aufgelistet und erklärt werden. Alle für die Barrierefreiheit relevanten Informationen zur App sollen in der Dokumentation aufgelistet und erklärt werden. Die Dokumentation kann dabei sowohl in die App integriert oder separat verfügbar sein. Zu finden ist solche Dokumentation in der Regel ubnter Einstellungen, auf Hilfeseiten bzw. in Support-Bereichen, Wikis oder in der Erklärung zur Barrierefreiheit. Dazu gehört etwa:

* Barrierefreiheitserklärung nach EU-Richtlinie 2016/2102
* Einzelheiten zu angebotenen Barrierefreiheits-Einstellungen, sofern diese in der App selbst integriert sind, zum Beispiel:
** Vorlesefunktion
** Einstellungsmögliochkeiten für individueller Farbschemata 
** Besondere Tastaturkürzel oder Gesten für die Nutzung mit assistiven Technologien
** Hinweise auf unterstützte Umgebungen, falls es Einschränkungen bei der Nutzbarkeit mit assistiven Technologien gibt
** Deaktivierung von Bewegungen oder automatischem Abspielen von Video- oder Audio-Inhalten



Für die Prüfpraxis sind weitere Hinweise notwendig, auf GitHub können Sie
https://github.com/BIK-BITV/BIK-App-Test/issues[dazu ein Issue eröffnen].




== Quellen

[.BLOCK_LANG_EN]
=== 12.1.1 Accessibility and compatibility features

[.BLOCK_LANG_EN]
--
Product documentation provided with the ICT whether provided separately or
integrated within the ICT shall list and explain how to use the accessibility
and compatibility features of the ICT. 

NOTE 1:
Accessibility and compatibility features include accessibility features that
are built-in and accessibility features that provide compatibility with
assistive technology. 

NOTE 2:
It is best practice to use WebSchemas/Accessibility 2.0 [i.38] to provide meta
data on the accessibility of the ICT.

NOTE 3:
The accessibility statement and help pages are both examples of the provision
of product information.
--

(Aus EN 301 549 V3.1.1 Abschnitt 12.1.1 "Accessibility and compatibility
features")
