= Prüfschritt 12.1.2 Barrierefreie Dokumentation
include::include/author.adoc[]
include::include/attributes.adoc[]

*Hinweis: Dies ist ein Entwurf. Inhalte können sich jederzeit ändern.*

== Was wird geprüft?

Wenn technische Dokumentation für die App bereitgestellt wird, 
soll sie in mindestens einem der folgenden Formate barrierefrei
zugänglich sein, sofern sie nicht in die App selbst integriert ist:

* Web-Dokument, erfüllt Kriterien der EN 301 549 Kapitel 9
* Nicht-Web-Dokument (u. a. PDF), erfüllt Kriterien der EN 301 549 Kapitel 10 

Weitere ggf. nicht barrierefreie Versionen der Dokumentation werden nicht
bewertet.

== Wie wird geprüft?

=== 1. Anwendbarkeit des Prüfschritts
* Der Prüfschritt ist nur anwendbar, wenn technische Dokumentation (bzw. Produktdokumentation) für die App bereitgestellt wird. 
Strukturierte Informationen zu inhaltlichen Themen der App, 
wie sie z.B. in FAQs (Frequently Asked Questions) bereitgestellt werden, 
gelten nicht als technische Dokumentation.
* Dokumentation, die ausschließlich außerhalb der App bereitgestellt wird, 
kann nicht im Rahmen dieses Prüfverfahrens geprüft werden. 
Dokumentation außerhalb der App muss dann in einem separaten Auftrag geprüft werden. 
Wenn es sich um technische Dokumentation auf HTML-Basis handelt, 
kann das das https://bitvtest.de/start.html[BIK-BITV-Test-Verfahren] genutzt werden.

=== 2. Prüfung
Die Prüfung von in die App integrierter technischer Dokumentation 
folgt den übrigen Prüfschritten des Verfahrens, 
genauso wie bei den anderen Ansichten der zu prüfenden Auswahl.

=== 3. Hinweise
* Der Prüfschritt schließt nicht die Möglichkeit aus, alternative Formate
anzubieten, die die Bedürfnisse einer bestimmten Nutzergruppe erfüllen (z.B.
Braille-Dokumente für blinde Menschen oder Informationen in leichter Sprache 
für Personen mit eingeschränkter Kognition, Sprache und Lernfähigkeit).
* Für Hinweise zu diesem Prüfschritt können Sie auf GitHub
https://github.com/BIK-BITV/BIK-App-Test/issues[ein Issue eröffnen].

=== 4. Bewertung
==== Nicht erfüllt:
* Ein oder mehrere der übrigen Prüfschritte des App-Tests sind für Seiten mit technischer Dokumentation nicht erfüllt. 
Dann ist auch dieser Prüfschritt nicht erfüllt.

== Quellen
* Zurzeit keine Quellen.

== Einordnung des Prüfschritts
=== Einordnung des Prüfschritts nach EN 301 549 V.3.2.1

[.BLOCK_LANG_EN]
==== 12.1.2 Accessible documentation
____
[.BLOCK_LANG_EN]
--
Product documentation provided with the ICT shall be made available in at
least one of the following electronic formats:

* a Web format that conforms to the requirements of clause 9; or 
* a non-web format that conforms to the requirements of clause 10. 

NOTE 1:
This does not preclude the possibility of also providing the product
documentation in other formats (electronic, printed or audio) that are not
accessible. 

NOTE 2:
It also does not preclude the possibility of providing alternate formats that
meet the needs of some specific type of users (e.g. Braille documents for
blind people or easy-to-read information for persons with limited cognitive,
language and learning abilities). 

NOTE 3:
Where documentation is incorporated into the ICT, the documentation falls
under the requirements for accessibility in the present document. 

NOTE 4:
A user agent that supports automatic media conversion would be beneficial to
enhancing accessibility.
--
____
