= Prüfschritt 12.1.1 Dokumentation von Kompatibilität und Barrierefreiheit
include::include/author.adoc[]
include::include/attributes.adoc[]

== Was wird geprüft?

Die Dokumentation der App soll, wenn vorhanden, besondere Eigenschaften und Funktionen in Bezug auf Barrierefreiheit auflisten und deren Nutzung erklären, sofern diese als Teil der App selbst implementiert wurden. Dazu gehören zum Beispiel Vorlesefunktionen, Funktionen zum Einstellen individueller Farbschemata oder verfügbare Tastaturkurzbefehle. Auch Informationen zur (möglicherweise eingeschränkten) Kompatibilität mit assistiven Technologien zählen dazu.

== Warum wird das geprüft? 

Wenn Apps bestimmte Barrierefreiheitsfunktionen enthalten, sollten diese gut dokumentiert sein, denn viele Nutzende werden ohne ausdrückliche Hinweise diese Funktionen nicht erkennen oder nutzen können.

== Wie wird geprüft?

=== 1. Anwendbarkeit des Prüfschritts

Dieser Prüfschritt ist anwendbar, wenn es Dokumentation zur Barrierefreiheit und Kompatibilität gibt, und diese Dokumentation in die App integriert ist. Dokumentation, die ausschließlich außerhalb der App bereitgestellt wird, kann nicht im Rahmen dieses Prüfverfahrens mitgetestet werden. Die entsprechende Dokumentation muss dann in einem separaten Auftrag geprüft werden.

=== 2. Prüfung

Wenn es für die Barrierefreiheit relevante Funktionen oder Einstellungsmöglichkeiten gibt, sollen diese in der Dokumentation aufgelistet und erklärt werden. Die Dokumentation kann dabei sowohl in die App integriert oder separat verfügbar sein. Zu finden ist eine solche Dokumentation in der Regel in den Einstellungen, auf Hilfeseiten bzw. in Support-Bereichen, in Wikis oder in der Erklärung zur Barrierefreiheit. Zu relevanten Funktionen und Einstellungsmöglichkeiten gehören etwa:

* Barrierefreiheitserklärung nach EU-Richtlinie 2016/2102
* Einzelheiten zu angebotenen Barrierefreiheits-Einstellungen, sofern diese in der App selbst integriert sind, zum Beispiel:
** Vorlesefunktion
** Einstellungsmögliochkeiten für individueller Farbschemata 
** Besondere Tastaturkürzel oder Gesten für die Nutzung mit assistiven Technologien
** Hinweise auf unterstützte Umgebungen, falls es Einschränkungen bei der Nutzbarkeit mit assistiven Technologien gibt
** Deaktivierung von Bewegungen oder automatischem Abspielen von Video- oder Audio-Inhalten

=== 3. Hinweise

3. Hinweise
. Das Fehlen von zusätzlichen Barrierefreiheits-Funktionen wird nicht negativ bewertet. Wenn sie eingesetzt werden, müssen sie aber dokumentiert sein.

. Es wird nur die Dokumentation von Barrierefreiheits-Funktionen verlangt, die von der App selbst implementiert werden. Dazu gehören auch Features wie Vorlesefunktionen, die von Drittanbietern definiert und im Angebot eingebunden werden. Barrierefreiheits-Funktionen des jeweiligen Betriebssystems müssen dagegen nicht dokumentiert werden.

Für die Prüfpraxis sind weitere Hinweise notwendig, auf GitHub können Sie
https://github.com/BIK-BITV/BIK-App-Test/issues[dazu ein Issue eröffnen].


== Quellen

[.BLOCK_LANG_EN]
=== 12.1.1 Accessibility and compatibility features

[.BLOCK_LANG_EN]
--
Product documentation provided with the ICT whether provided separately or
integrated within the ICT shall list and explain how to use the accessibility
and compatibility features of the ICT. 

NOTE 1:
Accessibility and compatibility features include accessibility features that
are built-in and accessibility features that provide compatibility with
assistive technology. 

NOTE 2:
It is best practice to use WebSchemas/Accessibility 2.0 [i.38] to provide meta
data on the accessibility of the ICT.

NOTE 3:
The accessibility statement and help pages are both examples of the provision
of product information.
--

(Aus EN 301 549 V3.1.1 Abschnitt 12.1.1 "Accessibility and compatibility
features")
