= Prüfschritt 12.2.4 Dokumentation verteilt durch Support
include::include/author.adoc[]
include::include/attributes.adoc[]

== Grundlage des Prüfschritts

Grundlage des Prüfschritts ist die Tabelle A.2 im Annex A der EN 301 549
V3.1.1.
In dieser Tabelle wird auf Abschnitt
12.2.4 "Accessible documentation" verwiesen.

== Was wird geprüft?

Die Dokumentation, die durch den (technischen) Support verteilt wird, soll
mindestens in eines der folgenden Formate barrierefrei zur Verfügung gestellt
werden:

* Web-Dokument, erfüllt Kriterien der EN 301 549 Kapitel 9
* Nicht-Web-Dokument (u. a. PDF), erfüllt Kriterien der EN 301 549 Kapitel 10 

Weitere, ggf. nicht barrierefreie Versionen der Dokumentation, werden nicht
bewertet.

== Wie wird geprüft?

=== Anwendbarkeit des Prüfschritts

Der Prüfschritt ist immer anwendbar.

Wenn dem Support der App lediglich die gleichen Dokumente wie dem Nutzer, für
dieVerteilung, zur Verfügung stehen, kann die Bewertung aus Prüfschritt
ifdef::env_embedded[x35 "Barrierefreie Dokumentation"]
ifndef::env_embedded[]
  <<x35 EN_12.1.2 Barrierefreie Dokumentation.adoc#,x35 Barrierefreie
  Dokumentation>>
endif::env_embedded[]
übernommen werden.

=== Prüfung

Wie dieser Prüfschritt in der Praxis berücksichtigt werdenkann, ist noch
nicht vollständig geklärt.
Für Hinweise zu diesem Prüfschritt können Sie auf GitHub
{app-issue-url}[ein Issue eröffnen].

. den Support der App kontaktieren
+
* Unterscheidet sich die Dokumentation von der herkömmlichen App-Dokumentation?
* Wenn ja, muss für die Prüfung die durch den Support verteilte
  Dokumentation angefordert werden.
  Dies umfasst alle Varianten der Dokumentation (HTML, PDF, ...).

. prüfen, in welchen Formaten die Dokumentation zur Verfügung gestellt wird
. falls mehrere Varianten zur Verfügung stehen, sollte Web-Dokumenten den
  Vorrang gegeben werden, da diese eher barrierearm sind und mit dem
  https://www.bitvtest.de[BITV-Test] getestet werden können
. prüfung der Dokumentation auf Barrierefreiheit
+
Kriterien sind dazu aus Kapitel 9 und 10 der EN 301 549 zu entnehmen.
Handelt es sich um Web-Dokumente, kann die Konformität mit dem
https://www.bitvtest.de[BITV-Test] überprüft werden.

==== Hinweise

Dokumentation bezieht sich in diesem Prüfschritt auf alle, *durch den Support*,
für den Nutzer zur Verfügung gestellten Dokumente.
Dies sind also Dokumente, die dem (technischen) Support vorliegen und auf
Anfrage bzw. zur Problemlösung, dem Nutzer bereitgestellt werden.

Der Prüfschritt schließt nicht die Möglichkeit aus, alternative Formate
anzubieten, die die Bedürfnisse einer bestimmten Nutzergruppe erfüllen (z. B.
Braille-Dokumente für blinde Menschen oder Informationen in leichter Sprache 
für Personen mit eingeschränkter Kognition, Sprache und Lernfähigkeit).

== Quellen

[.BLOCK_LANG_EN]
=== 12.2.4 Accessible documentation

[.BLOCK_LANG_EN]
--
Documentation provided by support services shall be made available in at least
one of the following electronic formats: 
* a Web format that conforms to clause 9; or
* a non-web format that conforms to clause 10.

NOTE 1:
This does not preclude the possibility of also providing the documentation in
other formats (electronic or printed) that are not accessible. 

NOTE 2:
It also does not preclude the possibility of providing alternate formats that
meet the needs of some specific type of users (e.g. Braille documents for
blind people or easy-to-read information for persons with limited cognitive,
language and learning abilities). 

NOTE 3:
Where the support documentation is incorporated into the ICT, the documentation
falls under the requirements for accessibility in the present document. 

NOTE 4:
A user agent that supports automatic media conversion would be beneficial to
enhancing accessibility.
--

(Aus EN 301 549 V3.1.1 Abschnitt 12.2.4 "Accessible documentation")
