= Prüfschritt 12.2.4 Barrierefreie Dokumentation (vom Support)
include::include/author.adoc[]
include::include/attributes.adoc[]

*Hinweis: Dies ist ein Entwurf. Inhalte können sich jederzeit ändern.*

== Was wird geprüft?

Wird durch den technischen Support eines Angebots eine Dokumentation bereitgestellt, 
wird diese zusätzlich in der App selbst 
oder in mindestens einem der folgenden Formate barrierefrei angeboten:

* Web-Dokument, erfüllt Kriterien der EN 301 549 Kapitel 9
* Nicht-Web-Dokument (u. a. PDF), erfüllt Kriterien der EN 301 549 Kapitel 10 

Weitere, ggf. nicht barrierefreie Versionen der Dokumentation, werden nicht
bewertet.

== Warum wird das geprüft?

Die technische Dokumentation ist ein wichtiger Bestandteil vieler Angebote, 
besonders bei komplexeren Apps. 
Damit auch Menschen mit Behinderungen sie gut nutzen können, 
sollte auf auf Anfrage bereitgestellte zusätzliche Dokumentation
alle Anforderungen der Barrierefreiheit erfüllen.

== Wie wird geprüft?

=== 1. Anwendbarkeit des Prüfschritts
* Der Prüfschritt ist anwendbar, wenn ein technischer Support
zusätzliche Dokumentation zur Nutzung des Angebots bereitstellt, 
etwa Hilfe-Systeme oder Anleitungen. 
* Im BIK App-Test kann lediglich Dokumentation geprüft wenn, 
die im Rahmen der App zusätzlich zur Verfügung gestellt wird (etwa in einem Webview).
* Dokumentation, die außerhalb der App bereitgestellt wird, 
kann nicht im Rahmen dieses Prüfverfahrens geprüft werden. 
Diese muss ggf. in einem separaten Auftrag geprüft werden. 
Wenn es sich um technische Dokumentation auf HTML-Basis handelt, 
kann das das Verfahren https://bitvtest.de/bitv_test/das_testverfahren_im_detail/bik_bitv_test_web.html[BIK-BITV-Test (Web)] genutzt werden.

=== 2. Prüfung
Wenn der technische Support zusätzliche Dokumentation zur Nutzung des Angebots bereitstellt, 
sind Ansichten mit dieser Dokumentation gemäß der übrigen Prüfschritte des App-Tests zu prüfen.
Die zusätzlich bereitgestellte Dokumentation
wird in einer erweiterten Auswahl von Ansichten berücksichtigt und mitgetestet.

=== 3. Hinweise
* Dokumentation bezieht sich in diesem Prüfschritt nur auf Informationen, die Nutzenden auf Anfrage durch den Support zusätzlich zur Verfügung gestellt werden.
* Die Einbindung oder Freischaltung zusätzlicher Dokumentation in die App nach Anfrage von Nutzenden ist keine gängige Praxis, aber nicht grundsätzlich ausgeschlossen. Nur Dokumentation innerhalb der App lässt sich mit dem App-Test Verfahren prüfen.
* Der Prüfschritt schließt nicht die Möglichkeit aus, alternative Formate anzubieten, die die Bedürfnisse einer bestimmten Nutzergruppe erfüllen (z.B. Braille-Dokumente für blinde Menschen oder Informationen in leichter Sprache für Personen mit eingeschränkter Kognition, Sprache und Lernfähigkeit).
* Wie dieser Prüfschritt in der Praxis berücksichtigt werden kann, ist noch nicht vollständig geklärt. 
Für Hinweise zu diesem Prüfschritt können Sie auf GitHub
https://github.com/BIK-BITV/BIK-App-Test/issues[ein Issue eröffnen].

=== 4. Bewertung
==== Erfüllt
* Die im Rahmen der App bereitgestellte zusätzliche Dokumentation erfüllt die Anforderungen aller anderen Prüfschritte des App-Tests.

==== Nicht erfüllt
* Die im Rahmen der App bereitgestellte zusätzliche Dokumentation erfüllt eine oder mehrere Prüfschritte des App-Tests nicht.

== Quellen
* Zurzeit keine Quellen.

== Einordnung des Prüfschritts
=== Einordnung des Prüfschritts nach EN 301 549 V3.1.1

[.BLOCK_LANG_EN]
==== 12.2.4 Accessible documentation
____
[.BLOCK_LANG_EN]
--
Documentation provided by support services shall be made available in at least
one of the following electronic formats: 
* a Web format that conforms to clause 9; or
* a non-web format that conforms to clause 10.

NOTE 1:
This does not preclude the possibility of also providing the documentation in
other formats (electronic or printed) that are not accessible. 

NOTE 2:
It also does not preclude the possibility of providing alternate formats that
meet the needs of some specific type of users (e.g. Braille documents for
blind people or easy-to-read information for persons with limited cognitive,
language and learning abilities). 

NOTE 3:
Where the support documentation is incorporated into the ICT, the documentation
falls under the requirements for accessibility in the present document. 

NOTE 4:
A user agent that supports automatic media conversion would be beneficial to
enhancing accessibility.
--
____
