= Prüfschritt 12.2.3 Effektive Kommunikation
include::include/author.adoc[]
include::include/attributes.adoc[]

== Was wird geprüft?
Werden für die App unterstützende Dienste angeboten (etwa über Telefon, Mail oder Chat), 
sollen diese die verschiedenen Kommunikationsformen von Menschen mit Behinderungen berücksichtigen.
Es sollen mindestens zwei effektive Kommunikationskanäle zur Verfügung stehen, z.B. E-Mail und Telefon, oder Chat und Telefon.
Dies kann auch durch die Vermittlung an Dritte geschehen.

== Warum wird das geprüft?
Menschen mit verschiedenen Behinderungen bevorzugen verschiedene Kommunikationskanäle. 
So haben zum Beispiel schwerhörige Menschen Schwierigkeiten beim Telefonieren und bevorzugen E-Mail oder Chat. 
Für Menschen, denen Schreiben aus welchen Gründen auch immer schwer fällt, ist ein Telefonat einfacher.

== Wie wird geprüft?
=== 1. Anwendbarkeit des Prüfschritts
Der Prüfschritt ist anwendbar, wenn die App unterstützende Dienste anbietet 
(etwa eine Hotline oder eine Chatfunktion für technischen Support).

=== 2. Prüfung
. Werden mehrere Kommunikationsmöglichkeiten für die Nutzenden angeboten (mindestens zwei)? 
Also etwa Kommunikation über

* E-Mail
* Chat
* Telefon
* Videotelefonie

=== 3. Hinweise
* Wie dieser Prüfschritt in der Praxis berücksichtigt werden kann, 
ist noch nicht vollständig geklärt. 
* Auf GitHub können Sie https://github.com/BIK-BITV/BIK-App-Test/issues[Hinweise zu diesem Prüfschritt
hinterlassen].

== Einordnung des Prüfschritts
=== Einordnung des Prüfschritts nach EN 301 549 V3.2.1

[.BLOCK_LANG_EN]
==== 12.2.3 Effective communication
____
[.BLOCK_LANG_EN]
ICT support services shall accommodate the communication needs of individuals
with disabilities either directly or through a referral point. 
____

