= Prüfschritt 2.4.7a Aktuelle Position des Fokus deutlich
include::include/author.adoc[]
include::include/attributes.adoc[]

== Was wird geprüft?

Bei fokussierten Bedienelementen soll der Tastaturfokus sich deutlich von der ausgewählten Hintergrundfarbe abheben.

Versteckte Sprunglinks sollen bei Fokuserhalt eingeblendet werden.

== Warum wird das geprüft?

Für den Tastaturbenutzer ist es wichtig, zu sehen, wo sich der Tastaturfokus gerade befindet, welches Bedienelement also ausgelöst wird, wenn er die Enter-Taste drückt.

Wenn Apps allein durch die Tastatur bedient werden, muss das fokussierte Bedienelement für den Nutzer deutlich hervorgehoben sein, da eine sichere Bedienung der Anwendung andernfalls für visuelle Nutzer kaum möglich ist.

Die vom Betriebssystem vorgesehene Kennzeichnung des Tastaturfokus hebt sich von dunklen Seitenhintergründen meist nicht so gut ab, wie in der "normalen" Ansicht des Betriebssystems oder des Benutzers. Das muss dann ausgeglichen werden, zum Beispiel durch farbige Hinterlegung des angesteuerten Bedienelements. ???

== Wie wird geprüft?

=== Anwendbarkeit des Prüfschritts

Der Prüfschritt ist anwendbar, wenn die App-Ansicht interaktive Elemente enthält.

=== Prüfung

[arabic]
. Zu prüfende Ansicht in der Software öffnen.
. Alle Bedienelemente mit Tabulator durchlaufen und prüfen, ob sie mit grafischen Veränderungen auf den Fokus reagieren (zum Beispiel mit Farbwechseln, Unterstreichungen oder eingeblendeten Symbolen). Versteckte Sprunglinks sollen bei Fokuserhalt eingeblendet werden.
. Wenn die Fokushervorhebung ausschließlich über einen Farbwechsel geschieht, prüfen, ob der Kontrastabstand zwischen fokussiertem und unfokussiertem Zustand mindestens 3:1 beträgt.
. Bei Bedienelementen, die sich im Fokus nicht verändern, prüfen, ob der Tastaturfokus (Systemkranz) an dieser Stelle vor hellem Hintergrund dargestellt ist, also gut zu erkennen ist. In Zweifelsfällen gemäß Prüfschritt 1.4.3a "Kontraste von Texten ausreichend" ermitteln, ob die Farbe Schwarz vor dem gewählten Hintergrund ausreichend kontrastiert.

*[.underline]#Hinweise#*

* Der Prüfschritt ist nicht erfüllt, wenn überhaupt kein Tastaturcursor sichtbar ist. Dann ist eventuell auch Prüfschritt 2.1.1a "Ohne Maus nutzbar" nicht erfüllt! (Ohne Touch-Gesten bedienbar?)
* Bei mobilen Systemen muss ggf. eine Bluetooth-Tastatur zum Einsatz kommen.

=== Bewertung

Erfüllt:

Die Hervorhebung des Fokusses ist nicht schlechter als ein ausreichend kontrastierender Systemkranz.

Bei Bedienelementen, die sich bei Fokuserhalt nicht verändern, jedoch einen Systemkranz zur Hervorhebung erhalten, erfüllt der Helligkeitskontrast der Farbe Schwarz vor dem gewählten Hintergrund die Anforderungen von Prüfschritt 1.4.3a "Kontraste von Texten ausreichend".

Nicht voll erfüllt:

Sprunglinks bleiben bei Fokuserhalt versteckt.

Nicht erfüllt:

Der System-Fokus wird unterdrückt, bei Tastaturnutzung wird kein Fokus angezeigt. Hier muss eine Abwertung auf "schlecht zugänglich" erwogen werden.

== Einordnung des Prüfschritts

=== Formulierung BITV 2.0

2.4.7 Sichtbarer Fokus

Bei Tastaturbedienung ist immer ein Tastaturfokus sichtbar.

=== Einordnung des Prüfschritts nach WCAG 2.1

Guideline

Guideline 2.4 Navigable: Provide ways to help users navigate, find content, and determine where they are

Success criterion

2.4.7 Focus Visible (Level AA)

1.4.11 Non-Text Contrast (Level AA)

Techniques

General Techniques

G149: Using user interface components that are highlighted by the user agent when they receive focus

G165: Using the default focus indicator for the platform so that high visibility default focus indicators will carry over

G195: Using an author-supplied, highly visible focus indicator

CSS Techniques

C15: Using CSS to change the presentation of a user interface component when it receives focus

Client-side Scripting Techniques

SCR31: Using script to change the background color or border of the element with focus

Failures

F55: Failure of Success Criteria 2.1.1, 2.4.7, and 3.2.1 due to using script to remove focus when focus is received

F78: Failure of Success Criterion 2.4.7 due to styling element outlines and borders in a way that removes or renders non-visible the visual focus indicator

== Fragen zu diesem Prüfschritt

Ist die Anzeige des Fokus nicht Sache des Betriebssystems?

Alle Betriebssysteme zeigen dem Tastaturnutzer in irgendeiner Weise, wo der Fokus ist, wenn diese Anzeige nicht aktiv unterdrückt wird. ???

Dennoch ist die Anzeige des Fokus nicht allein Sache des Betriebssystems. Die App legt fest, wie sie aussehen soll. Sie ändert etwa die Farben fokussierter Bedienelemente und Hintergründe von Bedienelementen oder setzt andere Gestaltungselemente ein. In dieser von der App festgelegten Umgebung muss der Fokus für Tastaturnutzer gut sichtbar sein.
