= Prüfschritt 2.4.1a Bereiche überspringbar
include::include/author.adoc[]
include::include/attributes.adoc[]

== Was wird geprüft?

In Apps kann der Nutzer die verschiedenen Bereiche in der Ansicht
anspringen bzw. überspringen.
Dies gilt z. B. für Menüleisten, Werkzeugleisten, Navigationsleisten,
Dokumentenbereiche usw.
Unter iOS kann zwischen s. g. Containern hin und her gesprungen werden.
In einem Container kann bspw. Der Navigationsbereich enthalten sein und in
einem weiteren Container könnte eine Dokumentenansicht beinhaltet sein.

== Warum wird das geprüft?

Software wird oftmals visuell in verschiedene Bereiche aufgeteilt.
Hier könnten z. B. Werkzeuge nach ihrer Verwendung in verschiedene Leisten
gruppiert sein.
Diese Bereiche müssen dann z. B. mittels Tastatur oder Touch-Gesten (ggf.
mittels Screenreader) anspringbar sein, um eine effiziente und barrierearme
Nutzung zu ermöglichen.
Dies gilt insbesondere für komplexere Anwendungen.

== Wie wird geprüft?

=== Anwendbarkeit des Prüfschritts

Der Prüfschritt ist anwendbar, wenn es in der App-Ansicht deutlich
voneinander abgegrenzte Bereiche gibt, etwa Navigation und Inhalt.
Das ist bei informationsorientierten Seiten und der Mehrzahl an Apps meist der
Fall.

=== Prüfung

Die verschiedenen Bereiche der Software-Ansicht (Menü- und Werkzeugleisten,
Seitenleisten, Dokumentenbereiche, …) sind mittels Tastatur oder Touchgesten
anspringbar.
Unter mobilen Systemen ist es möglich, Bereiche als solche programmatisch
auszuzeichnen.
Unter iOS/iPadOS kann z. B. mit dem Screenreader VoiceOver zwischen
„Containern“ mittels VO-Rotor navigiert werden.
Ggf. muss der Punkt „Container“ noch dem VoiceOver-Rotor hinzugefügt
werden, dies geschieht in den iOS / iPadOS Einstellungen unter Allgemein
-> Bedienungshilfen -> VoiceOver -> Rotor.

Mit aktiviertem Screenreader muss dann getestet werden, ob sich die
verschiedenen Bereiche der Software anspringen lassen.
ggf. sollte im Handbuch der Software nachgesehen werden, ob für diese Aufgabe
eine andere Taste bzw. Tastenkombination vorgesehen wird.

Auf den Apple-Systemen inkl. MacOS kann mittels VO-Rotor zwischen
den Containern gewechselt werden.
Ist die VO-Schnellnavigation unter MacOS aktiv, kann auch mittels der
Kombination Strg + Pfeil links bzw. Strg + Pfeil rechts zwischen den
Containern gewechselt werden.
Die Schnellnavigation lässt sich mit dem gleichzeitigen Betätigen der linken
und rechten Pfeiltaste aktivieren und wieder deaktivieren.

=== Hinweise

==== Eigenständige Bereiche

Eigenständige Bereiche sind zum Beispiel:

* Navigation und Inhalt
* Spalten mit unterschiedlichen Inhalten
* Bereiche, die durch Umrahmung als zusammengehörig gekennzeichnet sind

=== Bewertung

*Erfüllt:*

* Bei Anwendungen sind alle Bereiche wie Navigation, Werkzeugleiste,
  Dokumentenbereich usw. mittels Tastenkombination oder Touch-Gesten anspringbar.

*Nicht erfüllt:*

* In der Software existieren klar abgegrenzte Bereiche wie z. B. Navigation
  und Dokumentenbereich, diese Lassen sich jedoch nicht einzeln anspringen.

== Einordnung des Prüfschritts

=== Einordnung des Prüfschritts nach WCAG 2.1

==== Guidelines

* https://www.w3.org/WAI/WCAG21/quickref/#navigable[Guideline 2.4 Navigable:
  Provide ways to help users navigate, find content, and determine where they are]

==== Success criteria

* https://www.w3.org/WAI/WCAG21/quickref/#bypass-blocks[2.4.1 Bypass Blocks
  (Level A)]

==== Techniques

.General Techniques
* https://www.w3.org/WAI/WCAG21/Techniques/general/G115.html[G115: Using
  semantic elements to mark up structure]
* https://www.w3.org/WAI/WCAG21/Techniques/general/G130.html[G130: Providing
  descriptive headings]
* https://www.w3.org/WAI/WCAG21/Techniques/general/G140.html[G140: Separating information and structure from presentation to enable different presentations]

// == Quellen
