= Prüfschritt 2.4.6a Aussagekräftige Überschriften und Beschriftungen
include::include/author.adoc[]
include::include/attributes.adoc[]

== Was wird geprüft?

Überschriften beschreiben den folgenden Inhaltsteil, Beschriftungen sind
sinngebend.

== Warum wird das geprüft?

Visuell werden Webseiten-und Software-Inhalte durch Überschriften strukturiert.
Dank dieser Strukturierung weiß der Benutzer, was zusammengehört, kann die
Inhalte leicht überblicken und gezielt auf Inhalte zugreifen, die ihn
interessieren.

Wenn Formularfelder sinngebend beschriftet sind, können Sie von Nutzer als
solche erkannt und bedient werden.

== Wie wird geprüft?

=== Anwendbarkeit des Prüfschritts

Der Prüfschritt ist anwendbar, wenn es in der App-Ansicht Inhalte gibt, die
durch Überschriften strukturiert werden können und wenn die Ansicht
Formularelemente enthält.

=== Prüfung

. App mit zu prüfender Ansicht öffnen
. Prüfen, ob die Überschriften im Zusammenhang mit den durch sie
  strukturierten Inhalten aussagekräftig sind
. Prüfen, ob Beschriftungen von Formularelementen aussagekräftig sind
. Wenn Gruppen von Bedienelementen durch Legenden beschriftet werden:
  Sind Legende und Label bzw. Beschriftung des Bedienelements, zusammen
  vorgelesen, bei allen Formularelementen in der Gruppierung sinnvoll?

=== Hinweise

Besonders in Fachanwendungen gibt es Labels und Überschriften, die in dem
betreffenden Nutzerkreis bestimmten, etablierten Vokabularen entsprechen 
einschließlich viel genutzter Abkürzungen).
Die Verwendung in Interfaces bringt Vorteile mit (Wiedererkennbarkeit,
Präzision, Kürze), kann aber auch dazu führen, dass sie nicht unbedingt
für jeden aussagekräftig oder anschaulich sind, was aber nicht zu einer
negativen Bewertung führen soll.

== Einordnung des Prüfschritts

=== Abgrenzung von anderen Prüfkriterien

* In diesem Prüfschritt geht es um die Aussagekraft von Überschriften und
  Beschriftungen.
  Die programmatische Ermittelbarkeit durch Assistive Technologien ist den Prüfkriterien
ifdef::env_embedded[1.3.1a "Strukturelemente für Überschriften"]
ifndef::env_embedded[]
  <<1.3.1a Strukturelemente für Überschriften.adoc#,1.3.1a Strukturelemente
  für Überschriften>>
endif::env_embedded[]
  und
ifdef::env_embedded[1.3.1h "Beschriftung programmatisch ermittelbar"]
ifndef::env_embedded[]
  <<1.3.1h Beschriftung von Formularelementen programmatisch ermittelbar.adoc#,
  1.3.1h Beschriftung von Formularelementen programmatisch ermittelbar>>
endif::env_embedded[]
  zugeordnet.

=== Einordnung des Prüfschritts nach WCAG 2.1

==== Guideline

* https://www.w3.org/TR/WCAG21/#navigable[Guideline 2.4 Navigable: Provide
  ways to help users navigate, find content, and determine where they are]

==== Success criterion

* https://www.w3.org/TR/WCAG21/#headings-and-labels[2.4.6 Headings and Labels
  (Level A)]

==== Techniques

.General Techniques
* https://www.w3.org/WAI/WCAG21/Techniques/general/G130.html[G130: Providing
  descriptive headings]
* https://www.w3.org/WAI/WCAG21/Techniques/general/G131.html[G131: Providing
  descriptive labels]
