= Prüfschritt 3.1.1a Hauptsprache angegeben
include::include/author.adoc[]
include::include/attributes.adoc[]

== Was wird geprüft?

Die Hauptsprache der App soll angegeben werden.

==  Warum wird das geprüft?

Screenreader verwenden Wortlisten, in denen die Aussprache der Wörter
festgelegt ist.
Sie müssen wissen, in welcher Sprache ein Text verfasst ist, damit sie die
richtige Wortliste für die Aussprache verwenden und den Text korrekt
aussprechen können.

== Wie wird geprüft?

=== Anwendbarkeit des Prüfschritts

Der Prüfschritt ist immer anwendbar.

=== Prüfung

Prüfen ob sich die Anwendung an die Systemsprache hält.
Falls dies nicht der Fall ist, soll die Software ihre verwendete Sprache an
das System melden.
Gegebenenfalls ist dies mit einem Screenreader prüfbar, indem man prüft, ob
der Screenreader eine zur Sprache der Anwendung passende Stimme beim Vorlesen
der Bedienelemente wählt.

Ggf. müssen hier noch bessere Prüfmethoden gefunden werden.
Die meiste Software richtet sich jedoch nach der Systemsprache und ist somit
konform.

Für Hinweise zur Prüfpraxis erstellen Sie gerne ein {app-issue-url}[Issue
auf GitHub].

=== Bewertung

*Erfüllt:*

* Die Anwendung hält sich an die Systemsprache oder meldet ihre verwendete
  Sprache an das System.

*Nicht erfüllt:*

* Die Anwendungssoftware hält sich nicht an die Systemsprache und meldet
  dabei ihre verwendete Hauptsprache nicht an das System, sodass z. B. ein
  Screenreader eine falsche Sprachausgabe-Engine einsetzt und damit
  beispielsweise englischer Text mit einer deutschen Stimme vorgelesen wird.

==  Einordnung des Prüfschritts

=== Einordnung des Prüfschritts nach WCAG 2.1

==== Guideline

* https://www.w3.org/TR/WCAG21/#readable[Guideline 3.1 Readable: Make text
  content readable and understandable]

==== Success criterion

* https://www.w3.org/TR/WCAG21/#language-of-page[3.1.1 Language of Page
  (Level A)]
