= Prüfschritt 3.3.2a Beschriftungen von Formularelementen vorhanden
include::include/author.adoc[]
include::include/config.adoc[]

== Was wird geprüft?

Beschriftungen von Formularelementen sind vorhanden.

Die Beschriftung von Formularelementen soll vor (das heißt links neben oder über) dem zugehörigen Eingabefeld angeordnet werden. Nur die Beschriftung von Checkboxes und Radiobuttons kann (und sollte normalerweise) rechts neben dem zugehörigen Eingabefeld angeordnet werden.

Wenn für die Eingabe ein bestimmtes Format verlangt wird, so sind die Anweisungen für alle Benutzer lesbar.

== Warum wird das geprüft?

Wenn Beschriftungen zur Verfügung gestellt werden, wissen Nutzer, welche Eingaben erwartet werden und Fehler können vermieden werden.

Die Anordnung von Beschriftungen direkt vor oder über dem Eingabefeld entspricht den üblichen Gestaltungskonventionen. Auch in ausschnitthaften Ansichten (etwa in Vergrößerungssoftware) wird schnell klar, welche Beschriftung zu welchem Feld gehört.

== Wie wird geprüft?

=== Anwendbarkeit des Prüfschritts

Der Prüfschritt ist anwendbar, wenn die App-Ansicht Formularelemente enthält.

=== Prüfung

[arabic]
. App mit zu prüfender Ansicht öffnen.
. Sind Beschriftungen vorhanden ?
. Sind alle Formularelemente beschriftet?
. Sind Pflichtfelder in label- oder legend-Elementen klar angezeigt? Wenn zur Anzeige Symbole wie etwa ein Sternchen (*) genutzt werden, muss deren Bedeutung am Beginn des Formulars erklärt sein.
. Wenn Eingabefelder ein bestimmtes Eingabeformat vorgeben, wird dieses vor dem Eingabefeld klar beschrieben? (Beispiele wären "Format der Datumseingabe: TT.MM.JJJJ" oder "Telefonnummer: Nur Zahlen ohne Leerstellen oder Bindestriche eingeben".)
. Sind Beschriftungen richtig positioniert?

=== Hinweise

Bei kombinierten Eingabeelementen hat nicht immer jedes Element eine zugeordnete Beschriftung. In diesem Fall sollen Elemente mit einem unsichtbaren erklärenden Label versehen werden, welches dann von einem Screenreader ausgegeben werden kann. Beispiel: In einem Formular werden für die Eingabe eines Datums drei Auswahllisten angeboten (Tag, Monat und Jahr). Die drei Auswahllisten haben eine gemeinsame Beschriftung: Datum. Die Auswahllisten für Tag, Monat und Jahr sind jeweils mit einem unsichtbaren erklärenden Label für Hilfstechnologien versehen.

Wenn ein einfaches Suchformular nur aus einem Eingabefeld und einem Button besteht, ist oftmals keine sichtbare Beschriftung notwendig. Hier ist es ausreichend, wenn Eingabefeld und Button direkt nebeneinander positioniert sind, das Eingabefeld eine sinnvolle Textvorbelegung hat oder die Beschriftung des Buttons die Funktion eindeutig kennzeichnet (etwa "Suchen"). Das unbeschriftete Eingabefeld mit Textvorbelegung muss in solchen Fällen ein aussagekräftiges verstecktes Label haben, da für Screenreader-Nutzer der nachfolgende Button nicht gleichermaßen als Beschriftung taugt.

Es kann sinnvoll sein, dass bei Formularen Hinweise zum Eingabeformat oder zu ausgelösten Aktionen einmal am Beginn des Formulars stehen statt vor jedem einzelnen Eingabefeld.

=== Bewertung

Nicht erfüllt:

Wichtige Formularelemente (z.B. die Sucheingabe) sind ohne Beschriftung, auch angrenzende Elemente erklären nicht die Funktion.

Nicht voll erfüllt:

Beschriftungen werden nur als Formularfeld-Vorbelegung bereitgestellt.

== Einordnung des Prüfschritts

=== Formulierung BITV 2.0

3.3.2 Beschriftungen

Für notwendige Eingaben der Nutzerinnen und Nutzer sind Hinweise oder Label (Beschriftungen) zur Verfügung zu stellen.

=== Einordnung des Prüfschritts nach WCAG 2.1

Guidelines

Guideline 3.3 Input Assistance: Help users avoid and correct mistakes.

Success criteria

3.3.2 Labels or Instructions (Level A)

Techniques

General Techniques

G13: Describing what will happen before a change to a form control that causes a change of context to occur is made

G89: Providing expected data format and example

G131: Providing descriptive labels

G162: Positioning labels to maximize predictability of relationships

G184: Providing text instructions at the beginning of a form or set of fields that describes the necessary input

HTML Techniques

H44: Using label elements to associate text labels with form controls

H65: Using the title attribute to identify form controls when the label element cannot be used

H71: Providing a description for groups of form controls using fieldset and legend elements

H90: Indicating required form controls using label or legend

ARIA Techniques

ARIA1: Using the aria-describedby property to provide a descriptive label for user interface controls

ARIA9: Using aria-labelledby to concatenate a label from several text nodes

ARIA17: Using grouping roles to identify related form controls

Failures

F82: Failure of Success Criterion 3.3.2 by visually formatting a set of phone number fields but not including a text label
