= Prüfschritt 4.1.1a Korrekte Syntax
include::include/author.adoc[]
include::include/config.adoc[]

== Was wird geprüft?

Die verwendete Markup-Sprache, auf Webseiten bspw. HTML, muss korrekt eingesetzt werden. Dabei muss für jedes Element folgendes gewährleistet sein:

Sie besitzen vollständige Start- und Endtags,

sie sind gemäß Spezifikation korrekt verschachtelt

sie enthalten keine doppelten Attribute

alle ihre IDs sind eindeutig, außer dort wo die Spezifikationen etwas anderes erlauben

== Warum wird das geprüft?

Eine saubere Markup-Syntax hilft in Einzelfällen der Hilfstechnologie im Umgang mit der App.

== Wie wird geprüft?

=== Anwendbarkeit des Prüfschritts:

Bei Anwendungssoftware muss die Software Markup-Sprachen so einsetzen, dass das Markup separat exponiert und für Hilfstechnologien und Zugänglichkeitsmerkmale der Software oder für einen vom Nutzer definierbaren User-Agent verfügbar ist. Andernfalls ist der Prüfschritt nicht anwendbar.

=== Prüfung

Ein genaues Prüfverfahren steht für diesen Prüfschritt noch nicht zur Verfügung. Je nach Markup-Sprache kann ggf. analog zur HTML-Prüfung ein Online-Validator für das entsprechende Format genutzt werden.

=== Hinweise

* Wenn die Prüfung aufgrund einer fehlenden doctype-Definition nicht ausgeführt werden kann, dann validiert die App nicht, der Prüfschritt ist dann nicht bestanden. Der doctype soll nicht manuell eingetragen werden!

=== Bewertung

*???*

== Einordnung des Prüfschritts

=== Formulierung BITV 2.0

4.1.1 Syntaxanalyse

Inhalte, die mit Markup-Sprachen erstellt werden, bestehen aus Elementen, für die folgende Eigenschaften gelten:

Sie verfügen über vollständige Start- und End-Tags,

sie werden entsprechend ihren Spezifikationen verschachtelt,

sie enthalten keine doppelten Attribute und

alle ihre IDs sind eindeutig,

es sei denn, ihre Spezifikationen erlauben diese Besonderheit.

=== Einordnung des Prüfschritts nach WCAG 2.1

==== Guideline

* https://www.w3.org/TR/WCAG21/#compatible[Guideline 4.1 Compatible: Maximize compatibility with current and future user agents, including assistive technologies]

==== Success criterion

* https://www.w3.org/TR/WCAG21/#parsing[4.1.1 Parsing (Level A)]

==== Techniques

.General Techniques
* https://www.w3.org/WAI/WCAG21/Techniques/general/G134.html[G134: Validating Web pages]
* https://www.w3.org/WAI/WCAG21/Techniques/general/G192.html[G192: Fully conforming to specifications]

==== Failures

* https://www.w3.org/WAI/WCAG21/Techniques/failures/F70.html[F70: Failure of Success Criterion 4.1.1 due to incorrect use of start and end tags or attribute markup]
* https://www.w3.org/WAI/WCAG21/Techniques/failures/F77.html[F77: Failure of Success Criterion 4.1.1 due to duplicate values of type ID]

== Quellen

Validation will usually eliminate ambiguities (and more) because an essential step in validation is to check for proper use of that technology's markup (in a markup language) or code (in other technologies). Validation does not necessarily check for full conformance with a specification but it is the best means for automatically checking content against its specification.

Quelle: * https://www.w3.org/WAI/WCAG21/Techniques/general/G134[WCAG 2.1 Technik G134: Validating web pages]

=== Prüfung von generiertem Quelltext

Auf Stackoverflow.com gibt es eine ausführliche Diskussion der Schwierigkeiten, den generierten Quelltext auf verschiedenen Wegen zu extrahieren und zu validieren (auf Englisch)

Quelle: * https://stackoverflow.com/questions/1750865/best-way-to-view-generated-source-of-webpage[Best way to view generated source of web page (stackoverflow.com)]

== Fragen zu diesem Prüfschritt

Scripts, die beim Laden der Seite ausgeführt werden, verändern den ursprünglichen Quelltext. Auch AJAX-Anfragen können den Quelltext noch nach dem Laden der Seite erweitern und ändern. Warum wird nicht der geparste (also veränderte) HTML-Code validiert?

Tatsächlich wäre es wünschenswert, die Validität des geparsten Quelltextes zu prüfen, einschließlich späterer Modifikationen des DOM durch AJAX-Anfragen. Es gibt zur Zeit aber keine handhabbare Möglichkeit, das zu tun: Browser verändern und reparieren den ursprünglichen Quelltext, und Werkzeuge, die den generierten Quelltext anzeigen, enthalten nicht die doctype-Deklaration des Quelltexts. Deshalb wird lediglich der ungeparste Quelltext validiert.

Was ist, wenn die Seite aufgrund von Fremdinhalten, zum Beispiel wegen von einem fremden Server gelieferter Werbung nicht validiert?

Die Zugänglichkeit von deutlich abgegrenzter Werbung wird im BITV-Test nicht geprüft. Geprüft wird aber, ob die Werbung die Nutzung der anderen Seiteninhalte einschränkt. Das ist der Fall, wenn sie blinkt oder sich bewegt (Prüfschritt 2.2.2a "Bewegte Inhalte anhaltbar") oder nicht valide ist.

Was ist, wenn der HTML-Validator fehlerhaft arbeitet?

"Anerkannte" Fehler bestehen nicht dauerhaft, sie werden vom W3C bearbeitet und behoben. Gegebenenfalls ist die Prüfung zu wiederholen, nachdem der Fehler gemeldet und behoben worden ist. Für die Bewertung des Prüfschritts ist allein das Ergebnis relevant. Auf welcher Basis es zustande kommt, spielt keine Rolle!

Sollte der Prüfschritt nicht als teilweise erfüllt bewertet werden, wenn der W3C-Validator nur wenige Fehler anzeigt?

Die Anzahl der vom W3C-Validator angezeigten Fehler ist nicht aussagekräftig. Denn im Unterschied zu gängigen Browsern versucht der W3C-Validator nicht, aus fehlerhaften Seiten irgendwie etwas Brauchbares heraus zu holen. Ein einzelner Fehler kann dazu führen, dass der Validator den Rest der Seite nicht mehr richtig liest und endlose Listen von vermeintlichen weiteren Fehlern erzeugt.
