= Prüfschritt 4.1.1a Korrekte Syntax
include::include/author.adoc[]
include::include/attributes.adoc[]

== Was wird geprüft?

Die verwendete Markup-Sprache, auf Webseiten bspw. HTML, muss korrekt
eingesetzt werden.
Dabei muss für jedes Element folgendes gewährleistet sein:

* sie besitzen vollständige Start- und Endtags
* sie sind gemäß Spezifikation korrekt verschachtelt
* sie enthalten keine doppelten Attribute
* alle ihre IDs sind eindeutig, außer dort wo die Spezifikationen etwas
  anderes erlauben

== Warum wird das geprüft?

Eine saubere Markup-Syntax hilft in Einzelfällen der Hilfstechnologie im
Umgang mit der App.

== Wie wird geprüft?

=== Anwendbarkeit des Prüfschritts:

Bei Anwendungssoftware muss die Software Markup-Sprachen so einsetzen, dass
das Markup separat exponiert und für Hilfstechnologien und
Zugänglichkeitsmerkmale der Software oder für einen vom Nutzer definierbaren
User-Agent verfügbar ist.
Andernfalls ist der Prüfschritt nicht anwendbar.

=== Prüfung

Ein genaues Prüfverfahren steht für diesen Prüfschritt noch nicht zur
Verfügung.
Je nach Markup-Sprache kann ggf. analog zur HTML-Prüfung ein Online-Validator
für das entsprechende Format genutzt werden.

Für Hinweise zur Prüfpraxis, können Sie auf GitHub {app-issue-url}[ein
Issue anlegen].

=== Hinweise

* Wenn die Prüfung aufgrund einer fehlenden doctype-Definition nicht
  ausgeführt werden kann, dann validiert die App nicht, der Prüfschritt ist
  dann nicht bestanden. Der doctype soll nicht manuell eingetragen werden!

=== Bewertung

Noch nicht festgelegt.
Mehrheitlich für Apps wahrscheinlich nicht anwendbar.

== Einordnung des Prüfschritts

=== Einordnung des Prüfschritts nach WCAG 2.1

==== Guideline

* https://www.w3.org/TR/WCAG21/#compatible[Guideline 4.1 Compatible: Maximize
  compatibility with current and future user agents, including assistive
  technologies]

==== Success criterion

* https://www.w3.org/TR/WCAG21/#parsing[4.1.1 Parsing (Level A)]

==== Techniques

.General Techniques
* https://www.w3.org/WAI/WCAG21/Techniques/general/G192.html[G192: Fully
  conforming to specifications]

==== Failures

* https://www.w3.org/WAI/WCAG21/Techniques/failures/F70.html[F70: Failure of
  Success Criterion 4.1.1 due to incorrect use of start and end tags or
  attribute markup]
* https://www.w3.org/WAI/WCAG21/Techniques/failures/F77.html[F77: Failure of
  Success Criterion 4.1.1 due to duplicate values of type ID]

== Quellen

[.BLOCK_LANG_EN]
Validation will usually eliminate ambiguities (and more) because an essential
step in validation is to check for proper use of that technology's markup (in
a markup language) or code (in other technologies).
Validation does not necessarily check for full conformance with a
specification but it is the best means for automatically checking content
against its specification.

* Quelle: https://www.w3.org/WAI/WCAG21/Techniques/general/G134[WCAG 2.1
  Technik G134: Validating web pages]
