= Prüfschritt 4.1.2a Name, Rolle, Wert verfügbar
include::include/author.adoc[]
include::include/config.adoc[]

== Was wird geprüft?

Alle selbst gestalteten Komponenten einer Software (also Elemente oder Widgets, keine Standard Bedienelemente des Betriebssystems) sind so umgesetzt, dass die semantischen Informationen (Name, Rolle, Eigenschaften) vorhanden sind.

Die wechselnden Zustände der selbsterstellten Bedienelemente von Apps werden nicht nur visuell abgebildet, sondern auch über programmatische Änderung der Zustandswerte an das System weitergegeben, damit die Semantik auch bei nicht-visueller Nutzung verfügbar ist, z. B. über einen Screenreader.

Bei Software werden dazu die Accessibility-Schnittstellen des jeweiligen Betriebssystems genutzt.

== Warum wird das geprüft?

Standard- Bedienelemente wie Formularelemente (Eingabefelder, Buttons, Checkboxen etc.) haben Namen, Rollen, Wert und Zustände, sofern sie gemäß Spezifikation umgesetzt sind und sind für Hilfsmittel wie Screenreader generell erkennbar. So bekommen etwa blinde Nutzer mit, wenn sie auf einen Button tabben und können diesen dann auslösen. Auch Zustände, beispielsweise einer Checkbox (ausgewählt oder nicht ausgewählt) werden vermittelt. Interaktive Schaltflächen sollten deshalb mit Hilfe von geeigneten Elementen umgesetzt werden, damit ihre Bedeutung klar wird.

Bei vom Entwickler der App selbsterstellte Bedienelementen müssen dann Plattformspezifische Methoden (meist im Quelltext) angewandt werden, um den Namen, die Rolle und den Wert des Bedienelements an das Betriebssystem weiterzugeben. Dadurch kann das Betriebssystem diese Werte an Hilfstechnologien wie Screenreader weiterreichen.

== Wie wird geprüft?

=== Anwendbarkeit des Prüfschritts

Der Prüfschritt ist anwendbar, wenn in der Software-Ansicht Bedienelemente eingesetzt werden, die *nicht* vom Betriebssystem bereitgestellt werden (Custom controls, vom Programmhersteller definierte Bedienelemente). Eine Sichtprüfung reicht dabei *[.underline]#nicht#* aus, da rein visuell nicht mit Sicherheit festgestellt werden kann, ob es sich um ein Custom Control handelt.

=== Prüfung

[arabic]
. Screenreader starten (iOS / iPadOS: Einstellungen -> Allgemein -> Bedienungshilfen -> VoiceOver).
. Software mit zu prüfender Ansicht starten.
. Möglichst alle Bedienelemente mit dem Screenreader untersuchen: Wird der Name, die Rolle und der Wert des Bedienelements vom Screenreader korrekt ausgegeben?

Der Name ist dabei der Name des Bedienelements und ist meist gleichlautend mit dem Label des Bedienelements. Z. B. „Nachname“ für ein Eingabefeld.

Zu den Rollen gehören u. a. „Eingabefeld“, „Ausklappliste“, „Checkbox“ und „Button“

Der Wert beschreibt z. B. den Inhalt des Bedienelements z. B. „Müller“ bei einem Eingabefeld für Nachnamen. Zu den Werten des Bedienelements gehört auch der aktuelle Status, z. B. „ausgewählt“ für ein ausgewählten Listeneintrag oder eine angekreuzte Checkbox.

=== Hinweise

Dieses Erfolgskriterium richtet sich in erster Linie an Softwareentwickler, die benutzerdefinierte bzw. selbstgestaltete Komponenten für die Benutzeroberfläche entwickeln oder einsetzen. Standard-Benutzeroberflächenkomponenten auf den meisten barrierefrei gestalteten Plattformen erfüllen dieses Erfolgskriterium bereits bei bestimmungsgemäßer Verwendung.

Um diesem Erfolgskriterium gerecht zu werden, ist es in der Regel empfehlenswert, dass Software-Benutzeroberflächen die Barrierefreiheitsdienste der Plattformsoftware nutzen. Diese Zugänglichkeitsdienste ermöglichen die Interoperabilität zwischen Software-Benutzeroberflächen und sowohl unterstützenden Technologien als auch Zugänglichkeitsfunktionen von Software auf standardisierte Weise. Die meisten Dienste zur Zugänglichkeit der Plattform gehen über die programmatische Offenlegung von Namen und Rolle und die programmatische Einstellung von Zuständen, Eigenschaften und Werten (und deren Benachrichtigung) hinaus und spezifizieren zusätzliche Informationen, die offengelegt werden könnten oder sollten (z.B. eine Liste der verfügbaren Aktionen für eine bestimmte Komponente der Benutzeroberfläche und ein Mittel zur programmatischen Ausführung einer der aufgeführten Aktionen).

=== Bewertung

Nicht erfüllt:

Wichtige Bedienelemente sind mit Custom Controls umgesetzt, auf eine Nachbildung der Semantik für die Barrierefreiheitsschnittstellen des Systems, wurde verzichtet.

== Einordnung des Prüfschritts

=== Formulierung BITV 2.0

4.1.2 Name, Rolle, Wert

Für alle Komponenten der Benutzerschnittstelle sind Name und Rolle durch Programme erkennbar. Zustände, Eigenschaften und Werte, die von Nutzerinnen und Nutzern eingestellt werden können, können auch durch ein Programm gesetzt werden. Bei Änderungen dieser Zustände, Eigenschaften und Werte erhalten Benutzeragenten, einschließlich assistiver Technologien, eine Mitteilung.

=== Abgrenzung von anderen Prüfkriterien

In diesem Prüfschritt geht es nicht um die Bewertung der Tastaturbedienbarkeit geskripteter Bedienelemente. Dies ist Gegenstand von Prüfschritt 2.1.1a "Ohne Maus nutzbar".

=== Einordnung des Prüfschritts nach WCAG 2.1

Guideline

Guideline 4.1 Compatible: Maximize compatibility with current and future user agents, including assistive technologies.

Success criterion

4.1.2 Name, Role, Value (Level A)

Techniques

General Techniques

G10: Creating components using a technology that supports the accessibility API features of the platforms on which the user agents will be run to expose the names and roles, allow user-settable properties to be directly set, and provide notification of changes

G108: Using markup features to expose the name and role, allow user-settable properties to be directly set, and provide notification of changes

G135: Using the accessibility API features of a technology to expose names and roles, to allow user-settable properties to be directly set, and to provide notification of changes

HTML Techniques

H64: Using the title attribute of the frame and iframe elements

H91: Using HTML form controls and links

ARIA Techniques

ARIA4: Using a WAI-ARIA role to expose the role of a user interface component

ARIA5: Using WAI-ARIA state and property attributes to expose the state of a user interface component

ARIA14: Using aria-label to provide an invisible label where a visible label cannot be used

ARIA16: Using aria-labelledby to provide a name for user interface controls

Failures

F15: Failure of Success Criterion 4.1.2 due to implementing custom controls that do not use an accessibility API for the technology, or do so incompletely

F20: Failure of Success Criterion 1.1.1 and 4.1.2 due to not updating text alternatives when changes to non-text content occur

F59: Failure of Success Criterion 4.1.2 due to using script to make div or span a user interface control in HTML

F79: Failure of Success Criterion 4.1.2 due to the focus state of a user interface component not being programmatically determinable or no notification of change of focus state available

Quellen

WAI-ARIA Spezifikation

Accessible Rich Internet Applications (WAI-ARIA) 1.1 (zur Zeit Candidate Recommendation)

ARIA in HTML

ARIA in HTML

ARIA-Widgets

WAI-ARIA Authoring Practices 1.1
