= Prüfschritt 5.2 Aktivierung von Barrierefreiheitsfunktionen
include::include/author.adoc[]
include::include/attributes.adoc[]

== Grundlage des Prüfschritts

Grundlage des Prüfschritts ist die Tabelle A.2 im Annex A der EN 301 549
V3.1.1.
In dieser Tabelle wird auf Abschnitt
5.2 "Activation of accessibility features" verwiesen.

== Was wird geprüft?

Wenn die App Funktionen für die Barrierefreiheit bereithält, die
spezielle Bedürfnisse von Nutzernerfüllt, soll die Aktivierung dieser
Funktionen für diese Nutzergruppe barrierefrei möglich sein.
Das bedeutet, dass die Barrierefreiheitsfunktion für die Nutzergruppe, die
sie unterstützen soll, selbstständig  aktivierbar sein soll.

Beispiele für Barrierefreiheitsfunktionen:

* Vorlesefunktion
* Kontrasterhöhung, Farbschemata
* Schriftgröße, Schriftformatierungen (z. B. Zeilenabstand, Schriftart usw.)
* Leichte Sprache
* Deutsche Gebärdensprache
* Animationen / automatische Audios pausieren

== Wie wird geprüft?

=== Anwendbarkeit des Prüfschritts

Der Prüfschritt ist anwendbar, wenn die zu prüfende App Funktionen für die
Barrierefreiheit bereithält.
Dieser Prüfschritt ist explizit nicht auf Systemseitige Bedienungshilfen
anzuwenden.

=== Prüfung

. App starten
. prüfen, ob Barrierefreiheitsfunktionen in den zu testenden Ansichten
  angeboten werden
. Einstellungen der App aufrufen und auch dort nach entsprechenden
  Funktionen suchen
. falls Barrierefreiheitsfunktionen angeboten werden:
+
  * Ist die Funktion für die Zielgruppe deutlich identifizierbar? Siehe
    <<Hinweis zur Identifizierbarkeit>>.
  * Ist die Funktion für die Zielgruppe selbstständig aktivierbar?

==== Hinweis zur Identifizierbarkeit

Die Barrierefreiheitsfunktionen müssen insbesondere für deren Zielgruppen
identifizierbar sein.
Dazu erfüllen die Barrierefreiheitsfunktionen bzw. die zugehörigen
Bedienelemente alle auf sie anwendbaren Prüfschritte, z. B.:

* Alternativtexte
* Tastaturbedienbarkeit, sichtbarer Fokus
* Kontrast
* Vergrößerung
* Name, Rolle, Wert

== Quellen

[.BLOCK_LANG_EN]
=== 5.2 Activation of accessibility features

[.BLOCK_LANG_EN]
Where ICT has documented accessibility features, it shall be possible to
activate those documented accessibility 
features that are required to meet a specific need without relying on a method
that does not support that need.

(Aus EN 301 549 V3.1.1 Abschnitt 5.2)
