= Prüfschritt 5.2 Aktivierung von Barrierefreiheitsfunktionen
include::include/author.adoc[]
include::include/attributes.adoc[]

== Was wird geprüft?

Wenn die App Funktionen für die Barrierefreiheit bereithält, die spezielle Bedürfnisse von Nutzenden erfüllt, soll die Aktivierung dieser Funktionen für diese Nutzergruppe barrierefrei möglich sein. Das bedeutet, dass die Barrierefreiheitsfunktion für die Nutzergruppe, die sie unterstützen soll, selbstständig aktivierbar sein soll.

Beispiele für Barrierefreiheitsfunktionen:

* Vorlesefunktion
* Kontrasterhöhung, abweichende Farbschemata
* Anpassung der Schriftgröße, Schriftformatierungen (z.B. Zeilenabstand, Schriftart usw.)
* Versionen in Leichter Sprache oder Deutscher Gebärdensprache
* Einstellungen zum Deaktivieren automatischen Abspielens bei Animationen, Videos oder Audio

== Warum wird das geprüft?

Barrierefreiheitsfunktionen, die von der App (also nicht vom Betriebssystem) bereitgestellt werden, sollen von Nutzenden selbstständig aktivierbar sein.

Wenn die App beispielsweise eine Funktion zur Verfügung stellt, mit derer die Kontrastverhältnisse innerhalb der App verbessert werden, müssen sämtliche Bedienelemente, die zur Aktivierung der Funktion bedient werden müssen, auch in der Standardansicht ein ausreichendes Kontrastverhältnis aufweisen. Damit wird sichergestellt, dass auch Nutzende, die mit kontrastarmen Inhalten und Bedienelementen Schwierigkeiten haben (also zur Zielgruppe der Barrierefreiheitsfunktion gehören), die Funktion zur Kontrasterhöhung selbstständig aktivieren können.

== Wie wird geprüft?

=== 1. Anwendbarkeit des Prüfschritts

Der Prüfschritt ist anwendbar, wenn die zu prüfende App spezielle Barrierefreiheits-Funktionen bereithält. Nicht berücksichtigt werden systemseitige Bedienungshilfen (z.B. vom Browser oder Betriebssystem).

=== 2. Prüfung

. Zu prüfende Ansicht der App öffnen
. Einstellungen der App aufrufen und auch dort nach entsprechenden Funktionen suchen
. Falls Barrierefreiheitsfunktionen angeboten werden:
  * Ist die Barrierefreiheits-Funktion für die Zielgruppe identifizierbar?
  * Ist die Barrierefreiheits-Funktion für die Zielgruppe selbstständig aktivierbar?

=== 3. Hinweise

==== 3.1 Hinweis zur Bestimmung der Zielgruppe der Barrierefreiheits-Funktion

Viele Menschen mit Behinderung nutzen verschiedene Eingabemöglichkeiten. Menschen mit kognitiven Einschränkungen haben zum Teil auch weitere Einschränkungen, sehbehinderte Nutzende nutzen oft zusätzlich Screenreader. Bei der Bestimmung der Zielgruppe ist es deshalb wichtig, auch Anforderungen zu berücksichtigen, die nicht in erster Linie mit der Einschränkung zu tun haben, für die die Barrierefreiheits-Funktion gedacht ist. So sollten Elemente zur Aktivierung von Barrierefreiheitsfunktionen generell alle Anforderungen der Barrierefreiheit erfüllen.

==== 3.2 Hinweis zur Identifizierbarkeit und Aktivierbarkeit

Bedienelemente für Barrierefreiheits-Funktionen sollen grundsätzlich alle Barrierefreiheits-Anforderungen erfüllen. Zwei Beispiele:

. Ein Schalter zum Laden einer Version in Leichter Sprache sollte leicht verständlich, kontrastreich und zugänglich beschriftet sein, denn es gibt Menschen mit kognitiven Einschränkungen, die außerdem sehbehindert oder blind sind.

. Ein visueller Kontrastmodus-Schalter für Menschen mit Sehbehinderung braucht auch eine zugängliche Beschriftung, denn manche sehbehinderte Menschen nutzen auch den Screenreader.

=== 4. Bewertung

==== Erfüllt

* Die Barrierefreiheits-Funktion ist barrierefrei identifizierbar und aktivierbar.

==== Teilweise erfüllt oder schlechter

* Bedienelemente der Barrierefreiheitsfunktion oder die Funktion selbst verstoßen gegen Anforderungen der EN.

== Einordnung des Prüfschritts

=== Einordnung des Prüfschritts nach EN 301 549 V3.1.1

[.BLOCK_LANG_EN]
==== 5.2 Activation of accessibility features
____ 

[.BLOCK_LANG_EN]
Where ICT has documented accessibility features, it shall be possible to
activate those documented accessibility 
features that are required to meet a specific need without relying on a method
that does not support that need.
____
