= 5.5.1 Möglichkeiten der Bedienung
include::include/author.adoc[]
include::include/attributes.adoc[]

== Was wird geprüft?

Wenn die ICT bedienbare Teile hat, die ein physisches Greifen, Zusammendrücken oder eine Drehung des Handgelenks erfordern, muss eine zugängliche alternative Bedienmöglichkeit zur Verfügung gestellt werden, die diese Handlungen nicht erfordert.

== Warum wird das geprüft?

Menschen mit motorischen Einschränkungen sollen physische Informations- und Kommunikationssysteme selbstständig nutzen können.

== Wie wird das geprüft?

=== 1. Anwendbarkeit des Prüfschritts

Der Prüfschritt ist vor allem anwendbar, 
wenn die zu prüfende App zusammen mit physischem Zubehör genutzt wird
und dieses Szenario geprüft wird. 
Beispiele für physisches Zubehör wären etwa ein Handscanner 
oder ein Kartenlesegerät zur Authentifizierung.

Der Prüfschritt ist auch anwendbar, wenn die Nutzung der App 
die Bedienung physischer Tasten oder Regler am Gerät (etwa Smartphone oder Tablet) einschließt 
oder das Gerät selbst für bestimmte Formen der Eingabe gegriffen, gedreht, geschüttelt oder anders ausgerichtet werden kann.

=== 2. Prüfung
. Prüfen, ob bei die Nutzung der App, z.B. für bestimmte Eingaben, die Bedienung physischer Tasten oder Regler am Gerät oder die Manipulation des Geräts selbst vorgesehen ist, und dabei ein physisches Greifen, ein Zusammendrücken, oder eine Drehung des Handgelenks erforderlich ist.
. Prüfen, ob bei der Nutzung von Zubehör, z.B. bei der Bedienung physischer Bestandteile wie Schalter, Regler oder Drehknöpfe, ein physisches Greifen, ein Zusammendrücken, 
oder eine Drehung des Handgelenks erforderlich sind.
. Falls ja: Gibt es für den Prozess eine alternative Bedienmethode ohne diese Aktionen?

=== 3. Hinweise

* Wenn es eine alternative Bedienmethode gibt, müssen alle erforderlichen Schritte dieser Methode voll barrierefrei sein.
* Ein einfaches Drücken einer Taste (etwa die Taste eines Nummernblocks) fällt nicht unter die genannten physischen Aktionen.

=== 4. Bewertung

==== Erfüllt:
* Zur Nutzung der App bzw. des Zubehörs sind physisches Greifen, Zusammendrücken, oder eine Drehung des Handgelenks nicht erforderlich.
*  Es gibt eine barrierefreie Alternative, alle für die Nutzung der App oder des Zubehörs erforderlichen Funktionen lassen sich ohne die genannten physischen Aktionen (Greifen, Zusammendrücken, Drehung des Handgelenks) ausführen.

== Einordnung des Prüfschritts

=== Abgrenzung von anderen Prüfschritten
In diesem Prüfschritt geht es um die Bedienbarkeit von physischen Geräten und zusätzlichem Zubehör mit physischen Bedienelementen durch Menschen mit motorischen Einschränkungen. Wenn die Anforderung so interpretiert wird, dass auch virtuelle Bedienelemente gemeint sind, so ist die Prüfung der Bedienbarkeit von diesen schon über verschiedene andere Prüfschritte abgedeckt, besonders durch:

* 11.2.1.1 Tastatur
* 11.2.1.4 Tastatur-Kurzbefehle abschaltbar oder anpassbar
* 11.2.5.1 Alternativen für komplexe Zeigergesten
* 11.2.5.2 Zeigergesten-Eingaben können abgebrochen oder widerrufen werden
* 11.2.5.4 Betätigung durch Bewegung

=== Einordnung des Prüfschritts nach EN 301 549 V3.2.1

[.BLOCK_LANG_EN]
==== 5.5.1 Means of operation
____
[.BLOCK_LANG_EN]
--
Where ICT has operable parts that require grasping, pinching, or twisting of the wrist to operate, an accessible alternative means of operation that does not require these actions shall be provided.
--
____
