= 5.5.2 Unterscheidbarkeit der bedienbaren Elemente
include::include/author.adoc[]
include::include/attributes.adoc[]

*Hinweis: Dies ist ein Entwurf. Inhalte können sich jederzeit ändern.*

== Was wird geprüft?

Wenn die IKT physisch bedienbare Teile hat, müssen die physisch bedienbaren Elemente als solche erkennbar sein, ohne dass Sehvermögen zwingend erforderlich ist.
Um das physische Bedienelement als solches zu erkennen, darf es außerdem nicht erforderlich sein, dass Element auszulösen bzw. zu bedienen.

== Warum wird das geprüft?

Physische Bedienelemente eines Informations- und Kommunikationssystems sollen auch durch Menschen mit Sehbehinderung als solche erkennbar sein.

== Wie wird das geprüft?

=== 1. Anwendbarkeit des Prüfschritts

Der Prüfschritt ist für die Prüfung von mobilen Apps für iOS und Android im Regelfall nicht anwendbar.
Ist die zu prüfende App für die Nutzung zusammen mit physischem Spezialzubehör gedacht, findet der Prüfschritt jedoch ggf. Anwendung.

=== 2. Prüfung

=== 3. Hinweise

Eine Möglichkeit, diese Anforderung zu erfüllen, besteht darin, die physisch bedienbaren Teile taktil wahrnehmbar zu machen.

=== 4. Bewertung

==== Erfüllt:

== Einordnung des Prüfschritts

=== Abgrenzung von anderen Prüfschritten

In diesem Prüfschritt geht es um die Bedienbarkeit von zusätzlichem Zubehör durch Menschen mit motorischen Einschränkungen, wenn dieses zusammen mit der App genutzt wird. Wenn die Anforderung so interpretiert wird, dass auch virtuelle Bedienelemente gemeint sind, so ist die Prüfung der Bedienbarkeit von diesen schon über verschiedene andere Prüfschritte der En abgedeckt, besonders durch:

* 11.1.4.11 Kontraste von Grafiken und Bedienelementen ausreichend
* 11.4.1.2 Name, Rolle, Wert verfügbar
* 11.5.2.15 Änderungsbenachrichtigung
* 11.5.2.16 Änderungen von Zuständen und Eigenschaften

=== Einordnung des Prüfschritts nach EN 301 549 V3.2.1

[.BLOCK_LANG_EN]
==== 5.5.2 Operable parts discernibility
____
[.BLOCK_LANG_EN]
--
Where ICT has operable parts, it shall provide a means to discern each operable part, without requiring vision and without performing the action associated with the operable part.

NOTE:
One way of meeting this requirement is by making the operable parts tactilely discernible.
--
____
