= 5.5.1 Möglichkeiten der Bedienung
include::include/author.adoc[]
include::include/attributes.adoc[]

*Hinweis: Dies ist ein Entwurf. Inhalte können sich jederzeit ändern.*

== Was wird geprüft?

Wenn die ICT bedienbare Teile hat, die ein physisches Greifen, Zusammendrücken oder eine Drehung des Handgelenks erfordern, muss eine zugängliche alternative Bedienmöglichkeit zur Verfügung gestellt werden, die diese Handlungen nicht erfordert.

== Warum wird das geprüft?

Menschen mit motorischen Einschränkungen sollen physische Informations- und Kommunikationssysteme selbstständig nutzen können.

== Wie wird das geprüft?

=== 1. Anwendbarkeit des Prüfschritts

Der Prüfschritt ist anwendbar, wenn die zu prüfende App zusammen mit physischem Zubehör genutzt wird und dieses Szenario geprüft wird. Beispiele für physisches Zubehör wären etwa ein Handscanner oder ein Kartenlesegerät zur Authentifizierung.

=== 2. Prüfung
. Prüfen, ob während der Nutzung des Zubehörs  bei der Bedienung phyischer Teile (etwa Schalter, Regler oder Drehknöpfe) ein physisches Greifen, ein Zusammendrücken, oder eine Drehung des Handgelenks erforderlich sind.
. Falls ja: Gibt es für den Prozess eine alternative Bedienmethode ohne diese Aktionen?

=== 3. Hinweise

* Wenn es eine alternative Bedienmethode gibt, müssen alle erforderlichen Schritte dieser Methode voll barrierefrei sein.
* Ein einfaches Drücken einer Taste (etwa die Taste eines Nummernblocks) fällt nicht unter die genannten physischen Aktionen.

=== 4. Bewertung

==== Erfüllt:
* Zur Nutzung des Zubehörs sind physisches Greifen, Zusammendrücken, und eine Drehung des Handgelenks nicht erforderlich.
*  Es gibt eine barrierefreie Alternative, alle erforderliche Aktionen zur Nutzung der App mit Zubehör ohne die physischen Aktionen (Greifen, Zusammendrückenm Drehung des Handgelenks) auszuführen.

== Einordnung des Prüfschritts

=== Einordnung des Prüfschritts nach EN 301 549 V3.2.1

Kriterium 5.5.1 Means of operation

== Quellen

[.BLOCK_LANG_EN]
=== 5.5.1 Means of operation

____
[.BLOCK_LANG_EN]
--
Where ICT has operable parts that require grasping, pinching, or twisting of the wrist to operate, an accessible alternative means of operation that does not require these actions shall be provided.
--
____

(Aus EN 301 549 V3.2.1 Abschnitt 5.5.1 Means of operation)
