= 5.6.1 Taktiler oder auditiver Status
include::include/author.adoc[]
include::include/attributes.adoc[]

== Was wird geprüft?
Manche Apps können zusammen mit spezieller Hardware genutzt werden. 
Ein Beispiel ist eine App, die das Einscannen von Produkten über einen Handscanner erlaubt. 
Ein weiteres Beispiel wäre eine App, die die Authentifizierung von Nutzenden über ein Kartenlesegerät ermöglicht. 
Wenn es in Hardware, die zusammen mit der App genutzt wird, visuell wahrnehmbare Umschalter gibt, soll es möglich sein, den Zustand des Umschalters auch akustisch oder taktil (also durch Fühlen mit den Fingern) zu erfassen. 
Dies gilt für Schalter mit zwei oder drei Zuständen.

Auch Umschalter auf dem Ausgabegerät selbst können für die Nutzung der App relevant sein, etwa physische Umschalter für das Stummschalten oder das Feststellen der Bildschirmausrichtung. Auch der Zustand solcher Schalter am Gerät selbst soll taktil oder auditiv ermittelbar sein.

Beispiele wären:

* An/Aus Schalter an einem Kartenlesegerät oder Hand-Scanner
* Umschalter für Ton an / Ton aus (Stummschalten) an einem Eingabegerät oder Ausgabegerät
* Voreinstellungs-Schalter für drei verschiedene Lautstärke-Stufen für die aktustische Ausgabe an einem Gerät

== Warum wird das geprüft?

Wenn physische Umschalter am Ausgabegerät oder zusätzlicher Hardware bei der Nutzung von Apps relevant sind, soll deren Zustand wahrnehmbar sein. Dazu gehört, das der Zustand nicht nur visuell, sondern auch mit dem Finger fühlbar oder aber akustisch ermittelbar ist.

== Wie wird das geprüft?

=== 1. Anwendbarkeit des Prüfschritts
Der Prüfschritt ist nur anwendbar, wenn für die Nutzung der App der Zustand von Hardware-Schaltern auf einem Ausgabegrät oder spezieller zusätzlicher Hardware relevant sind. Dazu gehören etwa Schalter zum Feststellen der Bildschirmausrichtung oder zum Stummschalten am genutzten Ausgabegerät, oder physische Umaschalter an gekoppelter spezieller Hardware.

=== 2. Prüfung
. Wird die App zusammen mit zusätzliche Hardware genutzt?
. ist der Zustand physische Umschalter an der Hardware mit zwei oder drei Positionen taktil oder akustisch ermittelbar?

=== 3. Hinweise
* Wenn die App einen Modus hat, der die gleiche Funktionalität auch ohne gekoppeltes Zubehör bietet oder der Schalter-Zustand des Zubehörs auch in der App sowohl visuell als auch programmatisch ermittelbar ist, wäre der Prüfschritt erfüllt.
* Die Feststelltasten bei ggf. gekoppelten Tastaturen geben ihren Feststell-Status bei entsprechender Voreistellung im Betriebssystem oft nur einmalig bei Aktivierung und Deaktivierung des Feststellmodus aus. 
Da App-Entwickler keinen Einfluss auf das Verhalten der Tastaturen haben, werden sie in diesem Prüfschritt nicht berücksichtigt.

=== 4. Bewertung
==== Nicht erfüllt
* In der mit der App zusammen genutzten Hardware ist ein Umschalter vorhanden, dessen Zustand nicht taktil oder über Tonsignal ermittelbar ist. 

== Quellen

* ETSI Labs Issue #49: https://labs.etsi.org/rep/HF/en301549/-/issues/49[5.6.1 and 5.6.2 applicable to on-screen graphic controls?]

== Einordnung des Prüfschritts
=== Abgrenzung zu anderen Prüfschritten
In diesem Prüfschritt geht es um die Bedienbarkeit von zusätzlichem Zubehör durch Menschen mit motorischen Einschränkungen, wenn dieses zusammen mit der App genutzt wird. Wenn die Anforderung so interpretiert wird, dass auch virtuelle Bedienelemente gemeint sind, so ist die Prüfung der Bedienbarkeit von diesen schon über andere Prüfschritte abgedeckt, besonders durch:

* 11.4.1.2 Name, Rolle, Wert verfügbar
* 11.5.2.15 Änderungsbenachrichtigung
* 11.5.2.16 Änderungen von Zuständen und Eigenschaften

=== Einordnung des Prüfschritts nach EN 301 549 V3.1.1

[.BLOCK_LANG_EN]
==== 5.6.1 Tactile or auditory status
____
[.BLOCK_LANG_EN]
--
Where ICT has a locking or toggle control and the status of that control is visually presented to the user, the ICT shall provide at least one mode of operation where the status of the control can be determined either through touch or sound without operating the control.

NOTE 1:
Locking or toggle controls are those controls that can only have two or three states and that keep their state while being used.

NOTE 2:
An example of a locking or toggle control is the "Caps Lock" key found on most keyboards. Another example is the volume button on a pay telephone, which can be set at normal, loud, or extra loud volume.
--
____
