= 5.6.1 Taktiler oder auditiver Status
include::include/author.adoc[]
include::include/attributes.adoc[]

*Hinweis: Dies ist ein Entwurf. Inhalte können sich jederzeit ändern.*

== Was wird geprüft?
Manche Apps können zusammen mit spezieller Hardware genutzt werden. 
Ein Beispiel ist eine App, die das Einscannen von Produkten über einen Handscanner erlaubt. 
Ein weiteres Beispiel wäre eine App, die die Authentifizierung von Nutzenden über ein Kartenlesegerät ermöglicht. 
Wenn es in Hardware, die zusammen mit der App genutzt wird, visuell wahrnehmbare Umschalter gibt, soll es möglich sein, den Zustand des Umschalters auch akustisch oder taktil (also durch Fühlen mit den Fingern) zu erfassen. 
Dies gilt für Schalter mit zwei oder drei Zuständen.
Beispiele wären:

* An/Aus Schalter an einem Kartenlesegerät oder Hand-Scanner
* Umschalttaste für Ton an/Ton aus an einem Eingabegerät
* Voreinstellungs-Schalter für drei verschiedene Lautstärke-Stufen für die aktustische Ausgabe an einem Gerät

== Warum wird das geprüft?

Wenn zusätzliche Hardware bei der Nutzung von Apps erforderlich ist, soll auch der Zustand physischer Bedienelemente wahrnehmbar sein. Dazu gehört, das der Zustand nicht nur visuell, sondern auch mit dem Finger fühlbar oder aber akustisch ermittelbar ist.

== Wie wird das geprüft?

=== 1. Anwendbarkeit des Prüfschritts
Der Prüfschritt ist nur anwendbar, die App zusammen mit gekoppelter Hardware geprüft wird. 
Dazu gehören z.B. Handscanner oder Kartenlesegerät.

=== 2. Prüfung
. Wird die App zusammen mit zusätzliche Hardware genutzt?
. ist der Zustand physische Umschalter an der Hardware mit zwei oder drei Positionen taktil oder akustisch ermittelbar?

=== 3. Hinweise
Wenn die App einen Modus hat, der die gleiche Funktionalität auch ohne gekoppelte Hardware bietet oder der Schalter-Zustand der Hardware auch in der App sowohl visuell als auch programmatisch ermittelbar ist, wäre der Prüfschritt erfüllt.

=== 4. Bewertung
==== Nicht erfüllt
* In der mit der App zusammen genutzten Hardware ist ein Umschalter vorhanden, dessen Zustand nicht taktil oder über Tonsignal ermittelbar ist. 

== Einordnung des Prüfschritts

=== Abgrenzung zu virtuellen Schaltern in der App 
Die programmatische Ermittelbarkeit des Zustandes von virtuellen Umschaltern wird in Prüfschritt 11.4.1.2 "Name, Rolle, Wert" sowie 11.5.2.16 "Änderungen von Zuständen und Eigenschaften" geprüft.

=== Abgrenzung zu Tastaturen 
Die Feststelltasten bei ggf. gekoppelten Tastaturen geben ihren Feststell-Status bei entsprechender Voreistellung im Betriebssystem oft nur einmalig bei Aktivierung und Deaktivierung des Feststellmodus aus. 
Da App-Entwickler keinen Einfluss auf das Verhalten der Tastaturen haben, werden sie in diesem Prüfschritt nicht berücksichtigt.

== Einordnung des Prüfschritts

=== Einordnung des Prüfschritts nach EN 301 549 V3.1.1

[.BLOCK_LANG_EN]
==== 5.6.1 Tactile or auditory status
____
[.BLOCK_LANG_EN]
--
Where ICT has a locking or toggle control and the status of that control is visually presented to the user, the ICT shall provide at least one mode of operation where the status of the control can be determined either through touch or sound without operating the control.

NOTE 1:
Locking or toggle controls are those controls that can only have two or three states and that keep their state while being used.

NOTE 2:
An example of a locking or toggle control is the "Caps Lock" key found on most keyboards. Another example is the volume button on a pay telephone, which can be set at normal, loud, or extra loud volume.
--
____

== Quellen

* ETSI Labs Issue #49: https://labs.etsi.org/rep/HF/en301549/-/issues/49[5.6.1 and 5.6.1 applicable to on-screen graphic controls?]
