= 5.6.1 Taktile oder Auditive Statusvermittlung
include::include/author.adoc[]
include::include/attributes.adoc[]

== Was wird geprüft?
Wenn es in der App visuell wahrnehmbare Kipp-Schalter oder dreiwertige Schalter gibt, die den Kontext der Ausgabe oder Eingabe beeinflussen, etwa einen Schalter zum Feststellen der Bildschirm-Ausrichtung, müssen diese Schalter über geeignete Ausgabesoftware oder -Hardware sowohl taktil als auch akustisch wahrnehmbar sein. Taktile Wharnehmung kann etwa über eine Braille-Zeile, akustische Wahrnehmung über einen Screenreader erfolgen. Grundlegend für beides ist die programmatische Ermittelbarkeit des Status.

Die Intention dieser Anforderung ist die Einbeziehung von physischen Schaltern an Geräten, welche Zustände im Sinn eines Kippschalters oder dreiwertigen Schalters ändern. Dazu gehören etwa Großbuchstaben-Feststelltaste oder dreiwertige Lautstärke-Taste. Im Kontext von Mobilgeräten ist insbesondere die Feststelltaste für die Bildschirmausrichtung relevant. Es lässt sich also ableiten, dass es hier speziell um Bedienelemente geht, die nicht Funktionen der App selbst betreffen, sondern den Kontext der Eingabe oder Ausgabe.

Da sich der Test auf die Prüfung der App selbst beschränkt und Peripherie nicht einbezieht (siehe "Einordnung des Prüfschritts" unten), werden in diesem Prüfschritt nur virtualisierte Schalter geprüft, die den Kontext der Ausgabe oder Eingabe betreffen. Dazu würden zum Beispiel ein Schalter zum Sperren der Ausrichtung oder auch ein Schalter zum Stumm-Stellen gehören, da sie den Gesamtkontext der Ausgabe betreffen. Bei solchen Schaltern muss der Status programmatisch ermittelbar sein, ohne den jeweiligen Schalter bedienen / aktivieren zu müssen.

== Warum wird das geprüft?

Von der App implementierte Schalter, die den Kontext der Ein- oder Ausgabe ändern können dazu führen, dass App-Inhalte nicht oder nur in einer für Nutzende unvertrauten Form erscheinen.  Beispiel Ausrichtungssperre: Bei manchen Apps sind Layout und direkte Verfügbarkeit von Inhalten von der Viewportbreite des Displays abhängig. Andere Apps bieten ihre Inhalte ausschließlich im Hochformat. Die Feststellung einer nicht gewünschten Orientierung, die von Nutzenden nicht programmatisch zu ermitteln ist, kann unter Umständen also eine schwere Barriere darstellen. Der Status solcher Einstellungen muss also programmatisch (und damit takil für die Braillezeile, und auditiv für den Screenreader) verfügbar sein.

== Wie wird das geprüft?

=== 1. Anwendbarkeit des Prüfschritts
Der Prüfschritt ist nur anwendbar, wenn in der App Bedienelemente vorkommen, die Einstellungen außerhalb der App, also auf Betriebssystem-Ebene, ändern. Dazu gehören Schalter zum Feststellen der Bildschirmausrichtung, zum Aktivieren der Taschenlampe, der Kamera usw. Andere Schalter für Einstellungen mit zwei oder drei Werten, die Aspekte der Darstellung oder Funktion der App selbst ändern, etwa Kontrastschalter, genereller Ausklappstatus, erweiterte Linktexte oder Ähnliches, werden in Prüfschritt 11.4.1.2 bewertet.

=== 2. Prüfung
Mittels Quelltextanalyse oder Screenreader-Ausgabe prüfen, ob der Zustand von Bedienelementen für Einstellungen, die sich außerhalb der App auswirken, programmatisch ermittelbar ist.

=== 3. Hinweise

=== 4. Bewertung
==== 4.1 Nicht erfüllt:
Ist in der App selbst ein Bedienelement für Einstellungen, die sich außerhalb der App auswirken, vorhanden und dessen Zustand ist nicht programmatisch ermittelbar, sind sowohl dieser Prüfschritt als auch 11.4.1.2 nicht erfüllt.

== Einordnung des Prüfschritts

=== Zur Abgrenzung zu physischen Schaltern und solchen auf Betriebssystem-Ebene 

App-Entwickler haben auf die genutzten physischen Geräte und Peripherie-Geräte wie Tastastuen keinerlei Einfluss. Ebensowenig können sie beeinflöussen, ob die von nutzendne verwendeten virtuellen Tastaturen die Anforderung erfüllen. Die dominanten mobilen Betriebssysteme bieten Bedienelemente zum Arretieren der Ausrichtung: "Ausrichtungssperre" (iOS) und "Bildschirm automatisch drehen" (Android). Der Zustand beider programmatisch zugänglich und damit über eine Braillzeile taktil und über eine Screenreader-Ausgabe akustisch wahrnehmbar. 

=== Zur Abgrenzung zu virtuellen Tastaturen 
Die Feststelltasten bei virtuellen Tastaturen geben ihren Feststell-Status oft nur einmalig bei Aktivierung des Feststellmodus aus: so bei den Android-Tastaturen GBoard und SwiftKey. Bei der iOS Tastatur wird der Feststell-Modus aktivierungsunabhängig ausgegeben. Da App-Entwickler keinen Einfluss darauf haben, werden sie in diesem Prüfschritt nicht berücksichtigt.

=== Einordnung des Prüfschritts nach EN 301 549 V3.1.1

Kriterium

== Quellen

[.BLOCK_LANG_EN]
=== 5.6.1 Tactile or auditory status

____
[.BLOCK_LANG_EN]
--
Where ICT has a locking or toggle control and the status of that control is visually presented to the user, the ICT shall provide at least one mode of operation where the status of the control can be determined either through touch or sound without operating the control.

NOTE 1:
Locking or toggle controls are those controls that can only have two or three states and that keep their state while being used.

NOTE 2:
An example of a locking or toggle control is the "Caps Lock" key found on most keyboards. Another example is the volume button on a pay telephone, which can be set at normal, loud, or extra loud volume.
--
____

(Aus EN 301 549 V3.2.1 Abschnitt 5.6.1 Tactile or auditory status)
