= 5.6.2 Visuelle Statusvermittlung
include::include/author.adoc[]
include::include/attributes.adoc[]

== Was wird geprüft?

== Warum wird das geprüft?

== Wie wird das geprüft?

=== 1. Anwendbarkeit des Prüfschritts

=== 2. Prüfung

=== 3. Hinweise

=== 4. Bewertung

==== Erfüllt:

== Einordnung des Prüfschritts

=== Einordnung des Prüfschritts nach EN 301 549 V3.1.1

Kriterium

== Quellen

[.BLOCK_LANG_EN]
=== 5.6.2 Visual status

____
[.BLOCK_LANG_EN]
--
Where ICT has a locking or toggle control and the status of the control is non-visually presented to the user, the ICT shall provide at least one mode of operation where the status of the control can be visually determined when the control is presented.

NOTE 1:
Locking or toggle controls are those controls that can only have two or three states and that keep their state while being used.

NOTE 2:
An example of a locking or toggle control is the "Caps Lock" key found on most keyboards. An example of making the status of a control determinable is a visual status indicator on a keyboard.
--
____

(Aus EN 301 549 V3.2.1 Abschnitt 5.6.2 Visual status)
