= 5.6.2 Visueller Status
include::include/author.adoc[]
include::include/attributes.adoc[]

== Was wird geprüft?

Manche Apps können zusammen mit spezieller Hardware genutzt werden. Ein Beispiel ist eine App, die das Einscannen von Produkten über einen Handscanner erlaubt. Ein weiteres Beispiel wäre eine App, die die Authentifizierung von Nutzenden über ein Kartenlesegerät ermöglicht. Wenn es in Hardware, die zusammen mit der App genutzt wird, nicht-visuell wahrnehmbare Umschalter gibt, soll es möglich sein, den Zustand des Umschalters auch visuell zu erfassen. Dies gilt für Schalter mit zwei oder drei Zuständen. 

Für die Nutzung mancher Apps können bestimmte Zustände von Umschaltern am Ausgabegerät selbst relevant sin, z.B. zum Stummschalten des Geräts oder Feststellen der Bildschirmausrichtung. Auch der Zustand solcher Schalter am Gerät selbst soll visuell ermittelbar sein.

Beispiele wären:

* An/Aus Schalter an einem Kartenlesegerät oder Hand-Scanner
* Umschalter für Ton an/Ton aus (Stummschalten) an einem Eingabegerät oder Ausgabegerät
* Voreinstellungs-Schalter für drei verschiedene Lautstärke-Stufen für die aktustische Ausgabe an einem Gerät

Wenn es auf dem Ausgabegerät oder einer speziellen Hardware, die zusammen mit der App genutzt wird, Umschalter oder dreiwertige Schalter gibt, die den Kontext der Ausgabe oder Eingabe beeinflussen, müssen diese Schalter auch visuell wahrnehmbar sein.

Die Intention dieser Anforderung ist ebenso wie bei Prüfschritt 5.6.1 die Einbeziehung von physischen Schaltern an Geräten, welche Zustände der Ausgabe (etwa Lautstärke) oder Eingabe (etwa Großbuchstaben) mittels Umschalter oder dreiwertigem Schalter feststellen. Dazu gehören etwa Großbuchstaben-Feststelltaste oder dreiwertige Lautstärke-Taste. Im Kontext von Mobilgeräten wären insbesondere physische Umschalter für die Stummschaltung oder das Feststellen der Bildschirmausrichtung relevant, für die sich abhängig vom genutzten Gerät auch physische Tasten finden (etwa beim iPhone). Es lässt sich also ableiten, dass es hier speziell um Bedienelemente geht, die nicht Funktionen der App selbst betreffen, sondern den Kontext der Eingabe oder Ausgabe.

Virtualisierte Schalter innerhalb der App sind nicht von diesem Prüfschritt erfasst. Für diese ist der Prüfschritt 11.4.1.2 Name, Rolle, Wert zuständig.

== Warum wird das geprüft?

Wenn der Zustand von Umschaltern auf dem Gerät oder auf spezieller Hardware bei der Nutzung der App relevant ist, soll dieser Zustand auch visuell erkennbar sein. Dies ist zum Beispiel dann der Fall, wenn ein Umschalter zwei visuell unterschiedbare Zustände hat. Beim Stummschalten des iPhones wird z.B. der Umschalter Richtung Geräterückseite geschoben, es erscheint zusätzlich ein schmaler roter Streifen im Ausschnitt, in dem sich der Schalter bewegt. Damit wird visuell signalisiert, dass der Ton abgestellt ist.

== Wie wird das geprüft?

=== 1. Anwendbarkeit des Prüfschritts
Der Prüfschritt ist nur anwendbar, wenn für die Nutzung der App der Zustand von Hardware-Schaltern auf einem Ausgabegrät oder spezieller zusätzlicher Hardware relevant sind. Dazu gehören etwa Schalter zum Feststellen der Bildschirmausrichtung oder zum Stummschalten am genutzten Ausgabegerät, oder physische Umaschalter an gekoppelter spezieller Hardware.

=== 2. Prüfung
. Gibt es auf dem Ausgabegerät oder zusätzlich genutzter Hardware Umschalter, die generell den Kontext der Ausgabe oder Eingabe beeinflussen (z.B. die Bildschirm-Ausrichtung feststellen oder den Ton stumm schalten)?
. Falls das zutrifft: Mittels Sichtprüfung für solche physischen Umschalter prüfen, ob der Zustand visuell ermittelbar ist.

=== 3. Hinweise
* Wenn die App einen Modus hat, der die gleiche Funktionalität auch ohne gekoppeltes Zubehör bietet oder der Schalter-Zustand des Zubehörs auch in der App sowohl visuell als auch programmatisch ermittelbar ist, wäre der Prüfschritt erfüllt.

=== 4. Bewertung
==== Nicht erfüllt
* Für die Nutzung der App ist ein physischer Umschalter auf dem Ausgabegerät oder auf zusätzlicher Hardware relevant, der den Kontext der Ausgabe oder Eingabe beeinflusst und dessen Zustand nicht visuell ermittelbar ist.

== Quellen

* ETSI Labs Issue #49: https://labs.etsi.org/rep/HF/en301549/-/issues/49[5.6.1 and 5.6.2 applicable to on-screen graphic controls?]

== Einordnung des Prüfschritts
=== Abgrenzung zu anderen Prüfschritten
In diesem Prüfschritt geht es um die Bedienbarkeit von zusätzlichem Zubehör durch Menschen mit motorischen Einschränkungen, wenn dieses zusammen mit der App genutzt wird. Wenn die Anforderung so interpretiert wird, dass auch virtuelle Bedienelemente gemeint sind, so ist die Prüfung der Bedienbarkeit von diesen schon über andere Prüfschritte abgedeckt, besonders durch:

* 11.1.4.11 Kontraste von Grafiken und Bedienelementen ausreichend

=== Zur Abgrenzung zu Einstellungen auf Betriebssystem-Ebene 

Die dominanten mobilen Betriebssysteme bieten Bedienelemente zum Arretieren der Ausrichtung: "Ausrichtungssperre" (iOS) und "Bildschirm automatisch drehen" (Android). Der Zustand ist bei beiden visuell zugänglich. 

=== Zur Abgrenzung zu virtuellen Tastaturen 
Der Status "festgestellt" bei der Shift-Taste virtueller Tastaturen wird bei allen uns bekannten Tastaturen visuell vermittelt. Da App-Entwickler keinen Einfluss auf installierte Tastaturen haben, werden sie in diesem Prüfschritt nicht berücksichtigt.

=== Einordnung des Prüfschritts nach EN 301 549 V3.2.1

[.BLOCK_LANG_EN]
==== 5.6.2 Visual status
____
[.BLOCK_LANG_EN]
--
Where ICT has a locking or toggle control and the status of the control is non-visually presented to the user, the ICT shall provide at least one mode of operation where the status of the control can be visually determined when the control is presented.

NOTE 1:
Locking or toggle controls are those controls that can only have two or three states and that keep their state while being used.

NOTE 2:
An example of a locking or toggle control is the "Caps Lock" key found on most keyboards. An example of making the status of a control determinable is a visual status indicator on a keyboard.
--
____

