= 5.6.1 Taktile oder Auditive Statusvermittlung
include::include/author.adoc[]
include::include/attributes.adoc[]

== Was wird geprüft?
Wenn es einen Schalter zum Feststellen der Bildschirm-Ausrichtung oder andere Feststelltasten (etwa für Großbuchstaben) gibt und dessen Einstellung visuell wahrnehmbar ist, soll dessen Einstellung sowohl taktil als auch akustisch wahrnehmbar sein.

In diesem Prüfschritt wird geprüft, ob die App selbst eine Funktion zum Sperren der Ausrichtung anbietet. Wenn dies der Fall ist, muss der Sperr-Status programmatisch ermittelbar sein, ohne Schalter für diese Funktion zu bedienen zu müssen.

=== Zur Abgrenzung zu physischen Schaltern und solchen auf Betriebssystem-Ebene 

App-Entwickler haben auf die genutzten physischen Geräte und Peripherie-Geräte wie Tastastuen keinerlei Einfluss. Ebensowenig können sie beeinflöussen, ob die von nutzendne verwendeten virtuellen Tastaturen die Anforderung erfüllen. Die dominanten mobilen Betriebssysteme bieten Bedienelemente zum Arretieren der Ausrichtung: "Ausrichtungssperre" (iOS) und "Bildschirm automatisch drehen" (Android). Der Zustand beider programmatisch zugänglich und damit über eine Braillzeile taktil und über eine Screenreader-Ausgabe akustisch wahrnehmbar. 

=== Zur Abgrenzung zu virtuellen Tastaturen 
Die Feststelltasten bei virtuellen Tastaturen geben ihren Feststell-Status oft nur einmalig bei Aktivierung des Feststellmodus aus: so bei den Android-Tastaturen GBoard und SwiftKey. Bei der iOS Tastatur wird der Feststell-Modus aktivierungsunabhängig ausgegeben. Da App-Entwickler keinen Einfluss darauf haben, werden sie in diesem Prüfschritt nicht berücksichtigt.

== Warum wird das geprüft?

Von der App implementierte Ausrichtungssperren, falls vorhanden, müssen

== Wie wird das geprüft?

=== 1. Anwendbarkeit des Prüfschritts

=== 2. Prüfung

=== 3. Hinweise

=== 4. Bewertung

==== Erfüllt:

== Einordnung des Prüfschritts

=== Einordnung des Prüfschritts nach EN 301 549 V3.1.1

Kriterium

== Quellen

[.BLOCK_LANG_EN]
=== 5.6.1 Tactile or auditory status

____
[.BLOCK_LANG_EN]
--
Where ICT has a locking or toggle control and the status of that control is visually presented to the user, the ICT shall provide at least one mode of operation where the status of the control can be determined either through touch or sound without operating the control.

NOTE 1:
Locking or toggle controls are those controls that can only have two or three states and that keep their state while being used.

NOTE 2:
An example of a locking or toggle control is the "Caps Lock" key found on most keyboards. Another example is the volume button on a pay telephone, which can be set at normal, loud, or extra loud volume.
--
____

(Aus EN 301 549 V3.2.1 Abschnitt 5.6.1 Tactile or auditory status)
