= 5.7 Tastenwiederholung
include::include/author.adoc[]
include::include/attributes.adoc[]

*Hinweis: Dies ist ein Entwurf. Inhalte können sich jederzeit ändern.*

== Was wird geprüft?
Die Tastenwiederholung, die automatisch beim Halten einer Taste auf der Tastatur das jeweilige Zeichen wiederholt, soll so konfigurierbar sein, dass die Taste mindestens zwei Sekunden gedrückt werden kann, bevor die Tastenwiederholung einsetzt (der Standard ist etwa eine halbe Sekunde). Dies sind üblicherweise Einstellungen des Betriebssystems, auf die Entwickler in der Regel keinen Einfluss haben, bzw. keinen Einfluss nehmen sollten.

Bei der Nutzung virtueller Tastaturen (Touch-Eingabe) unter iOS und Android erfolgt keine Tastenwiederholung. Der Prüfschritt wäre für eine Accessibility Baseline, die Apps nur mit Toucheingabe (ohne Anschluss externer Tastaturen) betrachten wollte, also ohnehin erfüllt. Unter iOS und iPadOS (iPad mit Magic Keyboard) gibt es die geforderten Einstellungsmöglichkeiten unter Bedienungshilfen / Tastaturen / Tastenwiederholung. Hier lässt sich die Tastenwiederholung ganz abstellen.

Hinweis: Ist bei iOS Tastenwiederholung aktiviert, funktioniert diese nur bei bestimmten Tasten, nicht jedoch bei 0-9 und A-Z. Dies ist ein bekannter iOS-Bug.

Unter Android mit externer Tastatur lässt sich die Tastenwiederholung zur Zeit nicht abstellen oder einstellen. Eine App, https://play.google.com/store/apps/details?id=com.apedroid.hwkeyboardhelper&pli=1[External Keyboard Helper Pro], bietet diese Möglichkeit.

Da im App-Test nur Aspekte geprüft werden, welche Entwickler direkt in der Gestaltung der App beeinflussen können und sollen, wird diese Anforderung zur Zeit nicht aktiv geprüft, da sie die Betriebssystem-Ebene betrifft.

== Warum wird das geprüft?
Menschen mit motorischen Einschränkungen haben manchmal das Problem, dass sie durch zu langes Drücken von Tasten unabsichtlich die Tastenwiederholung auslösen und dann Eingaben wieder löschen müssen. Die Verlängerung der Verzögerung vor Einsetzen der Tastenwiederholung und Verlangsamung des Intervalls zwischen wiederholten Eingaben verringert dieses Risiko.

== Wie wird das geprüft?
Der Prüfschritt wird nicht geprüft, da Einstellungsmöglichkeiten der Tastenwiederholung Aufgabe des Betriebssystems sind und nicht auf der Ebene der App implementiert werden sollten. Selbst wenn Android-App-Entwickler die Tastenwiederholung bei der Nutzung externer Tastaturen erfolgreich unterbinden, wäre hieraus keine generelle Anforderung abzuleiten, dies auf der Ebene der App umzusetzen.

=== 1. Anwendbarkeit des Prüfschritts
Der Prüfschritt wird nicht angewandt. 

=== 2. Prüfung
Keine Prüfung.

=== 3. Bewertung

==== Nicht anwendbar:
Der Prüfschritt ist zurzeit nicht anwendbar.

== Einordnung des Prüfschritts

=== Einordnung des Prüfschritts nach EN 301 549 V3.1.1

Kriterium

== Quellen

* Android App offering key repeat settings: https://play.google.com/store/apps/details?id=com.apedroid.hwkeyboardhelper&pli=1[External Keyboard Helper Pro]

[.BLOCK_LANG_EN]
=== 5.7 Key repeat
____
[.BLOCK_LANG_EN]
--
Where ICT has a key repeat function that cannot be turned off:

a) the delay before the key repeat shall be adjustable to at least 2 seconds; and

b) the key repeat rate shall be adjustable down to one character per 2 seconds.
--
____
