= 5.7 Tastenwiederholung
include::include/author.adoc[]
include::include/attributes.adoc[]

== Was wird geprüft?
Die Tastenwiederholung, 
die automatisch beim Halten einer Taste auf der Tastatur 
das jeweilige Zeichen wiederholt, 
soll, wenn sie sich nicht deaktivieren lässt, 
so konfigurierbar sein, 
dass die Taste mindestens zwei Sekunden gedrückt werden muss, 
bevor die Tastenwiederholung einsetzt 
(der Standard ist etwa eine halbe Sekunde). 
Dies sind üblicherweise Einstellungen des Betriebssystems, 
auf die Entwickler in der Regel keinen Einfluss haben. 
Apps sollten diese betriebssystemseitigen Einstellungen, wo vorhanden, für Texteingaben übernehmen.

== Warum wird das geprüft?
Menschen mit motorischen Einschränkungen haben manchmal das Problem, 
dass sie durch zu langes Drücken von Tasten 
unabsichtlich die Tastenwiederholung auslösen 
und dann Eingaben wieder löschen müssen. 
Das Abschalten der Tastenwiederholung bzw. das Einstellen 
einer längeren Verzögerung vor Einsetzen der Tastenwiederholung 
verringert dieses Risiko.

== Wie wird das geprüft?

=== 1. Anwendbarkeit des Prüfschritts
Der Prüfschritt wird nur geprüft, 
wenn die Tastenwiederholung nicht abstellbar ist 
und die Funktion in der App unterstützt wird. 
Bei iOS-Apps ist der Prüfschritt generell nicht anwendbar, 
da die Tastenwiederholfunktion abgeschaltet werden kann.
Bei Android-Apps ist der Prüfschritt nur anwendbar, 
wenn die Ansicht Texteingabefelder für Tastatureingaben enthält.
Geprüft wird nicht die systemseitige Einstellung selbst, 
sondern nur, ob diese auch bei Texteingaben in der App greifen.

=== 2. Prüfung
Die Funktion Tastenwiederholung ist, soweit vorhanden, 
eine generelle Einstellung auf Betriebssystem-Ebene. 
Für die App selbst kann also nur geprüft werden, 
ob Einstellungen wie von Nutzenden intendiert 
bei Texteingaben auf der Ansicht greifen. 

==== iOS
* Unter iOS und iPadOS (iPad mit Magic Keyboard) 
gibt es die geforderten Einstellungsmöglichkeiten unter Bedienungshilfen / Tastaturen & Texteingabe / Tastenwiederholung. 
Hier lässt sich die Tastenwiederholung auch ganz abstellen. 
Der Prüfschritt ist deshalb nicht anwendbar.

==== Android
. Unter System > Tastatur > Physische Tastatur > Bedienungshilfen für physische Tastaturen > Anschlagverzögerung aktivieren (Tasteneingaben erfolgen nun erst nach 500 ms) 
. Texteingabefeld fokussieren
. Einen Buchstaben der Tastatur  drücken
. Prüfen, ob der Buchstabe nach Verzögerung erscheint. 
Damit ist klar, dass die App die Android-Betriebssystemeinstellung berücksichtigt.
. Eine weitere Taste drücken. 
Funktioniert die erneute Eingabe erst nach 2 Sekunden?

=== 3. Hinweise
* Die Android-Funktion System > Tastatur > Physische Tastatur > Anschlagverzögerung 
leistet etwas anderes als die in der Anforderung intendierte Funktion, 
das Einsetzen der kontinuierlichen Eingabe des gleichen Zeichens 
bei längerem Drücken einer Taste zu verzögern. 
Die Verzögerung betrifft nämlich auch schon das initiale Drücken der Taste, 
was den Wert der Funktion sehr veringert. 
Denn gezielte Tastatureingaben sollen ja nicht grundsätzlich verzögert werden, 
sondern nur das Einsetzen der Wiederholung.
* Die Abweichung von der betriebssystemseitig möglichen Einstellungen 
von der Intention der Anforderung sind der App nicht anzulasten. 
Der Prüfschritt wäre nur dann nicht erfüllt, 
wenn betriebsystemseitige Einstellungen 
von Anschlaggeschwindigkeit und Tastenanschlagfunktion 
bei Texteingaben in der App nicht greifen würden.
* Bei der Nutzung virtueller Tastaturen (Touch-Eingabe) unter iOS und Android 
erfolgt keine Tastenwiederholung. 
* Hinweis zu iOS: Ist bei Tastenwiederholung aktiviert, 
funktioniert diese nur bei bestimmten Tasten, 
z.B. bei den Zeichen `.`, `-` oder `/`, 
nicht jedoch bei 0-9 und A-Z. Dies ist ein bekannter iOS-Bug.

=== 4. Bewertung

==== Nicht anwendbar (iOS)
* Der Prüfschritt ist zurzeit für iOS-Apps nicht anwendbar 
(denn die Tastenwiederholung ist in den Betriebssystemeinstellungen komplett abstellbar).

==== Erfüllt (Android)
* Für Android ist der Prüfschritt erfüllt, 
wenn wenn die aktivierte Anschlagverzögerung bei Texteingabefeldern der App greift.

==== Nicht erfüllt (Android)
* Für Android-Apps ist der Prüfschritt nicht erfüllt, 
wenn die aktivierte Anschlagverzögerung bei Texteingabefeldern der App nicht greifen.

== Quellen

* Android App offering key repeat settings: https://play.google.com/store/apps/details?id=com.apedroid.hwkeyboardhelper&pli=1[External Keyboard Helper Pro]

== Einordnung des Prüfschritts

=== Einordnung des Prüfschritts nach EN 301 549 V3.2.1

[.BLOCK_LANG_EN]
==== 5.7 Key repeat
____
[.BLOCK_LANG_EN]

Where ICT has a key repeat function that cannot be turned off:

a) the delay before the key repeat shall be adjustable to at least 2 seconds; and

b) the key repeat rate shall be adjustable down to one character per 2 seconds.
____

