= 5.8 Annahme identischer Tastenanschläge
include::include/author.adoc[]
include::include/attributes.adoc[]

== Was wird geprüft?
Die die erneute Aktivierung einer Taste auf der Tastatur, die das jeweilige Zeichen wiederholen würde, soll so konfigurierbar sein, dass die wiederholter Eingabe der Taste der zeotraum, in dem diese Eingabe nicht angenommen wird auf mindestens 0,5 Sekunden eingestellt werden kann. Dies sind üblicherweise Einstellungen des Betriebssystems, auf die Entwickler in der Regel keinen Einfluss haben, bzw. keinen Einfluss nehmen sollten.

Bei der Nutzung virtueller Tastaturen (Touch-Eingabe) unter iOS und Android erfolgt keine Tastenwiederholung. Der Prüfschritt wäre für eine Accessibility Baseline, die Apps nur mit Toucheingabe (ohne Anschluss externer Tastaturen) betrachten wollte, also ohnehin erfüllt. Unter iOS und iPadOS (iPad mit Magic Keyboard) gibt es eine Einstellungsmöglichkeit unter Bedienungshilfen / Tastaturen / Tastenverzögerung, die sich jedoch nicht speziell auf die versehentlich wiederholte Aktivierung der gleichen Taste bezieht.

Unter Android mit externer Tastatur gibt es die Einstellung Tastenverzögerung bei Berühren/Halten.

Da im App-Test nur Aspekte geprüft werden, welche Entwickler direkt in der Gestaltung der App beeinflussen können und sollen, wird diese Anforderung zur Zeit nicht aktiv geprüft, da sie die Betriebssystem-Ebene betrifft.

== Warum wird das geprüft?
Menschen mit motorischen Einschränkungen haben manchmal das Problem, dass sie versehentlich unabsichtlich wiederholt Tasten drücken und dann diese Eingaben wieder löschen müssen. Die Möglichkeit der Einstellung einer Tastenverzögerung verringert dieses Risiko.

== Wie wird das geprüft?

=== 1. Anwendbarkeit des Prüfschritts
Der Prüfschritt wird nicht geprüft, da Einstellungsmöglichkeiten der Tastenverzögerung Aufgabe des Betriebssystems sind und nicht auf der Ebene der App implementiert werden sollten. Selbst wenn Android-App-Entwickler die Tastenverzögerung bei der Nutzung externer Tastaturen erfolgreich implementieren könnten, wäre hieraus keine generelle Anforderung abzuleiten, dies auf der Ebene der App umzusetzen.

=== 2. Prüfung
Keine Prüfung.

=== 3. Hinweise

=== 4. Bewertung

==== Nicht anwendbar:

Der Prüfschritt ist zurzeit nicht anwendbar.

== Einordnung des Prüfschritts

=== Einordnung des Prüfschritts nach EN 301 549 V3.1.1

[.BLOCK_LANG_EN]
==== 5.8 Double-strike key
____
[.BLOCK_LANG_EN]
--
Where ICT has a keyboard or keypad, the delay after any keystroke, during which an additional key-press will not be accepted if it is identical to the previous keystroke, shall be adjustable up to at least 0,5 seconds.
--
____
