= Simultane Aktionen
include::include/author.adoc[]
include::include/attributes.adoc[]

== Was wird geprüft?
Für die Nutzung der App soll es einen Modus der Bedienung geben, der keine gleichzeitigen Aktivitäten von Nutzenden für die Bedienung verlangt. Beispiele:

* das gleichzeitige Drücken zweier Tasten auf der Tastatur 
* das Halten eines Bedienelements auf einem Tochscreen, während ein weiteres Bedienelement aktiviert wird.



Die Situation ist unterscheidlich für verschiedene Bedienungsmodi:

* *Tastaturbedienung:* iOS hat unter Einstellungen > Bedienungshilfen > Tastaturen > Einfingerbedienung die Einstellungsmöglichkeit, simultane Tasteneingaben so aufzulösen, dass Sondertasten gesetzt werden können, ohne gleichzeitig andere Tassten gedrückt halten zu müssen. In manchen Umgebungen (Android mit Tastatur) gibt es zur Zeit keine Einfingerbedienung. Die Konfigurationsmöglichkeiten für Einfingerbedienung haben Entwickler keinen Einfluss.

* *Touchbedienung:* Das gleichzeitige Eingabe über mehrere Berührungspunkte wird unter 11.2.5.1 "Alternativen für komplexe Zeiger-Gesten" geprüft - für Mehrfinger-Gesten muss es Einfinger-bedienbare Eingaben geben.

* *Mausbedienung und andere Zeigereingaben:* Hier gibt es nur einen Cursor (es sei denn bei Multi-User Schnittstellen, die für diese auf Einzelnutzende ausgerichteten Anforderungen nicht in Betracht kommen). Auf die Konfiguration einer Maus mit mehreren Tasten haben Entwickler keinen Einfluss.

* *Sprachsteuerung:* Diese funkioniert in der Regel ohne physische Eingaben.

== Warum wird das geprüft?

== Wie wird das geprüft?

=== 1. Anwendbarkeit des Prüfschritts

=== 2. Prüfung

=== 3. Hinweise

=== 4. Bewertung

==== Erfüllt:

== Einordnung des Prüfschritts

=== Einordnung des Prüfschritts nach EN 301 549 V3.1.1

[.BLOCK_LANG_EN]
==== 5.9 Simultaneous user actions

____
[.BLOCK_LANG_EN]
--
Where ICT has a mode of operation requiring simultaneous user actions for its operation, such ICT shall provide at least one mode of operation that does not require simultaneous user actions to operate the ICT.

NOTE:
Having to use both hands to open the lid of a laptop, having to press two or more keys at the same time or having to touch a surface with more than one finger are examples of simultaneous user actions.
--
____
