= Simultane Aktionen
include::include/author.adoc[]
include::include/attributes.adoc[]

*Hinweis: Dies ist ein Entwurf. Inhalte können sich jederzeit ändern.*

== Was wird geprüft?
Für die Nutzung der App soll es einen Modus der Bedienung geben, der für die Bedienung keine simultanen Aktivitäten bzw. Eingaben von Nutzenden verlangt. Die Einfingerbedienung wird üblicherweise über Einstellungen des Betriebssystems festgelegt, auf die Entwickler keinen Einfluss haben, bzw. keinen Einfluss nehmen sollten. Für Toucheingaben wird ein Teil der Anforderung in Prüfschritt 11.2.5.1 geprüft.

Beispiele für simultane Aktionen:

* das gleichzeitige Drücken zweier Tasten auf der Tastatur 
* das Halten eines Bedienelements auf einem Touchscreen, während ein weiteres Bedienelement über Touch bedient wird.

Die Situation ist unterscheidlich für verschiedene Bedienungsmodi:

* *Tastaturbedienung:* iOS hat unter Einstellungen > Bedienungshilfen > Tastaturen > Einfingerbedienung die Möglichkeit, simultane Tasteneingaben so aufzulösen, dass Sondertasten gesetzt werden können, ohne gleichzeitig andere Tasten gedrückt halten zu müssen ("sticky keys"). In manchen Umgebungen (Android mit Tastatur) ist zur Zeit keine Einfingerbedienung einstellbar. Auf die Einstellungsmöglichkeiten für Einfingerbedienung haben Entwickler keinen Einfluss.

* *Touchbedienung:* Das gleichzeitige Eingabe über mehrere Berührungspunkte wird unter 11.2.5.1 "Alternativen für komplexe Zeiger-Gesten" geprüft - für Mehrfinger-Gesten muss es alternativ Einfinger-bedienbare Eingaben geben.

* *Mausbedienung und andere Zeigereingaben:* Hier gibt es nur einen Cursor (es sei denn bei Multi-User Schnittstellen, die für diese auf Einzelnutzende ausgerichteten Anforderungen nicht in Betracht kommen). Auf die Konfiguration einer Maus mit mehreren Tasten haben Entwickler keinen Einfluss.

* *Sprachsteuerung:* Diese funktioniert in der Regel ohne physische Eingaben.

== Warum wird das geprüft?
Menschen mit motorischen Einschränkungen haben oft Probleme, mehrere Aktionen zur gleichen Zeit auszuführen. Deshalb sollten alle Funktionen über einfache Eingaben möglich sein.

== Wie wird das geprüft?

=== 1. Anwendbarkeit des Prüfschritts
Der Prüfschritt ist immer anwendbar, das Egebnis ist aber ggf. aus Prüfschritt 11.2.5.1 "Alternativen für komplexe Zeiger-Gesten" übertragen.

Bezüglich Tastasturbedienung wir dieser Prüfschritt nicht geprüft, da Einstellungsmöglichkeiten der Einfingerbedienung Aufgabe des Betriebssystems sind und nicht auf der Ebene der App implementiert werden sollten.

=== 2. Prüfung
Wenn die Accessibility Baseline Umgebungen einschließt, die bei Tastaturnutzung keine Einfingerbedienung anbietet:

. Bezüglich der Prüfung von Aktionen bei der Toucheingabe wird das Ergebnis von 11.2.5.1 hierhin übertragen, wenn es Fehler bei der Nutzung von Mehrfingergesten gibt.
. Bedienung mit Toucheingabe überprüfen. Sind alle Funktionen mit Einfinger-Gesten aktivierbar, ohne das gleichzeitig Gerätetasten gedrückt oder das Gerät bewegt bzw. ausgerichtet werden muss?

=== 3. Hinweise
ggf. sind außer dem gleichzeitigen Drücken von Gerätetasten oder der Ausrichtuing des Geräts andere hier nicht nährer spezifizierte Aktionen denkbar, die für die erfolgreiche Bedienuung simultan ausgeführt werden, etwa die Auswertung von Gesten über dem Gerät, der Auswertung des Kamera-Bildes, wofür das Gerät gehalten bzw. bewegt werden müsste, usw.

=== 4. Bewertung

==== Erfüllt:
Wenn die Accessibility Baseline Umgebungen einschließt, die bei Tastaturnutzung keine Einfingerbedienung anbietet, müssen alle Funktionen der App über Einfinger-Gesten aktivierbar sein.

== Einordnung des Prüfschritts

=== Einordnung des Prüfschritts nach EN 301 549 V3.1.1

[.BLOCK_LANG_EN]
==== 5.9 Simultaneous user actions
____
[.BLOCK_LANG_EN]
--
Where ICT has a mode of operation requiring simultaneous user actions for its operation, such ICT shall provide at least one mode of operation that does not require simultaneous user actions to operate the ICT.

NOTE:
Having to use both hands to open the lid of a laptop, having to press two or more keys at the same time or having to touch a surface with more than one finger are examples of simultaneous user actions.
--
____
