= Prüfschritt 6.2.2.3 Sprecheridentifizierung
include::include/author.adoc[]
include::include/attributes.adoc[]

*Hinweis: Dies ist ein Entwurf. Inhalte können sich jederzeit ändern.*

== Was wird geprüft?

Wenn die App Echtzeit-Textkommunikation (RTT, Real-time Text) unterstützt und aktive Sprechende über Sprache identifiziert, sollen auch Sprechende, die Echtzeit-Texteingaben nutzen, gleichermaßen identifizierbar sein.

== Warum wird das geprüft?

Für alle Teilnehmenden in einer entfernten Kommunikation ist es sehr wichtig, sehen oder ermitteln zu können, wer gerade spricht, um sich in Antworten auf sie oder ihn beziehen zu können. Sprach-Eingaben und Text-Eingaben sollen deshalb gleichranging behandelt werden.

== Wie wird geprüft?

=== 1. Anwendbarkeit des Prüfschritts

Der Prüfschritt ist anwendbar, wenn die App Echtzeit-Textkommunikation (RTT, Real-time Text) unterstützt und den aktiven Sprecher über Sprache identifiziert. Der aktive Sprecher wird dabei in der App markiert oder anderweitig hervorgehoben.

=== 2. Prüfung

. App öffnen.
. Prüfen, ob aktive Sprechende über Sprache identifiziert und in der App markiert oder anderweitig hervorgehoben werden.
. Ist dies der Fall, prüfen, ob auch Teilnehmende, die Echtzeit-Texteingabe verwenden, beim Eingaben markiert oder anderweitig hervorgehoben werden.

=== 3. Hinweise

Bei diesem Test muss eine Video- und Sprachverbindung mit mehreren Teilnehmenden etabliert werden, um eine eventuelle Markierung oder anderweitige Hervorhebung zweifelsfrei festzustellen.

== Quellen
* https://labs.etsi.org/rep/HF/en301549/uploads/272bede3724c5c99efe777f778201f70/tr_103708v010101p.pdf[ETSI TR 103 708 V1.1.1: Human Factors (HF); Real-Time Text (RTT) in Multiparty Conference Calling (PDF)]
* RFC 8865 T.140 https://www.rfc-editor.org/rfc/rfc8865.pdf[Real-Time Text Conversation over WebRTC]
* https://w3c.github.io/webrtc-pc/[WebRTC 1.0: Real-Time Communication Between Browsers.] W3C Editor's Draft 06 February 2023

== Einordnung des Prüfschritts

=== Einordnung des Prüfschritts nach EN 301 549 V3.1.1

[.BLOCK_LANG_EN]
==== 6.2.2.3 Speaker identification
____
[.BLOCK_LANG_EN]
--
Where ICT has RTT capabilities, and provides speaker identification for voice, the ICT shall provide speaker identification for RTT.

NOTE: This is necessary to enable both voice and RTT participants to know who is currently communicating, whether it be in RTT or voice.
--
____
