= Prüfschritt 6.2.2.2 Programmatisch unterscheidbare Anzeige von Echtzeit-Textnachrichten
include::include/author.adoc[]
include::include/attributes.adoc[]

*Hinweis: Dies ist ein Entwurf. Inhalte können sich jederzeit ändern.*

== Was wird geprüft?

Wenn die App eine Funktion zur Echtzeit Textkommunikation (RTT, Real-Time Text) anbietet, soll die Sende- und Empfangsrichtung programmatisch ermittelbar sein. Das bedeutet konkret, dass Hilfsmittel-Nutzende beim Lesen der Text-Kommunikation die selbst gesendeten Texte von empfangenen Texten unterscheiden können.

== Warum wird das geprüft?

Wenn Menschen, die Hilfsmittel wie Screenreader einsetzen, die Äußerungen in einer Kommunikation lesen wollen, müssen sie eigene Text-Beiträge von denen anderer unterscheiden können. Darum muss die Sende- und Empfangsrichtung programmatisch ermittelbar sein. (Darüber hinaus ist es auch sinnvoll, programmatisch zwischen empfangenen Texten von verschiedenen Teilnehmenden unterscheiden zu können.)

== Wie wird geprüft?

=== 1. Anwendbarkeit des Prüfschritts

Der Prüfschritt ist anwendbar, wenn die Web-Anwendung Echtzeit-Textkommunikation (RTT, Real-Time Text) senden und empfangen kann.

=== 2. Prüfung

Die App-Ansicht mit der Echtzeit-Textkommunikation muss sehr genau mit dem
Screenreader geprüft werden, um zu beurteilen, ob die notwendigen
Informationen an den Screenreader gesendet werden und dieser die Richtung der
einzelnen Textnachrichten ansagen kann bzw. diese aus der Ausgabe deutlich
hervorgeht.

. Screenreader starten
. Zu prüfende Ansicht für Echtzeit-Textkommunikation aufrufen
. Einige Testnachrichten senden und empfangen (ggf. zweites Gerät notwendig)
. Die Textnachrichten antippen bzw. mit Hilfe der Wischgesten zu diesen navigieren
. Auf die Ausgabe des Screenreaders achten. Wird die Unterscheidung zwischen eigenen und fremden Textbeiträgen unterstützt?

=== 3. Hinweise

* Bei Echtzeit-Textkommunkation (RTT, Real-Time Text) erscheint der Text beim Empfänger dynamisch schon während der Eingabe des Senders. RTT ist also nicht das Gleiche wie etwa Chat, wo Nachrichten explizit abgeschickt werden und erst dann beim Empfänger erscheinen.

* Die Anforderung verlangt streng genommen nur die Unterscheidung der Senderichtung, sie verlangt also nicht, dass empfangene Textnachrichten verschiedener Teilnehmer unterscheidbar sind. In der Praxis wird jedoch anzunehmen sein, dass bei allen Echtzeit-Textbeiträgen der jeweilige Sender über einen Namen bzw. Kürzel identifizierbar ist und somit auch empfangene Textnachrichten von verschiedenen Teilnehmenden unterscheidbar sind.

=== 4. Bewertung

==== Erfüllt

Die Eingaben des Nutzers selbst und die empfangenen Echtzeit-Texteingaben anderer Nutzer sind programmatisch unterscheidbar, z.B. über einen Präfix.

==== Eher erfüllt

Die Eingaben des Nutzers selbst snd von empfangenen Echtzeit-Texteingaben anderer Nutzer sind programmatisch unterscheidbar, die anderen Nutzer sind aber nicht unterscheidbar.

==== Nicht erfüllt

Es gibt beim Lesen der Echtzeit-Texteingaben einer Kommunikation keine Möglichkeit, programmatisch zwischen eigenen und fremden Eingaben zu unterscheiden.

== Einordnung des Prüfschritts

=== Einordnung des Prüfschritts nach EN 301 549 V3.1.1

[.BLOCK_LANG_EN]
==== 6.2.2.2 Programmatically determinable send and receive direction
____
[.BLOCK_LANG_EN]
--
Where ICT has RTT send and receive capabilities, the send/receive direction of
transmitted/received text shall be programmatically determinable, unless the
RTT is implemented as closed functionality. 

NOTE:
This enables screen readers to distinguish between incoming text and outgoing
text when used with RTT functionality.
--
____

