= Prüfschritt 6.3 Anruferkennung
include::include/author.adoc[]
include::include/attributes.adoc[]

== Was wird geprüft?

Wenn die App Telekommunikationsfunktionen mit Anrufidentifizierung bietet, soll die Identifizierung (auch) in Textform verfügbar und programmatisch
ermittelbar sein.

Diese Anforderung stellt sicher, dass auch Nutzer von Hilfstechnologien den Anrufer identifizieren können.

== Warum wird das geprüft?

Diese Anforderung stellt sicher, dass auch Nutzende von Hilfsmittel-Technologien den Anrufer identifizieren können.

== Wie wird geprüft?

=== 1. Anwendbarkeit des Prüfschritts

Der Prüfschritt ist anwendbar, wenn die App Telekommunikationsfunktionen mit Anrufidentifizierung bietet.

Anrufidentifizierung bedeutet hier, die Signalisierung bzw. Anzeige der Anrufenden.

=== 2. Prüfung

Für die Prüfung muss die App gegebenenfalls auf zwei Geräten installiert werden.

. Screenreader starten
. Zu prüfende Ansicht der App öffnen
. Anruf von einem zweiten Gerät tätigen
. Prüfen, wie der Anruf in Zusammenhang mit dem aktiviertem Screenreader signalisiert wird. Wird der Anrufer automatisch angesagt oder sind die
  Informationen über den Anrufer auf dem Bildschirm für den Screenreader ohne Umwege auslesbar?
. Prüfen, wie der Anruf visuell signalisiert bzw. angezeigt wird. Die Anzeige muss den Anrufer in irgendeinerweise in Textform identifizieren, z.B. über
  die Telefonnummer, Name etc.

== Einordnung des Prüfschritts

=== Einordnung des Prüfschritts nach EN 301 549 V3.2.1

[.BLOCK_LANG_EN]
==== 6.3 Caller ID
____
[.BLOCK_LANG_EN]
Where ICT provides caller identification or similar telecommunications
functions, the caller identification and similar telecommunications functions
shall be available in text form as well as being programmatically
determinable, unless the functionality is closed.
____
