= Prüfschritt 6.5.5 Visueller Anzeiger von Audio bei Video
include::include/author.adoc[]
include::include/attributes.adoc[]

== Was wird geprüft?

Wenn die App Videotelefonie unterstützt, soll Audio-Aktivität visuell angezeigt werden.

== Warum wird das geprüft?

Die Anzeige der Audio-Aktivität ermöglicht gehörlosen Nutzenden die Wahrnehmung, dass jemand spricht und wer spricht.

== Wie wird geprüft?

=== 1. Anwendbarkeit des Prüfschritts

Der Prüfschritt ist anwendbar, wenn die App Videotelefonie mit Sprachübertragung unterstützt.

=== 2. Prüfung

. Die Ansicht der App auf zwei Geräten mit abweichenden Nutzenden-Konten öffnen.
. Videotelefonieverbindung zwischen den beiden Instanzen der App herstellen.
. Auf dem verbundenen Gerät Sprache eingeben und auf dem Prüfgerät überprüfen, ob die Spracheingabe visuell wahrnehmbar ist. 

=== 3. Hinweise

Für den Indikator der Sprachaktivität gelten weitere Anforderungen, z.B. bezüglich Grafik-Kontrast.

Der visuelle Indikator der Audio-Aktivitä kann ein einfacher visueller Punkt, eine LED oder eine andere Art von Ein- / Aus-Anzeige sein, die flackert.

Für Hinweise zu diesem Prüfschritt können Sie auf GitHub https://github.com/BIK-BITV/BIK-App-Test/issues[ein Issue] zu diesem Prüfschritt eröffnen.

== Einordnung des Prüfschritts

=== Einordnung des Prüfschritts nach EN 301 549 V3.1.1

==== 6.5.5 Visual indicator of audio with video
____
Where ICT provides two-way voice communication, and includes real-time video functionality, the ICT shall provide a real-time visual indicator of audio activity.

NOTE 1: The visual indicator may be a simple visual dot or LED, or other type of on/off indicator, that flickers to reflect audio activity.

NOTE 2: Without this indication a person who lacks the ability to hear does not know when someone is talking.
____
