= Prüfschritt 6.5.2 Auflösung
include::include/author.adoc[]
include::include/attributes.adoc[]

== Was wird geprüft?

Apps mit Videotelefonie-Funktion sollen mindestens die QVGA-Auflösung für die Videoübertragung unterstützen. Üblicherweise entspricht dies 320 x 240 Pixel. Bei anderen Seitenverhältnissen müssen entsprechend 76.800 Bildpunkte geboten werden.

== Warum wird das geprüft?

Bei zu geringer Auflösung sind wichtige Informationen, z.B. auch Untertitel, schlechter erkennbar.

== Wie wird geprüft?

=== 1. Anwendbarkeit des Prüfschritts

Der Prüfschritt ist anwendbar, wenn die App Videotelefonie unterstützt.

=== 2. Prüfung

. Die technische Dokumentation der App konsultieren. Wird mindestens eine QVGA (320x240 Pixel) angegeben?
. Testübertragung: Den visuellen Eindruck prüfen. Ist die Angabe in der App-Dokumentation plausibel?

=== 3. Hinweise

Für Hinweise zu diesem Prüfschritt eröffnen Sie gerne https://github.com/BIK-BITV/BIK-App-Test/issues[ein
Issue auf GitHub].

== Einordnung des Prüfschritts

=== Einordnung des Prüfschritts nach EN 301 549 V3.2.1

[.BLOCK_LANG_EN]
==== 6.5.2 Resolution
____
[.BLOCK_LANG_EN]
--
Where ICT that provides two-way voice communication includes real-time video
functionality, the ICT:

* shall support at least QVGA resolution
--
____
