= Prüfschritt 7.1.5 Gesprochene Untertitel
include::include/author.adoc[]
include::include/attributes.adoc[]

== Was wird geprüft?

Wenn die App ein Video mit einem Orginalton enthält, der nicht der Hauptsprache der App entspricht, sollen zuschaltbaren bzw. programmatisch ermittelbaren Untertitel, die in der Hauptsprache angeboten werden, als akustische Ausgabe zugänglich sein, z.B. über eine eigene Tonspur, die den Untertiteln entspricht, oder über eine generierte Sprachausgabe der Untertitel. Nicht programmatisch ermittelbar sind Untertitel, die "fest eingebrannt", also Teil der Bildinformation, sind.

== Warum wird das geprüft?

Für Menschen, die den fremdsprachigen Originalton eines Videos nicht verstehen, ist eine Übersetzung in Untertiteln in der eigenen Sprache wichtig. Diese Untertitel sollen auch für blinde oder seheingeschränkte Menschen als akustische Ausgabe zugänglich sein.

== Wie wird geprüft?

=== 1. Anwendbarkeit des Prüfschritts

Der Prüfschritt ist anwendbar:

* wenn der Original-Ton des Videos fremdsprachig ist (d.h. er entspricht nicht der Hauptsprache der App)
* und Untertitel in der Hauptsprache der App bereitgestellt werden
* und wenn es keine Version des Videos mit einer Tonspur in der Hauptsprache der App gibt.

=== 2. Prüfung

. App-Ansicht öffnen.
. Prüfen, ob der Originalton des Videos von der Hauptsprache der App abweicht.
. Prüfen, ob für Videos mit fremdsprachiger Tonspur Untertitel in der Hauptsprache der App angeboten werden.
. Prüfen, ob sich eine alternative Tonspur in der Hauptsprache des Angebots oder eine generierte Sprachausgabe der Untertitel aktivieren lässt.

=== 3. Hinweise

* Gängige Video-Player verfügen zur Zeit meist nicht über die Möglichkeit einer einschaltbaren Sprachausgabe der Untertitel. 
* Für blinde oder sehbehinderte Menschen, die den fremdsprachigen Originalton eines Videos nicht verstehen, sollen Untertitel in der Hauptsprache der App als akustische Ausgabe zugänglich sein. Ist der Original-Ton des Videos bereits in der Hauptsprache, so gelten Untertitel in anderen Sprachen als zusätzliche Informationen und sind daher nicht von der Anforderung betroffen.

Hinweise zu diesem Prüfschritt können Sie auf GitHub https://github.com/BIK-BITV/BIK-App-Test/issues[in einem Issue hinterlassen].

=== 4. Bewertung

==== Nicht erfüllt:

* Bei Videos mit fremdsprachiger Tonspur und zuschaltbaren Untertiteln in der Hauptsprache sind die Untertitel nicht als akustische Ausgabe zugänglich.

== Einordnung des Prüfschritts

=== Einordnung des Prüfschritts nach EN 301 549 V3.2.1

[.BLOCK_LANG_EN]
==== 7.1.5 Spoken subtitles

[.BLOCK_LANG_EN]
--
____
Where ICT displays video with synchronized audio, it shall have a mode of operation to provide a spoken output of the available captions, except where the content of the displayed captions is not programmatically determinable.

NOTE 1: Being able to manage speech output range for spoken subtitles independently from general ICT speech is preferable for most users. That is possible when the audio file with spoken subtitle is delivered in a separate audio track and mixed in the end users device.
____

