= Prüfschritt 7.1.1 Wiedergabe der Untertitelung
include::include/author.adoc[]
include::include/attributes.adoc[]

== Was wird geprüft?

Sind Videos mit synchroner Bild- und Tonspur vorhanden und werden dynamisch zuschaltbare, textbasierte Untertitel (closed captions) angeboten, bietet der Videoplayer die Möglichkeit, diese ein- und auszublenden.

== Warum wird das geprüft?

Filme sind in der Regel ohne den Ton nicht zu verstehen. Daher muss für Menschen mit Höreinschränkung der Inhalt der Tonspur durch Untertitel bereitgestellt werden.

Untertitel können auf unterschiedliche Arten eingebunden werden: Manche Player unterstützen nur die dauerhaft sichtbaren „open captions“, die meisten jedoch sogenannte textbasierte „closed captions“, die über ein Bedienelement am Player flexibel zuschaltbar sind.

Damit closed captions (dynamisch zuschaltbare Untertitel) von den Nutzenden wahrgenommen werden können, ist es erforderlich, dass der Videoplayer die Möglichkeit bietet, diese ein- und auszublenden. Bei open captions handelt es sich hingegen um immer sichtbare Untertitel, d.h. der Videoplayer wird hier nicht geprüft.


== Wie wird geprüft?

=== 1. Anwendbarkeit des Prüfschritts


* Der Prüfschritt ist anwendbar, wenn die App aufgezeichnete Videos mit synchroner Bild- und Tonspur anbietet und Untertitel zuschaltbar sind.
* Aufgezeichnete Videos ohne Tonspur (stumme Videos) brauchen keine Untertitelung, der Prüfschritt ist für sie nicht anwendbar.



=== 2. Prüfung

==== 2.1 Anzeigen von open captions

. Das Video wird im  eingebundenen Videoplayer abgespielt.
. Untertitel werden angezeigt (open captions).

==== 2.2 Anzeigen von closed captions

. Video im eingebundenen Player abspielen.
. Prüfen, ob ein Menü zum Einblenden von Untertiteln im Player angezeigt wird.
. Falls ja, testweise Untertitel ein- und abschalten. Werden die Untertitel angezeigt, funktioniert das Abschalten der Untertitel?

=== 3. Hinweise

* Empfehlenswert wäre, wenn der Videoplayer eine Funktion zur Verfügung stellt, um die Untertitel auf einer Braillezeile anzuzeigen.
* Nicht negativ bewertet wird, wenn ein alternatives Video mit open captions bei Aktivierung eines Bedienelements im Player neu geladen wird, oder wenn das Video mit open captions über einen zweiten Player angezeigt wird.

=== 4. Bewertung

==== Erfüllt: 

Sind Videos mit synchroner Bild- und Tonspur vorhanden, werden Untertitel als fester Bestandteil des Videos angezeigt (open captions) oder können über ein Bedienelement des Videoplayers ein- und ausgeblendet werden (closed captions).

== Einordnung des Prüfschritts

=== Abgrenzung zu anderen Prüfschritten

Bei diesem Prüfschritt geht es um den eigentlichen Prozess der Anzeige von Untertiteln während der Wiedergabe sowie um die Bedienelemente zum Ein- und Ausschalten von Untertiteln im Videoplayer.

ifdef::env_embedded[11.1.2.2 "Aufgezeichnete Videos mit Untertiteln"]
ifndef::env_embedded[]
<<11.1.2.2 Aufgezeichnete Videos mit Untertiteln.adoc#,11.1.2.2 Aufgezeichnete
Videos mit Untertiteln>> bezieht sich hingegen auf den Inhalt der Untertitel.
Es geht darum, dass der Autor bei der Erstellung der Untertitel sicherstellen muss, dass Audioinhalt korrekt transkribiert wurde und in einem Format erfasst werden, das für die Bereitstellung synchronisierter Untertitel verwendet werden kann. 

Anforderungen der Video-Bedienelemente bezüglich Kontrast, zugänglichem Namen, Tastaturbedienbarkeit, Fokushervorhebung usw. werden in den entsprechenden Prüfschritten geprüft.

== Einordnung des Prüfschritts

=== Einordnung des Prüfschritts nach EN 301 549 V3.1.1

[.BLOCK_LANG_EN]

==== 7.1.1 Captioning playback
____
[.BLOCK_LANG_EN]
--
Where ICT displays video with synchronized audio, it shall have a mode of
operation to display the available captions.
Where closed captions are provided as part of the content, the ICT shall allow
the user to choose to display the captions.

NOTE 1:
Captions may contain information about timing, colour and positioning.
This caption data is necessary for caption users.
Timing is used for caption synchronization.
Colour can be used for speaker identification.
Position can be used to avoid obscuring important information.

NOTE 2:
If a Braille device is connected, the ICT should provide an option to display
captions on the Braille device.
--
____
