= Prüfschritt 7.2.2 Synchronisation der Audiodeskription
include::include/author.adoc[]
include::include/attributes.adoc[]

== Was wird geprüft?

Sind Videos mit synchroner Bild- und Tonspur und zusätzlicher Audiodeskription vorhanden, soll der Videoplayer in der Lage sein, die zusätzliche Audiodeskription synchron zu Bild und Ton wiederzugeben.

== Warum wird das geprüft?

Bildbeschreibungen sollten möglichst handlungssynchron umgesetzt werden (siehe auch https://www.ndr.de/fernsehen/barrierefreie_angebote/audiodeskription/Vorgaben-fuer-Audiodeskriptionen,audiodeskription140.html[Vorgaben der Rundfunkanstalten für Audiodeskription]).
Das bedeutet, dass die Audiodeskription auf die visuellen Elemente des zu beschreibenden Videos abgestimmt und damit synchron ist. Die synchrone Ausgabe ist für die Gesamtverständlichkeit wichtig.

== Wie wird geprüft?

=== 1. Anwendbarkeit des Prüfschritts

Der Prüfschritt ist anwendbar, wenn auf der Ansicht der App Videos mit synchroner Bild- und Tonspur sowie einer zusätzlich eingebundenen Tonspur für Audiodeskription vorhanden sind. 
Wenn also ein Player bei der Auswahl einer angebotenen 'Version mit Audiodeskription' eine andere Videodatei mit erweitertem Ton lädt, ist der Prüfschritt nicht anwendbar, denn eine festgestellte mangelnde Synchronität läge dann in jedem Fall an der eingebundenen Video-Datei, nicht am Player.

=== 2. Prüfung

. Das Video mit zugeschalteter Audiodeskription in dem in der App eingebundenen Player abspielen.
. Prüfen, ob die Audiodeskription synchron zu Bild und Ton wiedergegeben wird.
. Wird Audiodeskription nicht synchron wiedergegeben, kann das an den technischen Möglichkeiten des Players 
  oder an fehlerhaften Umsetzung der Audiodeskription liegen. Die Ursache kann derzeit nur vom App-Entwickler geprüft werden.

=== 3. Hinweise

Falls die App keine eigenen Video-Inhalte bereithält, sondern zum Abspielen externer Inhalte gedacht ist, muss ggf. eine Beispiel-Video-Datei mit Audiodeskription in der App geöffnet werden.

Hinweise zu diesem Prüfschritt können Sie auf GitHub https://github.com/BIK-BITV/BIK-App-Test/issues[in einem Issue hinterlassen].

=== 4. Bewertung

==== Nicht erfüllt:
* Audiodeskription wird nicht synchron zu Bild und Ton wiedergegeben.

== Einordnung des Prüfschritts

=== Abgrenzung zu anderen Prüfschritten

In diesem Prüfschritt wird geprüft, ob der Videoplayer Audiodeskription synchron anzeigt.
In Prüfschritt
ifdef::env_embedded[11.1.2.5 "Audiodeskription für Videos"]
ifndef::env_embedded[]
<<11.1.2.5 Audiodeskription für Videos.adoc#,11.1.2.5 Audiodeskription für Videos>>
endif::env_embedded[]
erfolgt hingegen die inhaltliche Prüfung der Audiodeskription.
Die Prüfung, ob der Player oder die Umsetzung der Audiodeskription fehlerhaft ist, kann derzeit nicht erfolgen.
Wird Audiodeskription nicht synchron dargestellt, erfolgt in beiden Prüfschritten eine negative Bewertung mit dem Hinweis auf eine unklare Ursache.

=== Einordnung des Prüfschritts nach EN 301 549 V3.2.1

[.BLOCK_LANG_EN]
==== 7.2.2 Audio description synchronization
____
[.BLOCK_LANG_EN]
Where ICT has a mechanism to play audio description, it shall preserve the
synchronization between the audio/visual content and the corresponding audio
description.
____

