= x05 1.3.1se Fokusverfolgung, Texteinfügemarke und Textauswahl
include::include/author.adoc[]
include::include/attributes.adoc[]

== Grundlage des Prüfschritts

Dieser Prüfschritt basiert auf den Kriterien der EN 301 549 Abschnitt
11.5.2.13 Tracking of focus and selection attributes.

== Was wird geprüft?

Informationen und Mechanismen für die Fokusverfolgung, Einfügemarke und
Textauswahl müssen für die Hilfsmitteltechnologie programatisch verfügbar
sein.

== Wie wird geprüft?

* Kann Text mittels Screenreader navigiert werden?
* Kann die Einfügemarke bzw. der Cursor versetzt werden und ist dies mit dem
  Screenreader nachvollziehbar?
* Kann Text ausgewählt werden und ist dies auch mittels Hilfstechnologie
  möglich?

== Quellen

=== Auszug EN 301 549

[.BLOCK_LANG_EN]
==== 11.5.2.13 Tracking of focus and selection attributes 

[.BLOCK_LANG_EN]
Where software provides a user interface it shall, by using the services as
described in clause 11.5.2.3, make information and mechanisms necessary to
track focus, text insertion point, and selection attributes of user interface
elements programmatically determinable by assistive technologies.
