= x35 Barrierefreie Dokumentation
include::include/author.adoc[]
include::include/attributes.adoc[]

== Grundlage des Prüfschritts

Grundlage des Prüfschritts ist die Tabelle A.2 im Annex A der EN 301 549
V3.1.1.
In dieser Tabelle wird auf Abschnitt
12.1.2 "Accessible documentation" verwiesen.

== Was wird geprüft?

Die Dokumentation soll mindestens in eines der folgenden Formate barrierefrei
zur Verfügung gestellt werden:

* Web-Dokument, erfüllt Kriterien der EN 301 549 Kapitel 9
* Nicht-Web-Dokument (u. a. PDF), erfüllt Kriterien der EN 301 549 Kapitel 10 

Weitere, ggf. nicht barrierefreie Versionen der Dokumentation, werden nicht
bewertet.

== Wie wird geprüft?

=== Anwendbarkeit des Prüfschritts

Der Prüfschritt ist immer anwendbar.

=== Prüfung

Für weitere Hinweise zu diesem Prüfschritt können Sie auf GitHub
{app-issue-url}[ein Issue eröffnen].

. in der App bzw. in deren Hersteller-Webseite wird die zugehörige Dokumentation
  gesucht
. prüfen, in welchen Formaten die Dokumentation zur Verfügung gestellt wird
. falls mehrere Varianten zur Verfügung stehen, sollte Web-Dokumenten den
  Vorrang gegeben werden, da diese eher barrierearm sind und mit dem
  https://www.bitvtest.de[BITV-Test] getestet werden können
. prüfung der Dokumentation auf Barrierefreiheit
+
Kriterien sind dazu aus Kapitel 9 und 10 der EN 301 549 zu entnehmen.
Handelt es sich um Web-Dokumente, kann die Konformität mit dem
https://www.bitvtest.de[BITV-Test] überprüft werden.

==== Hinweise

Der Prüfschritt schließt nicht die Möglichkeit aus, alternative Formate
anzubieten, die die Bedürfnisse einer bestimmten Nutzergruppe erfüllen (z. B.
Braille-Dokumente für blinde Menschen oder Informationen in leichter Sprache 
für Personen mit eingeschränkter Kognition, Sprache und Lernfähigkeit).

== Quellen

[.BLOCK_LANG_EN]
=== 12.1.2 Accessible documentation

[.BLOCK_LANG_EN]
--
Product documentation provided with the ICT shall be made available in at
least one of the following electronic formats:

* a Web format that conforms to the requirements of clause 9; or 
* a non-web format that conforms to the requirements of clause 10. 

NOTE 1:
This does not preclude the possibility of also providing the product
documentation in other formats (electronic, printed or audio) that are not
accessible. 

NOTE 2:
It also does not preclude the possibility of providing alternate formats that
meet the needs of some specific type of users (e.g. Braille documents for
blind people or easy-to-read information for persons with limited cognitive,
language and learning abilities). 

NOTE 3:
Where documentation is incorporated into the ICT, the documentation falls
under the requirements for accessibility in the present document. 

NOTE 4:
A user agent that supports automatic media conversion would be beneficial to
enhancing accessibility.
--

(Aus EN 301 549 V3.1.1 Abschnitt 12.1.2 "Accessible documentation")
